part of '../record_generator.dart';

// ── C++ record decoder generator ────────────────────────────────────────────

/// NitroOpt* packed structs are typedef'd in the bridge.g.h C header —
/// emitting C++ structs for them would conflict. NitroNullable* record types
/// are NOT in the C header (they exist as library types on Dart/Kotlin/Swift
/// only), so the C++ generator MUST emit structs for them when referenced.
const _cppSkippedLibraryRecordTypes = {
  'NitroOptInt64',
  'NitroOptFloat64',
  'NitroOptBool',
};

/// Generates C++ struct definitions with a bounds-checked decoder
/// (`fromNative` / `fromReader`) and a mirroring encoder (`encodeInto`) for
/// every `@HybridRecord` type in the spec.  Emitted into the `*.native.g.h`
/// header so C++ native implementations can round-trip records without
/// hand-rolling binary parsing.
///
/// The caller ([CppInterfaceGenerator]) must emit [cppRecordReaderDefinition]
/// and the struct codec helpers ([generateCppStructCodecs]) BEFORE this output.
///
/// Safety guarantee: every `readNullTag()` call is preceded by an explicit
/// `if (offset + 1 > size)` check that throws `std::runtime_error`, preventing
/// out-of-bounds reads on malformed wire data (IMPROVEMENTS.md §3.3).
String _generateCppRecords(BridgeSpec spec) {
  final localRecords = spec.localRecordTypes;
  if (localRecords.isEmpty) return '';
  final enumNames = spec.enums.map((e) => e.name).toSet();
  final structNames = spec.structs.map((st) => st.name).toSet();

  final unordered = localRecords.where((r) => !_cppSkippedLibraryRecordTypes.contains(r.name)).toList();
  if (unordered.isEmpty) return '';

  // Dependency-order the structs: a record embedding another record BY VALUE
  // (recordObject / listRecordObject fields) needs the dependency's full
  // definition first — forward declarations only cover pointers/references.
  final byName = {for (final r in unordered) r.name: r};
  final cppRecords = <BridgeRecordType>[];
  final visited = <String>{};
  void visit(BridgeRecordType r) {
    if (!visited.add(r.name)) return;
    for (final f in r.fields) {
      final deps = [f.dartType.replaceFirst('?', ''), if (f.itemTypeName != null) f.itemTypeName!];
      for (final d in deps) {
        final dep = byName[d];
        if (dep != null && dep.name != r.name) visit(dep);
      }
    }
    cppRecords.add(r);
  }

  unordered.forEach(visit);

  final s = CodeWriter();

  // Note: NitroNullable* library records ARE in localRecordTypes and generate
  // through the normal path below — C++ has no package:nitro library to import
  // them from, unlike Dart/Kotlin/Swift. Only NitroOpt* are skipped (they are
  // typedef'd in bridge.g.h).

  // Forward declarations so mutually-referencing types compile in any order.
  s.writeln('// @HybridRecord C++ structs (generated by Nitrogen)');
  for (final rt in cppRecords) {
    s.writeln('struct ${rt.name};');
  }
  s.writeln();

  // Per-record struct + fromNative / fromReader / encodeInto.
  for (final rt in cppRecords) {
    s.writeln('struct ${rt.name} {');
    for (final f in rt.fields) {
      s.writeln('    ${_cppFieldType(f, enumNames)} ${f.name};');
    }
    s.writeln();
    s.writeln('    static ${rt.name} fromNative(NitroCppBuffer buf) {');
    s.writeln('        NitroRecordReader _r(buf);');
    s.writeln('        return fromReader(_r);');
    s.writeln('    }');
    s.writeln();
    s.writeln('    static ${rt.name} fromReader(NitroRecordReader& _r) {');
    s.writeln('        ${rt.name} _obj;');
    for (final f in rt.fields) {
      _cppEmitFieldRead(s, f, enumNames, structNames);
    }
    s.writeln('        return _obj;');
    s.writeln('    }');
    s.writeln();
    s.writeln('    // Mirrors fromReader — appends this record\'s fields to [w].');
    s.writeln('    void encodeInto(NitroRecordWriter& w) const {');
    for (final f in rt.fields) {
      _cppEmitFieldWrite(s, f, enumNames, structNames);
    }
    s.writeln('    }');
    s.writeln();
    s.writeln('    /// Heap-allocated [4B length][payload] for returning to Dart.');
    s.writeln('    NitroCppBuffer toNativeBuffer() const {');
    s.writeln('        NitroRecordWriter _w;');
    s.writeln('        encodeInto(_w);');
    s.writeln('        return _w.toNativeBuffer();');
    s.writeln('    }');
    s.writeln('};');
    s.writeln();
  }

  return s.toString();
}

/// Free-function binary codecs for @HybridStruct types embedded in records or
/// variants. Structs are plain C typedefs (declared in bridge.g.h), so member
/// functions cannot be added — free functions are used instead.
///
/// String fields are `const char*` in the C struct: fromReader strdup's (the
/// struct owner must free), encodeInto writes empty string for nullptr.
String generateCppStructCodecs(BridgeSpec spec) {
  if (spec.structs.isEmpty) return '';
  final s = CodeWriter();
  s.writeln('// @HybridStruct inline binary codecs (generated by Nitrogen).');
  for (final st in spec.structs) {
    s.writeln('inline ${st.name} nitro_${st.name}_fromReader(NitroRecordReader& _r) {');
    s.writeln('    ${st.name} _s{};');
    for (final f in st.fields) {
      final base = f.type.name.replaceFirst('?', '');
      if (base == 'double') {
        s.writeln('    _s.${f.name} = _r.readDouble();');
      } else if (base == 'int') {
        s.writeln('    _s.${f.name} = _r.readInt();');
      } else if (base == 'bool') {
        s.writeln('    _s.${f.name} = _r.readBool() ? 1 : 0;');
      } else if (base == 'String') {
        s.writeln('    { std::string _tmp = _r.readString(); _s.${f.name} = strdup(_tmp.c_str()); }');
      } else if (spec.structs.any((x) => x.name == base)) {
        // Nested struct pointer fields are not representable inline — skip.
        s.writeln('    // ${f.name}: nested struct field not supported in inline codec');
      } else {
        s.writeln('    // ${f.name}: unsupported field type ${f.type.name} in inline codec');
      }
    }
    s.writeln('    return _s;');
    s.writeln('}');
    s.writeln('inline void nitro_${st.name}_encodeInto(const ${st.name}& _s, NitroRecordWriter& w) {');
    for (final f in st.fields) {
      final base = f.type.name.replaceFirst('?', '');
      if (base == 'double') {
        s.writeln('    w.writeDouble(_s.${f.name});');
      } else if (base == 'int') {
        s.writeln('    w.writeInt(_s.${f.name});');
      } else if (base == 'bool') {
        s.writeln('    w.writeBool(_s.${f.name} != 0);');
      } else if (base == 'String') {
        s.writeln('    w.writeString(_s.${f.name} ? std::string(_s.${f.name}) : std::string());');
      } else {
        s.writeln('    // ${f.name}: unsupported field type ${f.type.name} in inline codec');
      }
    }
    s.writeln('}');
  }
  s.writeln();
  return s.toString();
}

String _cppFieldType(BridgeRecordField f, Set<String> enumNames) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final t = _cppPrimType(f.dartType.replaceFirst('?', ''));
      return f.isNullable ? 'std::optional<$t>' : t;
    case RecordFieldKind.enumValue:
      final base = f.dartType.replaceFirst('?', '');
      final t = enumNames.contains(base) ? base : 'int64_t';
      return f.isNullable ? 'std::optional<$t>' : t;
    case RecordFieldKind.recordObject:
      final base = f.dartType.replaceFirst('?', '');
      return f.isNullable ? 'std::optional<$base>' : base;
    case RecordFieldKind.listPrimitive:
      return 'std::vector<${_cppPrimType(f.itemTypeName ?? 'int')}>';
    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName ?? 'int64_t';
      return 'std::vector<${enumNames.contains(item) ? item : 'int64_t'}>';
    case RecordFieldKind.listRecordObject:
      return 'std::vector<${f.itemTypeName}>';
    case RecordFieldKind.typedData:
      return f.isNullable ? 'std::optional<std::vector<uint8_t>>' : 'std::vector<uint8_t>';
    case RecordFieldKind.struct:
      final base = f.dartType.replaceFirst('?', '');
      return f.isNullable ? 'std::optional<$base>' : base;
  }
}

String _cppPrimType(String dartType) {
  switch (dartType) {
    case 'int':
      return 'int64_t';
    case 'double':
      return 'double';
    case 'bool':
      return 'bool';
    case 'String':
      return 'std::string';
    default:
      return 'int64_t';
  }
}

String _cppPrimRead(String dartType) {
  switch (dartType) {
    case 'int':
      return 'readInt';
    case 'double':
      return 'readDouble';
    case 'bool':
      return 'readBool';
    case 'String':
      return 'readString';
    default:
      return 'readInt';
  }
}

void _cppEmitFieldRead(CodeWriter s, BridgeRecordField f, Set<String> enumNames, Set<String> structNames) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final base = f.dartType.replaceFirst('?', '');
      final t = _cppPrimType(base);
      final read = _cppPrimRead(base);
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$t>(_r.$read()); }');
      } else {
        s.writeln('        _obj.${f.name} = _r.$read();');
      }
      break;
    case RecordFieldKind.enumValue:
      final base = f.dartType.replaceFirst('?', '');
      final t = enumNames.contains(base) ? base : 'int64_t';
      final readExpr = enumNames.contains(base) ? 'static_cast<$base>(_r.readInt())' : '_r.readInt()';
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$t>($readExpr); }');
      } else {
        s.writeln('        _obj.${f.name} = $readExpr;');
      }
      break;
    case RecordFieldKind.recordObject:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$base>($base::fromReader(_r)); }');
      } else {
        s.writeln('        _obj.${f.name} = $base::fromReader(_r);');
      }
      break;
    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'int';
      final read = _cppPrimRead(item);
      s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back(_r.$read()); }');
      break;
    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName ?? 'int64_t';
      final readExpr = enumNames.contains(item) ? 'static_cast<$item>(_r.readInt())' : '_r.readInt()';
      s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back($readExpr); }');
      break;
    case RecordFieldKind.listRecordObject:
      final item = f.itemTypeName!;
      s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back($item::fromReader(_r)); }');
      break;
    case RecordFieldKind.typedData:
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); if (!_null) { int32_t _n = _r.readInt32(); _obj.${f.name}.emplace().resize((size_t)_n); _r.readBytes(_obj.${f.name}->data(), (size_t)_n); } }');
      } else {
        s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.resize((size_t)_n); _r.readBytes(_obj.${f.name}.data(), (size_t)_n); }');
      }
      break;
    case RecordFieldKind.struct:
      // Structs are plain C typedefs from bridge.g.h — decoded via the
      // nitro_<Name>_fromReader free function (see generateCppStructCodecs).
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); if (!_null) _obj.${f.name} = nitro_${base}_fromReader(_r); }');
      } else {
        s.writeln('        _obj.${f.name} = nitro_${base}_fromReader(_r);');
      }
      break;
  }
}

void _cppEmitFieldWrite(CodeWriter s, BridgeRecordField f, Set<String> enumNames, Set<String> structNames) {
  // Presence flag convention: 1 = present, 0 = null (mirrors Dart writeBool /
  // readNullTag — a zero byte means null).
  final v = f.isNullable ? '(*${f.name})' : f.name;
  String core;
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final base = f.dartType.replaceFirst('?', '');
      core = base == 'String'
          ? 'w.writeString($v);'
          : base == 'double'
          ? 'w.writeDouble($v);'
          : base == 'bool'
          ? 'w.writeBool($v);'
          : 'w.writeInt($v);';
      break;
    case RecordFieldKind.enumValue:
      final base = f.dartType.replaceFirst('?', '');
      // Record enum fields use nativeValue on the wire (mirrors Dart
      // `writer.writeInt(field.nativeValue)`) — unlike variant fields (index).
      core = enumNames.contains(base) ? 'w.writeInt(static_cast<int64_t>($v));' : 'w.writeInt($v);';
      break;
    case RecordFieldKind.recordObject:
      core = '$v.encodeInto(w);';
      break;
    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'int';
      final itemWrite = item == 'String'
          ? 'w.writeString(_e);'
          : item == 'double'
          ? 'w.writeDouble(_e);'
          : item == 'bool'
          ? 'w.writeBool(_e);'
          : 'w.writeInt(_e);';
      core = '{ w.writeInt32((int32_t)${f.name}.size()); for (const auto& _e : ${f.name}) { $itemWrite } }';
      break;
    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName ?? 'int64_t';
      final itemWrite = enumNames.contains(item) ? 'w.writeInt(static_cast<int64_t>(_e));' : 'w.writeInt(_e);';
      core = '{ w.writeInt32((int32_t)${f.name}.size()); for (const auto& _e : ${f.name}) { $itemWrite } }';
      break;
    case RecordFieldKind.listRecordObject:
      core = '{ w.writeInt32((int32_t)${f.name}.size()); for (const auto& _e : ${f.name}) { _e.encodeInto(w); } }';
      break;
    case RecordFieldKind.typedData:
      core = '{ w.writeInt32((int32_t)$v.size()); w.writeBytes($v.data(), $v.size()); }';
      break;
    case RecordFieldKind.struct:
      final base = f.dartType.replaceFirst('?', '');
      core = 'nitro_${base}_encodeInto($v, w);';
      break;
  }
  final isListKind = f.kind == RecordFieldKind.listPrimitive || f.kind == RecordFieldKind.listEnumValue || f.kind == RecordFieldKind.listRecordObject;
  if (f.isNullable && !isListKind) {
    s.writeln('        w.writeBool(${f.name}.has_value());');
    s.writeln('        if (${f.name}.has_value()) { $core }');
  } else {
    s.writeln('        $core');
  }
}

/// Inline C++ definition of the bounds-checked record reader.
/// Emitted by [CppInterfaceGenerator] whenever records, variants, or structs
/// are present (the codecs above all depend on it).
const cppRecordReaderDefinition = '''
// Bounds-checked binary reader for @HybridRecord wire payloads.
// Every readNullTag() bounds-checks before the byte access (IMPROVEMENTS.md §3.3).
struct NitroRecordReader {
  const uint8_t* _data;
  size_t         _size;
  size_t         _offset;
  explicit NitroRecordReader(NitroCppBuffer buf)
      : _data(buf.data), _size(buf.size), _offset(0) {}
  explicit NitroRecordReader(const uint8_t* data, size_t size)
      : _data(data), _size(size), _offset(0) {}
private:
  void _require(size_t n) const {
      if (_offset + n > _size)
          throw std::runtime_error("NitroRecordReader: buffer underflow");
  }
public:
  int64_t readInt() {
      _require(8); int64_t v; std::memcpy(&v, _data + _offset, 8); _offset += 8; return v;
  }
  int32_t readInt32() {
      _require(4); int32_t v; std::memcpy(&v, _data + _offset, 4); _offset += 4; return v;
  }
  int8_t readInt8() {
      _require(1); return static_cast<int8_t>(_data[_offset++]);
  }
  double readDouble() {
      _require(8); uint64_t b; std::memcpy(&b, _data + _offset, 8);
      _offset += 8; double v; std::memcpy(&v, &b, 8); return v;
  }
  bool readBool() {
      _require(1); return _data[_offset++] != 0;
  }
  std::string readString() {
      int32_t len = readInt32(); _require((size_t)len);
      std::string s(reinterpret_cast<const char*>(_data + _offset), (size_t)len);
      _offset += (size_t)len; return s;
  }
  // Bounds-checked null tag read — throws if no byte remains.
  bool readNullTag() {
      if (_offset + 1 > _size)
          throw std::runtime_error("NitroRecordReader: null tag read past end of buffer");
      return _data[_offset++] == 0;
  }
  // TypedData blob: [4B count][count bytes] → reads into caller-owned vector.
  void readBytes(uint8_t* dst, size_t n) {
      _require(n); std::memcpy(dst, _data + _offset, n); _offset += n;
  }
};''';
