part of '../record_generator.dart';

// ── C++ record decoder generator ────────────────────────────────────────────

/// Generates C++ struct definitions and a bounds-checked `NitroRecordReader`
/// for every `@HybridRecord` type in the spec.  Emitted into the
/// `*.native.g.h` header so C++ native implementations can call
/// `MyRecord::fromNative(buf)` without hand-rolling binary parsing.
///
/// Safety guarantee: every `readNullTag()` call is preceded by an explicit
/// `if (offset + 1 > size)` check that throws `std::runtime_error`, preventing
/// out-of-bounds reads on malformed wire data (IMPROVEMENTS.md §3.3).
String _generateCppRecords(BridgeSpec spec) {
  final localRecords = spec.localRecordTypes;
  if (localRecords.isEmpty) return '';
  final enumNames = spec.enums.map((e) => e.name).toSet();

  final s = CodeWriter();

  // Forward declarations so mutually-referencing types compile in any order.
  s.writeln('// @HybridRecord C++ structs (generated by Nitrogen)');
  for (final rt in localRecords) {
    s.writeln('struct ${rt.name};');
  }
  s.writeln();

  // NitroRecordReader — shared helper used by all fromReader implementations.
  s.writeln(_cppRecordReaderDef);
  s.writeln();

  // Per-record struct + fromNative / fromReader.
  for (final rt in localRecords) {
    s.writeln('struct ${rt.name} {');
    for (final f in rt.fields) {
      s.writeln('    ${_cppFieldType(f, enumNames)} ${f.name};');
    }
    s.writeln();
    s.writeln('    static ${rt.name} fromNative(NitroCppBuffer buf) {');
    s.writeln('        NitroRecordReader _r(buf);');
    s.writeln('        return fromReader(_r);');
    s.writeln('    }');
    s.writeln();
    s.writeln('    static ${rt.name} fromReader(NitroRecordReader& _r) {');
    s.writeln('        ${rt.name} _obj;');
    for (final f in rt.fields) {
      _cppEmitFieldRead(s, f, enumNames);
    }
    s.writeln('        return _obj;');
    s.writeln('    }');
    s.writeln('};');
    s.writeln();
  }

  return s.toString();
}

String _cppFieldType(BridgeRecordField f, Set<String> enumNames) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final t = _cppPrimType(f.dartType.replaceFirst('?', ''));
      return f.isNullable ? 'std::optional<$t>' : t;
    case RecordFieldKind.enumValue:
      final base = f.dartType.replaceFirst('?', '');
      final t = enumNames.contains(base) ? base : 'int64_t';
      return f.isNullable ? 'std::optional<$t>' : t;
    case RecordFieldKind.recordObject:
      final base = f.dartType.replaceFirst('?', '');
      return f.isNullable ? 'std::optional<$base>' : base;
    case RecordFieldKind.listPrimitive:
      return 'std::vector<${_cppPrimType(f.itemTypeName ?? 'int')}>';
    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName ?? 'int64_t';
      return 'std::vector<${enumNames.contains(item) ? item : 'int64_t'}>';
    case RecordFieldKind.listRecordObject:
      return 'std::vector<${f.itemTypeName}>';
    case RecordFieldKind.typedData:
      return f.isNullable ? 'std::optional<std::vector<uint8_t>>' : 'std::vector<uint8_t>';
    case RecordFieldKind.struct:
      final base = f.dartType.replaceFirst('?', '');
      return f.isNullable ? 'std::optional<$base>' : base;
  }
}

String _cppPrimType(String dartType) {
  switch (dartType) {
    case 'int':
      return 'int64_t';
    case 'double':
      return 'double';
    case 'bool':
      return 'bool';
    case 'String':
      return 'std::string';
    default:
      return 'int64_t';
  }
}

String _cppPrimRead(String dartType) {
  switch (dartType) {
    case 'int':
      return 'readInt';
    case 'double':
      return 'readDouble';
    case 'bool':
      return 'readBool';
    case 'String':
      return 'readString';
    default:
      return 'readInt';
  }
}

void _cppEmitFieldRead(CodeWriter s, BridgeRecordField f, Set<String> enumNames) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final base = f.dartType.replaceFirst('?', '');
      final t = _cppPrimType(base);
      final read = _cppPrimRead(base);
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$t>(_r.$read()); }');
      } else {
        s.writeln('        _obj.${f.name} = _r.$read();');
      }
      break;
    case RecordFieldKind.enumValue:
      final base = f.dartType.replaceFirst('?', '');
      final t = enumNames.contains(base) ? base : 'int64_t';
      final readExpr = enumNames.contains(base) ? 'static_cast<$base>(_r.readInt())' : '_r.readInt()';
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$t>($readExpr); }');
      } else {
        s.writeln('        _obj.${f.name} = $readExpr;');
      }
      break;
    case RecordFieldKind.recordObject:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$base>($base::fromReader(_r)); }');
      } else {
        s.writeln('        _obj.${f.name} = $base::fromReader(_r);');
      }
      break;
    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'int';
      final read = _cppPrimRead(item);
      s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back(_r.$read()); }');
      break;
    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName ?? 'int64_t';
      final readExpr = enumNames.contains(item) ? 'static_cast<$item>(_r.readInt())' : '_r.readInt()';
      s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back($readExpr); }');
      break;
    case RecordFieldKind.listRecordObject:
      final item = f.itemTypeName!;
      s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back($item::fromReader(_r)); }');
      break;
    case RecordFieldKind.typedData:
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); if (!_null) { int32_t _n = _r.readInt32(); _obj.${f.name}.emplace().resize((size_t)_n); _r.readBytes(_obj.${f.name}->data(), (size_t)_n); } }');
      } else {
        s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.resize((size_t)_n); _r.readBytes(_obj.${f.name}.data(), (size_t)_n); }');
      }
      break;
    case RecordFieldKind.struct:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        s.writeln('        { bool _null = _r.readNullTag(); if (!_null) _obj.${f.name} = $base::fromReader(_r); }');
      } else {
        s.writeln('        _obj.${f.name} = $base::fromReader(_r);');
      }
      break;
  }
}

/// Inline C++ definition of the bounds-checked record reader.
const _cppRecordReaderDef = '''
// Bounds-checked binary reader for @HybridRecord wire payloads.
// Every readNullTag() bounds-checks before the byte access (IMPROVEMENTS.md §3.3).
struct NitroRecordReader {
  const uint8_t* _data;
  size_t         _size;
  size_t         _offset;
  explicit NitroRecordReader(NitroCppBuffer buf)
      : _data(buf.data), _size(buf.size), _offset(0) {}
  explicit NitroRecordReader(const uint8_t* data, size_t size)
      : _data(data), _size(size), _offset(0) {}
private:
  void _require(size_t n) const {
      if (_offset + n > _size)
          throw std::runtime_error("NitroRecordReader: buffer underflow");
  }
public:
  int64_t readInt() {
      _require(8); int64_t v; std::memcpy(&v, _data + _offset, 8); _offset += 8; return v;
  }
  int32_t readInt32() {
      _require(4); int32_t v; std::memcpy(&v, _data + _offset, 4); _offset += 4; return v;
  }
  double readDouble() {
      _require(8); uint64_t b; std::memcpy(&b, _data + _offset, 8);
      _offset += 8; double v; std::memcpy(&v, &b, 8); return v;
  }
  bool readBool() {
      _require(1); return _data[_offset++] != 0;
  }
  std::string readString() {
      int32_t len = readInt32(); _require((size_t)len);
      std::string s(reinterpret_cast<const char*>(_data + _offset), (size_t)len);
      _offset += (size_t)len; return s;
  }
  // Bounds-checked null tag read — throws if no byte remains.
  bool readNullTag() {
      if (_offset + 1 > _size)
          throw std::runtime_error("NitroRecordReader: null tag read past end of buffer");
      return _data[_offset++] == 0;
  }
  // TypedData blob: [4B count][count bytes] → reads into caller-owned vector.
  void readBytes(uint8_t* dst, size_t n) {
      _require(n); std::memcpy(dst, _data + _offset, n); _offset += n;
  }
};''';

