part of '../record_generator.dart';

String _generateDartRecordExtensions(BridgeSpec spec) {
  // Exclude built-in library types: their Dart codec is already on the class
  // in package:nitro/src/nitro_nullable.dart; generating an extension would
  // duplicate methods and cause "already defined" compile errors.
  final allLocalRecords = spec.localRecordTypes.where((r) => !_nitroLibraryRecordTypes.contains(r.name)).toList();
  // Tuples emit standalone free functions; named records emit extension methods.
  final localTuples = allLocalRecords.where((r) => r.isTuple).toList();
  final localRecords = allLocalRecords.where((r) => !r.isTuple).toList();

  // Compute referencedStructs before the early-return so that modules with
  // NO @HybridRecord types (localRecords.isEmpty) but with List<@HybridStruct T>
  // method returns still get their ${T}RecordExt extensions emitted.
  final structMap = {for (final st in spec.structs) st.name: st};
  final enumNames = spec.enums.map((e) => e.name).toSet();
  final structNames = spec.structs.map((s) => s.name).toSet();

  // Collect structs directly referenced in record fields, then transitively.
  final referencedStructs = <String>{};
  for (final rt in localRecords) {
    for (final f in rt.fields) {
      if (f.kind == RecordFieldKind.recordObject || f.kind == RecordFieldKind.listRecordObject) {
        final typeName = f.kind == RecordFieldKind.listRecordObject ? (f.itemTypeName ?? f.dartType.replaceFirst('?', '')) : f.dartType.replaceFirst('?', '');
        if (structMap.containsKey(typeName)) referencedStructs.add(typeName);
      }
      // @HybridStruct embedded in @HybridRecord — needs RecordExt (fromReader/writeFields).
      if (f.kind == RecordFieldKind.struct) {
        final base = f.dartType.replaceFirst('?', '');
        if (structMap.containsKey(base)) referencedStructs.add(base);
      }
    }
  }

  // Also include structs appearing as List<@HybridStruct T> return types on methods/properties.
  for (final func in spec.functions) {
    final item = func.returnType.recordListItemType;
    if (item != null && !func.returnType.recordListItemIsPrimitive && structMap.containsKey(item) && !spec.isRecordName(item)) {
      referencedStructs.add(item);
    }
  }
  for (final prop in spec.properties) {
    final item = prop.type.recordListItemType;
    if (item != null && !prop.type.recordListItemIsPrimitive && structMap.containsKey(item) && !spec.isRecordName(item)) {
      referencedStructs.add(item);
    }
  }

  void collectNestedDart(String typeName) {
    final st = structMap[typeName];
    if (st == null) return;
    for (final f in st.fields) {
      final base = f.type.name.replaceFirst('?', '');
      if (structMap.containsKey(base) && !referencedStructs.contains(base)) {
        referencedStructs.add(base);
        collectNestedDart(base);
      }
    }
  }

  for (final name in referencedStructs.toList()) {
    collectNestedDart(name);
  }

  if (localRecords.isEmpty && localTuples.isEmpty && referencedStructs.isEmpty) return '';

  final s = CodeWriter();
  s.writeln(
    '// --- @HybridRecord binary extensions (generated by Nitrogen) ---',
  );
  s.writeln();

  for (final stName in referencedStructs) {
    final st = structMap[stName]!;
    s.writeln('extension ${st.name}RecordExt on ${st.name} {');

    // fromNative
    s.writeln('  static ${st.name} fromNative(Pointer<Uint8> ptr) =>');
    s.writeln('      fromReader(RecordReader.fromNative(ptr));');
    s.writeln();

    // fromReader
    s.writeln('  static ${st.name} fromReader(RecordReader r) =>');
    s.writeln('      ${st.name}(');
    for (final f in st.fields.where((f) => !f.isNamed)) {
      s.writeln('        ${_structFieldReadExpr(f, enumNames, structNames)},');
    }
    for (final f in st.fields.where((f) => f.isNamed)) {
      s.writeln('        ${f.name}: ${_structFieldReadExpr(f, enumNames, structNames)},');
    }
    s.writeln('      );');
    s.writeln();

    // writeFields
    s.writeln('  void writeFields(RecordWriter writer) {');
    for (final f in st.fields) {
      _writeStructFieldStmt(s, f, enumNames, structNames);
    }
    s.writeln('  }');
    // NOTE: toNative(Allocator) is intentionally omitted for @HybridStruct types.
    // The struct already has XxxExt.toNative(Arena arena) via its FFI extension,
    // and Arena implements Allocator, so emitting a second toNative(Allocator)
    // here would create an ambiguous call-site error ("member defined in both
    // XxxExt and XxxRecordExt"). Nested serialisation only needs writeFields.
    s.writeln('}');
    s.writeln();
  }

  for (final rt in localRecords) {
    s.writeln('extension ${rt.name}RecordExt on ${rt.name} {');

    // ── static fromNative (top-level, with 4-byte length prefix) ──────
    s.writeln(
      '  static ${rt.name} fromNative(Pointer<Uint8> ptr) =>',
    );
    s.writeln('      fromReader(RecordReader.fromNative(ptr));');
    s.writeln();

    // ── static fromReader (inner, for use inside lists) ───────────────
    s.writeln(
      '  static ${rt.name} fromReader(RecordReader r) =>',
    );
    s.writeln('      ${rt.name}(');
    for (final f in rt.fields) {
      s.writeln('        ${f.name}: ${_readExpr(f)},');
    }
    s.writeln('      );');
    s.writeln();

    // ── writeFields (inner, for use inside lists) ─────────────────────
    s.writeln('  void writeFields(RecordWriter writer) {');
    for (final f in rt.fields) {
      _writeFieldStmt(s, f);
    }
    s.writeln('  }');
    s.writeln();

    // ── toNative (top-level, allocates native buffer) ─────────────────
    s.writeln('  Pointer<Uint8> toNative(Allocator alloc) {');
    s.writeln('    final writer = RecordWriter();');
    s.writeln('    writeFields(writer);');
    s.writeln('    return writer.toNative(alloc);');
    s.writeln('  }');

    s.writeln('}');
    s.writeln();
  }

  // ── @NitroTuple free functions ────────────────────────────────────────────
  // Dart 3 typedefs cannot have extension methods, so tuples get standalone
  // free functions: _nitroDecode_<Name>, _nitroDecodeNullable_<Name>,
  // _nitroEncode_<Name>. Called from _decodeRecordExpr / _encodeRecordParam.
  for (final rt in localTuples) {
    s.writeln('// --- @NitroTuple encode/decode for ${rt.name} ---');

    // Build the inline Dart 3 tuple type string from fields, e.g. "(int, String)".
    final fieldTypes = rt.fields
        .map((f) {
          if (f.isNullable) return '${f.dartType.replaceFirst("?", "")}?';
          return f.dartType;
        })
        .join(', ');
    final tupleType = '($fieldTypes)';

    // ── _nitroDecode_<Name> ──
    s.writeln('$tupleType _nitroDecode_${rt.name}(Pointer<Uint8> ptr) {');
    s.writeln('  final r = RecordReader.fromNative(ptr);');
    final fieldExprs = rt.fields.map((f) => _readExpr(f)).join(', ');
    s.writeln('  return ($fieldExprs);');
    s.writeln('}');
    s.writeln();

    // ── _nitroDecodeNullable_<Name> ──
    s.writeln('$tupleType? _nitroDecodeNullable_${rt.name}(Pointer<Uint8> ptr) {');
    s.writeln('  if (ptr == nullptr) return null;');
    s.writeln('  return _nitroDecode_${rt.name}(ptr);');
    s.writeln('}');
    s.writeln();

    // ── _nitroEncode_<Name> ──
    s.writeln('Pointer<Uint8> _nitroEncode_${rt.name}($tupleType v, Allocator alloc) {');
    s.writeln('  final writer = RecordWriter();');
    for (var i = 0; i < rt.fields.length; i++) {
      _writeTupleFieldStmt(s, rt.fields[i], i + 1);
    }
    s.writeln('  return writer.toNative(alloc);');
    s.writeln('}');
    s.writeln();
  }

  return s.toString();
}

// ── @NitroTuple write statement helpers ────────────────────────────────────
// Like _writeFieldStmt but accesses tuple fields via v.$N positional accessors.

void _writeTupleFieldStmt(CodeWriter s, BridgeRecordField f, int index) {
  final accessor = 'v.\$$index';
  switch (f.kind) {
    case RecordFieldKind.primitive:
      _writePrimitiveStmt(s, f.dartType, accessor);
      break;
    case RecordFieldKind.enumValue:
      if (f.isNullable) {
        s.writeln('  writer.writeNullTag($accessor == null);');
        s.writeln('  if ($accessor != null) { writer.writeInt($accessor!.nativeValue); }');
      } else {
        s.writeln('  writer.writeInt($accessor.nativeValue);');
      }
      break;
    case RecordFieldKind.recordObject:
      if (f.isNullable) {
        s.writeln('  writer.writeNullTag($accessor == null);');
        s.writeln('  if ($accessor != null) { $accessor!.writeFields(writer); }');
      } else {
        s.writeln('  $accessor.writeFields(writer);');
      }
      break;
    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'dynamic';
      final writeCall = _primitiveWriteCall(item, 'e');
      s.writeln('  writer.writeInt32($accessor.length);');
      s.writeln('  for (final e in $accessor) { writer.$writeCall; }');
      break;
    case RecordFieldKind.listEnumValue:
      s.writeln('  writer.writeInt32($accessor.length);');
      s.writeln('  for (final e in $accessor) { writer.writeInt(e.nativeValue); }');
      break;
    case RecordFieldKind.listRecordObject:
      s.writeln('  writer.writeInt32($accessor.length);');
      s.writeln('  for (final e in $accessor) { e.writeFields(writer); }');
      break;
    case RecordFieldKind.typedData:
      final base = f.dartType.replaceFirst('?', '');
      final toBytes = base == 'Uint8List' ? accessor : '$accessor.buffer.asUint8List()';
      if (f.isNullable) {
        s.writeln('  writer.writeNullTag($accessor == null);');
        s.writeln('  if ($accessor != null) { writer.writeBlob($toBytes!); }');
      } else {
        s.writeln('  writer.writeBlob($toBytes);');
      }
      break;
    case RecordFieldKind.struct:
      if (f.isNullable) {
        s.writeln('  writer.writeNullTag($accessor == null);');
        s.writeln('  $accessor?.writeFields(writer);');
      } else {
        s.writeln('  $accessor.writeFields(writer);');
      }
      break;
  }
}

// ── Read expression helpers ─────────────────────────────────────────────

String _readExpr(BridgeRecordField f) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      return _primitiveReadExpr(f.dartType);

    case RecordFieldKind.enumValue:
      final baseType = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        return 'r.readNullTag() ? null : r.readInt().to$baseType()';
      }
      return 'r.readInt().to$baseType()';

    case RecordFieldKind.recordObject:
      final baseType = f.dartType.replaceFirst('?', '');
      // Built-in library types (NitroNullableInt etc.) define fromReader on the
      // class itself — call directly. All others use the generated RecordExt.
      final readerCall = _nitroLibraryRecordTypes.contains(baseType) ? '$baseType.fromReader(r)' : '${baseType}RecordExt.fromReader(r)';
      if (f.isNullable) {
        return 'r.readNullTag() ? null : $readerCall';
      }
      return readerCall;

    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'dynamic';
      return 'List.generate(r.readInt32(), (_) => ${_primitiveReadCall(item)})';

    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName!;
      return 'List.generate(r.readInt32(), (_) => r.readInt().to$item())';

    case RecordFieldKind.listRecordObject:
      final item = f.itemTypeName!;
      final itemReaderCall = _nitroLibraryRecordTypes.contains(item) ? '$item.fromReader(r)' : '${item}RecordExt.fromReader(r)';
      return 'List.generate(r.readInt32(), (_) => $itemReaderCall)';

    case RecordFieldKind.typedData:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        return 'r.readNullTag() ? null : ${_typedDataReadCall(base)}';
      }
      return _typedDataReadCall(base);

    case RecordFieldKind.struct:
      // @HybridStruct embedded inline — read via RecordReader using the struct's RecordExt.
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        return 'r.readNullTag() ? null : ${base}RecordExt.fromReader(r)';
      }
      return '${base}RecordExt.fromReader(r)';
  }
}

/// Read expression for a TypedData field from a RecordReader.
/// All TypedData types are stored as [4B element_count][element_bytes].
/// Uint8List uses readBlob() directly; others use buffer view over readBlob().
String _typedDataReadCall(String dartType) {
  switch (dartType) {
    case 'Uint8List':
      return 'r.readBlob()';
    case 'Int8List':
      return 'Int8List.view(r.readBlob().buffer)';
    case 'Int16List':
      return 'Int16List.view(r.readBlob().buffer)';
    case 'Uint16List':
      return 'Uint16List.view(r.readBlob().buffer)';
    case 'Int32List':
      return 'Int32List.view(r.readBlob().buffer)';
    case 'Uint32List':
      return 'Uint32List.view(r.readBlob().buffer)';
    case 'Int64List':
      return 'Int64List.view(r.readBlob().buffer)';
    case 'Uint64List':
      return 'Uint64List.view(r.readBlob().buffer)';
    case 'Float32List':
      return 'Float32List.view(r.readBlob().buffer)';
    case 'Float64List':
      return 'Float64List.view(r.readBlob().buffer)';
    default:
      return 'r.readBlob()';
  }
}

String _primitiveReadExpr(String dartType) {
  final base = dartType.replaceFirst('?', '');
  final nullable = dartType.endsWith('?');
  if (nullable) {
    return 'r.readNullTag() ? null : ${_primitiveReadCall(base)}';
  }
  return _primitiveReadCall(base);
}

String _primitiveReadCall(String base) {
  switch (base) {
    case 'int':
      return 'r.readInt()';
    case 'double':
      return 'r.readDouble()';
    case 'bool':
      return 'r.readBool()';
    case 'String':
      return 'r.readString()';
    case 'Uint8List':
      return 'r.readBlob()';
    default:
      return 'r.readInt()';
  }
}

// ── Write statement helpers ─────────────────────────────────────────────

void _writeFieldStmt(CodeWriter s, BridgeRecordField f) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      _writePrimitiveStmt(s, f.dartType, f.name);
      break;

    case RecordFieldKind.enumValue:
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == null);');
        s.writeln('    if (${f.name} != null) {');
        s.writeln('      writer.writeInt(${f.name}!.nativeValue);');
        s.writeln('    }');
      } else {
        s.writeln('    writer.writeInt(${f.name}.nativeValue);');
      }
      break;

    case RecordFieldKind.recordObject:
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == null);');
        s.writeln('    if (${f.name} != null) {');
        s.writeln('      ${f.name}!.writeFields(writer);');
        s.writeln('    }');
      } else {
        s.writeln('    ${f.name}.writeFields(writer);');
      }
      break;

    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'dynamic';
      final writeCall = _primitiveWriteCall(item, 'e');
      s.writeln('    writer.writeInt32(${f.name}.length);');
      s.writeln('    for (final e in ${f.name}) { writer.$writeCall; }');
      break;

    case RecordFieldKind.listEnumValue:
      s.writeln('    writer.writeInt32(${f.name}.length);');
      s.writeln('    for (final e in ${f.name}) { writer.writeInt(e.nativeValue); }');
      break;

    case RecordFieldKind.listRecordObject:
      s.writeln('    writer.writeInt32(${f.name}.length);');
      s.writeln('    for (final e in ${f.name}) { e.writeFields(writer); }');
      break;

    case RecordFieldKind.typedData:
      // TypedData: convert to Uint8List bytes via .buffer.asUint8List() then writeBlob.
      final base = f.dartType.replaceFirst('?', '');
      final toBytes = base == 'Uint8List' ? f.name : '${f.name}.buffer.asUint8List()';
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == null);');
        s.writeln('    if (${f.name} != null) {');
        final toBytesNonNull = base == 'Uint8List' ? '${f.name}!' : '${f.name}!.buffer.asUint8List()';
        s.writeln('      writer.writeBlob($toBytesNonNull);');
        s.writeln('    }');
      } else {
        s.writeln('    writer.writeBlob($toBytes);');
      }
      break;

    case RecordFieldKind.struct:
      // @HybridStruct embedded inline — write via the struct's RecordExt.writeFields.
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == null);');
        s.writeln('    ${f.name}?.writeFields(writer);');
      } else {
        s.writeln('    ${f.name}.writeFields(writer);');
      }
      break;
  }
}

void _writePrimitiveStmt(
  CodeWriter s,
  String dartType,
  String fieldName,
) {
  final base = dartType.replaceFirst('?', '');
  final nullable = dartType.endsWith('?');
  if (nullable) {
    s.writeln('    writer.writeNullTag($fieldName == null);');
    s.writeln('    if ($fieldName != null) {');
    s.writeln('      writer.${_primitiveWriteCall(base, '$fieldName!')};');
    s.writeln('    }');
  } else {
    s.writeln('    writer.${_primitiveWriteCall(base, fieldName)};');
  }
}

String _primitiveWriteCall(String base, String expr) {
  switch (base) {
    case 'int':
      return 'writeInt($expr)';
    case 'double':
      return 'writeDouble($expr)';
    case 'bool':
      return 'writeBool($expr)';
    case 'String':
      return 'writeString($expr)';
    case 'Uint8List':
      return 'writeBlob($expr)';
    default:
      return 'writeInt($expr)';
  }
}

// ── Struct field read/write helpers (for RecordExt generated above) ───────────

/// Dart read expression for one field of a @HybridStruct embedded in a record.
String _structFieldReadExpr(BridgeField f, Set<String> enumNames, Set<String> structNames) {
  final base = f.type.name.replaceFirst('?', '');
  if (enumNames.contains(base)) return _primitiveReadCall('int');
  if (structNames.contains(base)) return '${base}RecordExt.fromReader(r)';
  return _primitiveReadCall(base);
}

/// Emits a Dart write statement for one field of a @HybridStruct embedded in a record.
void _writeStructFieldStmt(
  CodeWriter s,
  BridgeField f,
  Set<String> enumNames,
  Set<String> structNames,
) {
  final base = f.type.name.replaceFirst('?', '');
  if (enumNames.contains(base)) {
    s.writeln('    writer.${_primitiveWriteCall('int', '${f.name}.nativeValue')};');
  } else if (structNames.contains(base)) {
    s.writeln('    ${f.name}.writeFields(writer);');
  } else {
    _writePrimitiveStmt(s, f.type.name, f.name);
  }
}
