part of '../record_generator.dart';

// ── Kotlin generator ────────────────────────────────────────────────────────

/// Generates `@Keep data class` declarations for every `@HybridRecord` type
/// into the Kotlin bridge file.  Each class also gets static `decode` /
/// `encode` helpers so callers never have to hand-roll ByteArray parsing.
String _generateKotlinRecords(BridgeSpec spec) {
  final localRecords = spec.localRecordTypes;
  if (localRecords.isEmpty) return '';
  final enumNames = spec.enums.map((e) => e.name).toSet();

  final s = CodeWriter();
  s.writeln('// --- @HybridRecord Kotlin data classes (generated by Nitrogen) ---');
  s.writeln();

  for (final rt in localRecords) {
    final fields = rt.fields.map((f) => 'val ${f.name}: ${_kotlinType(f, enumNames)}').join(', ');
    s.writeln('@androidx.annotation.Keep');
    s.writeln('data class ${rt.name}($fields) {');

    // --- companion: decodeFrom(buf) reads fields from a shared ByteBuffer cursor ---
    //                decode(bytes) wraps a standalone ByteArray (strips 4-byte prefix)
    s.writeln('    companion object {');
    s.writeln('        @JvmStatic fun decodeFrom(buf: java.nio.ByteBuffer): ${rt.name} {');
    for (final f in rt.fields) {
      s.writeln('            val ${f.name} = ${_kotlinReadExpr(f, enumNames)}');
    }
    final ctorArgs = rt.fields.map((f) => f.name).join(', ');
    s.writeln('            return ${rt.name}($ctorArgs)');
    s.writeln('        }');
    s.writeln('        @JvmStatic fun decode(bytes: ByteArray): ${rt.name} {');
    s.writeln('            val buf = java.nio.ByteBuffer.wrap(bytes).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
    s.writeln('            buf.position(4) // skip 4-byte length prefix');
    s.writeln('            return decodeFrom(buf)');
    s.writeln('        }');
    // --- fromJson() for Map<String, ${rt.name}> support (#2) ---
    final companionFromJsonFields = rt.fields.map((f) {
      final base = f.dartType.replaceFirst('?', '');
      switch (f.kind) {
        case RecordFieldKind.primitive:
          final kBase = f.dartType.replaceFirst('?', '');
          if (f.isNullable) {
            if (kBase == 'int') return '${f.name} = (map["${f.name}"] as Number?)?.toLong()';
            if (kBase == 'double') return '${f.name} = (map["${f.name}"] as Number?)?.toDouble()';
            if (kBase == 'bool') return '${f.name} = map["${f.name}"] as Boolean?';
            return '${f.name} = map["${f.name}"] as String?';
          }
          if (kBase == 'int') return '${f.name} = (map["${f.name}"] as Number).toLong()';
          if (kBase == 'double') return '${f.name} = (map["${f.name}"] as Number).toDouble()';
          if (kBase == 'bool') return '${f.name} = map["${f.name}"] as Boolean';
          return '${f.name} = map["${f.name}"] as String';
        case RecordFieldKind.enumValue:
          return f.isNullable
              ? '${f.name} = (map["${f.name}"] as Long?)?.let { $base.fromNative(it) }'
              : '${f.name} = $base.fromNative(map["${f.name}"] as Long)';
        case RecordFieldKind.recordObject:
          // @Suppress must be on the EXPRESSION, not on the named argument itself.
          return f.isNullable
              ? '${f.name} = (map["${f.name}"] as? Map<*, *>)?.let { $base.fromJson(@Suppress("UNCHECKED_CAST") (it as Map<String, Any?>)) }'
              : '${f.name} = $base.fromJson(@Suppress("UNCHECKED_CAST") (map["${f.name}"] as Map<String, Any?>))';
        case RecordFieldKind.struct:
          // @HybridStruct in a record — structs don't have fromJson.
          // fromJson is used for Map<String,@HybridRecord>; struct fields not supported there.
          return '${f.name} = ${f.isNullable ? "null" : "throw UnsupportedOperationException(\"Struct field \\'${f.name}\\' cannot be reconstructed from JSON — use binary bridge instead\")"}';
        default:
          return '${f.name} = @Suppress("UNCHECKED_CAST") (map["${f.name}"] as ${_kotlinType(f, enumNames)})';
      }
    }).join(',\n                ');
    s.writeln('        @Suppress("UNCHECKED_CAST")');
    s.writeln('        @JvmStatic fun fromJson(map: Map<String, Any?>): ${rt.name} = ${rt.name}(');
    s.writeln('                $companionFromJsonFields');
    s.writeln('        )');
    // Thread-local encode buffers (#8 perf): avoid per-call ByteArrayOutputStream allocation.
    s.writeln('        // Thread-local encode buffers — avoids allocation per bridge call.');
    s.writeln('        val _tlsOut = ThreadLocal.withInitial { java.io.ByteArrayOutputStream(${_recordBytesHint(rt)}) }');
    s.writeln('        val _tlsBuf = ThreadLocal.withInitial { java.nio.ByteBuffer.allocate(8).order(java.nio.ByteOrder.LITTLE_ENDIAN) }');
    s.writeln('    }');
    // ── Built-in NitroNullable types: add nullable getter + single-arg constructor ──
    // These are used by the bridge to wrap/unwrap nullable primitives without sentinels.
    if (rt.name == 'NitroNullableInt') {
      s.writeln('    constructor(v: Long?) : this(v != null, v ?: 0L)');
      s.writeln('    val nullable: Long? get() = if (hasValue) value else null');
    } else if (rt.name == 'NitroNullableDouble') {
      s.writeln('    constructor(v: Double?) : this(v != null, v ?: 0.0)');
      s.writeln('    val nullable: Double? get() = if (hasValue) value else null');
    } else if (rt.name == 'NitroNullableBool') {
      s.writeln('    constructor(v: Boolean?) : this(v != null, v ?: false)');
      s.writeln('    val nullable: Boolean? get() = if (hasValue) value else null');
    }
    s.writeln();

    // --- writeFieldsTo: writes fields without length prefix (for use inside lists) ---
    s.writeln('    fun writeFieldsTo(out: java.io.ByteArrayOutputStream, buf: java.nio.ByteBuffer) {');
    s.writeln('        fun writeInt(v: Long) { buf.clear(); buf.putLong(v); out.write(buf.array()) }');
    s.writeln('        fun writeInt32(v: Int) { buf.clear(); buf.putInt(v); out.write(buf.array(), 0, 4) }');
    s.writeln('        fun writeDouble(v: Double) { buf.clear(); buf.putDouble(v); out.write(buf.array()) }');
    s.writeln('        fun writeBool(v: Boolean) { out.write(if (v) 1 else 0) }');
    s.writeln('        fun writeString(v: String) { val b = v.toByteArray(Charsets.UTF_8); writeInt32(b.size); out.write(b) }');
    for (final f in rt.fields) {
      _kotlinWriteStmt(s, f);
    }
    s.writeln('    }');
    s.writeln();

    // --- encode to ByteArray (with 4-byte length prefix) ---
    // Thread-local buffers avoid per-call ByteArrayOutputStream/ByteBuffer allocation (#8 perf).
    s.writeln('    fun encode(): ByteArray {');
    s.writeln('        val out = _tlsOut.get()!!.also { it.reset() }');
    s.writeln('        val buf = _tlsBuf.get()!!');
    s.writeln('        writeFieldsTo(out, buf)');
    s.writeln('        val payload = out.toByteArray()');
    s.writeln('        val lenBuf = java.nio.ByteBuffer.allocate(4).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
    s.writeln('        lenBuf.putInt(payload.size)');
    s.writeln('        return lenBuf.array() + payload');
    s.writeln('    }');
    s.writeln();

    // --- toJson() / fromJson() for Map<String, @HybridRecord> support (#2) ---
    // Allows Kotlin bridge to serialize/deserialize when used as Map values.
    s.writeln('    // --- toJson/fromJson for Map<String, ${rt.name}> support ---');
    final toJsonFields = rt.fields.map((f) {
      switch (f.kind) {
        case RecordFieldKind.enumValue:
          return f.isNullable
              ? '"${f.name}" to ${f.name}?.nativeValue'
              : '"${f.name}" to ${f.name}.nativeValue';
        case RecordFieldKind.recordObject:
          return f.isNullable
              ? '"${f.name}" to ${f.name}?.toJson()'
              : '"${f.name}" to ${f.name}.toJson()';
        case RecordFieldKind.listPrimitive:
        case RecordFieldKind.listEnumValue:
        case RecordFieldKind.listRecordObject:
          return '"${f.name}" to ${f.name}';
        case RecordFieldKind.typedData:
          return '"${f.name}" to ${f.name}';
        case RecordFieldKind.struct:
          return '"${f.name}" to ${f.name}';
        default: // primitive
          return '"${f.name}" to ${f.name}';
      }
    }).join(', ');
    s.writeln('    fun toJson(): Map<String, Any?> = mapOf($toJsonFields)');
    s.writeln();

    s.writeln('}');
    s.writeln();
  }

  return s.toString();
}

String _kotlinType(BridgeRecordField f, Set<String> enumNames) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      return _kotlinBase(f.dartType) + (f.isNullable ? '?' : '');
    case RecordFieldKind.enumValue:
      final base = f.dartType.replaceFirst('?', '');
      return (enumNames.contains(base) ? base : 'Long') + (f.isNullable ? '?' : '');
    case RecordFieldKind.recordObject:
      final base = f.dartType.replaceFirst('?', '');
      return base + (f.isNullable ? '?' : '');
    case RecordFieldKind.listPrimitive:
      return 'List<${_kotlinBase(f.itemTypeName ?? 'int')}>';
    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName ?? 'Long';
      return 'List<${enumNames.contains(item) ? item : 'Long'}>';
    case RecordFieldKind.listRecordObject:
      return 'List<${f.itemTypeName}>';
    case RecordFieldKind.typedData:
      final kotlinType = _kotlinTypedDataType(f.dartType.replaceFirst('?', ''));
      return kotlinType + (f.isNullable ? '?' : '');
    case RecordFieldKind.struct:
      return f.dartType.replaceFirst('?', '') + (f.isNullable ? '?' : '');
  }
}

String _kotlinTypedDataType(String dartType) {
  switch (dartType) {
    case 'Uint8List':
    case 'Int8List':   return 'ByteArray';
    case 'Int16List':
    case 'Uint16List': return 'ShortArray';
    case 'Int32List':
    case 'Uint32List': return 'IntArray';
    case 'Int64List':
    case 'Uint64List': return 'LongArray';
    case 'Float32List': return 'FloatArray';
    case 'Float64List': return 'DoubleArray';
    default: return 'ByteArray';
  }
}

String _kotlinBase(String dartType) {
  final base = dartType.replaceFirst('?', '');
  switch (base) {
    case 'int':
      return 'Long';
    case 'double':
      return 'Double';
    case 'bool':
      return 'Boolean';
    case 'String':
      return 'String';
    default:
      return 'Long';
  }
}

String _kotlinReadExpr(BridgeRecordField f, Set<String> enumNames) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        return '(if (buf.get().toInt() == 0) null else ${_kotlinPrimRead(base)})';
      }
      return _kotlinPrimRead(base);
    case RecordFieldKind.enumValue:
      final base = f.dartType.replaceFirst('?', '');
      final read = enumNames.contains(base) ? '$base.fromNative(buf.long)' : 'buf.long';
      if (f.isNullable) {
        return '(if (buf.get().toInt() == 0) null else $read)';
      }
      return read;
    case RecordFieldKind.recordObject:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        return '(if (buf.get().toInt() == 0) null else $base.decodeFrom(buf))';
      }
      return '$base.decodeFrom(buf)';
    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'int';
      return '(0 until buf.int).map { ${_kotlinPrimRead(item)} }';
    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName ?? 'Long';
      final read = enumNames.contains(item) ? '$item.fromNative(buf.long)' : 'buf.long';
      return '(0 until buf.int).map { $read }';
    case RecordFieldKind.listRecordObject:
      final item = f.itemTypeName!;
      return '(0 until buf.int).map { $item.decodeFrom(buf) }';
    case RecordFieldKind.typedData:
      final base = f.dartType.replaceFirst('?', '');
      final read = _kotlinTypedDataRead(base);
      if (f.isNullable) {
        return '(if (buf.get().toInt() == 0) null else $read)';
      }
      return read;
    case RecordFieldKind.struct:
      final structBase = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        return '(if (buf.get().toInt() == 0) null else $structBase.decodeFrom(buf))';
      }
      return '$structBase.decodeFrom(buf)';
  }
}

String _kotlinTypedDataRead(String dartType) {
  // Wire format: [4B byteCount][byteCount bytes] — byte count, not element count.
  // Dart writes byte count via writeBlob(TypedData.buffer.asUint8List()).
  // Kotlin must divide by element size to get element count.
  switch (dartType) {
    case 'Uint8List':
    case 'Int8List':   return '{ val _len = buf.int; val _b = ByteArray(_len); buf.get(_b); _b }()';
    case 'Int16List':
    case 'Uint16List': return '{ val _len = buf.int; ShortArray(_len / 2) { buf.short } }()';
    case 'Int32List':
    case 'Uint32List': return '{ val _len = buf.int; IntArray(_len / 4) { buf.int } }()';
    case 'Int64List':
    case 'Uint64List': return '{ val _len = buf.int; LongArray(_len / 8) { buf.long } }()';
    case 'Float32List': return '{ val _len = buf.int; FloatArray(_len / 4) { buf.float } }()';
    case 'Float64List': return '{ val _len = buf.int; DoubleArray(_len / 8) { buf.double } }()';
    default: return '{ val _len = buf.int; val _b = ByteArray(_len); buf.get(_b); _b }()';
  }
}

String _kotlinPrimRead(String base) {
  switch (base) {
    case 'int':
      return 'buf.long';
    case 'double':
      return 'buf.double';
    case 'bool':
      return '(buf.get().toInt() != 0)';
    case 'String':
      return '{ val len = buf.int; val b = ByteArray(len); buf.get(b); b.toString(Charsets.UTF_8) }()';
    case 'Uint8List':
    case 'ByteArray':
      return '{ val len = buf.int; val b = ByteArray(len); buf.get(b); b }()';
    default:
      return 'buf.long';
  }
}

void _kotlinWriteStmt(CodeWriter s, BridgeRecordField f) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
        s.writeln('        ${f.name}?.let { ${_kotlinWriteCall(base, 'it')} }');
      } else {
        s.writeln('        ${_kotlinWriteCall(base, f.name)}');
      }
      break;
    case RecordFieldKind.enumValue:
      if (f.isNullable) {
        s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
        s.writeln('        ${f.name}?.let { writeInt(it.nativeValue) }');
      } else {
        s.writeln('        writeInt(${f.name}.nativeValue)');
      }
      break;
    case RecordFieldKind.recordObject:
      if (f.isNullable) {
        s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
        s.writeln('        ${f.name}?.writeFieldsTo(out, buf)');
      } else {
        s.writeln('        ${f.name}.writeFieldsTo(out, buf)');
      }
      break;
    case RecordFieldKind.listPrimitive:
      final base = f.itemTypeName ?? 'int';
      s.writeln('        writeInt32(${f.name}.size)');
      s.writeln('        ${f.name}.forEach { e -> ${_kotlinWriteCall(base, 'e')} }');
      break;
    case RecordFieldKind.listEnumValue:
      s.writeln('        writeInt32(${f.name}.size)');
      s.writeln('        ${f.name}.forEach { e -> writeInt(e.nativeValue) }');
      break;
    case RecordFieldKind.listRecordObject:
      s.writeln('        writeInt32(${f.name}.size)');
      s.writeln('        ${f.name}.forEach { e -> e.writeFieldsTo(out, buf) }');
      break;
    case RecordFieldKind.typedData:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
        s.writeln('        ${f.name}?.let { ${_kotlinTypedDataWrite(base, 'it')} }');
      } else {
        s.writeln('        ${_kotlinTypedDataWrite(base, f.name)}');
      }
      break;
    case RecordFieldKind.struct:
      // @HybridStruct embedded inline — write via writeFieldsTo.
      if (f.isNullable) {
        s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
        s.writeln('        ${f.name}?.writeFieldsTo(out, buf)');
      } else {
        s.writeln('        ${f.name}.writeFieldsTo(out, buf)');
      }
      break;
  }
}

String _kotlinTypedDataWrite(String dartType, String expr) {
  // Wire format: [4B byteCount][byteCount bytes] — must write BYTE count, not element count,
  // to match Dart's writeBlob which writes byteCount = TypedData.buffer.byteLength.
  // Use `run { }` instead of `{ }()` to prevent Kotlin trailing-lambda misparse.
  switch (dartType) {
    case 'Uint8List':
    case 'Int8List':   return 'run { writeInt32($expr.size); out.write($expr) }';
    case 'Int16List':
    case 'Uint16List': return 'run { writeInt32($expr.size * 2); $expr.forEach { e -> buf.clear(); buf.putShort(e); buf.flip(); out.write(buf.array(), 0, 2) } }';
    case 'Int32List':
    case 'Uint32List': return 'run { writeInt32($expr.size * 4); $expr.forEach { e -> buf.clear(); buf.putInt(e); buf.flip(); out.write(buf.array(), 0, 4) } }';
    case 'Int64List':
    case 'Uint64List': return 'run { writeInt32($expr.size * 8); $expr.forEach { e -> buf.clear(); buf.putLong(e); buf.flip(); out.write(buf.array(), 0, 8) } }';
    case 'Float32List': return 'run { writeInt32($expr.size * 4); $expr.forEach { e -> buf.clear(); buf.putFloat(e); buf.flip(); out.write(buf.array(), 0, 4) } }';
    case 'Float64List': return 'run { writeInt32($expr.size * 8); $expr.forEach { e -> buf.clear(); buf.putDouble(e); buf.flip(); out.write(buf.array(), 0, 8) } }';
    default: return 'run { writeInt32($expr.size); out.write($expr) }';
  }
}

String _kotlinWriteCall(String base, String expr) {
  switch (base) {
    case 'int':
      return 'writeInt($expr.toLong())';
    case 'double':
      return 'writeDouble($expr)';
    case 'bool':
      return 'writeBool($expr)';
    case 'String':
      return 'writeString($expr)';
    case 'Uint8List':
    case 'ByteArray':
      return 'writeInt32($expr.size); out.write($expr)';
    default:
      return 'writeInt($expr.toLong())';
  }
}

/// Returns a static byte-size estimate for one serialized instance of [rt].
/// Used to pre-size [ByteArrayOutputStream] in [encode] and list paths,
/// avoiding the default 32-byte initial buffer and subsequent grow copies.
///
/// Estimates per field kind:
///   int/double   → 8 bytes (+ 1 nullable tag)
///   bool         → 1 byte  (+ 1 nullable tag)
///   String       → 4 (len) + 32 (avg content) = 36 (+ 1 nullable tag)
///   nested record → 32 rough estimate (+ 1 nullable tag)
///   list         → 4 (count) + 8 * 4 avg items = 36
int _recordBytesHint(BridgeRecordType rt) {
  var total = 0;
  for (final f in rt.fields) {
    final nullableTag = f.isNullable ? 1 : 0;
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        switch (base) {
          case 'bool':
            total += nullableTag + 1;
          case 'String':
            total += nullableTag + 36;
          default: // int, double
            total += nullableTag + 8;
        }
      case RecordFieldKind.enumValue:
        total += nullableTag + 8;
      case RecordFieldKind.recordObject:
        total += nullableTag + 32;
      case RecordFieldKind.listPrimitive:
      case RecordFieldKind.listEnumValue:
      case RecordFieldKind.listRecordObject:
        total += 36; // 4-byte count + ~4 items * 8 bytes avg
      case RecordFieldKind.typedData:
        total += nullableTag + 68; // 4-byte count + ~64 bytes avg payload
      case RecordFieldKind.struct:
        total += nullableTag + 64; // struct fields inline, estimate 64 bytes
    }
  }
  return total > 0 ? total : 32;
}

