part of '../record_generator.dart';

// ── Native generators ───────────────────────────────────────────────────

String _generateSwiftRecords(BridgeSpec spec, {bool emitBoilerplate = true}) {
  // NativeImpl.cpp bridge files use emitBoilerplate:false — shared library types
  // (NitroNullableInt, NitroOptInt64, etc.) are provided by the non-cpp bridge in
  // the same Swift module. Skip them here to avoid "invalid redeclaration" errors.
  final localRecords = emitBoilerplate
      ? spec.localRecordTypes
      : spec.localRecordTypes.where((r) => !_nitroLibraryRecordTypes.contains(r.name)).toList();

  // ── fromReader/writeFields extensions for plain structs embedded in records ──
  // The Dart side generates RecordExt for HybridStructs; we mirror this for Swift.
  // Without these extensions, `LiveTrackingUpdate.fromReader` cannot call
  // `PackageDimensions.fromReader(r)` because plain structs have no such method.
  final structMap = {for (final st in spec.structs) st.name: st};
  final enumNames = spec.enums.map((e) => e.name).toSet();
  final structNames = spec.structs.map((st) => st.name).toSet();

  // Collect structs directly referenced in record fields, then transitively.
  final referencedStructs = <String>{};
  for (final rt in localRecords) {
    for (final f in rt.fields) {
      if (f.kind == RecordFieldKind.recordObject || f.kind == RecordFieldKind.listRecordObject) {
        final typeName = f.kind == RecordFieldKind.listRecordObject ? (f.itemTypeName ?? f.dartType.replaceFirst('?', '')) : f.dartType.replaceFirst('?', '');
        if (structMap.containsKey(typeName)) referencedStructs.add(typeName);
      }
      // @HybridStruct embedded in @HybridRecord — needs RecordExt (fromReader/writeFields).
      if (f.kind == RecordFieldKind.struct) {
        final base = f.dartType.replaceFirst('?', '');
        if (structMap.containsKey(base)) referencedStructs.add(base);
      }
    }
  }

  // Also include structs appearing as List<@HybridStruct T> return types on methods/properties.
  for (final func in spec.functions) {
    final item = func.returnType.recordListItemType;
    if (item != null && !func.returnType.recordListItemIsPrimitive && structMap.containsKey(item) && !spec.isRecordName(item)) {
      referencedStructs.add(item);
    }
  }
  for (final prop in spec.properties) {
    final item = prop.type.recordListItemType;
    if (item != null && !prop.type.recordListItemIsPrimitive && structMap.containsKey(item) && !spec.isRecordName(item)) {
      referencedStructs.add(item);
    }
  }

  void collectNestedSwift(String typeName) {
    final st = structMap[typeName];
    if (st == null) return;
    for (final f in st.fields) {
      final base = f.type.name.replaceFirst('?', '');
      if (structMap.containsKey(base) && !referencedStructs.contains(base)) {
        referencedStructs.add(base);
        collectNestedSwift(base);
      }
    }
  }

  for (final name in referencedStructs.toList()) {
    collectNestedSwift(name);
  }

  // Variants use NitroRecordReader/Writer for their binary payload, even when
  // there are no @HybridRecord declarations in the file.
  final needsBoilerplateForVariants = emitBoilerplate && spec.localVariants.isNotEmpty;
  // Early exit only when there is truly nothing to generate.
  if (localRecords.isEmpty && referencedStructs.isEmpty && !needsBoilerplateForVariants) return '';

  final s = CodeWriter();
  s.writeln('// --- @HybridRecord binary extensions (generated by Nitrogen) ---');
  s.writeln();

  for (final stName in referencedStructs) {
    final st = structMap[stName]!;
    s.writeln('extension ${st.name} {');

    s.writeln('  public static func fromReader(_ r: NitroRecordReader) -> ${st.name} {');
    s.writeln('    return ${st.name}(');
    for (final f in st.fields) {
      s.writeln('      ${f.name}: ${_swiftStructReadExpr(f, enumNames, structNames)},');
    }
    s.writeln('    )');
    s.writeln('  }');
    s.writeln();

    s.writeln('  public func writeFields(_ writer: NitroRecordWriter) {');
    for (final f in st.fields) {
      _swiftStructWriteStmt(s, f, enumNames, structNames, st);
    }
    s.writeln('  }');
    s.writeln('}');
    s.writeln();
  }

  for (final rt in localRecords) {
    s.writeln('public struct ${rt.name}: NitroEncodable {');
    for (final f in rt.fields) {
      final opt = f.isNullable ? '?' : '';
      s.writeln('  public var ${f.name}: ${_swiftType(f)}$opt');
    }
    s.writeln();

    final params = rt.fields.map((f) => '${f.name}: ${_swiftType(f)}${f.isNullable ? '?' : ''}').join(', ');
    s.writeln('  public init($params) {');
    for (final f in rt.fields) {
      s.writeln('    self.${f.name} = ${f.name}');
    }
    s.writeln('  }');
    s.writeln();

    s.writeln('  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> ${rt.name} {');
    s.writeln('    return fromReader(NitroRecordReader(ptr: ptr))');
    s.writeln('  }');
    s.writeln();

    s.writeln('  public static func fromReader(_ r: NitroRecordReader) -> ${rt.name} {');
    s.writeln('    return ${rt.name}(');
    for (final f in rt.fields) {
      s.writeln('      ${f.name}: ${_swiftRead(f)},');
    }
    s.writeln('    )');
    s.writeln('  }');
    s.writeln();

    s.writeln('  public func writeFields(_ writer: NitroRecordWriter) {');
    for (final f in rt.fields) {
      _swiftWriteStmt(s, f);
    }
    s.writeln('  }');
    s.writeln();

    s.writeln('  public func toNative() -> UnsafeMutablePointer<UInt8>? {');
    s.writeln('    let writer = NitroRecordWriter()');
    s.writeln('    writeFields(writer)');
    s.writeln('    return writer.toNative()');
    s.writeln('  }');
    // ── Built-in NitroNullable types: add nullable computed var + fromNullable factory ──
    if (rt.name == 'NitroNullableInt') {
      s.writeln('  public var nullable: Int64? { hasValue ? value : nil }');
      s.writeln('  public static func fromNullable(_ v: Int64?) -> NitroNullableInt {');
      s.writeln('    return NitroNullableInt(hasValue: v != nil, value: v ?? 0)');
      s.writeln('  }');
    } else if (rt.name == 'NitroNullableDouble') {
      s.writeln('  public var nullable: Double? { hasValue ? value : nil }');
      s.writeln('  public static func fromNullable(_ v: Double?) -> NitroNullableDouble {');
      s.writeln('    return NitroNullableDouble(hasValue: v != nil, value: v ?? 0.0)');
      s.writeln('  }');
    } else if (rt.name == 'NitroNullableBool') {
      s.writeln('  public var nullable: Bool? { hasValue ? value : nil }');
      s.writeln('  public static func fromNullable(_ v: Bool?) -> NitroNullableBool {');
      s.writeln('    return NitroNullableBool(hasValue: v != nil, value: v ?? false)');
      s.writeln('  }');
    }
    s.writeln('}');
    s.writeln();
  }

  if (emitBoilerplate) {
    s.writeln(_swiftRecordWriterReader);
  }
  return s.toString();
}

String _swiftType(BridgeRecordField f) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      return _swiftBase(f.dartType);
    case RecordFieldKind.enumValue:
      return f.dartType.replaceFirst('?', '');
    case RecordFieldKind.recordObject:
      return f.dartType.replaceFirst('?', '');
    case RecordFieldKind.listPrimitive:
      return '[${_swiftBase(f.itemTypeName ?? 'Any')}]';
    case RecordFieldKind.listEnumValue:
      return '[${f.itemTypeName}]';
    case RecordFieldKind.listRecordObject:
      return '[${f.itemTypeName}]';
    case RecordFieldKind.typedData:
      return _swiftTypedDataType(f.dartType.replaceFirst('?', ''));
    case RecordFieldKind.struct:
      return f.dartType.replaceFirst('?', '');
  }
}

String _swiftTypedDataType(String dartType) {
  switch (dartType) {
    case 'Uint8List':
    case 'Int8List':   return 'Data';
    case 'Int16List':
    case 'Uint16List': return '[Int16]';
    case 'Int32List':
    case 'Uint32List': return '[Int32]';
    case 'Int64List':
    case 'Uint64List': return '[Int64]';
    case 'Float32List': return '[Float]';
    case 'Float64List': return '[Double]';
    default: return 'Data';
  }
}

String _swiftBase(String dartType) {
  final base = dartType.replaceFirst('?', '');
  switch (base) {
    case 'int':
      return 'Int64';
    case 'double':
      return 'Double';
    case 'bool':
      return 'Bool';
    case 'String':
      return 'String';
    default:
      return 'Int64';
  }
}

String _swiftReadCall(String base) {
  switch (base) {
    case 'int':
      return 'r.readInt()';
    case 'double':
      return 'r.readDouble()';
    case 'bool':
      return 'r.readBool()';
    case 'String':
      return 'r.readString()';
    case 'Uint8List':
      return 'r.readBlob()';
    default:
      return 'r.readInt()';
  }
}

String _swiftRead(BridgeRecordField f) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) return 'r.readNullTag() ? nil : ${_swiftReadCall(base)}';
      return _swiftReadCall(base);
    case RecordFieldKind.enumValue:
      final base = f.dartType.replaceFirst('?', '');
      final read = '$base(rawValue: r.readInt())!';
      if (f.isNullable) return 'r.readNullTag() ? nil : $read';
      return read;
    case RecordFieldKind.recordObject:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) return 'r.readNullTag() ? nil : $base.fromReader(r)';
      return '$base.fromReader(r)';
    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'int';
      return '(0..<Int(r.readInt32())).map { _ in ${_swiftReadCall(item)} }';
    case RecordFieldKind.listEnumValue:
      final item = f.itemTypeName!;
      return '(0..<Int(r.readInt32())).map { _ in $item(rawValue: r.readInt())! }';
    case RecordFieldKind.listRecordObject:
      final item = f.itemTypeName!;
      return '(0..<Int(r.readInt32())).map { _ in $item.fromReader(r) }';
    case RecordFieldKind.typedData:
      final base = f.dartType.replaceFirst('?', '');
      final read = _swiftTypedDataRead(base);
      if (f.isNullable) return 'r.readNullTag() ? nil : $read';
      return read;
    case RecordFieldKind.struct:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) return 'r.readNullTag() ? nil : $base.fromReader(r)';
      return '$base.fromReader(r)';
  }
}

String _swiftTypedDataRead(String dartType) {
  // Note: \$0 uses raw string escaping so the generated Swift gets literal $0.
  const d0 = r'$0';
  switch (dartType) {
    case 'Uint8List':
    case 'Int8List':   return 'r.readBlob()';
    case 'Int16List':
    case 'Uint16List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Int16.self)) } }()';
    case 'Int32List':
    case 'Uint32List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Int32.self)) } }()';
    case 'Int64List':
    case 'Uint64List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Int64.self)) } }()';
    case 'Float32List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Float.self)) } }()';
    case 'Float64List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Double.self)) } }()';
    default: return 'r.readBlob()';
  }
}

void _swiftWriteStmt(CodeWriter s, BridgeRecordField f) {
  switch (f.kind) {
    case RecordFieldKind.primitive:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == nil)');
        s.writeln('    if let val = ${f.name} { writer.${_swiftWriterCall(base, 'val')} }');
      } else {
        s.writeln('    writer.${_swiftWriterCall(base, f.name)}');
      }
      break;
    case RecordFieldKind.enumValue:
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == nil)');
        s.writeln('    if let val = ${f.name} { writer.writeInt(val.rawValue) }');
      } else {
        s.writeln('    writer.writeInt(${f.name}.rawValue)');
      }
      break;
    case RecordFieldKind.recordObject:
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == nil)');
        s.writeln('    if let val = ${f.name} { val.writeFields(writer) }');
      } else {
        s.writeln('    ${f.name}.writeFields(writer)');
      }
      break;
    case RecordFieldKind.listPrimitive:
      final item = f.itemTypeName ?? 'int';
      s.writeln('    writer.writeInt32(Int32(${f.name}.count))');
      s.writeln('    for e in ${f.name} { writer.${_swiftWriterCall(item, 'e')} }');
      break;
    case RecordFieldKind.listEnumValue:
      s.writeln('    writer.writeInt32(Int32(${f.name}.count))');
      s.writeln('    for e in ${f.name} { writer.writeInt(e.rawValue) }');
      break;
    case RecordFieldKind.listRecordObject:
      s.writeln('    writer.writeInt32(Int32(${f.name}.count))');
      s.writeln('    for e in ${f.name} { e.writeFields(writer) }');
      break;
    case RecordFieldKind.typedData:
      final base = f.dartType.replaceFirst('?', '');
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == nil)');
        s.writeln('    if let val = ${f.name} { ${_swiftTypedDataWrite(base, 'val', 'writer')} }');
      } else {
        s.writeln('    ${_swiftTypedDataWrite(base, f.name, 'writer')}');
      }
      break;
    case RecordFieldKind.struct:
      // @HybridStruct embedded inline — write via writeFields.
      if (f.isNullable) {
        s.writeln('    writer.writeNullTag(${f.name} == nil)');
        s.writeln('    if let val = ${f.name} { val.writeFields(writer) }');
      } else {
        s.writeln('    ${f.name}.writeFields(writer)');
      }
      break;
  }
}

String _swiftTypedDataWrite(String dartType, String expr, String writer) {
  switch (dartType) {
    case 'Uint8List':
    case 'Int8List':   return '$writer.writeBlob($expr)';
    case 'Int16List':
    case 'Uint16List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
    case 'Int32List':
    case 'Uint32List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
    case 'Int64List':
    case 'Uint64List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
    case 'Float32List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
    case 'Float64List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
    default: return '$writer.writeBlob($expr)';
  }
}

String _swiftWriterCall(String base, String expr) {
  switch (base) {
    case 'int':
      return 'writeInt($expr)';
    case 'double':
      return 'writeDouble($expr)';
    case 'bool':
      return 'writeBool($expr)';
    case 'String':
      return 'writeString($expr)';
    case 'Uint8List':
      return 'writeBlob($expr)';
    default:
      return 'writeInt($expr)';
  }
}

String _swiftStructReadExpr(BridgeField f, Set<String> enumNames, Set<String> structNames) {
  final base = f.type.name.replaceFirst('?', '');
  if (enumNames.contains(base)) return '$base(rawValue: Int(r.readInt()))!';
  if (structNames.contains(base)) return '$base.fromReader(r)';
  if (base == 'Uint8List' && f.zeroCopy) {
    return 'r.readBlobAsPointer()';
  }
  return _swiftReadCall(base);
}

void _swiftStructWriteStmt(CodeWriter s, BridgeField f, Set<String> enumNames, Set<String> structNames, BridgeStruct st) {
  final base = f.type.name.replaceFirst('?', '');
  if (enumNames.contains(base)) {
    s.writeln('    writer.writeInt(Int64(${f.name}.rawValue))');
  } else if (structNames.contains(base)) {
    s.writeln('    ${f.name}.writeFields(writer)');
  } else {
    if (base == 'Uint8List' && f.zeroCopy) {
      final countField = st.fields.firstWhere(
        (cf) => ['stride', 'length', 'size', 'count'].contains(cf.name),
        orElse: () => st.fields.first,
      );
      final countExpr = 'Int(${countField.name})';
      s.writeln('    if let ptr = ${f.name} {');
      s.writeln('        writer.writeBlob(Data(bytes: ptr, count: $countExpr))');
      s.writeln('    } else {');
      s.writeln('        writer.writeInt32(0)');
      s.writeln('    }');
    } else {
      s.writeln('    writer.${_swiftWriterCall(base, f.name)}');
    }
  }
}

const _swiftRecordWriterReader = '''
public class NitroRecordWriter {
  public var bytes: [UInt8] = []
  public init() {}
  public func writeInt(_ v: Int64) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
  }
  public func writeInt32(_ v: Int32) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
  }
  public func writeDouble(_ v: Double) {
      var val = v.bitPattern.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
  }
  public func writeBool(_ v: Bool) {
      bytes.append(v ? 1 : 0)
  }
  public func writeString(_ v: String) {
      let utf8 = Array(v.utf8)
      writeInt32(Int32(utf8.count))
      bytes.append(contentsOf: utf8)
  }
  public func writeNullTag(_ isNull: Bool) {
      bytes.append(isNull ? 0 : 1)
  }
  public func writeBlob(_ v: Data) {
      writeInt32(Int32(v.count))
      bytes.append(contentsOf: Array(v))
  }
  public func toNative() -> UnsafeMutablePointer<UInt8>? {
      let total = 4 + bytes.count
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
      var length = Int32(bytes.count).littleEndian
      _ = memcpy(ptr, &length, 4)
      if bytes.count > 0 {
          _ = memcpy(ptr.advanced(by: 4), bytes, bytes.count)
      }
      return ptr
  }
  public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      let w = NitroRecordWriter()
      w.writeInt32(Int32(items.count))
      for item in items { writeItem(w, item) }
      return w.toNative()
  }
  /// Encodes a list of nullable items.
  /// Wire format: [4B count][for each: 1B hasValue][item bytes (only if hasValue)]
  /// Counterpart: NitroRecordReader.decodeNullableList / Dart RecordReader.decodeNullableList.
  public static func encodeNullableList<T>(_ items: [T?], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      let w = NitroRecordWriter()
      w.writeInt32(Int32(items.count))
      for item in items {
          w.writeBool(item != nil)
          if let v = item { writeItem(w, v) }
      }
      return w.toNative()
  }
  /// Encodes a list with a per-item byte-offset table for O(1) random access.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// Counterpart: Dart LazyRecordList.decode / RecordWriter.encodeIndexedList.
  public static func encodeIndexedList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      var blobs: [[UInt8]] = []
      for item in items {
          let w = NitroRecordWriter()
          writeItem(w, item)
          blobs.append(w.bytes)
      }
      var pos = 4 + 8 * blobs.count
      var offsets: [Int64] = []
      for blob in blobs {
          offsets.append(Int64(pos))
          pos += blob.count
      }
      let w = NitroRecordWriter()
      w.writeInt32(Int32(blobs.count))
      for off in offsets { w.writeInt(off) }
      for blob in blobs { w.bytes.append(contentsOf: blob) }
      return w.toNative()
  }
}

public class NitroRecordReader {
  public let bytes: UnsafeMutablePointer<UInt8>
  public var pos: Int = 0
  public init(ptr: UnsafeMutablePointer<UInt8>) {
      self.bytes = ptr.advanced(by: 4)
  }
  public init(payload: UnsafeMutablePointer<UInt8>) {
      self.bytes = payload
  }
  public func readInt() -> Int64 {
      var v: Int64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Int64(littleEndian: v)
  }
  public func readInt32() -> Int32 {
      var v: Int32 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 4)
      pos += 4
      return Int32(littleEndian: v)
  }
  public func readDouble() -> Double {
      var v: UInt64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Double(bitPattern: UInt64(littleEndian: v))
  }
  public func readBool() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v != 0
  }
  public func readString() -> String {
      let len = Int(readInt32())
      guard len > 0 else { return "" }
      let s = String(bytes: UnsafeBufferPointer(start: bytes.advanced(by: pos), count: len), encoding: .utf8) ?? ""
      pos += len
      return s
  }
  public func readNullTag() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v == 0
  }
  public func readBlob() -> Data {
      let len = Int(readInt32())
      let data = Data(bytes: bytes.advanced(by: pos), count: len)
      pos += len
      return data
  }
  public func readBlobAsPointer() -> UnsafeMutablePointer<UInt8>? {
      let len = Int(readInt32())
      if (len == 0) { return nil }
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: len)
      ptr.initialize(from: bytes.advanced(by: pos), count: len)
      pos += len
      return ptr
  }
  public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
  /// Decodes a list of nullable items.
  /// Wire format: [4B count][for each: 1B hasValue][item bytes (only if hasValue)]
  /// Counterpart: NitroRecordWriter.encodeNullableList / Dart RecordWriter.encodeNullableList.
  public static func decodeNullableList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T?] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      var items: [T?] = []
      for _ in 0..<count {
          let hasValue = r.readBool()
          items.append(hasValue ? readItem(r) : nil)
      }
      return items
  }
  /// Decodes a list encoded by Dart's RecordWriter.encodeIndexedList / encodeIndexedPrimitiveList.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// The offset table is skipped; items are read sequentially after it.
  public static func decodeIndexedList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      r.pos += Int(count) * 8  // skip Int64 offset table
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
}
''';
