builders:
  nitrogen:
    import: 'package:nitrogen/builder.dart'
    builder_factories: ['nitrogenBuilder']
    build_extensions:
      '{{dir}}/{{file}}.native.dart':
        - '{{dir}}/{{file}}.g.dart'
        - '{{dir}}/generated/kotlin/{{file}}.bridge.g.kt'
        - '{{dir}}/generated/swift/{{file}}.bridge.g.swift'
        - '{{dir}}/generated/cpp/{{file}}.bridge.g.h'
        - '{{dir}}/generated/cmake/{{file}}.CMakeLists.g.txt'
    auto_apply: dependents
    build_to: source
