builders:
  nitrogen:
    import: 'package:nitrogen/builder.dart'
    builder_factories: ['nitrogenBuilder']
    build_extensions:
      '.native.dart':
        - '.g.dart'
        - '_bridge.g.kt'
        - '_bridge.g.swift'
        - '_bridge.g.h'
        - '_CMakeLists.g.txt'
    auto_apply: dependents
    build_to: source
    applies_builders: ['source_gen|combining_builder']
