part of '../dart_ffi_generator.dart';

/// Emits binary map encode/decode helpers and the PX19 platform factory.
void _emitMapAndFactory(CodeWriter writer, BridgeSpec spec) {
writer.blankLine();

// Emit binary map encode/decode helpers for each map value type used in the spec.
final mapValueTypes = <String>{};
for (final func in spec.functions) {
  _collectMapValueTypes(func.returnType, mapValueTypes);
  for (final p in func.params) _collectMapValueTypes(p.type, mapValueTypes);
}
for (final prop in spec.properties) {
  _collectMapValueTypes(prop.type, mapValueTypes);
}
if (mapValueTypes.isNotEmpty) {
  writer.line('// Binary map encode/decode helpers (generated by Nitrogen)');
  writer.line('// Wire: [4B payload_len][4B count][entries: [4B key_len][key_bytes][value_bytes]]');
  writer.blankLine();
  // Shared low-level helper (emitted once). Type tags: 1=int64, 2=float64, 3=bool, 4=string, 9=bytes
  writer.line('Uint8List _nitroMapPayload(Map<String, dynamic> m, void Function(ByteData h, BytesBuilder bb, dynamic v) writeVal) {');
  // copy: true (default) is required: copy:false holds references to hdr.buffer,
  // so every hdr.setInt32 call would silently corrupt all previously-added count/kLen bytes.
  writer.line('  final bb = BytesBuilder();');
  writer.line('  final hdr = ByteData(8);');
  writer.line('  hdr.setInt32(0, m.length, Endian.little); bb.add(hdr.buffer.asUint8List(0, 4));');
  writer.line('  for (final e in m.entries) {');
  writer.line('    final k = utf8.encode(e.key); hdr.setInt32(0, k.length, Endian.little);');
  writer.line('    bb.add(hdr.buffer.asUint8List(0, 4)); bb.add(k); writeVal(hdr, bb, e.value);');
  writer.line('  }');
  writer.line('  final payload = bb.toBytes();');
  writer.line('  final lenBuf = ByteData(4)..setInt32(0, payload.length, Endian.little);');
  writer.line('  return Uint8List.fromList([...lenBuf.buffer.asUint8List(0, 4), ...payload]);');
  writer.line('}');
  writer.blankLine();
  for (final vt in mapValueTypes) {
    _emitMapBinaryHelpers(writer, vt, spec);
  }
}

// PX19: Platform-conditional factory used by web-targeting specs.
// When `web: NativeImpl.wasm` is targeted, the spec can route via:
//
//   import 'generated/web/xxx.web.bridge.g.dart'
//       if (dart.library.ffi) 'xxx.g.dart';
//
//   static final T instance = _T_createPlatformInstance();
//
// This factory creates the native (dart:ffi) instance. The web bridge
// exports a matching `create${ClassName}WebInstance()` factory.
if (spec.targetsWeb) {
  writer.line(
    '/// PX19: Creates the native (dart:ffi) implementation of [${spec.dartClassName}].',
  );
  writer.line(
    '/// On web, import `*.web.bridge.g.dart` conditionally and call',
  );
  writer.line(
    '/// `create${spec.dartClassName}WebInstance()` instead.',
  );
  // Build a safe Dart identifier: lowercase the first alphabetic character.
  // Handles edge cases: single-char names ('A' → 'a'), underscore-prefixed
  // names ('_X' → '_x'), digits-first (rare; kept as-is for safety).
  final firstAlpha = spec.dartClassName.split('').indexWhere((c) => RegExp(r'[A-Za-z]').hasMatch(c));
  final camelName = firstAlpha >= 0
      ? spec.dartClassName.substring(0, firstAlpha) +
        spec.dartClassName[firstAlpha].toLowerCase() +
        spec.dartClassName.substring(firstAlpha + 1)
      : spec.dartClassName;
  writer.line(
    '${spec.dartClassName} ${camelName}_createNativeInstance() => _${spec.dartClassName}Impl();',
  );
  writer.blankLine();
}

}
