name: nitro_annotations
description: >
  Annotations package for Nitro Modules (Nitrogen).
  Provides the @NitroModule, @HybridRecord, and other annotations used by the nitro_generator.
version: 0.3.1
homepage: https://nitro.shreeman.dev
repository: https://github.com/Shreemanarjun/nitro_ecosystem

environment:
  sdk: ^3.11.3
resolution: workspace
