import '../bridge_spec.dart';
import 'struct_generator.dart';
import 'enum_generator.dart';

class CppHeaderGenerator {
  static String generate(BridgeSpec spec) {
    final s = StringBuffer();
    s.writeln('// Generated by Nitrogen Modules. Do not edit.');
    s.writeln('// Generated from: ${spec.sourceUri.split('/').last}');
    s.writeln('#pragma once');
    s.writeln();
    s.writeln('#include <stdint.h>');
    s.writeln('#include <stdbool.h>');
    s.writeln('#include <stdlib.h>');
    s.writeln();
    // Inline nitro.h content so this header is fully self-contained.
    // Using ifndef guards so it composes cleanly with user-supplied nitro.h copies.
    s.writeln('#ifndef NITRO_EXPORT');
    s.writeln('#  if defined(_WIN32)');
    s.writeln('#    define NITRO_EXPORT __declspec(dllexport)');
    s.writeln('#  else');
    s.writeln('#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))');
    s.writeln('#  endif');
    s.writeln('#endif');
    s.writeln();
    s.writeln('#ifndef NITRO_ERROR_DEFINED');
    s.writeln('#define NITRO_ERROR_DEFINED');
    s.writeln('typedef struct {');
    s.writeln('  int8_t hasError;');
    s.writeln('  const char* name;');
    s.writeln('  const char* message;');
    s.writeln('  const char* code;');
    s.writeln('  const char* stackTrace;');
    s.writeln('} NitroError;');
    s.writeln('#endif');
    s.writeln();

    // Include headers for types imported from other .native.dart files.
    if (spec.importedTypeFiles.isNotEmpty) {
      for (final inc in spec.importedTypeFiles) {
        s.writeln('#include "$inc"');
      }
      s.writeln();
    }

    final cEnums = EnumGenerator.generateCEnums(spec);
    if (cEnums.isNotEmpty) s.write(cEnums);

    final cStructs = StructGenerator.generateCStructs(spec);
    if (cStructs.isNotEmpty) s.write(cStructs);

    if (spec.isTypeOnly) {
      return s.toString();
    }

    s.writeln('#ifdef __cplusplus');
    s.writeln('extern "C" {');
    s.writeln('#endif');
    s.writeln();

    final libStem = spec.lib.replaceAll('-', '_');
    s.writeln('NITRO_EXPORT intptr_t ${libStem}_init_dart_api_dl(void* data);');
    s.writeln('NITRO_EXPORT NitroError* ${libStem}_get_error(void);');
    s.writeln('NITRO_EXPORT void ${libStem}_clear_error(void);');
    s.writeln();
    s.writeln();
    s.writeln();

    // ── Methods ─────────────────────────────────────────────────────────────
    if (spec.functions.isNotEmpty) {
      s.writeln('// Methods');
      for (final func in spec.functions) {
        final isEnumRet = spec.enums.any(
          (en) => en.name == func.returnType.name.replaceFirst('?', ''),
        );
        final paramParts = <String>[];
        for (final p in func.params) {
          final isStructParam = spec.structs.any(
            (st) => st.name == p.type.name.replaceFirst('?', ''),
          );
          paramParts.add('${isStructParam ? 'void*' : _typeToC(p.type.name)} ${p.name}');
          if (p.type.isTypedData) paramParts.add('int64_t ${p.name}_length');
        }
        // @NitroNativeAsync: C entry point is always void + extra dart_port param.
        if (func.isNativeAsync) {
          paramParts.add('int64_t dart_port');
          final paramStr = paramParts.join(', ');
          s.writeln('NITRO_EXPORT void ${func.cSymbol}($paramStr);');
        } else {
          final ret = isEnumRet ? 'int64_t' : _typeToC(func.returnType.name);
          final params = paramParts.join(', ');
          final paramStr = params.isEmpty ? 'void' : params;
          s.writeln('NITRO_EXPORT $ret ${func.cSymbol}($paramStr);');
        }
      }
      s.writeln();
    }

    // ── Properties ──────────────────────────────────────────────────────────
    if (spec.properties.isNotEmpty) {
      s.writeln('// Properties');
      for (final prop in spec.properties) {
        final isEnumProp = spec.enums.any(
          (en) => en.name == prop.type.name.replaceFirst('?', ''),
        );
        final cType = isEnumProp ? 'int64_t' : _typeToC(prop.type.name);
        if (prop.hasGetter) {
          s.writeln('NITRO_EXPORT $cType ${prop.getSymbol}(void);');
        }
        if (prop.hasSetter) {
          s.writeln('NITRO_EXPORT void ${prop.setSymbol}($cType value);');
        }
      }
      s.writeln();
    }

    // ── Streams ─────────────────────────────────────────────────────────────
    if (spec.streams.isNotEmpty) {
      s.writeln('// Streams');
      for (final stream in spec.streams) {
        s.writeln('// Stream<${stream.itemType.name}> ${stream.dartName}');
        s.writeln('NITRO_EXPORT void ${stream.registerSymbol}(int64_t dart_port);');
        s.writeln('NITRO_EXPORT void ${stream.releaseSymbol}(int64_t dart_port);');
      }
      s.writeln();
    }

    // ── Struct release functions ────────────────────────────────────────────
    if (spec.structs.isNotEmpty) {
      s.writeln('// Struct release functions');
      for (final st in spec.structs) {
        s.writeln('NITRO_EXPORT void ${libStem}_release_${st.name}(void* ptr);');
      }
      s.writeln();
    }

    s.writeln('#ifdef __cplusplus');
    s.writeln('}');
    s.writeln('#endif');

    return s.toString();
  }

  static String _typeToC(String dartType) {
    switch (dartType.replaceFirst('?', '')) {
      case 'int':
        return 'int64_t';
      case 'double':
        return 'double';
      case 'bool':
        return 'int8_t';
      case 'String':
        return 'const char*';
      case 'Uint8List':
        return 'uint8_t*';
      case 'Int8List':
        return 'int8_t*';
      case 'Int16List':
        return 'int16_t*';
      case 'Int32List':
        return 'int32_t*';
      case 'Uint16List':
        return 'uint16_t*';
      case 'Uint32List':
        return 'uint32_t*';
      case 'Float32List':
        return 'float*';
      case 'Float64List':
        return 'double*';
      case 'Int64List':
        return 'int64_t*';
      case 'Uint64List':
        return 'uint64_t*';
      case 'void':
        return 'void';
      default:
        return 'void*';
    }
  }
}
