import '../bridge_spec.dart';

class CppBridgeGenerator {
  static String generate(BridgeSpec spec) {
    // All targeted platforms use C++ — emit a lean direct-call bridge.
    if (spec.isCppImpl) {
      return _generateCppDirect(spec);
    }
    // Single-platform: skip the platform block that is not targeted.
    if (spec.targetsIos && !spec.targetsAndroid) {
      return _generateJniSwift(spec, includeAndroid: false);
    }
    if (!spec.targetsIos && spec.targetsAndroid) {
      return _generateJniSwift(spec, includeIos: false);
    }
    return _generateJniSwift(spec);
  }

  // ── Direct C++ path (NativeImpl.cpp on all targeted platforms) ─────────────

  static String _generateCppDirect(BridgeSpec spec) {
    final s = StringBuffer();
    final libStem = spec.lib.replaceAll('-', '_');
    final className = spec.dartClassName;
    final headerName = '$libStem.bridge.g.h';
    final ifaceHeader = '$libStem.native.g.h';

    final recordNames = spec.recordTypes.map((r) => r.name).toSet();
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final structNames = spec.structs.map((st) => st.name).toSet();

    // Single-platform C++ — emit a compile-time guard so the code is only
    // compiled on the targeted platform.
    final cppIosOnly = spec.targetsIos && !spec.targetsAndroid;
    final cppAndroidOnly = spec.targetsAndroid && !spec.targetsIos;

    s.writeln('// Generated by Nitrogen Modules. Do not edit.');
    s.writeln('// Generated from: ${spec.sourceUri.split('/').last}');
    s.writeln('// NativeImpl: cpp — direct C++ virtual-dispatch bridge (no JNI / Swift).');
    if (cppIosOnly) s.writeln('#ifdef __APPLE__');
    if (cppAndroidOnly) s.writeln('#ifdef __ANDROID__');
    s.writeln('#include <stdint.h>');
    s.writeln('#include <stdbool.h>');
    s.writeln('#include <string.h>');
    s.writeln('#include <stdlib.h>');
    s.writeln('#include <string>');
    s.writeln('#include <stdexcept>');
    s.writeln('#include "dart_api_dl.h"');
    s.writeln('#include "$headerName"');
    s.writeln('#include "$ifaceHeader"');
    s.writeln();

    // Dart API DL init
    s.writeln('extern "C" {');
    s.writeln('intptr_t ${libStem}_init_dart_api_dl(void* data) {');
    s.writeln('    return Dart_InitializeApiDL(data);');
    s.writeln('}');
    s.writeln('}');
    s.writeln();

    // Error state
    s.writeln('static thread_local NitroError g_nitro_error = { 0, nullptr, nullptr, nullptr, nullptr };');
    s.writeln();
    s.writeln('extern "C" {');
    s.writeln('NitroError* ${libStem}_get_error() { return &g_nitro_error; }');
    s.writeln('void ${libStem}_clear_error() {');
    s.writeln('    if (!g_nitro_error.hasError) return;');
    s.writeln('    g_nitro_error.hasError = 0;');
    s.writeln('    if (g_nitro_error.name)       { free((void*)g_nitro_error.name);       g_nitro_error.name       = nullptr; }');
    s.writeln('    if (g_nitro_error.message)    { free((void*)g_nitro_error.message);    g_nitro_error.message    = nullptr; }');
    s.writeln('    if (g_nitro_error.code)       { free((void*)g_nitro_error.code);       g_nitro_error.code       = nullptr; }');
    s.writeln('    if (g_nitro_error.stackTrace) { free((void*)g_nitro_error.stackTrace); g_nitro_error.stackTrace = nullptr; }');
    s.writeln('}');
    s.writeln('static void nitro_report_error(const char* name, const char* message, const char* code, const char* stack) {');
    s.writeln('    ${libStem}_clear_error();');
    s.writeln('    g_nitro_error.hasError = 1;');
    s.writeln('    g_nitro_error.name       = name    ? strdup(name)    : strdup("NativeException");');
    s.writeln('    g_nitro_error.message    = message ? strdup(message) : strdup("An unknown C++ exception occurred.");');
    s.writeln('    g_nitro_error.code       = code    ? strdup(code)    : nullptr;');
    s.writeln('    g_nitro_error.stackTrace = stack   ? strdup(stack)   : nullptr;');
    s.writeln('}');
    s.writeln('}');
    s.writeln();

    // Implementation registry.
    // Thread-safety contract: register_impl() MUST be called (and complete)
    // before any concurrent native call can reach get_impl().  In practice this
    // is guaranteed because registration always happens in an
    // __attribute__((constructor)) which runs synchronously at DSO load —
    // before Dart's isolate threads can invoke any bridge function.
    // We intentionally do NOT use std::atomic here: the pointer is written
    // exactly once at startup and never mutated during concurrent use, so a
    // plain load is safe and avoids seq_cst memory barriers on every hot call.
    s.writeln('// g_impl is written once during DSO load (see __attribute__((constructor)))');
    s.writeln('// and is read-only during concurrent bridge calls — no std::atomic needed.');
    s.writeln('static Hybrid$className* g_impl = nullptr;');
    s.writeln();
    s.writeln('void ${libStem}_register_impl(Hybrid$className* impl) { g_impl = impl; }');
    s.writeln('Hybrid$className* ${libStem}_get_impl() { return g_impl; }');
    s.writeln();

    // Stream state: one Dart port per stream (simplest model)
    for (final stream in spec.streams) {
      s.writeln('static int64_t g_port_${stream.dartName} = 0;');
    }
    if (spec.streams.isNotEmpty) s.writeln();

    // Stream emit helpers (called by user's C++ implementation)
    for (final stream in spec.streams) {
      final isStruct = structNames.contains(stream.itemType.name.replaceFirst('?', ''));
      final itemCpp = _cppScalarType(stream.itemType.name, enumNames, structNames);
      s.writeln('void Hybrid$className::emit_${stream.dartName}($itemCpp item) {');
      s.writeln('    int64_t port = g_port_${stream.dartName};');
      s.writeln('    if (port == 0) return;');
      s.writeln('    Dart_CObject obj;');
      if (stream.itemType.name == 'double') {
        s.writeln('    obj.type = Dart_CObject_kDouble;');
        s.writeln('    obj.value.as_double = item;');
      } else if (stream.itemType.name == 'int') {
        s.writeln('    obj.type = Dart_CObject_kInt64;');
        s.writeln('    obj.value.as_int64 = item;');
      } else if (stream.itemType.name == 'bool') {
        s.writeln('    obj.type = Dart_CObject_kBool;');
        s.writeln('    obj.value.as_bool = item;');
      } else if (isStruct) {
        final stName = stream.itemType.name.replaceFirst('?', '');
        s.writeln('    $stName* st_ptr = ($stName*)malloc(sizeof($stName));');
        s.writeln('    *st_ptr = item;');
        s.writeln('    obj.type = Dart_CObject_kInt64;');
        s.writeln('    obj.value.as_int64 = (intptr_t)st_ptr;');
      } else {
        s.writeln('    obj.type = Dart_CObject_kNull;');
      }
      s.writeln('    Dart_PostCObject_DL(port, &obj);');
      s.writeln('}');
      s.writeln();
    }

    // Guard snippet used in every exported function
    final notInit =
        'nitro_report_error("NotInitialized", '
        '"No C++ implementation registered. Call ${libStem}_register_impl() first.", '
        'nullptr, nullptr)';

    s.writeln('extern "C" {');
    s.writeln();

    // ── Methods ──────────────────────────────────────────────────────────────
    for (final func in spec.functions) {
      final isEnumRet = enumNames.contains(func.returnType.name.replaceFirst('?', ''));
      final isStructRet = structNames.contains(func.returnType.name.replaceFirst('?', ''));
      final isRecordRet = recordNames.contains(func.returnType.name.replaceFirst('?', ''));
      final cRet = isEnumRet ? 'int64_t' : _typeToC(func.returnType.name);
      final dflt = _defaultValue(cRet);

      final paramParts = <String>[];
      for (final p in func.params) {
        final isStructParam = structNames.contains(p.type.name.replaceFirst('?', ''));
        final isRecordParam = recordNames.contains(p.type.name.replaceFirst('?', ''));
        paramParts.add('${(isStructParam || isRecordParam) ? 'void*' : _typeToC(p.type.name)} ${p.name}');
        if (p.type.isTypedData) paramParts.add('int64_t ${p.name}_length');
      }
      final paramsDecl = paramParts.isEmpty ? 'void' : paramParts.join(', ');

      s.writeln('$cRet ${func.cSymbol}($paramsDecl) {');
      s.writeln('    ${libStem}_clear_error();');
      if (func.returnType.name == 'void') {
        s.writeln('    if (!g_impl) { $notInit; return; }');
      } else {
        s.writeln('    if (!g_impl) { $notInit; return $dflt; }');
      }
      s.writeln('    try {');

      // Build call args (C → C++ types)
      final callArgs = <String>[];
      for (final p in func.params) {
        final base = p.type.name.replaceFirst('?', '');
        if (base == 'String') {
          callArgs.add('std::string(${p.name})');
        } else if (structNames.contains(base)) {
          callArgs.add('*static_cast<const $base*>(${p.name})');
        } else if (recordNames.contains(base)) {
          final opt = p.type.name.endsWith('?');
          if (opt) {
            s.writeln('        NitroCppBuffer _buf_${p.name} = { nullptr, 0 };');
            s.writeln('        if (${p.name} != nullptr) {');
            s.writeln('            _buf_${p.name}.data = (const uint8_t*)${p.name} + 4;');
            s.writeln('            _buf_${p.name}.size = (size_t)*(int32_t*)${p.name};');
            s.writeln('        }');
            callArgs.add('_buf_${p.name}');
          } else {
            s.writeln('        NitroCppBuffer _buf_${p.name} = { (const uint8_t*)${p.name} + 4, (size_t)*(int32_t*)${p.name} };');
            callArgs.add('_buf_${p.name}');
          }
        } else if (p.type.isTypedData) {
          callArgs.add(p.name);
          callArgs.add('static_cast<size_t>(${p.name}_length)');
        } else if (enumNames.contains(base)) {
          callArgs.add('static_cast<$base>(${p.name})');
        } else {
          callArgs.add(p.name);
        }
      }
      final callArgStr = callArgs.join(', ');

      if (func.returnType.name == 'void') {
        s.writeln('        g_impl->${func.dartName}($callArgStr);');
      } else if (func.returnType.name == 'String') {
        s.writeln('        std::string _res = g_impl->${func.dartName}($callArgStr);');
        s.writeln('        return strdup(_res.c_str());');
      } else if (isEnumRet) {
        s.writeln('        return static_cast<int64_t>(g_impl->${func.dartName}($callArgStr));');
      } else if (isStructRet) {
        final stName = func.returnType.name.replaceFirst('?', '');
        s.writeln('        $stName _res = g_impl->${func.dartName}($callArgStr);');
        s.writeln('        $stName* _ptr = ($stName*)malloc(sizeof($stName));');
        s.writeln('        *_ptr = _res;');
        s.writeln('        return _ptr;');
      } else if (isRecordRet) {
        s.writeln('        NitroCppBuffer _res = g_impl->${func.dartName}($callArgStr);');
        s.writeln('        return (void*)_res.data;');
      } else {
        s.writeln('        return g_impl->${func.dartName}($callArgStr);');
      }

      s.writeln('    } catch (const std::exception& e) {');
      s.writeln('        nitro_report_error("CppException", e.what(), nullptr, nullptr);');
      if (func.returnType.name != 'void') {
        s.writeln('        return $dflt;');
      }
      s.writeln('    } catch (...) {');
      s.writeln('        nitro_report_error("CppException", "Unknown C++ exception", nullptr, nullptr);');
      if (func.returnType.name != 'void') {
        s.writeln('        return $dflt;');
      }
      s.writeln('    }');
      s.writeln('}');
      s.writeln();
    }

    // ── Properties ───────────────────────────────────────────────────────────
    for (final prop in spec.properties) {
      final isEnum = enumNames.contains(prop.type.name.replaceFirst('?', ''));
      final cType = isEnum ? 'int64_t' : _typeToC(prop.type.name);

      if (prop.hasGetter) {
        s.writeln('$cType ${prop.getSymbol}(void) {');
        s.writeln('    ${libStem}_clear_error();');
        s.writeln('    if (!g_impl) { $notInit; return ${_defaultValue(cType)}; }');
        s.writeln('    try {');
        if (prop.type.name == 'String') {
          s.writeln('        std::string _res = g_impl->get_${prop.dartName}();');
          s.writeln('        return strdup(_res.c_str());');
        } else if (isEnum) {
          s.writeln('        return static_cast<int64_t>(g_impl->get_${prop.dartName}());');
        } else if (recordNames.contains(prop.type.name.replaceFirst('?', ''))) {
          s.writeln('        NitroCppBuffer _res = g_impl->get_${prop.dartName}();');
          s.writeln('        return (void*)_res.data;');
        } else if (structNames.contains(prop.type.name.replaceFirst('?', ''))) {
          final stName = prop.type.name.replaceFirst('?', '');
          s.writeln('        $stName _res = g_impl->get_${prop.dartName}();');
          s.writeln('        $stName* _ptr = ($stName*)malloc(sizeof($stName));');
          s.writeln('        *_ptr = _res;');
          s.writeln('        return _ptr;');
        } else {
          s.writeln('        return g_impl->get_${prop.dartName}();');
        }
        s.writeln('    } catch (const std::exception& e) {');
        s.writeln('        nitro_report_error("CppException", e.what(), nullptr, nullptr);');
        s.writeln('        return ${_defaultValue(cType)};');
        s.writeln('    }');
        s.writeln('}');
        s.writeln();
      }

      if (prop.hasSetter) {
        final isStructParam = structNames.contains(prop.type.name.replaceFirst('?', ''));
        final isRecordParam = recordNames.contains(prop.type.name.replaceFirst('?', ''));
        final paramCType = (isEnum || isStructParam || isRecordParam) ? (isEnum ? 'int64_t' : 'void*') : _typeToC(prop.type.name);
        s.writeln('void ${prop.setSymbol}($paramCType value) {');
        s.writeln('    ${libStem}_clear_error();');
        s.writeln('    if (!g_impl) { $notInit; return; }');
        s.writeln('    try {');
        if (prop.type.name == 'String') {
          s.writeln('        g_impl->set_${prop.dartName}(std::string(value));');
        } else if (isEnum) {
          final enumName = prop.type.name.replaceFirst('?', '');
          s.writeln('        g_impl->set_${prop.dartName}(static_cast<$enumName>(value));');
        } else if (isRecordParam) {
          final opt = prop.type.name.endsWith('?');
          if (opt) {
            s.writeln('        NitroCppBuffer _buf = { nullptr, 0 };');
            s.writeln('        if (value != nullptr) {');
            s.writeln('            _buf.data = (const uint8_t*)value + 4;');
            s.writeln('            _buf.size = (size_t)*(int32_t*)value;');
            s.writeln('        }');
            s.writeln('        g_impl->set_${prop.dartName}(_buf);');
          } else {
            s.writeln('        NitroCppBuffer _buf = { (const uint8_t*)value + 4, (size_t)*(int32_t*)value };');
            s.writeln('        g_impl->set_${prop.dartName}(_buf);');
          }
        } else if (isStructParam) {
          final stName = prop.type.name.replaceFirst('?', '');
          s.writeln('        g_impl->set_${prop.dartName}(*static_cast<const $stName*>(value));');
        } else {
          s.writeln('        g_impl->set_${prop.dartName}(value);');
        }
        s.writeln('    } catch (const std::exception& e) {');
        s.writeln('        nitro_report_error("CppException", e.what(), nullptr, nullptr);');
        s.writeln('    }');
        s.writeln('}');
        s.writeln();
      }
    }

    // ── Streams ──────────────────────────────────────────────────────────────
    for (final stream in spec.streams) {
      s.writeln('void ${stream.registerSymbol}(int64_t dart_port) {');
      s.writeln('    g_port_${stream.dartName} = dart_port;');
      s.writeln('}');
      s.writeln('void ${stream.releaseSymbol}(int64_t dart_port) {');
      s.writeln('    if (g_port_${stream.dartName} == dart_port) g_port_${stream.dartName} = 0;');
      s.writeln('}');
      s.writeln();
    }

    // ── Struct release functions (used by NativeFinalizer in Dart proxy classes) ─
    for (final st in spec.structs) {
      s.writeln('// Frees a malloc\'d [${st.name}] wrapper allocated by the stream emitter.');
      s.writeln('// Called automatically by NativeFinalizer when the Dart proxy is GC\'d.');
      s.writeln('void ${libStem}_release_${st.name}(void* ptr) {');
      s.writeln('    if (!ptr) return;');
      s.writeln('    free(ptr);');
      s.writeln('}');
      s.writeln();
    }

    s.writeln('} // extern "C"');
    if (cppIosOnly) s.writeln('#endif // __APPLE__');
    if (cppAndroidOnly) s.writeln('#endif // __ANDROID__');
    return s.toString();
  }

  // ── Helpers shared between both paths ────────────────────────────────────

  static String _cppScalarType(String dartType, Set<String> enumNames, Set<String> structNames) {
    final base = dartType.replaceFirst('?', '');
    if (base == 'String') return 'std::string';
    if (enumNames.contains(base)) return base;
    if (structNames.contains(base)) return base;
    return _typeToC(base);
  }

  // ── Legacy JNI+Swift path (NativeImpl.kotlin / NativeImpl.swift) ───────────

  // ignore: avoid_positional_boolean_parameters
  static String _generateJniSwift(
    BridgeSpec spec, {
    bool includeAndroid = true,
    bool includeIos = true,
  }) {
    final s = StringBuffer();
    final headerName = '${spec.lib.replaceAll('-', '_')}.bridge.g.h';

    s.writeln('// Generated by Nitrogen Modules. Do not edit.');
    s.writeln('// Generated from: ${spec.sourceUri.split('/').last}');
    s.writeln('#include <stdint.h>');
    s.writeln('#include <stdbool.h>');
    s.writeln('#include <string.h>');
    s.writeln('#include <stdlib.h>');
    s.writeln('#include "dart_api_dl.h"');
    s.writeln('#include "$headerName"');
    s.writeln();

    final libStem = spec.lib.replaceAll('-', '_');
    final libPkg = 'nitro/${libStem}_module';
    // Pre-build O(1) lookup sets — avoids O(n×m) .any() scans inside the
    // generation loops (functions × enums, params × structs, etc.).
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final structNames = spec.structs.map((s) => s.name).toSet();
    s.writeln('extern "C" {');
    s.writeln('intptr_t ${libStem}_init_dart_api_dl(void* data) {');
    s.writeln('    return Dart_InitializeApiDL(data);');
    s.writeln('}');
    s.writeln('}');

    s.writeln('static thread_local NitroError g_nitro_error = { 0, nullptr, nullptr, nullptr, nullptr };');
    s.writeln();
    s.writeln('extern "C" {');
    s.writeln('NitroError* ${libStem}_get_error() { return &g_nitro_error; }');
    s.writeln('void ${libStem}_clear_error() {');
    s.writeln('    g_nitro_error.hasError = 0;');
    s.writeln('    if (g_nitro_error.name) { free((void*)g_nitro_error.name); g_nitro_error.name = nullptr; }');
    s.writeln('    if (g_nitro_error.message) { free((void*)g_nitro_error.message); g_nitro_error.message = nullptr; }');
    s.writeln('    if (g_nitro_error.code) { free((void*)g_nitro_error.code); g_nitro_error.code = nullptr; }');
    s.writeln('    if (g_nitro_error.stackTrace) { free((void*)g_nitro_error.stackTrace); g_nitro_error.stackTrace = nullptr; }');
    s.writeln('}');
    s.writeln();
    s.writeln('static void nitro_report_error(const char* name, const char* message, const char* code, const char* stack) {');
    s.writeln('    ${libStem}_clear_error();');
    s.writeln('    g_nitro_error.hasError = 1;');
    s.writeln('    g_nitro_error.name = name ? strdup(name) : strdup("NativeException");');
    s.writeln('    g_nitro_error.message = message ? strdup(message) : strdup("An unknown native exception occurred.");');
    s.writeln('    g_nitro_error.code = code ? strdup(code) : nullptr;');
    s.writeln('    g_nitro_error.stackTrace = stack ? strdup(stack) : nullptr;');
    s.writeln('}');
    s.writeln('}');
    s.writeln('');

    // Preprocessor branch for Android JNI vs iOS Swift
    if (includeAndroid && includeIos) s.writeln('#ifdef __ANDROID__');
    if (includeAndroid) {
    s.writeln('#include <jni.h>');
    s.writeln('#include <android/log.h>');
    s.writeln(
      '#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "Nitrogen", __VA_ARGS__)',
    );
    s.writeln();
    s.writeln('static JavaVM* g_jvm = nullptr;');
    s.writeln('static jclass g_bridgeClass = nullptr;');
    s.writeln();
    s.writeln('// ── Cached JNI IDs (initialized once in JNI_OnLoad, safe to use from any thread) ──');
    s.writeln('static jmethodID g_exc_getName = nullptr;');
    s.writeln('static jmethodID g_exc_getMessage = nullptr;');
    for (final func in spec.functions) {
      s.writeln('static jmethodID g_mid_${func.dartName}_call = nullptr;');
    }
    for (final prop in spec.properties) {
      if (prop.hasGetter) s.writeln('static jmethodID g_mid_${prop.getSymbol}_call = nullptr;');
      if (prop.hasSetter) s.writeln('static jmethodID g_mid_${prop.setSymbol}_call = nullptr;');
    }
    for (final stream in spec.streams) {
      s.writeln('static jmethodID g_mid_${stream.registerSymbol}_call = nullptr;');
      s.writeln('static jmethodID g_mid_${stream.releaseSymbol}_call = nullptr;');
    }
    for (final st in spec.structs) {
      s.writeln('static jclass g_cls_${st.name} = nullptr;');
      s.writeln('static jmethodID g_ctor_${st.name} = nullptr;');
      for (final f in st.fields) {
        s.writeln('static jfieldID g_fid_${st.name}_${f.name} = nullptr;');
      }
    }
    s.writeln();
    s.writeln('// RAII guard: auto-detaches a thread from the JVM when it exits.');
    s.writeln('// One instance is stored in thread-local storage; its destructor fires');
    s.writeln('// when the thread terminates, ensuring no JVM thread descriptor leaks.');
    s.writeln('struct NitroJniThreadGuard {');
    s.writeln('    bool attached = false;');
    s.writeln('    ~NitroJniThreadGuard() {');
    s.writeln('        if (attached && g_jvm != nullptr) {');
    s.writeln('            g_jvm->DetachCurrentThread();');
    s.writeln('        }');
    s.writeln('    }');
    s.writeln('};');
    s.writeln('static thread_local NitroJniThreadGuard g_thread_guard;');
    s.writeln();
    s.writeln('static void nitro_report_jni_exception(JNIEnv* env, jthrowable ex) {');
    s.writeln('    // MUST clear the pending exception before making any further JNI calls.');
    s.writeln('    // JNI aborts if any JNI function (e.g. GetObjectClass) is called while');
    s.writeln('    // an exception is still pending.');
    s.writeln('    env->ExceptionClear();');
    s.writeln('    jclass ex_class = env->GetObjectClass(ex);');
    s.writeln('    jstring j_name = (jstring)env->CallObjectMethod(ex_class, g_exc_getName);');
    s.writeln('    const char* name = (j_name != nullptr) ? env->GetStringUTFChars(j_name, 0) : "JavaException";');
    s.writeln();
    s.writeln('    jstring j_msg = (jstring)env->CallObjectMethod(ex, g_exc_getMessage);');
    s.writeln('    const char* msg = (j_msg != nullptr) ? env->GetStringUTFChars(j_msg, 0) : "No message provided";');
    s.writeln();
    s.writeln('    nitro_report_error(name, msg, nullptr, nullptr);');
    s.writeln();
    s.writeln('    if (j_name) env->ReleaseStringUTFChars(j_name, name);');
    s.writeln('    if (j_msg) env->ReleaseStringUTFChars(j_msg, msg);');
    s.writeln('    env->DeleteLocalRef(ex);');
    s.writeln('}');
    s.writeln();

    // JNI struct unpack helpers (C struct → Java object)
    for (final st in spec.structs) {
      // pack: Java object → C struct (used for stream emit and return values)
      s.writeln(
        'static ${st.name} pack_${st.name}_from_jni(JNIEnv* env, jobject obj) {',
      );
      s.writeln('    ${st.name} result;');
      for (final f in st.fields) {
        final isEnumField = enumNames.contains(f.type.name.replaceFirst('?', ''));
        final isZeroCopyField = _isZeroCopy(st, f.name);
        final getter = isEnumField ? 'GetLongField' : _jniGetter(f.type.name);
        if (isZeroCopyField) {
          final elemCast = _zeroCopyCElementCast(f.type.name);
          s.writeln(
            '    jobject buf_${f.name} = env->GetObjectField(obj, g_fid_${st.name}_${f.name});',
          );
          // Null guard: GetDirectBufferAddress(null) returns null — assign it
          // to the struct field unchecked causes a silent null-deref on use.
          s.writeln('    if (buf_${f.name} == nullptr) {');
          s.writeln('        jclass npe = env->FindClass("java/lang/NullPointerException");');
          s.writeln('        if (npe) env->ThrowNew(npe, "${st.name}.${f.name}: TypedData ByteBuffer is null");');
          s.writeln('        return result;');
          s.writeln('    }');
          s.writeln(
            '    result.${f.name} = ($elemCast)env->GetDirectBufferAddress(buf_${f.name});',
          );
        } else if (f.type.name == 'String') {
          s.writeln(
            '    jstring j_${f.name} = (jstring)env->GetObjectField(obj, g_fid_${st.name}_${f.name});',
          );
          s.writeln(
            '    const char* str_${f.name} = env->GetStringUTFChars(j_${f.name}, 0);',
          );
          s.writeln('    result.${f.name} = strdup(str_${f.name});');
          s.writeln(
            '    env->ReleaseStringUTFChars(j_${f.name}, str_${f.name});',
          );
        } else if (isEnumField) {
          final enumType = f.type.name.replaceFirst('?', '');
          s.writeln(
            '    result.${f.name} = ($enumType)(int32_t)env->$getter(obj, g_fid_${st.name}_${f.name});',
          );
        } else {
          s.writeln('    result.${f.name} = env->$getter(obj, g_fid_${st.name}_${f.name});');
        }
      }
      s.writeln('    return result;');
      s.writeln('}');

      // unpack: C struct → Java object (used for passing struct params to Kotlin)
      s.writeln(
        'static jobject unpack_${st.name}_to_jni(JNIEnv* env, const ${st.name}* st) {',
      );
      // Pre-compute zero-copy ByteBuffer objects with null guards.
      // NewDirectByteBuffer(nullptr, n) is undefined behaviour in JNI — guard
      // every zeroCopy pointer before passing it to the constructor.
      for (final f in st.fields) {
        if (!_isZeroCopy(st, f.name)) continue;
        final lenField = _zeroCopyLenField(st, f.name);
        final elemSize = _zeroCopyElementSizeExpr(f.type.name);
        s.writeln('    if (st->${f.name} == nullptr) {');
        s.writeln('        jclass npe = env->FindClass("java/lang/NullPointerException");');
        s.writeln('        if (npe) env->ThrowNew(npe, "${st.name}.${f.name}: TypedData pointer is null");');
        s.writeln('        return nullptr;');
        s.writeln('    }');
        // NewDirectByteBuffer takes a BYTE count, not element count.
        s.writeln('    jobject dbuf_${f.name} = env->NewDirectByteBuffer((void*)st->${f.name}, st->$lenField$elemSize);');
      }
      final ctorArgs = st.fields
          .map((f) {
            final isEnum = enumNames.contains(f.type.name.replaceFirst('?', ''));
            if (_isZeroCopy(st, f.name)) {
              // Reference the pre-computed (and null-guarded) local variable.
              return 'dbuf_${f.name}';
            } else if (f.type.name == 'String') {
              return 'env->NewStringUTF(st->${f.name})';
            } else if (isEnum) {
              return '(jlong)(int32_t)st->${f.name}';
            } else {
              return '(${_jniCast(f.type.name)})st->${f.name}';
            }
          })
          .join(', ');
      s.writeln('    return env->NewObject(g_cls_${st.name}, g_ctor_${st.name}, $ctorArgs);');
      s.writeln('}');
    }
    s.writeln();

    s.writeln('extern "C" {');
    s.writeln();
    s.writeln(
      'JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {',
    );
    s.writeln('    g_jvm = vm;');
    s.writeln(
      '    __android_log_print(ANDROID_LOG_INFO, "Nitrogen", "JNI_OnLoad called for ${spec.lib}");',
    );
    s.writeln('    JNIEnv* env = nullptr;');
    s.writeln(
      '    if (vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) != JNI_OK) {',
    );
    s.writeln('        return -1;');
    s.writeln('    }');
    s.writeln(
      '    jclass localClass = env->FindClass("nitro/${spec.lib.replaceAll('-', '_')}_module/${spec.dartClassName}JniBridge");',
    );
    s.writeln('    if (localClass != nullptr) {');
    s.writeln('        g_bridgeClass = (jclass)env->NewGlobalRef(localClass);');
    s.writeln('        env->DeleteLocalRef(localClass);');
    s.writeln('    } else {');
    s.writeln('        LOGE("Failed to find JniBridge class");');
    s.writeln('    }');
    s.writeln();
    s.writeln('    // Cache exception introspection method IDs');
    s.writeln('    {');
    s.writeln('        jclass cls_class = env->FindClass("java/lang/Class");');
    s.writeln('        if (cls_class) { g_exc_getName = env->GetMethodID(cls_class, "getName", "()Ljava/lang/String;"); env->DeleteLocalRef(cls_class); }');
    s.writeln('        jclass throwable_class = env->FindClass("java/lang/Throwable");');
    s.writeln('        if (throwable_class) { g_exc_getMessage = env->GetMethodID(throwable_class, "getMessage", "()Ljava/lang/String;"); env->DeleteLocalRef(throwable_class); }');
    s.writeln('    }');
    s.writeln();
    if (spec.functions.isNotEmpty || spec.properties.isNotEmpty || spec.streams.isNotEmpty) {
      s.writeln('    // Cache bridge method IDs');
      s.writeln('    if (g_bridgeClass != nullptr) {');
      for (final func in spec.functions) {
        final jniSig = _jniSig(func.params, func.returnType, enumNames, structNames, libPkg);
        s.writeln('        g_mid_${func.dartName}_call = env->GetStaticMethodID(g_bridgeClass, "${func.dartName}_call", "$jniSig");');
      }
      for (final prop in spec.properties) {
        final isEnum = enumNames.contains(prop.type.name);
        if (prop.hasGetter) {
          final jniRetSig = isEnum ? 'J' : _jniSigType(prop.type.name);
          s.writeln('        g_mid_${prop.getSymbol}_call = env->GetStaticMethodID(g_bridgeClass, "${prop.getSymbol}_call", "()$jniRetSig");');
        }
        if (prop.hasSetter) {
          final jniParamSig = isEnum ? 'J' : _jniSigType(prop.type.name);
          s.writeln('        g_mid_${prop.setSymbol}_call = env->GetStaticMethodID(g_bridgeClass, "${prop.setSymbol}_call", "($jniParamSig)V");');
        }
      }
      for (final stream in spec.streams) {
        s.writeln('        g_mid_${stream.registerSymbol}_call = env->GetStaticMethodID(g_bridgeClass, "${stream.registerSymbol}_call", "(J)V");');
        s.writeln('        g_mid_${stream.releaseSymbol}_call = env->GetStaticMethodID(g_bridgeClass, "${stream.releaseSymbol}_call", "(J)V");');
      }
      s.writeln('    }');
      s.writeln();
    }
    if (spec.structs.isNotEmpty) {
      s.writeln('    // Cache struct class + ctor + field IDs');
      for (final st in spec.structs) {
        final jniClass = 'nitro/${spec.lib.replaceAll('-', '_')}_module/${st.name}';

        final ctorSig =
            '(${st.fields.map((f) {
              final isEnum = enumNames.contains(f.type.name.replaceFirst('?', ''));
              if (isEnum) return 'J';
              if (_isZeroCopy(st, f.name)) return 'Ljava/nio/ByteBuffer;';
              return _jniSigType(f.type.name);
            }).join('')})V';
        s.writeln('    {');
        s.writeln('        jclass local_cls_${st.name} = env->FindClass("$jniClass");');
        s.writeln('        if (local_cls_${st.name} != nullptr) {');
        s.writeln('            g_cls_${st.name} = (jclass)env->NewGlobalRef(local_cls_${st.name});');
        s.writeln('            env->DeleteLocalRef(local_cls_${st.name});');
        s.writeln('            g_ctor_${st.name} = env->GetMethodID(g_cls_${st.name}, "<init>", "$ctorSig");');
        for (final f in st.fields) {
          final isEnum = enumNames.contains(f.type.name.replaceFirst('?', ''));
          final isZeroCopy = _isZeroCopy(st, f.name);
          final sig = isEnum ? 'J' : (isZeroCopy ? 'Ljava/nio/ByteBuffer;' : _jniSigType(f.type.name));
          s.writeln('            g_fid_${st.name}_${f.name} = env->GetFieldID(g_cls_${st.name}, "${f.name}", "$sig");');
        }
        s.writeln('        }');
        s.writeln('    }');
      }
      s.writeln();
    }
    s.writeln('    return JNI_VERSION_1_6;');
    s.writeln('}');
    s.writeln();
    s.writeln('static JNIEnv* GetEnv() {');
    s.writeln('    if (g_jvm == nullptr) return nullptr;');
    s.writeln('    JNIEnv* env = nullptr;');
    s.writeln(
      '    int status = g_jvm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);',
    );
    s.writeln('    if (status == JNI_EDETACHED) {');
    s.writeln('        g_jvm->AttachCurrentThread(&env, nullptr);');
    s.writeln('        g_thread_guard.attached = true; // will DetachCurrentThread on thread exit');
    s.writeln('    }');
    s.writeln('    return env;');
    s.writeln('}');
    s.writeln();

    // ── Functions ─────────────────────────────────────────────────────────────
    for (final func in spec.functions) {
      final isEnum = enumNames.contains(func.returnType.name);
      final isStruct = structNames.contains(func.returnType.name);
      final isRecord = func.returnType.isRecord && !func.returnType.isMap;
      // For enum returns: bridge returns Long (nativeValue); C returns int64_t
      // For struct returns: bridge returns jobject; C packs to C struct via malloc
      // For record returns: bridge returns ByteArray; C copies bytes to malloc'd buffer
      final cReturnType = isEnum ? 'int64_t' : _typeToC(func.returnType.name);
      final paramsDeclParts = <String>[];
      for (final p in func.params) {
        paramsDeclParts.add('${_paramTypeToC(p.type.name, structNames)} ${p.name}');
        if (p.type.isTypedData) paramsDeclParts.add('int64_t ${p.name}_length');
      }
      final paramsDecl = paramsDeclParts.join(', ');

      s.writeln(
        '$cReturnType ${func.cSymbol}(${paramsDecl.isEmpty ? 'void' : paramsDecl}) {',
      );
      s.writeln('    JNIEnv* env = GetEnv();');
      if (func.returnType.name == 'void') {
        s.writeln('    if (env == nullptr) return;');
      } else {
        s.writeln(
          '    if (env == nullptr) return ${_defaultValue(cReturnType)};',
        );
      }
      s.writeln('    jmethodID methodId = g_mid_${func.dartName}_call;');
      if (func.returnType.name == 'void') {
        s.writeln('    if (methodId == nullptr) { LOGE("Method not found"); return; }');
      } else {
        s.writeln('    if (methodId == nullptr) { LOGE("Method not found"); return ${_defaultValue(cReturnType)}; }');
      }
      s.writeln();
      s.writeln('    ${libStem}_clear_error();');

      // Build call args (converting C types to JNI types)
      final callArgsList = <String>[];
      final jniTypedArrayParams = <String>[];
      for (final p in func.params) {
        final pt = p.type.name;
        if (pt == 'String') {
          s.writeln('    jstring j_${p.name} = env->NewStringUTF(${p.name});');
          callArgsList.add('j_${p.name}');
        } else if (structNames.contains(pt)) {
          s.writeln(
            '    jobject jobj_${p.name} = unpack_${pt}_to_jni(env, (const $pt*)${p.name});',
          );
          callArgsList.add('jobj_${p.name}');
        } else if (p.zeroCopy && p.type.isTypedData) {
          // Zero-copy: wrap native pointer in a DirectByteBuffer (no data copy)
          final elemSize = _zeroCopyElementSizeExpr(pt);
          s.writeln('    jobject j_${p.name} = env->NewDirectByteBuffer(${p.name}, ${p.name}_length$elemSize);');
          callArgsList.add('j_${p.name}');
        } else if (!p.zeroCopy && p.type.isTypedData) {
          // Non-zero-copy: copy data into a JNI typed array
          final ops = _typedDataJniOps(pt);
          s.writeln('    ${ops[0]} j_${p.name} = env->${ops[1]}((jsize)${p.name}_length);');
          s.writeln('    env->${ops[2]}(j_${p.name}, 0, (jsize)${p.name}_length, (const ${ops[3]}*)${p.name});');
          callArgsList.add('j_${p.name}');
          jniTypedArrayParams.add(p.name);
        } else {
          callArgsList.add(p.name);
        }
      }

      final callArgs = callArgsList.join(', ');
      final bridgeArgs = callArgs.isEmpty ? '' : ', $callArgs';

      if (func.returnType.name == 'void') {
        s.writeln(
          '    env->CallStaticVoidMethod(g_bridgeClass, methodId$bridgeArgs);',
        );
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
      } else if (func.returnType.name == 'double') {
        s.writeln(
          '    double res = env->CallStaticDoubleMethod(g_bridgeClass, methodId$bridgeArgs);',
        );
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
        s.writeln('    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred()); return 0.0; }');
        s.writeln('    return res;');
      } else if (func.returnType.name == 'int') {
        s.writeln(
          '    int64_t res = env->CallStaticLongMethod(g_bridgeClass, methodId$bridgeArgs);',
        );
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
        s.writeln('    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred()); return 0; }');
        s.writeln('    return res;');
      } else if (func.returnType.name == 'bool') {
        s.writeln(
          '    bool res = env->CallStaticBooleanMethod(g_bridgeClass, methodId$bridgeArgs);',
        );
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
        s.writeln('    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred()); return false; }');
        s.writeln('    return res;');
      } else if (func.returnType.name == 'String') {
        s.writeln(
          '    jstring jstr = (jstring)env->CallStaticObjectMethod(g_bridgeClass, methodId$bridgeArgs);',
        );
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
        s.writeln('    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred()); return nullptr; }');
        s.writeln('    if (jstr == nullptr) return nullptr;');
        s.writeln(
          '    const char* nativeStr = env->GetStringUTFChars(jstr, 0);',
        );
        s.writeln('    char* result = strdup(nativeStr);');
        s.writeln('    env->ReleaseStringUTFChars(jstr, nativeStr);');
        for (final p in func.params) {
          if (p.type.name == 'String') {
            s.writeln('    env->DeleteLocalRef(j_${p.name});');
          }
        }
        s.writeln('    env->DeleteLocalRef(jstr);');
        s.writeln('    return result;');
      } else if (isEnum) {
        // Bridge returns Long (nativeValue)
        s.writeln(
          '    int64_t res = env->CallStaticLongMethod(g_bridgeClass, methodId$bridgeArgs);',
        );
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
        s.writeln('    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred()); return 0; }');
        s.writeln('    return res;');
      } else if (isStruct) {
        // Bridge returns the Kotlin data class; pack it to C struct via malloc
        final stName = func.returnType.name;
        s.writeln(
          '    jobject jobj = env->CallStaticObjectMethod(g_bridgeClass, methodId$bridgeArgs);',
        );
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
        s.writeln('    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred()); return nullptr; }');
        s.writeln('    if (jobj == nullptr) return nullptr;');
        s.writeln('    $stName* result = ($stName*)malloc(sizeof($stName));');
        s.writeln('    *result = pack_${stName}_from_jni(env, jobj);');
        s.writeln('    env->DeleteLocalRef(jobj);');
        s.writeln('    return result;');
      } else if (isRecord) {
        // Bridge returns ByteArray (serialized @HybridRecord / List<@HybridRecord>)
        // Copy bytes to malloc'd buffer and return as void* for Dart RecordReader
        s.writeln('    jbyteArray jarr = (jbyteArray)env->CallStaticObjectMethod(g_bridgeClass, methodId$bridgeArgs);');
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
        s.writeln('    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred()); return nullptr; }');
        s.writeln('    if (jarr == nullptr) return nullptr;');
        s.writeln('    jsize len = env->GetArrayLength(jarr);');
        s.writeln('    uint8_t* result = (uint8_t*)malloc(len);');
        s.writeln('    env->GetByteArrayRegion(jarr, 0, len, (jbyte*)result);');
        s.writeln('    env->DeleteLocalRef(jarr);');
        s.writeln('    return result;');
      } else {
        for (final n in jniTypedArrayParams) {
          s.writeln('    env->DeleteLocalRef(j_$n);');
        }
        s.writeln('    return ${_defaultValue(cReturnType)};');
      }
      if (func.returnType.name == 'void') {
        s.writeln('    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred()); }');
      }
      s.writeln('}');
      s.writeln('');
    }

    // ── Properties ────────────────────────────────────────────────────────────
    for (final prop in spec.properties) {
      final isEnum = enumNames.contains(prop.type.name);
      final cType = isEnum ? 'int64_t' : _typeToC(prop.type.name);

      if (prop.hasGetter) {
        s.writeln('$cType ${prop.getSymbol}(void) {');
        s.writeln('    JNIEnv* env = GetEnv();');
        s.writeln('    if (env == nullptr) return ${_defaultValue(cType)};');
        s.writeln('    jmethodID methodId = g_mid_${prop.getSymbol}_call;');
        s.writeln(
          '    if (methodId == nullptr) { LOGE("Method not found"); return ${_defaultValue(cType)}; }',
        );
        if (prop.type.name == 'double') {
          s.writeln(
            '    return env->CallStaticDoubleMethod(g_bridgeClass, methodId);',
          );
        } else if (prop.type.name == 'int' || isEnum) {
          s.writeln(
            '    return ($cType)env->CallStaticLongMethod(g_bridgeClass, methodId);',
          );
        } else if (prop.type.name == 'bool') {
          s.writeln(
            '    return env->CallStaticBooleanMethod(g_bridgeClass, methodId);',
          );
        } else if (prop.type.name == 'String') {
          s.writeln(
            '    jstring jstr = (jstring)env->CallStaticObjectMethod(g_bridgeClass, methodId);',
          );
          s.writeln(
            '    const char* nativeStr = env->GetStringUTFChars(jstr, 0);',
          );
          s.writeln('    char* result = strdup(nativeStr);');
          s.writeln('    env->ReleaseStringUTFChars(jstr, nativeStr);');
          s.writeln('    env->DeleteLocalRef(jstr);');
          s.writeln('    return result;');
        } else {
          s.writeln('    return ${_defaultValue(cType)};');
        }
        s.writeln('}');
        s.writeln('');
      }

      if (prop.hasSetter) {
        final paramCType = isEnum ? 'int64_t' : _typeToC(prop.type.name);
        s.writeln('void ${prop.setSymbol}($paramCType value) {');
        s.writeln('    JNIEnv* env = GetEnv();');
        s.writeln('    if (env == nullptr) return;');
        s.writeln('    jmethodID methodId = g_mid_${prop.setSymbol}_call;');
        s.writeln(
          '    if (methodId == nullptr) { LOGE("Method not found"); return; }',
        );
        if (prop.type.name == 'String') {
          s.writeln('    jstring jval = env->NewStringUTF(value);');
          s.writeln(
            '    env->CallStaticVoidMethod(g_bridgeClass, methodId, jval);',
          );
          s.writeln('    env->DeleteLocalRef(jval);');
        } else {
          s.writeln(
            '    env->CallStaticVoidMethod(g_bridgeClass, methodId, value);',
          );
        }
        s.writeln('}');
        s.writeln('');
      }
    }

    // ── Streams ───────────────────────────────────────────────────────────────
    for (final stream in spec.streams) {
      final isStruct = structNames.contains(stream.itemType.name);
      // JNI name: "nitro" + "_" + "{lib}_module" (with internal _ → _1)
      // e.g. nitro.my_camera_module → nitro_my_1camera_1module (NOT nitro_1my_1camera_1module)

      s.writeln('void ${stream.registerSymbol}(int64_t dart_port) {');
      s.writeln('    JNIEnv* env = GetEnv();');
      s.writeln('    if (env == nullptr) return;');
      s.writeln('    jmethodID methodId = g_mid_${stream.registerSymbol}_call;');
      s.writeln(
        '    if (methodId != nullptr) env->CallStaticVoidMethod(g_bridgeClass, methodId, dart_port);',
      );
      s.writeln('}');
      s.writeln('');
      s.writeln('void ${stream.releaseSymbol}(int64_t dart_port) {');
      s.writeln('    JNIEnv* env = GetEnv();');
      s.writeln('    if (env == nullptr) return;');
      s.writeln('    jmethodID methodId = g_mid_${stream.releaseSymbol}_call;');
      s.writeln(
        '    if (methodId != nullptr) env->CallStaticVoidMethod(g_bridgeClass, methodId, dart_port);',
      );
      s.writeln('}');
      s.writeln('');

      final jniEmit = _jniMethodName(
        spec.lib,
        spec.dartClassName,
        'emit_${stream.dartName}',
      );
      s.writeln(
        'JNIEXPORT void JNICALL $jniEmit(JNIEnv* env, jobject thiz, jlong dartPort, ${_jniSigTypeC(stream.itemType.name)} item) {',
      );
      s.writeln('    Dart_CObject obj;');
      if (stream.itemType.name == 'double') {
        s.writeln('    obj.type = Dart_CObject_kDouble;');
        s.writeln('    obj.value.as_double = item;');
      } else if (stream.itemType.name == 'int') {
        s.writeln('    obj.type = Dart_CObject_kInt64;');
        s.writeln('    obj.value.as_int64 = item;');
      } else if (stream.itemType.name == 'bool') {
        s.writeln('    obj.type = Dart_CObject_kBool;');
        s.writeln('    obj.value.as_bool = item;');
      } else if (isStruct) {
        s.writeln(
          '    ${stream.itemType.name}* st_ptr = (${stream.itemType.name}*)malloc(sizeof(${stream.itemType.name}));',
        );
        s.writeln(
          '    *st_ptr = pack_${stream.itemType.name}_from_jni(env, item);',
        );
        s.writeln('    obj.type = Dart_CObject_kInt64;');
        s.writeln('    obj.value.as_int64 = (intptr_t)st_ptr;');
      } else {
        s.writeln('    obj.type = Dart_CObject_kNull;');
      }
      s.writeln('    Dart_PostCObject_DL(dartPort, &obj);');
      s.writeln('}');
      s.writeln('');
    }

    final jniInit = _jniMethodName(spec.lib, spec.dartClassName, 'initialize');
    s.writeln(
      'JNIEXPORT void JNICALL $jniInit(JNIEnv* env, jobject thiz, jclass bridgeClass) {',
    );
    s.writeln('    if (g_bridgeClass == nullptr) {');
    s.writeln(
      '        g_bridgeClass = (jclass)env->NewGlobalRef(bridgeClass);',
    );
    s.writeln('    }');
    s.writeln('}');
    s.writeln();

    s.writeln('} // extern "C"');
    } // end if (includeAndroid)

    // ── iOS Swift section ──────────────────────────────────────────────────────
    if (includeAndroid && includeIos) s.writeln('#elif __APPLE__');
    if (includeIos) {
    s.writeln('extern "C" {');
    for (final func in spec.functions) {
      final isEnum = enumNames.contains(func.returnType.name);
      final cReturnType = isEnum ? 'int64_t' : _typeToC(func.returnType.name);
      final paramParts = <String>[];
      final callParamParts = <String>[];
      for (final p in func.params) {
        paramParts.add('${_paramTypeToC(p.type.name, structNames)} ${p.name}');
        callParamParts.add(p.name);
        if (p.type.isTypedData) {
          paramParts.add('int64_t ${p.name}_length');
          callParamParts.add('${p.name}_length');
        }
      }
      final params = paramParts.join(', ');
      final callParams = callParamParts.join(', ');
      s.writeln(
        'extern $cReturnType _call_${func.dartName}(${params.isEmpty ? 'void' : params});',
      );
      s.writeln(
        '$cReturnType ${func.cSymbol}(${params.isEmpty ? 'void' : params}) {',
      );
      s.writeln('    ${libStem}_clear_error();');
      s.writeln('#ifdef __OBJC__');
      s.writeln('    @try {');
      if (func.returnType.name != 'void') {
        s.writeln('        return _call_${func.dartName}($callParams);');
      } else {
        s.writeln('        _call_${func.dartName}($callParams);');
      }
      s.writeln('    } @catch (NSException* e) {');
      s.writeln('        nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);');
      if (func.returnType.name != 'void') {
        s.writeln('        return ${_defaultValue(cReturnType)};');
      }
      s.writeln('    }');
      s.writeln('#else');
      if (func.returnType.name != 'void') {
        s.writeln('    return _call_${func.dartName}($callParams);');
      } else {
        s.writeln('    _call_${func.dartName}($callParams);');
      }
      s.writeln('#endif');
      s.writeln('}');
      s.writeln('');
    }

    for (final prop in spec.properties) {
      final isEnum = enumNames.contains(prop.type.name);
      final cType = isEnum ? 'int64_t' : _typeToC(prop.type.name);
      if (prop.hasGetter) {
        s.writeln('extern $cType _call_get_${prop.dartName}(void);');
        s.writeln('$cType ${prop.getSymbol}(void) {');
        s.writeln('    return _call_get_${prop.dartName}();');
        s.writeln('}');
        s.writeln('');
      }
      if (prop.hasSetter) {
        final paramCType = isEnum ? 'int64_t' : _typeToC(prop.type.name);
        s.writeln('extern void _call_set_${prop.dartName}($paramCType value);');
        s.writeln('void ${prop.setSymbol}($paramCType value) {');
        s.writeln('    _call_set_${prop.dartName}(value);');
        s.writeln('}');
        s.writeln('');
      }
    }

    for (final stream in spec.streams) {
      final isStruct = structNames.contains(stream.itemType.name);
      final itemCType = isStruct ? 'void*' : _typeToC(stream.itemType.name);
      s.writeln(
        'void _emit_${stream.dartName}_to_dart(int64_t dartPort, $itemCType item) {',
      );
      s.writeln('    Dart_CObject obj;');
      if (stream.itemType.name == 'double') {
        s.writeln('    obj.type = Dart_CObject_kDouble;');
        s.writeln('    obj.value.as_double = item;');
      } else if (stream.itemType.name == 'int') {
        s.writeln('    obj.type = Dart_CObject_kInt64;');
        s.writeln('    obj.value.as_int64 = (int64_t)item;');
      } else if (stream.itemType.name == 'bool') {
        s.writeln('    obj.type = Dart_CObject_kBool;');
        s.writeln('    obj.value.as_bool = item;');
      } else if (isStruct) {
        s.writeln('    obj.type = Dart_CObject_kInt64;');
        s.writeln('    obj.value.as_int64 = (intptr_t)item;');
      } else {
        s.writeln('    obj.type = Dart_CObject_kNull;');
      }
      s.writeln('    Dart_PostCObject_DL(dartPort, &obj);');
      s.writeln('}');
      s.writeln('');
      s.writeln(
        'extern void _register_${stream.dartName}_stream(int64_t dartPort, void (*emitCb)(int64_t, $itemCType));',
      );
      s.writeln('void ${stream.registerSymbol}(int64_t dart_port) {');
      s.writeln(
        '    _register_${stream.dartName}_stream(dart_port, _emit_${stream.dartName}_to_dart);',
      );
      s.writeln('}');
      s.writeln(
        'extern void _release_${stream.dartName}_stream(int64_t dart_port);',
      );
      s.writeln('void ${stream.releaseSymbol}(int64_t dart_port) {');
      s.writeln('    _release_${stream.dartName}_stream(dart_port);');
      s.writeln('}');
      s.writeln('');
    }
    // ── Struct release functions ──────────────────────────────────────────────────
    for (final st in spec.structs) {
      s.writeln('void ${libStem}_release_${st.name}(void* ptr) {');
      s.writeln('    if (!ptr) return;');
      s.writeln('    free(ptr);');
      s.writeln('}');
      s.writeln();
    }

    s.writeln('} // extern "C"');
    } // end if (includeIos)
    if (includeAndroid && includeIos) s.writeln('#endif');
    return s.toString();
  }

  static String _typeToC(String dartType) {
    switch (dartType.replaceFirst('?', '')) {
      case 'int':
        return 'int64_t';
      case 'double':
        return 'double';
      case 'bool':
        return 'int8_t';
      case 'String':
        return 'const char*';
      case 'Uint8List':
        return 'uint8_t*';
      case 'Int8List':
        return 'int8_t*';
      case 'Int16List':
        return 'int16_t*';
      case 'Int32List':
        return 'int32_t*';
      case 'Uint16List':
        return 'uint16_t*';
      case 'Uint32List':
        return 'uint32_t*';
      case 'Float32List':
        return 'float*';
      case 'Float64List':
        return 'double*';
      case 'Int64List':
        return 'int64_t*';
      case 'Uint64List':
        return 'uint64_t*';
      case 'void':
        return 'void';
      default:
        return 'void*';
    }
  }

  /// Like _typeToC but for function parameters (struct params pass as void*)
  static String _paramTypeToC(String dartType, Set<String> structNames) {
    if (structNames.contains(dartType.replaceFirst('?', ''))) {
      return 'void*';
    }
    return _typeToC(dartType);
  }

  static bool _isZeroCopy(BridgeStruct st, String fieldName) {
    return st.fields.any((f) => f.name == fieldName && f.zeroCopy);
  }

  /// Returns the field name used as the byte length for a zero-copy field.
  static String _zeroCopyLenField(BridgeStruct st, String zeroCopyField) {
    // Heuristic: use 'stride' if present, otherwise 'size', otherwise 'length'
    const candidates = ['stride', 'size', 'length'];
    for (final c in candidates) {
      if (st.fields.any((f) => f.name == c)) return c;
    }
    return 'size';
  }

  static String _jniGetter(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'GetLongField';
      case 'double':
        return 'GetDoubleField';
      case 'bool':
        return 'GetBooleanField';
      default:
        return 'GetObjectField';
    }
  }

  static String _defaultValue(String cType) {
    switch (cType) {
      case 'int64_t':
        return '0';
      case 'double':
        return '0.0';
      case 'int8_t':
        return 'false';
      case 'const char*':
        return 'nullptr';
      default:
        return 'nullptr';
    }
  }

  static String _jniSigType(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'J';
      case 'double':
        return 'D';
      case 'bool':
        return 'Z';
      case 'String':
        return 'Ljava/lang/String;';
      case 'void':
        return 'V';
      // Non-@ZeroCopy TypedData → Kotlin array types
      // (@ZeroCopy variants are intercepted in _jniSig before this is called)
      case 'Uint8List':
      case 'Int8List':
        return '[B'; // ByteArray
      case 'Int16List':
      case 'Uint16List':
        return '[S'; // ShortArray
      case 'Int32List':
      case 'Uint32List':
        return '[I'; // IntArray
      case 'Float32List':
        return '[F'; // FloatArray
      case 'Float64List':
        return '[D'; // DoubleArray
      case 'Int64List':
      case 'Uint64List':
        return '[J'; // LongArray
      default:
        return 'Ljava/lang/Object;';
    }
  }

  static String _jniSigTypeC(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'jlong';
      case 'double':
        return 'jdouble';
      case 'bool':
        return 'jboolean';
      case 'String':
        return 'jstring';
      case 'void':
        return 'void';
      case 'Uint8List':
        return 'jobject';
      default:
        return 'jobject';
    }
  }

  static String _jniCast(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'jlong';
      case 'double':
        return 'jdouble';
      case 'bool':
        return 'jboolean';
      default:
        return 'jobject';
    }
  }

  /// Returns the C cast type for a zero-copy TypedData struct field.
  ///
  /// `GetDirectBufferAddress` returns `void*`. The struct field type is the
  /// element pointer (e.g. `float*` for Float32List).  An explicit cast avoids
  /// the implicit `void* → typed pointer` conversion warning in C++.
  static String _zeroCopyCElementCast(String dartType) {
    switch (dartType.replaceFirst('?', '')) {
      case 'Uint8List':
        return 'uint8_t*';
      case 'Int8List':
        return 'int8_t*';
      case 'Int16List':
        return 'int16_t*';
      case 'Uint16List':
        return 'uint16_t*';
      case 'Int32List':
        return 'int32_t*';
      case 'Uint32List':
        return 'uint32_t*';
      case 'Float32List':
        return 'float*';
      case 'Float64List':
        return 'double*';
      case 'Int64List':
        return 'int64_t*';
      case 'Uint64List':
        return 'uint64_t*';
      default:
        return 'uint8_t*';
    }
  }

  /// Returns a C expression suffix to multiply the element count by element
  /// byte-size when calling `NewDirectByteBuffer` (which expects byte count).
  ///
  /// Returns `''` for byte-sized elements (no-op multiply) or
  /// ` * N` for multi-byte elements (e.g. ` * sizeof(float)`).
  static String _zeroCopyElementSizeExpr(String dartType) {
    switch (dartType.replaceFirst('?', '')) {
      case 'Uint8List':
      case 'Int8List':
        return ''; // 1 byte — no multiplication needed
      case 'Int16List':
      case 'Uint16List':
        return ' * sizeof(int16_t)';
      case 'Int32List':
      case 'Uint32List':
        return ' * sizeof(int32_t)';
      case 'Float32List':
        return ' * sizeof(float)';
      case 'Float64List':
        return ' * sizeof(double)';
      case 'Int64List':
      case 'Uint64List':
        return ' * sizeof(int64_t)';
      default:
        return '';
    }
  }

  /// Escapes a single JNI identifier component: replaces '_' with '_1'.
  /// JNI spec §2.4: each '.' separator becomes '_', and each '_' within
  /// an identifier becomes '_1'. This function handles the latter.
  static String _jniMangle(String s) => s.replaceAll('_', '_1');

  /// Builds a fully-qualified JNI C function name from logical components.
  ///
  /// Kotlin package: "nitro.{lib}_module"
  /// Examples:
  ///   lib='my_camera', class='MyCamera', method='emit_frames'
  ///     → 'Java_nitro_my_1camera_1module_MyCameraJniBridge_emit_1frames'
  ///   lib='sensor_hub', class='SensorHub', method='emit_sensor_data'
  ///     → 'Java_nitro_sensor_1hub_1module_SensorHubJniBridge_emit_1sensor_1data'
  static String _jniMethodName(
    String lib,
    String className,
    String methodName,
  ) {
    return [
      'Java',
      _jniMangle('nitro'), // 'nitro' (no underscores)
      _jniMangle(
        '${lib.replaceAll('-', '_')}_module',
      ), // e.g. 'my_1camera_1module'
      _jniMangle('${className}JniBridge'), // usually CamelCase — no underscores
      _jniMangle(methodName), // e.g. 'emit_1frames'
    ].join('_');
  }

  /// Returns [jniArrayType, newFn, setRegionFn, elemCast] for a non-zero-copy TypedData param.
  static List<String> _typedDataJniOps(String dartType) {
    switch (dartType) {
      case 'Uint8List':
      case 'Int8List':
        return ['jbyteArray', 'NewByteArray', 'SetByteArrayRegion', 'jbyte'];
      case 'Int16List':
      case 'Uint16List':
        return ['jshortArray', 'NewShortArray', 'SetShortArrayRegion', 'jshort'];
      case 'Int32List':
      case 'Uint32List':
        return ['jintArray', 'NewIntArray', 'SetIntArrayRegion', 'jint'];
      case 'Float32List':
        return ['jfloatArray', 'NewFloatArray', 'SetFloatArrayRegion', 'jfloat'];
      case 'Float64List':
        return ['jdoubleArray', 'NewDoubleArray', 'SetDoubleArrayRegion', 'jdouble'];
      case 'Int64List':
      case 'Uint64List':
        return ['jlongArray', 'NewLongArray', 'SetLongArrayRegion', 'jlong'];
      default:
        return ['jbyteArray', 'NewByteArray', 'SetByteArrayRegion', 'jbyte'];
    }
  }

  static String _jniSig(
    List<BridgeParam> params,
    BridgeType returnType,
    Set<String> enumNames,
    Set<String> structNames,
    String libPkg,
  ) {
    final sb = StringBuffer();
    sb.write('(');
    for (final p in params) {
      if (structNames.contains(p.type.name)) {
        // Struct params are passed as the Kotlin data class object
        sb.write('L$libPkg/${p.type.name};');
      } else if (p.zeroCopy && p.type.isTypedData) {
        // Zero-copy TypedData params bridge as java.nio.ByteBuffer (direct buffer)
        sb.write('Ljava/nio/ByteBuffer;');
      } else {
        sb.write(_jniSigType(p.type.name));
      }
    }
    sb.write(')');
    // Enum return type: bridge returns Long
    if (enumNames.contains(returnType.name)) {
      sb.write('J');
    } else if (structNames.contains(returnType.name)) {
      sb.write('L$libPkg/${returnType.name};');
    } else if (returnType.isRecord && !returnType.isMap) {
      // @HybridRecord / List<@HybridRecord>: bridge returns ByteArray ("[B")
      sb.write('[B');
    } else {
      sb.write(_jniSigType(returnType.name));
    }
    return sb.toString();
  }
}
