import '../bridge_spec.dart';
import 'enum_generator.dart';
import 'struct_generator.dart';
import 'record_generator.dart';

class DartFfiGenerator {
  static String generate(BridgeSpec spec) {
    final s = StringBuffer();
    s.writeln('// Generated by Nitrogen Modules. Do not edit.');
    s.writeln('// Generated from: ${spec.sourceUri.split('/').last}');
    s.writeln("part of '${spec.sourceUri.split('/').last}';");
    s.writeln();

    // Enum & struct extensions (class bodies live in .native.dart)
    final enumExt = EnumGenerator.generateDartExtensions(spec);
    if (enumExt.isNotEmpty) s.write(enumExt);
    final structExt = StructGenerator.generateDartExtensions(spec);
    if (structExt.isNotEmpty) s.write(structExt);

    // Zero-copy native proxies for @HybridStruct (used by streams)
    final proxyExt = StructGenerator.generateDartProxies(spec);
    if (proxyExt.isNotEmpty) s.write(proxyExt);

    // @HybridRecord fromJson / toJson extensions
    final recordExt = RecordGenerator.generateDartExtensions(spec);
    if (recordExt.isNotEmpty) s.write(recordExt);

    // ── Impl class ──────────────────────────────────────────────────────────
    final libStem = spec.lib.replaceAll('-', '_');
    s.writeln(
      'class _${spec.dartClassName}Impl extends ${spec.dartClassName} {',
    );
    s.writeln('  final DynamicLibrary _dylib;');
    s.writeln();
    s.writeln(
      '  _${spec.dartClassName}Impl() : _dylib = NitroRuntime.loadLib(\'${spec.lib}\') {',
    );
    s.writeln(
      "    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>), int Function(Pointer<Void>)>('${libStem}_init_dart_api_dl');",
    );
    s.writeln('    final initCode = initFunc(NativeApi.initializeApiDLData);');
    s.writeln('    if (initCode != 0) {');
    s.writeln("      throw StateError('${spec.lib}: Dart API DL initialization failed with code \$initCode.');");
    s.writeln('    }');
    s.writeln('  }');
    s.writeln();

    // ── Method pointers ─────────────────────────────────────────────────────
    for (final func in spec.functions) {
      final nativeType = _toNativeType(func, spec);
      final dartType = _toDartType(func, spec);
      // isLeaf: true skips the Dart VM safepoint transition on every call —
      // valid for any sync bridge function whose C++ body never calls back into
      // Dart.  Candidates: explicitly "Fast"-suffixed methods AND any sync
      // method whose params/return are plain FFI scalars (no arena allocation).
      final isLeaf = _isLeafCandidate(func, spec);
      if (isLeaf) {
        s.writeln(
          "  late final $dartType _${func.dartName}Ptr = _dylib.lookup<NativeFunction<$nativeType>>('${func.cSymbol}').asFunction<$dartType>(isLeaf: true);",
        );
      } else {
        s.writeln(
          "  late final $dartType _${func.dartName}Ptr = _dylib.lookupFunction<$nativeType, $dartType>('${func.cSymbol}');",
        );
      }
    }

    // ── Property pointers ───────────────────────────────────────────────────
    for (final prop in spec.properties) {
      final ffiType = _typeToFFI(prop.type, spec);
      final dartType = _typeToDartFFI(prop.type, spec);
      final cap = _cap(prop.dartName);
      // Property accessors are always synchronous and their C++ bodies never
      // call back into Dart, so primitive-typed accessors qualify for isLeaf.
      final isLeafProp = _isPrimitiveType(prop.type, spec);
      if (prop.hasGetter) {
        if (isLeafProp) {
          s.writeln(
            "  late final $dartType Function() _get${cap}Ptr = _dylib.lookup<NativeFunction<$ffiType Function()>>('${prop.getSymbol}').asFunction<$dartType Function()>(isLeaf: true);",
          );
        } else {
          s.writeln(
            "  late final $dartType Function() _get${cap}Ptr = _dylib.lookupFunction<$ffiType Function(), $dartType Function()>('${prop.getSymbol}');",
          );
        }
      }
      if (prop.hasSetter) {
        if (isLeafProp) {
          s.writeln(
            "  late final void Function($dartType) _set${cap}Ptr = _dylib.lookup<NativeFunction<Void Function($ffiType)>>('${prop.setSymbol}').asFunction<void Function($dartType)>(isLeaf: true);",
          );
        } else {
          s.writeln(
            "  late final void Function($dartType) _set${cap}Ptr = _dylib.lookupFunction<Void Function($ffiType), void Function($dartType)>('${prop.setSymbol}');",
          );
        }
      }
    }

    // ── Stream register/release pointers ────────────────────────────────────
    for (final stream in spec.streams) {
      final cap = _cap(stream.dartName);
      s.writeln(
        "  late final void Function(int) _register${cap}Ptr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('${stream.registerSymbol}');",
      );
      s.writeln(
        "  late final void Function(int) _release${cap}Ptr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('${stream.releaseSymbol}');",
      );
    }

    // ── Error handling pointers (Cached to avoid dlsym on every check) ──────
    s.writeln('  // ignore: unused_field');
    s.writeln(
      "  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib.lookupFunction<Pointer<NitroErrorFfi> Function(), Pointer<NitroErrorFfi> Function()>('${libStem}_get_error');",
    );
    s.writeln('  // ignore: unused_field');
    s.writeln(
      "  late final void Function() _clearErrorPtr = _dylib.lookupFunction<Void Function(), void Function()>('${libStem}_clear_error');",
    );
    s.writeln('  // ignore: unused_field');
    s.writeln(
      "  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>> _getErrorNativePtr = _dylib.lookup('${libStem}_get_error');",
    );
    s.writeln('  // ignore: unused_field');
    s.writeln(
      "  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr = _dylib.lookup('${libStem}_clear_error');",
    );
    s.writeln();

    // ── dispose() override ───────────────────────────────────────────────────
    s.writeln('  @override');
    s.writeln('  // ignore: unnecessary_overrides');
    s.writeln('  void dispose() {');
    s.writeln(
      '    super.dispose(); // sets isDisposed = true, calls onDestroy()',
    );
    s.writeln('  }');
    s.writeln();

    // ── Method implementations ───────────────────────────────────────────────
    for (final func in spec.functions) {
      final returnType = func.isAsync ? 'Future<${func.returnType.name}>' : func.returnType.name;
      final asyncMod = func.isAsync ? 'async ' : '';

      final needsArena = func.params.any(
        (p) => p.type.isTypedData || p.type.name == 'String' || p.type.isRecord || spec.structs.any((st) => st.name == p.type.name),
      );

      final callArgs = func.params
          .expand((p) {
            final t = p.type.name;
            if (p.type.isRecord) {
              return [_encodeRecordParam(p.type, p.name, 'arena')];
            }
            if (p.type.isPointer) {
              return [p.name];
            }
            if (p.type.isTypedData) {
              return ['${p.name}.toPointer(arena)', '${p.name}.length'];
            }
            if (t == 'String') {
              return ['${p.name}.toNativeUtf8(allocator: arena)'];
            }
            if (spec.structs.any((st) => st.name == t)) {
              return ['${p.name}.toNative(arena).cast<Void>()'];
            }
            if (spec.enums.any((en) => en.name == t)) {
              return ['${p.name}.nativeValue'];
            }
            if (t == 'bool') return ['${p.name} ? 1 : 0'];
            return [p.name];
          })
          .join(', ');

      s.writeln('  @override');
      s.writeln(
        '  $returnType ${func.dartName}(${_paramList(func.params)}) $asyncMod{',
      );
      final isFast = func.dartName.endsWith('Fast');
      s.writeln('    checkDisposed();');

      final rt = func.returnType.name;
      final isRecordReturn = func.returnType.isRecord;

      if (func.isAsync) {
        final isStructReturn = spec.structs.any((st) => st.name == rt);
        final isEnumReturn = spec.enums.any((en) => en.name == rt);
        final plainCallArgs = func.params.map((p) => p.name).join(', ');
        final callAsyncType = isRecordReturn
            ? 'Pointer<Uint8>'
            : rt == 'String'
            ? 'Pointer<Utf8>'
            : isStructReturn
            ? 'Pointer<Void>'
            : isEnumReturn
            ? 'int'
            : _typeToDartFFI(func.returnType, spec);

        final errArgs = 'getError: _getErrorNativePtr, clearError: _clearErrorNativePtr';

        if (needsArena) {
          s.writeln('    final arena = Arena();');
          s.writeln('    try {');
          if (isRecordReturn) {
            s.writeln('      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(_${func.dartName}Ptr, [$callArgs], $errArgs);');
            final decodeExpr = _decodeRecordExpr(func.returnType, 'rawPtr');
            s.writeln('      try {');
            s.writeln('        return $decodeExpr;');
            s.writeln('      } finally {');
            s.writeln('        malloc.free(rawPtr);');
            s.writeln('      }');
          } else if (rt == 'String') {
            s.writeln('      final rawPtr = await NitroRuntime.callAsync<Pointer<Utf8>>(_${func.dartName}Ptr, [$callArgs], $errArgs);');
            s.writeln('      return rawPtr.toDartStringWithFree();');
          } else if (isStructReturn) {
            s.writeln('      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(_${func.dartName}Ptr, [$callArgs], $errArgs);');
            s.writeln('      final structPtr = Pointer<${rt}Ffi>.fromAddress(rawPtr.address);');
            s.writeln('      try {');
            s.writeln('        return structPtr.ref.toDart();');
            s.writeln('      } finally {');
            s.writeln('        malloc.free(structPtr);');
            s.writeln('      }');
          } else if (isEnumReturn) {
            s.writeln('      final res = await NitroRuntime.callAsync<int>(_${func.dartName}Ptr, [$callArgs], $errArgs);');
            s.writeln('      return res.to$rt();');
          } else {
            s.writeln('      final res = await NitroRuntime.callAsync<$callAsyncType>(_${func.dartName}Ptr, [$callArgs], $errArgs);');
            if (rt == 'bool') {
              s.writeln('      return res != 0;');
            } else {
              s.writeln('      return res;');
            }
          }
          s.writeln('    } finally {');
          s.writeln('      arena.releaseAll();');
          s.writeln('    }');
        } else {
          if (isRecordReturn) {
            s.writeln('    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(_${func.dartName}Ptr, [$plainCallArgs], $errArgs);');
            final decodeExpr = _decodeRecordExpr(func.returnType, 'rawPtr');
            s.writeln('    try {');
            s.writeln('      return $decodeExpr;');
            s.writeln('    } finally {');
            s.writeln('      malloc.free(rawPtr);');
            s.writeln('    }');
          } else if (isStructReturn) {
            s.writeln('    final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(_${func.dartName}Ptr, [$plainCallArgs], $errArgs);');
            s.writeln('    final structPtr = Pointer<${rt}Ffi>.fromAddress(rawPtr.address);');
            s.writeln('    try {');
            s.writeln('      return structPtr.ref.toDart();');
            s.writeln('    } finally {');
            s.writeln('      malloc.free(structPtr);');
            s.writeln('    }');
          } else if (isEnumReturn) {
            s.writeln('    final res = await NitroRuntime.callAsync<int>(_${func.dartName}Ptr, [$plainCallArgs], $errArgs);');
            s.writeln('    return res.to$rt();');
          } else {
            s.writeln('    final res = await NitroRuntime.callAsync<$callAsyncType>(_${func.dartName}Ptr, [$plainCallArgs], $errArgs);');
            if (rt == 'bool') {
              s.writeln('    return res != 0;');
            } else if (rt == 'String') {
              s.writeln('    return res.toDartStringWithFree();');
            } else {
              s.writeln('    return res;');
            }
          }
        }
      } else {
        if (needsArena) {
          s.writeln('    return withArena((arena) {');
          if (rt == 'void') {
            s.writeln('      _${func.dartName}Ptr($callArgs);');
          } else {
            s.writeln('      final res = _${func.dartName}Ptr($callArgs);');
          }
          if (!isFast) {
            s.writeln("      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);");
          }
          if (rt == 'void') {
            s.writeln('      return;');
          } else if (isRecordReturn) {
            final decodeExpr = _decodeRecordExpr(func.returnType, 'res as Pointer<Uint8>');
            s.writeln('      final $rt decoded;');
            s.writeln('      try {');
            s.writeln('        decoded = $decodeExpr;');
            s.writeln('      } finally {');
            s.writeln('        malloc.free(res);');
            s.writeln('      }');
            s.writeln('      return decoded;');
          } else if (spec.structs.any((st) => st.name == rt)) {
            s.writeln('      final structPtr = Pointer<${rt}Ffi>.fromAddress(res.address);');
            s.writeln('      final $rt decoded;');
            s.writeln('      try {');
            s.writeln('        decoded = structPtr.ref.toDart();');
            s.writeln('      } finally {');
            s.writeln('        malloc.free(structPtr);');
            s.writeln('      }');
            s.writeln('      return decoded;');
          } else if (rt == 'bool') {
            s.writeln('      return res != 0;');
          } else if (rt == 'String') {
            s.writeln('      return res.toDartStringWithFree();');
          } else if (spec.enums.any((en) => en.name == rt)) {
            s.writeln('      return res.to$rt();');
          } else {
            s.writeln('      return res;');
          }
          s.writeln('    });');
        } else {
          if (rt == 'void') {
            s.writeln('    _${func.dartName}Ptr($callArgs);');
            if (!isFast) {
              s.writeln("    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);");
            }
          } else {
            s.writeln('    final res = _${func.dartName}Ptr($callArgs);');
            if (!isFast) {
              s.writeln("    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);");
            }
            if (isRecordReturn) {
              final decodeExpr = _decodeRecordExpr(func.returnType, 'res as Pointer<Uint8>');
              s.writeln('    final $rt decoded;');
              s.writeln('    try {');
              s.writeln('      decoded = $decodeExpr;');
              s.writeln('    } finally {');
              s.writeln('      malloc.free(res);');
              s.writeln('    }');
              s.writeln('    return decoded;');
            } else if (spec.enums.any((en) => en.name == rt)) {
              s.writeln('    return res.to$rt();');
            } else if (spec.structs.any((st) => st.name == rt)) {
              s.writeln('    final structPtr = Pointer<${rt}Ffi>.fromAddress(res.address);');
              s.writeln('    final $rt decoded;');
              s.writeln('    try {');
              s.writeln('      decoded = structPtr.ref.toDart();');
              s.writeln('    } finally {');
              s.writeln('      malloc.free(structPtr);');
              s.writeln('    }');
              s.writeln('    return decoded;');
            } else if (rt == 'bool') {
              s.writeln('    return res != 0;');
            } else if (rt == 'String') {
              s.writeln('    return res.toDartStringWithFree();');
            } else {
              s.writeln('    return res;');
            }
          }
        }
      }
      s.writeln('  }');
      s.writeln();
    }

    // ── Property implementations ─────────────────────────────────────────────
    for (final prop in spec.properties) {
      final cap = _cap(prop.dartName);
      final rt = prop.type.name;
      final isRecordProp = prop.type.isRecord;

      if (prop.hasGetter) {
        s.writeln('  @override');
        if (isRecordProp) {
          final decodeExpr = _decodeRecordExpr(prop.type, "res");
          s.writeln('  $rt get ${prop.dartName} {');
          s.writeln('    checkDisposed();');
          s.writeln('    final res = _get${cap}Ptr();');
          s.writeln('    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);');
          s.writeln('    try {');
          s.writeln('      return $decodeExpr;');
          s.writeln('    } finally {');
          s.writeln('      malloc.free(res);');
          s.writeln('    }');
          s.writeln('  }');
        } else {
          s.writeln('  $rt get ${prop.dartName} {');
          s.writeln('    checkDisposed();');
          s.writeln('    final res = _get${cap}Ptr();');
          s.writeln("    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);");
          if (spec.enums.any((en) => en.name == rt)) {
            s.writeln('    return res.to$rt();');
          } else if (rt == 'bool') {
            s.writeln('    return res != 0;');
          } else {
            s.writeln('    return res;');
          }
          s.writeln('  }');
        }
      }

      if (prop.hasSetter) {
        s.writeln('  @override');
        if (isRecordProp) {
          final encodeExpr = _encodeRecordParam(prop.type, 'value', 'arena');
          s.writeln('  set ${prop.dartName}($rt value) {');
          s.writeln('    checkDisposed();');
          s.writeln('    withArena((arena) { _set${cap}Ptr($encodeExpr); NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr); });');
          s.writeln('  }');
        } else {
          final propNeedsArena = rt == 'String' || prop.type.isTypedData || spec.structs.any((st) => st.name == rt);
          if (propNeedsArena) {
            String valExpr;
            if (rt == 'String') {
              valExpr = 'value.toNativeUtf8(allocator: arena)';
            } else if (prop.type.isTypedData) {
              valExpr = 'value.toPointer(arena)';
            } else {
              valExpr = 'value.toNative(arena).cast<Void>()';
            }
            s.writeln("  set ${prop.dartName}($rt value) { checkDisposed(); withArena((arena) { _set${cap}Ptr($valExpr); NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr); }); }");
          } else {
            String valExpr = 'value';
            if (spec.enums.any((en) => en.name == rt)) {
              valExpr = 'value.nativeValue';
            } else if (rt == 'bool') {
              valExpr = 'value ? 1 : 0';
            }
            s.writeln("  set ${prop.dartName}($rt value) { checkDisposed(); _set${cap}Ptr($valExpr); NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr); }");
          }
        }
      }
      s.writeln();
    }

    // ── Stream implementations ───────────────────────────────────────────────
    for (final stream in spec.streams) {
      final cap = _cap(stream.dartName);
      final itemType = stream.itemType.name;
      final isRecord = stream.itemType.isRecord;
      final isStruct = spec.structs.any((st) => st.name == itemType);

      final String unpackExpr;
      final String streamItemType;

      if (isRecord) {
        final decodeExpr = _decodeRecordExpr(stream.itemType, 'rawPtr');
        unpackExpr = '(rawPtr) { try { return $decodeExpr; } finally { malloc.free(rawPtr); } }';
        streamItemType = itemType;
      } else if (isStruct) {
        // Zero-copy path: wrap the malloc'd pointer in a NativeProxy instead of
        // copying every field to the Dart heap.  The proxy owns the pointer and
        // releases it via NativeFinalizer when it is GC'd — no explicit free needed.
        unpackExpr = '(rawPtr) => ${itemType}Proxy(Pointer<${itemType}Ffi>.fromAddress(rawPtr))';
        streamItemType = '${itemType}Proxy';
      } else {
        unpackExpr = '(rawPtr) => rawPtr as $itemType';
        streamItemType = itemType;
      }

      s.writeln('  @override');
      s.writeln('  Stream<$streamItemType> get ${stream.dartName} {');
      s.writeln('    checkDisposed();');
      s.writeln('    return NitroRuntime.openStream<$streamItemType>(');
      s.writeln('      register: (port) => _register${cap}Ptr(port),');
      s.writeln('      unpack: $unpackExpr,');
      s.writeln('      release: (port) => _release${cap}Ptr(port),');
      s.writeln(
        '      backpressure: Backpressure.${stream.backpressure.name},',
      );
      s.writeln('    );');
      s.writeln('  }');
      s.writeln();
    }

    s.writeln('}');
    return s.toString();
  }

  static String _paramList(List<BridgeParam> params) => params.map((p) => '${p.type.name} ${p.name}').join(', ');
  static String _cap(String name) => name[0].toUpperCase() + name.substring(1);

  static String _toNativeType(BridgeFunction func, BridgeSpec spec) {
    final ret = _typeToFFI(func.returnType, spec);
    final params = func.params
        .expand((p) {
          if (p.type.isTypedData) return [_typeToFFI(p.type, spec), 'Int64'];
          return [_typeToFFI(p.type, spec)];
        })
        .join(', ');
    return '$ret Function($params)';
  }

  static String _toDartType(BridgeFunction func, BridgeSpec spec) {
    final ret = _typeToDartFFI(func.returnType, spec);
    final params = func.params
        .expand((p) {
          if (p.type.isTypedData) return [_typeToDartFFI(p.type, spec), 'int'];
          return [_typeToDartFFI(p.type, spec)];
        })
        .join(', ');
    return '$ret Function($params)';
  }

  static String _typeToFFI(BridgeType bt, BridgeSpec spec) {
    if (bt.isRecord) {
      return bt.isMap ? 'Pointer<Utf8>' : 'Pointer<Uint8>';
    }
    if (bt.isPointer) {
      return 'Pointer<${bt.pointerInnerType}>';
    }
    final name = bt.name.replaceFirst('?', '');
    switch (name) {
      case 'int':
        return 'Int64';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Int8';
      case 'String':
        return 'Pointer<Utf8>';
      case 'Uint8List':
        return 'Pointer<Uint8>';
      case 'Int8List':
        return 'Pointer<Int8>';
      case 'Int16List':
        return 'Pointer<Int16>';
      case 'Int32List':
        return 'Pointer<Int32>';
      case 'Uint16List':
        return 'Pointer<Uint16>';
      case 'Uint32List':
        return 'Pointer<Uint32>';
      case 'Float32List':
        return 'Pointer<Float>';
      case 'Float64List':
        return 'Pointer<Double>';
      case 'Int64List':
        return 'Pointer<Int64>';
      case 'Uint64List':
        return 'Pointer<Uint64>';
      case 'void':
        return 'Void';
    }
    if (spec.enums.any((en) => en.name == name)) return 'Int64';
    return 'Pointer<Void>';
  }

  static String _typeToDartFFI(BridgeType bt, BridgeSpec spec) {
    if (bt.isRecord) {
      return bt.isMap ? 'Pointer<Utf8>' : 'Pointer<Uint8>';
    }
    if (bt.isPointer) {
      return 'Pointer<${bt.pointerInnerType}>';
    }
    final name = bt.name.replaceFirst('?', '');
    switch (name) {
      case 'int':
        return 'int';
      case 'double':
        return 'double';
      case 'bool':
        return 'int';
      case 'String':
        return 'Pointer<Utf8>';
      case 'Uint8List':
        return 'Pointer<Uint8>';
      case 'Int8List':
        return 'Pointer<Int8>';
      case 'Int16List':
        return 'Pointer<Int16>';
      case 'Int32List':
        return 'Pointer<Int32>';
      case 'Uint16List':
        return 'Pointer<Uint16>';
      case 'Uint32List':
        return 'Pointer<Uint32>';
      case 'Float32List':
        return 'Pointer<Float>';
      case 'Float64List':
        return 'Pointer<Double>';
      case 'Int64List':
        return 'Pointer<Int64>';
      case 'Uint64List':
        return 'Pointer<Uint64>';
      case 'void':
        return 'void';
    }
    if (spec.enums.any((en) => en.name == name)) return 'int';
    return 'Pointer<Void>';
  }

  static String _decodeRecordExpr(BridgeType type, String ptrVar) {
    if (type.isMap) {
      return 'jsonDecode(($ptrVar as Pointer<Utf8>).toDartStringWithFree()) as Map<String, dynamic>';
    }
    final item = type.recordListItemType;
    if (item != null) {
      if (type.recordListItemIsPrimitive) {
        // Primitive lists are small scalars — eager decode is fast enough.
        final readCall = _primitiveReaderCall(item);
        return 'RecordReader.decodePrimitiveList($ptrVar, (r) => r.$readCall())';
      }
      // Object lists: decode lazily — items are only deserialized when accessed.
      // Requires the native buffer to have been written by encodeIndexedList.
      return 'LazyRecordList.decode($ptrVar, (r) => ${item}RecordExt.fromReader(r))';
    }
    final rt = type.name;
    return '${rt}RecordExt.fromNative($ptrVar)';
  }

  static String _primitiveReaderCall(String item) {
    switch (item) {
      case 'int':
        return 'readInt';
      case 'double':
        return 'readDouble';
      case 'bool':
        return 'readBool';
      default:
        return 'readString';
    }
  }

  static String _primitiveWriterCall(String item) {
    switch (item) {
      case 'int':
        return 'writeInt';
      case 'double':
        return 'writeDouble';
      case 'bool':
        return 'writeBool';
      default:
        return 'writeString';
    }
  }

  static String _encodeRecordParam(BridgeType type, String varName, String allocator) {
    if (type.isMap) {
      return 'jsonEncode($varName).toNativeUtf8(allocator: $allocator)';
    }
    final item = type.recordListItemType;
    if (item != null) {
      if (type.recordListItemIsPrimitive) {
        final writeCall = _primitiveWriterCall(item);
        return 'RecordWriter.encodeIndexedPrimitiveList($varName, (w, e) => w.$writeCall(e), $allocator)';
      }
      // Use indexed encoding so the receiving side can use LazyRecordList.
      return 'RecordWriter.encodeIndexedList($varName, (w, e) => e.writeFields(w), $allocator)';
    }
    return '$varName.toNative($allocator)';
  }

  // ── Leaf / isLeaf helpers ─────────────────────────────────────────────────

  /// Returns true when [bt] maps to a plain FFI scalar (int, double, bool, or
  /// a known enum) — types that require no arena allocation and no Dart heap
  /// object creation on the call boundary.
  static bool _isPrimitiveType(BridgeType bt, BridgeSpec spec) {
    if (bt.isRecord || bt.isTypedData || bt.isPointer) return false;
    final name = bt.name.replaceFirst('?', '');
    if (name == 'String' || name == 'void') return false;
    if (spec.structs.any((st) => st.name == name)) return false;
    // int, double, bool, and known enums are all FFI scalars.
    return true;
  }

  /// Returns true when the function pointer should be bound with `isLeaf: true`.
  ///
  /// `isLeaf: true` skips the Dart VM safepoint transition, shaving ~50–200 ns
  /// per call.  It is safe when the C++ body never calls back into Dart and the
  /// call is expected to be short-lived (no blocking I/O).
  ///
  /// Conditions:
  ///  • Not async (async calls dispatch to isolates, irrelevant here).
  ///  • Explicitly named "Fast" — a developer contract that the method is hot.
  ///  • OR all params and the return type are plain scalars (no arena needed).
  static bool _isLeafCandidate(BridgeFunction func, BridgeSpec spec) {
    if (func.isAsync) return false;
    if (func.dartName.endsWith('Fast')) return true;
    final rt = func.returnType;
    if (!_isPrimitiveType(rt, spec) && rt.name != 'void') return false;
    return func.params.every((p) => _isPrimitiveType(p.type, spec));
  }
}
