import '../bridge_spec.dart';

/// EnumGenerator: only emits FFI conversion extensions in Dart (not re-declaring enums).
class EnumGenerator {
  /// Only emit extension helpers — the enum is already declared in .native.dart.
  /// Skips imported enums (their extensions are generated in the other file's .g.dart).
  static String generateDartExtensions(BridgeSpec spec) {
    final enums = spec.localEnums;
    if (enums.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Enum FFI helpers (generated by Nitrogen) ---');
    s.writeln();
    for (final e in enums) {
      s.writeln('extension ${e.name}NativeExt on ${e.name} {');
      s.writeln('  int get nativeValue => index + ${e.startValue};');
      s.writeln('}');
      s.writeln();
      s.writeln('extension ${e.name}FromNativeExt on int {');
      s.writeln(
        '  ${e.name} to${e.name}() => ${e.name}.values[this - ${e.startValue}];',
      );
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates C typedef enums. Skips imported enums (declared in other bridge header).
  static String generateCEnums(BridgeSpec spec) {
    final enums = spec.localEnums;
    if (enums.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Enums ---');
    for (final e in enums) {
      s.writeln('typedef enum {');
      var val = e.startValue;
      for (final v in e.values) {
        s.writeln(
          '  ${e.name.toUpperCase()}_${_toScreamingSnake(v)} = ${val++},',
        );
      }
      s.writeln('} ${e.name};');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Kotlin enum classes. Skips imported enums (declared in other bridge file).
  static String generateKotlin(BridgeSpec spec) {
    final enums = spec.localEnums;
    if (enums.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Enums ---');
    for (final e in enums) {
      s.writeln('@Keep');
      s.writeln('enum class ${e.name}(val nativeValue: Long) {');
      var val = e.startValue;
      for (var i = 0; i < e.values.length; i++) {
        final comma = i < e.values.length - 1 ? ',' : ';';
        s.writeln('  ${e.values[i].toUpperCase()}(${val++})$comma');
      }
      s.writeln();
      s.writeln('  companion object {');
      s.writeln(
        '    fun fromNative(v: Long): ${e.name} = values().first { it.nativeValue == v }',
      );
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Swift public enums. Skips imported enums (declared in other bridge file).
  static String generateSwift(BridgeSpec spec) {
    final enums = spec.localEnums;
    if (enums.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Enums ---');
    for (final e in enums) {
      s.writeln('public enum ${e.name}: Int64 {');
      var val = e.startValue;
      for (final v in e.values) {
        s.writeln('  case $v = ${val++}');
      }
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  static String _toScreamingSnake(String camel) {
    return camel
        .replaceAllMapped(
          RegExp(r'([a-z0-9])([A-Z])'),
          (m) => '${m[1]}_${m[2]}',
        )
        .toUpperCase();
  }
}
