import '../bridge_spec.dart';
import 'code_writer.dart';

/// EnumGenerator: only emits FFI conversion extensions in Dart (not re-declaring enums).
class EnumGenerator {
  /// Only emit extension helpers — the enum is already declared in .native.dart.
  /// Skips imported enums (their extensions are generated in the other file's .g.dart).
  static String generateDartExtensions(BridgeSpec spec) {
    final enums = spec.localEnums;
    if (enums.isEmpty) return '';
    final s = CodeWriter();
    s.writeln('// --- Enum FFI helpers (generated by Nitrogen) ---');
    s.writeln();
    for (final e in enums) {
      s.writeln('extension ${e.name}NativeExt on ${e.name} {');
      if (e.rawValues != null) {
        // Non-contiguous: switch on each case to its explicit native value.
        s.writeln('  int get nativeValue {');
        s.writeln('    switch (this) {');
        for (var i = 0; i < e.values.length; i++) {
          s.writeln('      case ${e.name}.${e.values[i]}: return ${e.rawValues![i]};');
        }
        s.writeln('    }');
        s.writeln('  }');
      } else {
        s.writeln('  int get nativeValue => index + ${e.startValue};');
      }
      s.writeln('}');
      s.writeln();
      s.writeln('extension ${e.name}FromNativeExt on int {');
      if (e.rawValues != null) {
        // Non-contiguous: switch on each native value back to enum case.
        s.writeln('  ${e.name} to${e.name}() {');
        s.writeln('    switch (this) {');
        for (var i = 0; i < e.values.length; i++) {
          s.writeln('      case ${e.rawValues![i]}: return ${e.name}.${e.values[i]};');
        }
        s.writeln("      default: throw ArgumentError('Unknown ${e.name} native value: \$this');");
        s.writeln('    }');
        s.writeln('  }');
      } else {
        s.writeln(
          '  ${e.name} to${e.name}() => ${e.name}.values[this - ${e.startValue}];',
        );
      }
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates C typedef enums. Skips imported enums (declared in other bridge header).
  static String generateCEnums(BridgeSpec spec) {
    final enums = spec.localEnums;
    if (enums.isEmpty) return '';
    final s = CodeWriter();
    s.writeln('// --- Enums ---');
    for (final e in enums) {
      s.writeln('typedef enum {');
      for (var i = 0; i < e.values.length; i++) {
        s.writeln(
          '  ${e.name.toUpperCase()}_${_toScreamingSnake(e.values[i])} = ${e.nativeValueAt(i)},',
        );
      }
      s.writeln('} ${e.name};');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Kotlin enum classes. Skips imported enums (declared in other bridge file).
  static String generateKotlin(BridgeSpec spec) {
    final enums = spec.localEnums;
    if (enums.isEmpty) return '';
    final s = CodeWriter();
    s.writeln('// --- Enums ---');
    for (final e in enums) {
      s.writeln('@Keep');
      s.writeln('enum class ${e.name}(val nativeValue: Long) {');
      for (var i = 0; i < e.values.length; i++) {
        final comma = i < e.values.length - 1 ? ',' : ';';
        s.writeln('  ${e.values[i].toUpperCase()}(${e.nativeValueAt(i)})$comma');
      }
      s.writeln();
      s.writeln('  companion object {');
      s.writeln(
        '    fun fromNative(v: Long): ${e.name} = values().first { it.nativeValue == v }',
      );
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Swift public enums. Skips imported enums (declared in other bridge file).
  static String generateSwift(BridgeSpec spec) {
    final enums = spec.localEnums;
    if (enums.isEmpty) return '';
    final s = CodeWriter();
    s.writeln('// --- Enums ---');
    for (final e in enums) {
      s.writeln('public enum ${e.name}: Int64 {');
      for (var i = 0; i < e.values.length; i++) {
        s.writeln('  case ${e.values[i]} = ${e.nativeValueAt(i)}');
      }
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  static String _toScreamingSnake(String camel) {
    return camel
        .replaceAllMapped(
          RegExp(r'([a-z0-9])([A-Z])'),
          (m) => '${m[1]}_${m[2]}',
        )
        .toUpperCase();
  }
}
