import '../bridge_spec.dart';

/// Generates binary encode/decode extension methods for every @HybridRecord
/// type declared in the spec.  The output is written into the `.g.dart` part
/// file and shares the library namespace with the `.native.dart` source.
///
/// Performance design — each type gets an extension named `${TypeName}RecordExt`
/// with four members:
///
///   • `static T fromNative(Pointer<Uint8> ptr)`
///       Top-level decoder: reads the 4-byte length prefix then the fields.
///       Used for a bare return value / property getter.
///
///   • `static T fromReader(RecordReader r)`
///       Inner decoder: reads fields from an already-opened reader.
///       Used when this record is an element inside a list.
///
///   • `void writeFields(RecordWriter w)`
///       Writes fields into an in-progress writer.
///       Used when this record is inside a list param.
///
///   • `Pointer<Uint8> toNative(Allocator alloc)`
///       Top-level encoder: opens a writer, calls writeFields, seals + copies.
///       Used for a bare param / property setter.
///
/// Wire format is identical to [RecordWriter] / [RecordReader]:
///   int    → 8-byte little-endian int64
///   double → 8-byte little-endian float64
///   bool   → 1 byte
///   String → 4-byte length + UTF-8 bytes
///   null   → 1-byte tag (0=null, 1=present) then value if present
///   list   → 4-byte count then elements
///
/// `Map<String, T>` types are NOT handled here — they continue to use JSON.
class RecordGenerator {
  static String generateDartExtensions(BridgeSpec spec) {
    if (spec.recordTypes.isEmpty) return '';

    final s = StringBuffer();
    s.writeln(
      '// --- @HybridRecord binary extensions (generated by Nitrogen) ---',
    );
    s.writeln();

    for (final rt in spec.recordTypes) {
      s.writeln('extension ${rt.name}RecordExt on ${rt.name} {');

      // ── static fromNative (top-level, with 4-byte length prefix) ──────
      s.writeln(
        '  static ${rt.name} fromNative(Pointer<Uint8> ptr) =>',
      );
      s.writeln('      fromReader(RecordReader.fromNative(ptr));');
      s.writeln();

      // ── static fromReader (inner, for use inside lists) ───────────────
      s.writeln(
        '  static ${rt.name} fromReader(RecordReader r) =>',
      );
      s.writeln('      ${rt.name}(');
      for (final f in rt.fields) {
        s.writeln('        ${f.name}: ${_readExpr(f)},');
      }
      s.writeln('      );');
      s.writeln();

      // ── writeFields (inner, for use inside lists) ─────────────────────
      s.writeln('  void writeFields(RecordWriter w) {');
      for (final f in rt.fields) {
        _writeFieldStmt(s, f);
      }
      s.writeln('  }');
      s.writeln();

      // ── toNative (top-level, allocates native buffer) ─────────────────
      s.writeln('  Pointer<Uint8> toNative(Allocator alloc) {');
      s.writeln('    final w = RecordWriter();');
      s.writeln('    writeFields(w);');
      s.writeln('    return w.toNative(alloc);');
      s.writeln('  }');

      s.writeln('}');
      s.writeln();
    }

    return s.toString();
  }

  // ── Read expression helpers ─────────────────────────────────────────────

  static String _readExpr(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _primitiveReadExpr(f.dartType);

      case RecordFieldKind.recordObject:
        final baseType = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          return 'r.readNullTag() ? null : ${baseType}RecordExt.fromReader(r)';
        }
        return '${baseType}RecordExt.fromReader(r)';

      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'dynamic';
        return 'List.generate(r.readInt32(), (_) => ${_primitiveReadCall(item)})';

      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        return 'List.generate(r.readInt32(), (_) => ${item}RecordExt.fromReader(r))';
    }
  }

  static String _primitiveReadExpr(String dartType) {
    final base = dartType.replaceFirst('?', '');
    final nullable = dartType.endsWith('?');
    if (nullable) {
      return 'r.readNullTag() ? null : ${_primitiveReadCall(base)}';
    }
    return _primitiveReadCall(base);
  }

  static String _primitiveReadCall(String base) {
    switch (base) {
      case 'int':
        return 'r.readInt()';
      case 'double':
        return 'r.readDouble()';
      case 'bool':
        return 'r.readBool()';
      case 'String':
        return 'r.readString()';
      default:
        return 'r.readInt()';
    }
  }

  // ── Write statement helpers ─────────────────────────────────────────────

  static void _writeFieldStmt(StringBuffer s, BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        _writePrimitiveStmt(s, f.dartType, f.name);
        break;

      case RecordFieldKind.recordObject:
        if (f.isNullable) {
          s.writeln('    w.writeNullTag(${f.name} == null);');
          s.writeln('    if (${f.name} != null) ${f.name}!.writeFields(w);');
        } else {
          s.writeln('    ${f.name}.writeFields(w);');
        }
        break;

      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'dynamic';
        final writeCall = _primitiveWriteCall(item, 'e');
        s.writeln('    w.writeInt32(${f.name}.length);');
        s.writeln('    for (final e in ${f.name}) { w.$writeCall; }');
        break;

      case RecordFieldKind.listRecordObject:
        s.writeln('    w.writeInt32(${f.name}.length);');
        s.writeln('    for (final e in ${f.name}) { e.writeFields(w); }');
        break;
    }
  }

  static void _writePrimitiveStmt(
    StringBuffer s,
    String dartType,
    String fieldName,
  ) {
    final base = dartType.replaceFirst('?', '');
    final nullable = dartType.endsWith('?');
    if (nullable) {
      s.writeln('    w.writeNullTag($fieldName == null);');
      s.writeln(
        '    if ($fieldName != null) w.${_primitiveWriteCall(base, '$fieldName!')};',
      );
    } else {
      s.writeln('    w.${_primitiveWriteCall(base, fieldName)};');
    }
  }

  static String _primitiveWriteCall(String base, String expr) {
    switch (base) {
      case 'int':
        return 'writeInt($expr)';
      case 'double':
        return 'writeDouble($expr)';
      case 'bool':
        return 'writeBool($expr)';
      case 'String':
        return 'writeString($expr)';
      default:
        return 'writeInt($expr)';
    }
  }

  // ── Kotlin generator ────────────────────────────────────────────────────────

  /// Generates `@Keep data class` declarations for every `@HybridRecord` type
  /// into the Kotlin bridge file.  Each class also gets static `decode` /
  /// `encode` helpers so callers never have to hand-roll ByteArray parsing.
  static String generateKotlin(BridgeSpec spec) {
    if (spec.recordTypes.isEmpty) return '';

    final s = StringBuffer();
    s.writeln('// --- @HybridRecord Kotlin data classes (generated by Nitrogen) ---');
    s.writeln();

    for (final rt in spec.recordTypes) {
      final fields = rt.fields.map((f) => 'val ${f.name}: ${_kotlinType(f)}').join(', ');
      s.writeln('@androidx.annotation.Keep');
      s.writeln('data class ${rt.name}($fields) {');

      // --- companion: decodeFrom(buf) reads fields from a shared ByteBuffer cursor ---
      //                decode(bytes) wraps a standalone ByteArray (strips 4-byte prefix)
      s.writeln('    companion object {');
      s.writeln('        @JvmStatic fun decodeFrom(buf: java.nio.ByteBuffer): ${rt.name} {');
      for (final f in rt.fields) {
        s.writeln('            val ${f.name} = ${_kotlinReadExpr(f)}');
      }
      final ctorArgs = rt.fields.map((f) => f.name).join(', ');
      s.writeln('            return ${rt.name}($ctorArgs)');
      s.writeln('        }');
      s.writeln('        @JvmStatic fun decode(bytes: ByteArray): ${rt.name} {');
      s.writeln('            val buf = java.nio.ByteBuffer.wrap(bytes).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
      s.writeln('            buf.position(4) // skip 4-byte length prefix');
      s.writeln('            return decodeFrom(buf)');
      s.writeln('        }');
      s.writeln('    }');
      s.writeln();

      // --- writeFieldsTo: writes fields without length prefix (for use inside lists) ---
      s.writeln('    fun writeFieldsTo(out: java.io.ByteArrayOutputStream, buf: java.nio.ByteBuffer) {');
      s.writeln('        fun writeInt(v: Long) { buf.clear(); buf.putLong(v); out.write(buf.array()) }');
      s.writeln('        fun writeInt32(v: Int) { buf.clear(); buf.putInt(v); out.write(buf.array(), 0, 4) }');
      s.writeln('        fun writeDouble(v: Double) { buf.clear(); buf.putDouble(v); out.write(buf.array()) }');
      s.writeln('        fun writeBool(v: Boolean) { out.write(if (v) 1 else 0) }');
      s.writeln('        fun writeString(v: String) { val b = v.toByteArray(Charsets.UTF_8); writeInt32(b.size); out.write(b) }');
      // Indexed list helper — emits count + int64[] offsets + item bytes.
      // Matches the Dart RecordWriter.encodeIndexedList wire format.
      // Uses a 64-byte initial capacity per item to avoid dynamic growth on small records.
      s.writeln('        fun <T> writeIndexedList(items: List<T>, writeItem: (java.io.ByteArrayOutputStream) -> Unit) {');
      s.writeln('            val blobs = items.map { _ -> val io = java.io.ByteArrayOutputStream(64); writeItem(io); io.toByteArray() }');
      s.writeln('            writeInt32(blobs.size)');
      s.writeln('            var off = (4L + 8L * blobs.size)');
      s.writeln('            val offBuf = java.nio.ByteBuffer.allocate(8).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
      s.writeln('            blobs.forEach { b -> offBuf.clear(); offBuf.putLong(off); out.write(offBuf.array()); off += b.size }');
      s.writeln('            blobs.forEach { b -> out.write(b) }');
      s.writeln('        }');
      for (final f in rt.fields) {
        _kotlinWriteStmt(s, f);
      }
      s.writeln('    }');
      s.writeln();

      // --- encode to ByteArray (with 4-byte length prefix) ---
      final capacity = recordBytesHint(rt);
      s.writeln('    fun encode(): ByteArray {');
      s.writeln('        val out = java.io.ByteArrayOutputStream($capacity)');
      s.writeln('        val buf = java.nio.ByteBuffer.allocate(8).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
      s.writeln('        writeFieldsTo(out, buf)');
      s.writeln('        val payload = out.toByteArray()');
      s.writeln('        val lenBuf = java.nio.ByteBuffer.allocate(4).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
      s.writeln('        lenBuf.putInt(payload.size)');
      s.writeln('        return lenBuf.array() + payload');
      s.writeln('    }');
      s.writeln('}');
      s.writeln();
    }

    return s.toString();
  }

  static String _kotlinType(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _kotlinBase(f.dartType) + (f.isNullable ? '?' : '');
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        return base + (f.isNullable ? '?' : '');
      case RecordFieldKind.listPrimitive:
        return 'List<${_kotlinBase(f.itemTypeName ?? 'int')}>';
      case RecordFieldKind.listRecordObject:
        return 'List<${f.itemTypeName}>';
    }
  }

  static String _kotlinBase(String dartType) {
    final base = dartType.replaceFirst('?', '');
    switch (base) {
      case 'int':
        return 'Long';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Boolean';
      case 'String':
        return 'String';
      default:
        return 'Long';
    }
  }

  static String _kotlinReadExpr(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          return '(if (buf.get().toInt() == 0) null else ${_kotlinPrimRead(base)})';
        }
        return _kotlinPrimRead(base);
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          return '(if (buf.get().toInt() == 0) null else $base.decodeFrom(buf))';
        }
        return '$base.decodeFrom(buf)';
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        // Indexed format: count + int64[] offsets + item bytes.
        // Skip offset table (count * 8 bytes) before reading items.
        return '{ val _cnt = buf.int; repeat(_cnt) { buf.long }; (0 until _cnt).map { ${_kotlinPrimRead(item)} } }()';
      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        return '{ val _cnt = buf.int; repeat(_cnt) { buf.long }; (0 until _cnt).map { $item.decodeFrom(buf) } }()';
    }
  }

  static String _kotlinPrimRead(String base) {
    switch (base) {
      case 'int':
        return 'buf.long';
      case 'double':
        return 'buf.double';
      case 'bool':
        return '(buf.get().toInt() != 0)';
      case 'String':
        return '{ val len = buf.int; val b = ByteArray(len); buf.get(b); b.toString(Charsets.UTF_8) }()';
      default:
        return 'buf.long';
    }
  }

  static void _kotlinWriteStmt(StringBuffer s, BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
          s.writeln('        ${f.name}?.let { ${_kotlinWriteCall(base, 'it')} }');
        } else {
          s.writeln('        ${_kotlinWriteCall(base, f.name)}');
        }
        break;
      case RecordFieldKind.recordObject:
        if (f.isNullable) {
          s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
          s.writeln('        ${f.name}?.writeFieldsTo(out, buf)');
        } else {
          s.writeln('        ${f.name}.writeFieldsTo(out, buf)');
        }
        break;
      case RecordFieldKind.listPrimitive:
        final base = f.itemTypeName ?? 'int';
        // Use indexed format: count + int64[] offsets + item bytes.
        s.writeln('        writeIndexedList(${f.name}) { io ->');
        s.writeln('            val lb = java.nio.ByteBuffer.allocate(8).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
        s.writeln('            fun wInt(v: Long) { lb.clear(); lb.putLong(v); io.write(lb.array()) }');
        s.writeln('            fun wInt32(v: Int) { lb.clear(); lb.putInt(v); io.write(lb.array(), 0, 4) }');
        s.writeln('            fun wDouble(v: Double) { lb.clear(); lb.putDouble(v); io.write(lb.array()) }');
        s.writeln('            fun wBool(v: Boolean) { io.write(if (v) 1 else 0) }');
        s.writeln('            fun wString(v: String) { val b = v.toByteArray(Charsets.UTF_8); wInt32(b.size); io.write(b) }');
        s.writeln('            it.let { e -> ${_kotlinWriteCallInner(base, 'e')} }');
        s.writeln('        }');
        break;
      case RecordFieldKind.listRecordObject:
        s.writeln('        writeIndexedList(${f.name}) { io -> it.writeFieldsTo(io, buf) }');
        break;
    }
  }

  static String _kotlinWriteCall(String base, String expr) {
    switch (base) {
      case 'int':
        return 'writeInt($expr.toLong())';
      case 'double':
        return 'writeDouble($expr)';
      case 'bool':
        return 'writeBool($expr)';
      case 'String':
        return 'writeString($expr)';
      default:
        return 'writeInt($expr.toLong())';
    }
  }

  /// Like [_kotlinWriteCall] but uses the `w*` local functions inside the
  /// `writeIndexedList` lambda (avoids shadowing the outer `write*` helpers).
  static String _kotlinWriteCallInner(String base, String expr) {
    switch (base) {
      case 'int':
        return 'wInt($expr.toLong())';
      case 'double':
        return 'wDouble($expr)';
      case 'bool':
        return 'wBool($expr)';
      case 'String':
        return 'wString($expr)';
      default:
        return 'wInt($expr.toLong())';
    }
  }

  /// Returns a static byte-size estimate for one serialized instance of [rt].
  /// Used to pre-size [ByteArrayOutputStream] in [encode] and list paths,
  /// avoiding the default 32-byte initial buffer and subsequent grow copies.
  ///
  /// Estimates per field kind:
  ///   int/double   → 8 bytes (+ 1 nullable tag)
  ///   bool         → 1 byte  (+ 1 nullable tag)
  ///   String       → 4 (len) + 32 (avg content) = 36 (+ 1 nullable tag)
  ///   nested record → 32 rough estimate (+ 1 nullable tag)
  ///   list         → 4 (count) + 8 * 4 avg items = 36
  static int recordBytesHint(BridgeRecordType rt) {
    var total = 0;
    for (final f in rt.fields) {
      final nullableTag = f.isNullable ? 1 : 0;
      switch (f.kind) {
        case RecordFieldKind.primitive:
          final base = f.dartType.replaceFirst('?', '');
          switch (base) {
            case 'bool':
              total += nullableTag + 1;
            case 'String':
              total += nullableTag + 36;
            default: // int, double
              total += nullableTag + 8;
          }
        case RecordFieldKind.recordObject:
          total += nullableTag + 32;
        case RecordFieldKind.listPrimitive:
        case RecordFieldKind.listRecordObject:
          total += 36; // 4-byte count + ~4 items * 8 bytes avg
      }
    }
    return total > 0 ? total : 32;
  }

  // ── Native generators ───────────────────────────────────────────────────

  static String generateSwift(BridgeSpec spec) {
    if (spec.recordTypes.isEmpty) return '';

    final s = StringBuffer();
    s.writeln('// --- @HybridRecord binary extensions (generated by Nitrogen) ---');
    s.writeln();

    for (final rt in spec.recordTypes) {
      s.writeln('public struct ${rt.name} {');
      for (final f in rt.fields) {
        final opt = f.isNullable ? '?' : '';
        s.writeln('  public var ${f.name}: ${_swiftType(f)}$opt');
      }
      s.writeln();

      final params = rt.fields.map((f) => '${f.name}: ${_swiftType(f)}${f.isNullable ? '?' : ''}').join(', ');
      s.writeln('  public init($params) {');
      for (final f in rt.fields) {
        s.writeln('    self.${f.name} = ${f.name}');
      }
      s.writeln('  }');
      s.writeln();

      s.writeln('  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> ${rt.name} {');
      s.writeln('    return fromReader(NitroRecordReader(ptr: ptr))');
      s.writeln('  }');
      s.writeln();

      s.writeln('  public static func fromReader(_ r: NitroRecordReader) -> ${rt.name} {');
      s.writeln('    return ${rt.name}(');
      for (final f in rt.fields) {
        s.writeln('      ${f.name}: ${_swiftRead(f)},');
      }
      s.writeln('    )');
      s.writeln('  }');
      s.writeln();

      s.writeln('  public func writeFields(_ w: NitroRecordWriter) {');
      for (final f in rt.fields) {
        _swiftWriteStmt(s, f);
      }
      s.writeln('  }');
      s.writeln();

      s.writeln('  public func toNative() -> UnsafeMutablePointer<UInt8>? {');
      s.writeln('    let w = NitroRecordWriter()');
      s.writeln('    writeFields(w)');
      s.writeln('    return w.toNative()');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }

    s.writeln(_swiftRecordWriterReader);
    return s.toString();
  }

  static String _swiftType(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _swiftBase(f.dartType);
      case RecordFieldKind.recordObject:
        return f.dartType.replaceFirst('?', '');
      case RecordFieldKind.listPrimitive:
        return '[${_swiftBase(f.itemTypeName ?? 'Any')}]';
      case RecordFieldKind.listRecordObject:
        return '[${f.itemTypeName}]';
    }
  }

  static String _swiftBase(String dartType) {
    final base = dartType.replaceFirst('?', '');
    switch (base) {
      case 'int':
        return 'Int64';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Bool';
      case 'String':
        return 'String';
      default:
        return 'Int64';
    }
  }

  static String _swiftReadCall(String base) {
    switch (base) {
      case 'int':
        return 'r.readInt()';
      case 'double':
        return 'r.readDouble()';
      case 'bool':
        return 'r.readBool()';
      case 'String':
        return 'r.readString()';
      default:
        return 'r.readInt()';
    }
  }

  static String _swiftRead(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) return 'r.readNullTag() ? nil : ${_swiftReadCall(base)}';
        return _swiftReadCall(base);
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) return 'r.readNullTag() ? nil : $base.fromReader(r)';
        return '$base.fromReader(r)';
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        // Skip offset table before reading items (indexed format).
        return '{ let _cnt = r.readInt32(); for _ in 0..<_cnt { _ = r.readInt() }; return (0..<_cnt).map { _ in ${_swiftReadCall(item)} } }()';
      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        return '{ let _cnt = r.readInt32(); for _ in 0..<_cnt { _ = r.readInt() }; return (0..<_cnt).map { _ in $item.fromReader(r) } }()';
    }
  }

  static void _swiftWriteStmt(StringBuffer s, BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          s.writeln('    w.writeNullTag(${f.name} == nil)');
          s.writeln('    if let val = ${f.name} { w.${_swiftWriterCall(base, 'val')} }');
        } else {
          s.writeln('    w.${_swiftWriterCall(base, f.name)}');
        }
        break;
      case RecordFieldKind.recordObject:
        if (f.isNullable) {
          s.writeln('    w.writeNullTag(${f.name} == nil)');
          s.writeln('    if let val = ${f.name} { val.writeFields(w) }');
        } else {
          s.writeln('    ${f.name}.writeFields(w)');
        }
        break;
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        // Indexed format: count + int64[] offsets + item bytes.
        s.writeln('    w.writeIndexedList(${f.name}) { e, iw in iw.${_swiftWriterCall(item, 'e')} }');
        break;
      case RecordFieldKind.listRecordObject:
        s.writeln('    w.writeIndexedList(${f.name}) { e, iw in e.writeFields(iw) }');
        break;
    }
  }

  static String _swiftWriterCall(String base, String expr) {
    switch (base) {
      case 'int':
        return 'writeInt($expr)';
      case 'double':
        return 'writeDouble($expr)';
      case 'bool':
        return 'writeBool($expr)';
      case 'String':
        return 'writeString($expr)';
      default:
        return 'writeInt($expr)';
    }
  }

  static const _swiftRecordWriterReader = '''
public class NitroRecordWriter {
    public var bytes: [UInt8] = []
    public init() {}
    public func writeInt(_ v: Int64) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeInt32(_ v: Int32) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeDouble(_ v: Double) {
        var val = v.bitPattern.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeBool(_ v: Bool) {
        bytes.append(v ? 1 : 0)
    }
    public func writeString(_ v: String) {
        let utf8 = Array(v.utf8)
        writeInt32(Int32(utf8.count))
        bytes.append(contentsOf: utf8)
    }
    public func writeNullTag(_ isNull: Bool) {
        bytes.append(isNull ? 0 : 1)
    }
    public func toNative() -> UnsafeMutablePointer<UInt8>? {
        let total = 4 + bytes.count
        let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
        var length = Int32(bytes.count).littleEndian
        withUnsafeBytes(of: &length) {
            ptr.update(from: \$0.baseAddress!.assumingMemoryBound(to: UInt8.self), count: 4)
        }
        ptr.advanced(by: 4).update(from: bytes, count: bytes.count)
        return ptr
    }
    /// Writes items using the indexed list format:
    ///   int32 count | int64[count] offsets | item_bytes...
    /// Matches Dart's RecordWriter.encodeIndexedList wire format.
    public func writeIndexedList<T>(_ items: [T], writeItem: (T, NitroRecordWriter) -> Void) {
        var blobs: [[UInt8]] = []
        for item in items {
            let iw = NitroRecordWriter()
            writeItem(item, iw)
            blobs.append(iw.bytes)
        }
        writeInt32(Int32(blobs.count))
        var off = Int64(4 + 8 * blobs.count)
        for b in blobs {
            writeInt(off)
            off += Int64(b.count)
        }
        for b in blobs { bytes.append(contentsOf: b) }
    }
    public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
        let w = NitroRecordWriter()
        w.writeInt32(Int32(items.count))
        for item in items { writeItem(w, item) }
        return w.toNative()
    }
}

public class NitroRecordReader {
    public let bytes: UnsafeMutablePointer<UInt8>
    public var pos: Int = 0
    public init(ptr: UnsafeMutablePointer<UInt8>) {
        self.bytes = ptr.advanced(by: 4)
    }
    public init(payload: UnsafeMutablePointer<UInt8>) {
        self.bytes = payload
    }
    public func readInt() -> Int64 {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: Int64.self)
        pos += 8
        return Int64(littleEndian: v)
    }
    public func readInt32() -> Int32 {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: Int32.self)
        pos += 4
        return Int32(littleEndian: v)
    }
    public func readDouble() -> Double {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: UInt64.self)
        pos += 8
        return Double(bitPattern: UInt64(littleEndian: v))
    }
    public func readBool() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v != 0
    }
    public func readString() -> String {
        let len = Int(readInt32())
        let s = String(bytesNoCopy: UnsafeMutableRawPointer(bytes.advanced(by: pos)), length: len, encoding: .utf8, freeWhenDone: false) ?? ""
        pos += len
        return s
    }
    public func readNullTag() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v == 0
    }
    public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
        let r = NitroRecordReader(ptr: ptr)
        let count = r.readInt32()
        var items: [T] = []
        for _ in 0..<count {
            items.append(readItem(r))
        }
        return items
    }
}
''';
}
