import '../bridge_spec.dart';
import 'code_writer.dart';

/// Generates binary encode/decode extension methods for every @HybridRecord
/// type declared in the spec.  The output is written into the `.g.dart` part
/// file and shares the library namespace with the `.native.dart` source.
///
/// Performance design — each type gets an extension named `${TypeName}RecordExt`
/// with four members:
///
///   • `static T fromNative(Pointer<Uint8> ptr)`
///       Top-level decoder: reads the 4-byte length prefix then the fields.
///       Used for a bare return value / property getter.
///
///   • `static T fromReader(RecordReader r)`
///       Inner decoder: reads fields from an already-opened reader.
///       Used when this record is an element inside a list.
///
///   • `void writeFields(RecordWriter writer)`
///       Writes fields into an in-progress writer.
///       Used when this record is inside a list param.
///
///   • `Pointer<Uint8> toNative(Allocator alloc)`
///       Top-level encoder: opens a writer, calls writeFields, seals + copies.
///       Used for a bare param / property setter.
///
/// Wire format is identical to [RecordWriter] / [RecordReader]:
///   int    → 8-byte little-endian int64
///   double → 8-byte little-endian float64
///   bool   → 1 byte
///   String → 4-byte length + UTF-8 bytes
///   null   → 1-byte tag (0=null, 1=present) then value if present
///   list   → 4-byte count then elements
///
/// `Map<String, T>` types are NOT handled here — they continue to use JSON.
class RecordGenerator {
  /// Record types whose Dart codec lives in package:nitro — skip RecordExt for these.
  static const _nitroLibraryRecordTypes = {
    'NitroNullableInt',
    'NitroNullableDouble',
    'NitroNullableBool',
  };

  static String generateDartExtensions(BridgeSpec spec) {
    // Exclude built-in library types: their Dart codec is already on the class
    // in package:nitro/src/nitro_nullable.dart; generating an extension would
    // duplicate methods and cause "already defined" compile errors.
    final localRecords = spec.localRecordTypes
        .where((r) => !_nitroLibraryRecordTypes.contains(r.name))
        .toList();

    // Compute referencedStructs before the early-return so that modules with
    // NO @HybridRecord types (localRecords.isEmpty) but with List<@HybridStruct T>
    // method returns still get their ${T}RecordExt extensions emitted.
    final structMap = {for (final st in spec.structs) st.name: st};
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final structNames = spec.structs.map((s) => s.name).toSet();

    // Collect structs directly referenced in record fields, then transitively.
    final referencedStructs = <String>{};
    for (final rt in localRecords) {
      for (final f in rt.fields) {
        if (f.kind == RecordFieldKind.recordObject || f.kind == RecordFieldKind.listRecordObject) {
          final typeName = f.kind == RecordFieldKind.listRecordObject ? (f.itemTypeName ?? f.dartType.replaceFirst('?', '')) : f.dartType.replaceFirst('?', '');
          if (structMap.containsKey(typeName)) referencedStructs.add(typeName);
        }
      }
    }

    // Also include structs appearing as List<@HybridStruct T> return types on methods/properties.
    for (final func in spec.functions) {
      final item = func.returnType.recordListItemType;
      if (item != null && !func.returnType.recordListItemIsPrimitive && structMap.containsKey(item) && !spec.recordTypes.any((r) => r.name == item)) {
        referencedStructs.add(item);
      }
    }
    for (final prop in spec.properties) {
      final item = prop.type.recordListItemType;
      if (item != null && !prop.type.recordListItemIsPrimitive && structMap.containsKey(item) && !spec.recordTypes.any((r) => r.name == item)) {
        referencedStructs.add(item);
      }
    }

    void collectNestedDart(String typeName) {
      final st = structMap[typeName];
      if (st == null) return;
      for (final f in st.fields) {
        final base = f.type.name.replaceFirst('?', '');
        if (structMap.containsKey(base) && !referencedStructs.contains(base)) {
          referencedStructs.add(base);
          collectNestedDart(base);
        }
      }
    }

    for (final name in referencedStructs.toList()) {
      collectNestedDart(name);
    }

    if (localRecords.isEmpty && referencedStructs.isEmpty) return '';

    final s = CodeWriter();
    s.writeln(
      '// --- @HybridRecord binary extensions (generated by Nitrogen) ---',
    );
    s.writeln();

    for (final stName in referencedStructs) {
      final st = structMap[stName]!;
      s.writeln('extension ${st.name}RecordExt on ${st.name} {');

      // fromNative
      s.writeln('  static ${st.name} fromNative(Pointer<Uint8> ptr) =>');
      s.writeln('      fromReader(RecordReader.fromNative(ptr));');
      s.writeln();

      // fromReader
      s.writeln('  static ${st.name} fromReader(RecordReader r) =>');
      s.writeln('      ${st.name}(');
      for (final f in st.fields.where((f) => !f.isNamed)) {
        s.writeln('        ${_structFieldReadExpr(f, enumNames, structNames)},');
      }
      for (final f in st.fields.where((f) => f.isNamed)) {
        s.writeln('        ${f.name}: ${_structFieldReadExpr(f, enumNames, structNames)},');
      }
      s.writeln('      );');
      s.writeln();

      // writeFields
      s.writeln('  void writeFields(RecordWriter writer) {');
      for (final f in st.fields) {
        _writeStructFieldStmt(s, f, enumNames, structNames);
      }
      s.writeln('  }');
      // NOTE: toNative(Allocator) is intentionally omitted for @HybridStruct types.
      // The struct already has XxxExt.toNative(Arena arena) via its FFI extension,
      // and Arena implements Allocator, so emitting a second toNative(Allocator)
      // here would create an ambiguous call-site error ("member defined in both
      // XxxExt and XxxRecordExt"). Nested serialisation only needs writeFields.
      s.writeln('}');
      s.writeln();
    }

    for (final rt in localRecords) {
      s.writeln('extension ${rt.name}RecordExt on ${rt.name} {');

      // ── static fromNative (top-level, with 4-byte length prefix) ──────
      s.writeln(
        '  static ${rt.name} fromNative(Pointer<Uint8> ptr) =>',
      );
      s.writeln('      fromReader(RecordReader.fromNative(ptr));');
      s.writeln();

      // ── static fromReader (inner, for use inside lists) ───────────────
      s.writeln(
        '  static ${rt.name} fromReader(RecordReader r) =>',
      );
      s.writeln('      ${rt.name}(');
      for (final f in rt.fields) {
        s.writeln('        ${f.name}: ${_readExpr(f)},');
      }
      s.writeln('      );');
      s.writeln();

      // ── writeFields (inner, for use inside lists) ─────────────────────
      s.writeln('  void writeFields(RecordWriter writer) {');
      for (final f in rt.fields) {
        _writeFieldStmt(s, f);
      }
      s.writeln('  }');
      s.writeln();

      // ── toNative (top-level, allocates native buffer) ─────────────────
      s.writeln('  Pointer<Uint8> toNative(Allocator alloc) {');
      s.writeln('    final writer = RecordWriter();');
      s.writeln('    writeFields(writer);');
      s.writeln('    return writer.toNative(alloc);');
      s.writeln('  }');

      s.writeln('}');
      s.writeln();
    }

    return s.toString();
  }

  // ── Read expression helpers ─────────────────────────────────────────────

  static String _readExpr(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _primitiveReadExpr(f.dartType);

      case RecordFieldKind.enumValue:
        final baseType = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          return 'r.readNullTag() ? null : r.readInt().to$baseType()';
        }
        return 'r.readInt().to$baseType()';

      case RecordFieldKind.recordObject:
        final baseType = f.dartType.replaceFirst('?', '');
        // Built-in library types (NitroNullableInt etc.) define fromReader on the
        // class itself — call directly. All others use the generated RecordExt.
        final readerCall = _nitroLibraryRecordTypes.contains(baseType)
            ? '$baseType.fromReader(r)'
            : '${baseType}RecordExt.fromReader(r)';
        if (f.isNullable) {
          return 'r.readNullTag() ? null : $readerCall';
        }
        return readerCall;

      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'dynamic';
        return 'List.generate(r.readInt32(), (_) => ${_primitiveReadCall(item)})';

      case RecordFieldKind.listEnumValue:
        final item = f.itemTypeName!;
        return 'List.generate(r.readInt32(), (_) => r.readInt().to$item())';

      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        final itemReaderCall = _nitroLibraryRecordTypes.contains(item)
            ? '$item.fromReader(r)'
            : '${item}RecordExt.fromReader(r)';
        return 'List.generate(r.readInt32(), (_) => $itemReaderCall)';

      case RecordFieldKind.typedData:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          return 'r.readNullTag() ? null : ${_typedDataReadCall(base)}';
        }
        return _typedDataReadCall(base);
    }
  }

  /// Read expression for a TypedData field from a RecordReader.
  /// All TypedData types are stored as [4B element_count][element_bytes].
  /// Uint8List uses readBlob() directly; others use buffer view over readBlob().
  static String _typedDataReadCall(String dartType) {
    switch (dartType) {
      case 'Uint8List': return 'r.readBlob()';
      case 'Int8List':  return 'Int8List.view(r.readBlob().buffer)';
      case 'Int16List': return 'Int16List.view(r.readBlob().buffer)';
      case 'Uint16List': return 'Uint16List.view(r.readBlob().buffer)';
      case 'Int32List': return 'Int32List.view(r.readBlob().buffer)';
      case 'Uint32List': return 'Uint32List.view(r.readBlob().buffer)';
      case 'Int64List': return 'Int64List.view(r.readBlob().buffer)';
      case 'Uint64List': return 'Uint64List.view(r.readBlob().buffer)';
      case 'Float32List': return 'Float32List.view(r.readBlob().buffer)';
      case 'Float64List': return 'Float64List.view(r.readBlob().buffer)';
      default: return 'r.readBlob()';
    }
  }

  static String _primitiveReadExpr(String dartType) {
    final base = dartType.replaceFirst('?', '');
    final nullable = dartType.endsWith('?');
    if (nullable) {
      return 'r.readNullTag() ? null : ${_primitiveReadCall(base)}';
    }
    return _primitiveReadCall(base);
  }

  static String _primitiveReadCall(String base) {
    switch (base) {
      case 'int':
        return 'r.readInt()';
      case 'double':
        return 'r.readDouble()';
      case 'bool':
        return 'r.readBool()';
      case 'String':
        return 'r.readString()';
      case 'Uint8List':
        return 'r.readBlob()';
      default:
        return 'r.readInt()';
    }
  }

  // ── Write statement helpers ─────────────────────────────────────────────

  static void _writeFieldStmt(CodeWriter s, BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        _writePrimitiveStmt(s, f.dartType, f.name);
        break;

      case RecordFieldKind.enumValue:
        if (f.isNullable) {
          s.writeln('    writer.writeNullTag(${f.name} == null);');
          s.writeln('    if (${f.name} != null) {');
          s.writeln('      writer.writeInt(${f.name}!.nativeValue);');
          s.writeln('    }');
        } else {
          s.writeln('    writer.writeInt(${f.name}.nativeValue);');
        }
        break;

      case RecordFieldKind.recordObject:
        if (f.isNullable) {
          s.writeln('    writer.writeNullTag(${f.name} == null);');
          s.writeln('    if (${f.name} != null) {');
          s.writeln('      ${f.name}!.writeFields(writer);');
          s.writeln('    }');
        } else {
          s.writeln('    ${f.name}.writeFields(writer);');
        }
        break;

      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'dynamic';
        final writeCall = _primitiveWriteCall(item, 'e');
        s.writeln('    writer.writeInt32(${f.name}.length);');
        s.writeln('    for (final e in ${f.name}) { writer.$writeCall; }');
        break;

      case RecordFieldKind.listEnumValue:
        s.writeln('    writer.writeInt32(${f.name}.length);');
        s.writeln('    for (final e in ${f.name}) { writer.writeInt(e.nativeValue); }');
        break;

      case RecordFieldKind.listRecordObject:
        s.writeln('    writer.writeInt32(${f.name}.length);');
        s.writeln('    for (final e in ${f.name}) { e.writeFields(writer); }');
        break;

      case RecordFieldKind.typedData:
        // TypedData: convert to Uint8List bytes via .buffer.asUint8List() then writeBlob.
        // Uint8List is written directly; others are reinterpreted through the byte buffer.
        final base = f.dartType.replaceFirst('?', '');
        final toBytes = base == 'Uint8List' ? f.name : '${f.name}.buffer.asUint8List()';
        if (f.isNullable) {
          s.writeln('    writer.writeNullTag(${f.name} == null);');
          s.writeln('    if (${f.name} != null) {');
          final toBytesNonNull = base == 'Uint8List' ? '${f.name}!' : '${f.name}!.buffer.asUint8List()';
          s.writeln('      writer.writeBlob($toBytesNonNull);');
          s.writeln('    }');
        } else {
          s.writeln('    writer.writeBlob($toBytes);');
        }
        break;
    }
  }

  /// Write expression for a TypedData field to a RecordWriter.
  /// All TypedData types are stored as [4B byte_length][element_bytes].
  static String _typedDataWriteCall(String base, String expr) {
    final toBytes = base == 'Uint8List' ? expr : '$expr.buffer.asUint8List()';
    return 'writeBlob($toBytes)';
  }

  static void _writePrimitiveStmt(
    CodeWriter s,
    String dartType,
    String fieldName,
  ) {
    final base = dartType.replaceFirst('?', '');
    final nullable = dartType.endsWith('?');
    if (nullable) {
      s.writeln('    writer.writeNullTag($fieldName == null);');
      s.writeln('    if ($fieldName != null) {');
      s.writeln('      writer.${_primitiveWriteCall(base, '$fieldName!')};');
      s.writeln('    }');
    } else {
      s.writeln('    writer.${_primitiveWriteCall(base, fieldName)};');
    }
  }

  static String _primitiveWriteCall(String base, String expr) {
    switch (base) {
      case 'int':
        return 'writeInt($expr)';
      case 'double':
        return 'writeDouble($expr)';
      case 'bool':
        return 'writeBool($expr)';
      case 'String':
        return 'writeString($expr)';
      case 'Uint8List':
        return 'writeBlob($expr)';
      default:
        return 'writeInt($expr)';
    }
  }

  // ── Struct field read/write helpers (for RecordExt generated above) ───────────

  /// Dart read expression for one field of a @HybridStruct embedded in a record.
  static String _structFieldReadExpr(BridgeField f, Set<String> enumNames, Set<String> structNames) {
    final base = f.type.name.replaceFirst('?', '');
    if (enumNames.contains(base)) return _primitiveReadCall('int');
    if (structNames.contains(base)) return '${base}RecordExt.fromReader(r)';
    return _primitiveReadCall(base);
  }

  /// Emits a Dart write statement for one field of a @HybridStruct embedded in a record.
  static void _writeStructFieldStmt(
    CodeWriter s,
    BridgeField f,
    Set<String> enumNames,
    Set<String> structNames,
  ) {
    final base = f.type.name.replaceFirst('?', '');
    if (enumNames.contains(base)) {
      s.writeln('    writer.${_primitiveWriteCall('int', '${f.name}.nativeValue')};');
    } else if (structNames.contains(base)) {
      s.writeln('    ${f.name}.writeFields(writer);');
    } else {
      _writePrimitiveStmt(s, f.type.name, f.name);
    }
  }

  // ── C++ record decoder generator ────────────────────────────────────────────

  /// Generates C++ struct definitions and a bounds-checked `NitroRecordReader`
  /// for every `@HybridRecord` type in the spec.  Emitted into the
  /// `*.native.g.h` header so C++ native implementations can call
  /// `MyRecord::fromNative(buf)` without hand-rolling binary parsing.
  ///
  /// Safety guarantee: every `readNullTag()` call is preceded by an explicit
  /// `if (offset + 1 > size)` check that throws `std::runtime_error`, preventing
  /// out-of-bounds reads on malformed wire data (IMPROVEMENTS.md §3.3).
  static String generateCpp(BridgeSpec spec) {
    final localRecords = spec.localRecordTypes;
    if (localRecords.isEmpty) return '';
    final enumNames = spec.enums.map((e) => e.name).toSet();

    final s = CodeWriter();

    // Forward declarations so mutually-referencing types compile in any order.
    s.writeln('// @HybridRecord C++ structs (generated by Nitrogen)');
    for (final rt in localRecords) {
      s.writeln('struct ${rt.name};');
    }
    s.writeln();

    // NitroRecordReader — shared helper used by all fromReader implementations.
    s.writeln(_cppRecordReaderDef);
    s.writeln();

    // Per-record struct + fromNative / fromReader.
    for (final rt in localRecords) {
      s.writeln('struct ${rt.name} {');
      for (final f in rt.fields) {
        s.writeln('    ${_cppFieldType(f, enumNames)} ${f.name};');
      }
      s.writeln();
      s.writeln('    static ${rt.name} fromNative(NitroCppBuffer buf) {');
      s.writeln('        NitroRecordReader _r(buf);');
      s.writeln('        return fromReader(_r);');
      s.writeln('    }');
      s.writeln();
      s.writeln('    static ${rt.name} fromReader(NitroRecordReader& _r) {');
      s.writeln('        ${rt.name} _obj;');
      for (final f in rt.fields) {
        _cppEmitFieldRead(s, f, enumNames);
      }
      s.writeln('        return _obj;');
      s.writeln('    }');
      s.writeln('};');
      s.writeln();
    }

    return s.toString();
  }

  static String _cppFieldType(BridgeRecordField f, Set<String> enumNames) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final t = _cppPrimType(f.dartType.replaceFirst('?', ''));
        return f.isNullable ? 'std::optional<$t>' : t;
      case RecordFieldKind.enumValue:
        final base = f.dartType.replaceFirst('?', '');
        final t = enumNames.contains(base) ? base : 'int64_t';
        return f.isNullable ? 'std::optional<$t>' : t;
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        return f.isNullable ? 'std::optional<$base>' : base;
      case RecordFieldKind.listPrimitive:
        return 'std::vector<${_cppPrimType(f.itemTypeName ?? 'int')}>';
      case RecordFieldKind.listEnumValue:
        final item = f.itemTypeName ?? 'int64_t';
        return 'std::vector<${enumNames.contains(item) ? item : 'int64_t'}>';
      case RecordFieldKind.listRecordObject:
        return 'std::vector<${f.itemTypeName}>';
      case RecordFieldKind.typedData:
        // TypedData in @HybridRecord bridges as a raw byte vector in C++.
        return f.isNullable ? 'std::optional<std::vector<uint8_t>>' : 'std::vector<uint8_t>';
    }
  }

  static String _cppPrimType(String dartType) {
    switch (dartType) {
      case 'int':
        return 'int64_t';
      case 'double':
        return 'double';
      case 'bool':
        return 'bool';
      case 'String':
        return 'std::string';
      default:
        return 'int64_t';
    }
  }

  static String _cppPrimRead(String dartType) {
    switch (dartType) {
      case 'int':
        return 'readInt';
      case 'double':
        return 'readDouble';
      case 'bool':
        return 'readBool';
      case 'String':
        return 'readString';
      default:
        return 'readInt';
    }
  }

  static void _cppEmitFieldRead(CodeWriter s, BridgeRecordField f, Set<String> enumNames) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        final t = _cppPrimType(base);
        final read = _cppPrimRead(base);
        if (f.isNullable) {
          s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$t>(_r.$read()); }');
        } else {
          s.writeln('        _obj.${f.name} = _r.$read();');
        }
        break;
      case RecordFieldKind.enumValue:
        final base = f.dartType.replaceFirst('?', '');
        final t = enumNames.contains(base) ? base : 'int64_t';
        final readExpr = enumNames.contains(base) ? 'static_cast<$base>(_r.readInt())' : '_r.readInt()';
        if (f.isNullable) {
          s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$t>($readExpr); }');
        } else {
          s.writeln('        _obj.${f.name} = $readExpr;');
        }
        break;
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          s.writeln('        { bool _null = _r.readNullTag(); _obj.${f.name} = _null ? std::nullopt : std::optional<$base>($base::fromReader(_r)); }');
        } else {
          s.writeln('        _obj.${f.name} = $base::fromReader(_r);');
        }
        break;
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        final read = _cppPrimRead(item);
        s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back(_r.$read()); }');
        break;
      case RecordFieldKind.listEnumValue:
        final item = f.itemTypeName ?? 'int64_t';
        final readExpr = enumNames.contains(item) ? 'static_cast<$item>(_r.readInt())' : '_r.readInt()';
        s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back($readExpr); }');
        break;
      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.reserve((size_t)_n); for (int32_t _i = 0; _i < _n; _i++) _obj.${f.name}.push_back($item::fromReader(_r)); }');
        break;
      case RecordFieldKind.typedData:
        // TypedData: [4B count][count bytes] → std::vector<uint8_t>
        if (f.isNullable) {
          s.writeln('        { bool _null = _r.readNullTag(); if (!_null) { int32_t _n = _r.readInt32(); _obj.${f.name}.emplace().resize((size_t)_n); _r.readBytes(_obj.${f.name}->data(), (size_t)_n); } }');
        } else {
          s.writeln('        { int32_t _n = _r.readInt32(); _obj.${f.name}.resize((size_t)_n); _r.readBytes(_obj.${f.name}.data(), (size_t)_n); }');
        }
        break;
    }
  }

  /// Inline C++ definition of the bounds-checked record reader.
  static const _cppRecordReaderDef = '''
// Bounds-checked binary reader for @HybridRecord wire payloads.
// Every readNullTag() bounds-checks before the byte access (IMPROVEMENTS.md §3.3).
struct NitroRecordReader {
    const uint8_t* _data;
    size_t         _size;
    size_t         _offset;
    explicit NitroRecordReader(NitroCppBuffer buf)
        : _data(buf.data), _size(buf.size), _offset(0) {}
    explicit NitroRecordReader(const uint8_t* data, size_t size)
        : _data(data), _size(size), _offset(0) {}
private:
    void _require(size_t n) const {
        if (_offset + n > _size)
            throw std::runtime_error("NitroRecordReader: buffer underflow");
    }
public:
    int64_t readInt() {
        _require(8); int64_t v; std::memcpy(&v, _data + _offset, 8); _offset += 8; return v;
    }
    int32_t readInt32() {
        _require(4); int32_t v; std::memcpy(&v, _data + _offset, 4); _offset += 4; return v;
    }
    double readDouble() {
        _require(8); uint64_t b; std::memcpy(&b, _data + _offset, 8);
        _offset += 8; double v; std::memcpy(&v, &b, 8); return v;
    }
    bool readBool() {
        _require(1); return _data[_offset++] != 0;
    }
    std::string readString() {
        int32_t len = readInt32(); _require((size_t)len);
        std::string s(reinterpret_cast<const char*>(_data + _offset), (size_t)len);
        _offset += (size_t)len; return s;
    }
    // Bounds-checked null tag read — throws if no byte remains.
    bool readNullTag() {
        if (_offset + 1 > _size)
            throw std::runtime_error("NitroRecordReader: null tag read past end of buffer");
        return _data[_offset++] == 0;
    }
    // TypedData blob: [4B count][count bytes] → reads into caller-owned vector.
    void readBytes(uint8_t* dst, size_t n) {
        _require(n); std::memcpy(dst, _data + _offset, n); _offset += n;
    }
};''';

  // ── Kotlin generator ────────────────────────────────────────────────────────

  /// Generates `@Keep data class` declarations for every `@HybridRecord` type
  /// into the Kotlin bridge file.  Each class also gets static `decode` /
  /// `encode` helpers so callers never have to hand-roll ByteArray parsing.
  static String generateKotlin(BridgeSpec spec) {
    final localRecords = spec.localRecordTypes;
    if (localRecords.isEmpty) return '';
    final enumNames = spec.enums.map((e) => e.name).toSet();

    final s = CodeWriter();
    s.writeln('// --- @HybridRecord Kotlin data classes (generated by Nitrogen) ---');
    s.writeln();

    for (final rt in localRecords) {
      final fields = rt.fields.map((f) => 'val ${f.name}: ${_kotlinType(f, enumNames)}').join(', ');
      s.writeln('@androidx.annotation.Keep');
      s.writeln('data class ${rt.name}($fields) {');

      // --- companion: decodeFrom(buf) reads fields from a shared ByteBuffer cursor ---
      //                decode(bytes) wraps a standalone ByteArray (strips 4-byte prefix)
      s.writeln('    companion object {');
      s.writeln('        @JvmStatic fun decodeFrom(buf: java.nio.ByteBuffer): ${rt.name} {');
      for (final f in rt.fields) {
        s.writeln('            val ${f.name} = ${_kotlinReadExpr(f, enumNames)}');
      }
      final ctorArgs = rt.fields.map((f) => f.name).join(', ');
      s.writeln('            return ${rt.name}($ctorArgs)');
      s.writeln('        }');
      s.writeln('        @JvmStatic fun decode(bytes: ByteArray): ${rt.name} {');
      s.writeln('            val buf = java.nio.ByteBuffer.wrap(bytes).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
      s.writeln('            buf.position(4) // skip 4-byte length prefix');
      s.writeln('            return decodeFrom(buf)');
      s.writeln('        }');
      s.writeln('    }');
      s.writeln();

      // --- writeFieldsTo: writes fields without length prefix (for use inside lists) ---
      s.writeln('    fun writeFieldsTo(out: java.io.ByteArrayOutputStream, buf: java.nio.ByteBuffer) {');
      s.writeln('        fun writeInt(v: Long) { buf.clear(); buf.putLong(v); out.write(buf.array()) }');
      s.writeln('        fun writeInt32(v: Int) { buf.clear(); buf.putInt(v); out.write(buf.array(), 0, 4) }');
      s.writeln('        fun writeDouble(v: Double) { buf.clear(); buf.putDouble(v); out.write(buf.array()) }');
      s.writeln('        fun writeBool(v: Boolean) { out.write(if (v) 1 else 0) }');
      s.writeln('        fun writeString(v: String) { val b = v.toByteArray(Charsets.UTF_8); writeInt32(b.size); out.write(b) }');
      for (final f in rt.fields) {
        _kotlinWriteStmt(s, f);
      }
      s.writeln('    }');
      s.writeln();

      // --- encode to ByteArray (with 4-byte length prefix) ---
      final capacity = recordBytesHint(rt);
      s.writeln('    fun encode(): ByteArray {');
      s.writeln('        val out = java.io.ByteArrayOutputStream($capacity)');
      s.writeln('        val buf = java.nio.ByteBuffer.allocate(8).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
      s.writeln('        writeFieldsTo(out, buf)');
      s.writeln('        val payload = out.toByteArray()');
      s.writeln('        val lenBuf = java.nio.ByteBuffer.allocate(4).order(java.nio.ByteOrder.LITTLE_ENDIAN)');
      s.writeln('        lenBuf.putInt(payload.size)');
      s.writeln('        return lenBuf.array() + payload');
      s.writeln('    }');
      s.writeln('}');
      s.writeln();
    }

    return s.toString();
  }

  static String _kotlinType(BridgeRecordField f, Set<String> enumNames) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _kotlinBase(f.dartType) + (f.isNullable ? '?' : '');
      case RecordFieldKind.enumValue:
        final base = f.dartType.replaceFirst('?', '');
        return (enumNames.contains(base) ? base : 'Long') + (f.isNullable ? '?' : '');
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        return base + (f.isNullable ? '?' : '');
      case RecordFieldKind.listPrimitive:
        return 'List<${_kotlinBase(f.itemTypeName ?? 'int')}>';
      case RecordFieldKind.listEnumValue:
        final item = f.itemTypeName ?? 'Long';
        return 'List<${enumNames.contains(item) ? item : 'Long'}>';
      case RecordFieldKind.listRecordObject:
        return 'List<${f.itemTypeName}>';
      case RecordFieldKind.typedData:
        final kotlinType = _kotlinTypedDataType(f.dartType.replaceFirst('?', ''));
        return kotlinType + (f.isNullable ? '?' : '');
    }
  }

  static String _kotlinTypedDataType(String dartType) {
    switch (dartType) {
      case 'Uint8List':
      case 'Int8List':   return 'ByteArray';
      case 'Int16List':
      case 'Uint16List': return 'ShortArray';
      case 'Int32List':
      case 'Uint32List': return 'IntArray';
      case 'Int64List':
      case 'Uint64List': return 'LongArray';
      case 'Float32List': return 'FloatArray';
      case 'Float64List': return 'DoubleArray';
      default: return 'ByteArray';
    }
  }

  static String _kotlinBase(String dartType) {
    final base = dartType.replaceFirst('?', '');
    switch (base) {
      case 'int':
        return 'Long';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Boolean';
      case 'String':
        return 'String';
      default:
        return 'Long';
    }
  }

  static String _kotlinReadExpr(BridgeRecordField f, Set<String> enumNames) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          return '(if (buf.get().toInt() == 0) null else ${_kotlinPrimRead(base)})';
        }
        return _kotlinPrimRead(base);
      case RecordFieldKind.enumValue:
        final base = f.dartType.replaceFirst('?', '');
        final read = enumNames.contains(base) ? '$base.fromNative(buf.long)' : 'buf.long';
        if (f.isNullable) {
          return '(if (buf.get().toInt() == 0) null else $read)';
        }
        return read;
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          return '(if (buf.get().toInt() == 0) null else $base.decodeFrom(buf))';
        }
        return '$base.decodeFrom(buf)';
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        return '(0 until buf.int).map { ${_kotlinPrimRead(item)} }';
      case RecordFieldKind.listEnumValue:
        final item = f.itemTypeName ?? 'Long';
        final read = enumNames.contains(item) ? '$item.fromNative(buf.long)' : 'buf.long';
        return '(0 until buf.int).map { $read }';
      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        return '(0 until buf.int).map { $item.decodeFrom(buf) }';
      case RecordFieldKind.typedData:
        final base = f.dartType.replaceFirst('?', '');
        final read = _kotlinTypedDataRead(base);
        if (f.isNullable) {
          return '(if (buf.get().toInt() == 0) null else $read)';
        }
        return read;
    }
  }

  static String _kotlinTypedDataRead(String dartType) {
    // Wire format: [4B byteCount][byteCount bytes] — byte count, not element count.
    // Dart writes byte count via writeBlob(TypedData.buffer.asUint8List()).
    // Kotlin must divide by element size to get element count.
    switch (dartType) {
      case 'Uint8List':
      case 'Int8List':   return '{ val _len = buf.int; val _b = ByteArray(_len); buf.get(_b); _b }()';
      case 'Int16List':
      case 'Uint16List': return '{ val _len = buf.int; ShortArray(_len / 2) { buf.short } }()';
      case 'Int32List':
      case 'Uint32List': return '{ val _len = buf.int; IntArray(_len / 4) { buf.int } }()';
      case 'Int64List':
      case 'Uint64List': return '{ val _len = buf.int; LongArray(_len / 8) { buf.long } }()';
      case 'Float32List': return '{ val _len = buf.int; FloatArray(_len / 4) { buf.float } }()';
      case 'Float64List': return '{ val _len = buf.int; DoubleArray(_len / 8) { buf.double } }()';
      default: return '{ val _len = buf.int; val _b = ByteArray(_len); buf.get(_b); _b }()';
    }
  }

  static String _kotlinPrimRead(String base) {
    switch (base) {
      case 'int':
        return 'buf.long';
      case 'double':
        return 'buf.double';
      case 'bool':
        return '(buf.get().toInt() != 0)';
      case 'String':
        return '{ val len = buf.int; val b = ByteArray(len); buf.get(b); b.toString(Charsets.UTF_8) }()';
      case 'Uint8List':
      case 'ByteArray':
        return '{ val len = buf.int; val b = ByteArray(len); buf.get(b); b }()';
      default:
        return 'buf.long';
    }
  }

  static void _kotlinWriteStmt(CodeWriter s, BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
          s.writeln('        ${f.name}?.let { ${_kotlinWriteCall(base, 'it')} }');
        } else {
          s.writeln('        ${_kotlinWriteCall(base, f.name)}');
        }
        break;
      case RecordFieldKind.enumValue:
        if (f.isNullable) {
          s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
          s.writeln('        ${f.name}?.let { writeInt(it.nativeValue) }');
        } else {
          s.writeln('        writeInt(${f.name}.nativeValue)');
        }
        break;
      case RecordFieldKind.recordObject:
        if (f.isNullable) {
          s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
          s.writeln('        ${f.name}?.writeFieldsTo(out, buf)');
        } else {
          s.writeln('        ${f.name}.writeFieldsTo(out, buf)');
        }
        break;
      case RecordFieldKind.listPrimitive:
        final base = f.itemTypeName ?? 'int';
        s.writeln('        writeInt32(${f.name}.size)');
        s.writeln('        ${f.name}.forEach { e -> ${_kotlinWriteCall(base, 'e')} }');
        break;
      case RecordFieldKind.listEnumValue:
        s.writeln('        writeInt32(${f.name}.size)');
        s.writeln('        ${f.name}.forEach { e -> writeInt(e.nativeValue) }');
        break;
      case RecordFieldKind.listRecordObject:
        s.writeln('        writeInt32(${f.name}.size)');
        s.writeln('        ${f.name}.forEach { e -> e.writeFieldsTo(out, buf) }');
        break;
      case RecordFieldKind.typedData:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          s.writeln('        out.write(if (${f.name} == null) 0 else 1)');
          s.writeln('        ${f.name}?.let { ${_kotlinTypedDataWrite(base, 'it')} }');
        } else {
          s.writeln('        ${_kotlinTypedDataWrite(base, f.name)}');
        }
        break;
    }
  }

  static String _kotlinTypedDataWrite(String dartType, String expr) {
    // Wire format: [4B byteCount][byteCount bytes] — must write BYTE count, not element count,
    // to match Dart's writeBlob which writes byteCount = TypedData.buffer.byteLength.
    // Use `run { }` instead of `{ }()` to prevent Kotlin trailing-lambda misparse.
    switch (dartType) {
      case 'Uint8List':
      case 'Int8List':   return 'run { writeInt32($expr.size); out.write($expr) }';
      case 'Int16List':
      case 'Uint16List': return 'run { writeInt32($expr.size * 2); $expr.forEach { e -> buf.clear(); buf.putShort(e); buf.flip(); out.write(buf.array(), 0, 2) } }';
      case 'Int32List':
      case 'Uint32List': return 'run { writeInt32($expr.size * 4); $expr.forEach { e -> buf.clear(); buf.putInt(e); buf.flip(); out.write(buf.array(), 0, 4) } }';
      case 'Int64List':
      case 'Uint64List': return 'run { writeInt32($expr.size * 8); $expr.forEach { e -> buf.clear(); buf.putLong(e); buf.flip(); out.write(buf.array(), 0, 8) } }';
      case 'Float32List': return 'run { writeInt32($expr.size * 4); $expr.forEach { e -> buf.clear(); buf.putFloat(e); buf.flip(); out.write(buf.array(), 0, 4) } }';
      case 'Float64List': return 'run { writeInt32($expr.size * 8); $expr.forEach { e -> buf.clear(); buf.putDouble(e); buf.flip(); out.write(buf.array(), 0, 8) } }';
      default: return 'run { writeInt32($expr.size); out.write($expr) }';
    }
  }

  static String _kotlinWriteCall(String base, String expr) {
    switch (base) {
      case 'int':
        return 'writeInt($expr.toLong())';
      case 'double':
        return 'writeDouble($expr)';
      case 'bool':
        return 'writeBool($expr)';
      case 'String':
        return 'writeString($expr)';
      case 'Uint8List':
      case 'ByteArray':
        return 'writeInt32($expr.size); out.write($expr)';
      default:
        return 'writeInt($expr.toLong())';
    }
  }

  /// Returns a static byte-size estimate for one serialized instance of [rt].
  /// Used to pre-size [ByteArrayOutputStream] in [encode] and list paths,
  /// avoiding the default 32-byte initial buffer and subsequent grow copies.
  ///
  /// Estimates per field kind:
  ///   int/double   → 8 bytes (+ 1 nullable tag)
  ///   bool         → 1 byte  (+ 1 nullable tag)
  ///   String       → 4 (len) + 32 (avg content) = 36 (+ 1 nullable tag)
  ///   nested record → 32 rough estimate (+ 1 nullable tag)
  ///   list         → 4 (count) + 8 * 4 avg items = 36
  static int recordBytesHint(BridgeRecordType rt) {
    var total = 0;
    for (final f in rt.fields) {
      final nullableTag = f.isNullable ? 1 : 0;
      switch (f.kind) {
        case RecordFieldKind.primitive:
          final base = f.dartType.replaceFirst('?', '');
          switch (base) {
            case 'bool':
              total += nullableTag + 1;
            case 'String':
              total += nullableTag + 36;
            default: // int, double
              total += nullableTag + 8;
          }
        case RecordFieldKind.enumValue:
          total += nullableTag + 8;
        case RecordFieldKind.recordObject:
          total += nullableTag + 32;
        case RecordFieldKind.listPrimitive:
        case RecordFieldKind.listEnumValue:
        case RecordFieldKind.listRecordObject:
          total += 36; // 4-byte count + ~4 items * 8 bytes avg
        case RecordFieldKind.typedData:
          total += nullableTag + 68; // 4-byte count + ~64 bytes avg payload
      }
    }
    return total > 0 ? total : 32;
  }

  // ── Native generators ───────────────────────────────────────────────────

  static String generateSwift(BridgeSpec spec, {bool emitBoilerplate = true}) {
    final localRecords = spec.localRecordTypes;

    // ── fromReader/writeFields extensions for plain structs embedded in records ──
    // The Dart side generates RecordExt for HybridStructs; we mirror this for Swift.
    // Without these extensions, `LiveTrackingUpdate.fromReader` cannot call
    // `PackageDimensions.fromReader(r)` because plain structs have no such method.
    final structMap = {for (final st in spec.structs) st.name: st};
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final structNames = spec.structs.map((st) => st.name).toSet();

    // Collect structs directly referenced in record fields, then transitively.
    final referencedStructs = <String>{};
    for (final rt in localRecords) {
      for (final f in rt.fields) {
        if (f.kind == RecordFieldKind.recordObject || f.kind == RecordFieldKind.listRecordObject) {
          final typeName = f.kind == RecordFieldKind.listRecordObject ? (f.itemTypeName ?? f.dartType.replaceFirst('?', '')) : f.dartType.replaceFirst('?', '');
          if (structMap.containsKey(typeName)) referencedStructs.add(typeName);
        }
      }
    }

    // Also include structs appearing as List<@HybridStruct T> return types on methods/properties.
    for (final func in spec.functions) {
      final item = func.returnType.recordListItemType;
      if (item != null && !func.returnType.recordListItemIsPrimitive && structMap.containsKey(item) && !spec.recordTypes.any((r) => r.name == item)) {
        referencedStructs.add(item);
      }
    }
    for (final prop in spec.properties) {
      final item = prop.type.recordListItemType;
      if (item != null && !prop.type.recordListItemIsPrimitive && structMap.containsKey(item) && !spec.recordTypes.any((r) => r.name == item)) {
        referencedStructs.add(item);
      }
    }

    void collectNestedSwift(String typeName) {
      final st = structMap[typeName];
      if (st == null) return;
      for (final f in st.fields) {
        final base = f.type.name.replaceFirst('?', '');
        if (structMap.containsKey(base) && !referencedStructs.contains(base)) {
          referencedStructs.add(base);
          collectNestedSwift(base);
        }
      }
    }

    for (final name in referencedStructs.toList()) {
      collectNestedSwift(name);
    }

    // Early exit only when there is truly nothing to generate.
    if (localRecords.isEmpty && referencedStructs.isEmpty) return '';

    final s = CodeWriter();
    s.writeln('// --- @HybridRecord binary extensions (generated by Nitrogen) ---');
    s.writeln();

    for (final stName in referencedStructs) {
      final st = structMap[stName]!;
      s.writeln('extension ${st.name} {');

      s.writeln('  public static func fromReader(_ r: NitroRecordReader) -> ${st.name} {');
      s.writeln('    return ${st.name}(');
      for (final f in st.fields) {
        s.writeln('      ${f.name}: ${_swiftStructReadExpr(f, enumNames, structNames)},');
      }
      s.writeln('    )');
      s.writeln('  }');
      s.writeln();

      s.writeln('  public func writeFields(_ writer: NitroRecordWriter) {');
      for (final f in st.fields) {
        _swiftStructWriteStmt(s, f, enumNames, structNames, st);
      }
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }

    for (final rt in localRecords) {
      s.writeln('public struct ${rt.name} {');
      for (final f in rt.fields) {
        final opt = f.isNullable ? '?' : '';
        s.writeln('  public var ${f.name}: ${_swiftType(f)}$opt');
      }
      s.writeln();

      final params = rt.fields.map((f) => '${f.name}: ${_swiftType(f)}${f.isNullable ? '?' : ''}').join(', ');
      s.writeln('  public init($params) {');
      for (final f in rt.fields) {
        s.writeln('    self.${f.name} = ${f.name}');
      }
      s.writeln('  }');
      s.writeln();

      s.writeln('  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> ${rt.name} {');
      s.writeln('    return fromReader(NitroRecordReader(ptr: ptr))');
      s.writeln('  }');
      s.writeln();

      s.writeln('  public static func fromReader(_ r: NitroRecordReader) -> ${rt.name} {');
      s.writeln('    return ${rt.name}(');
      for (final f in rt.fields) {
        s.writeln('      ${f.name}: ${_swiftRead(f)},');
      }
      s.writeln('    )');
      s.writeln('  }');
      s.writeln();

      s.writeln('  public func writeFields(_ writer: NitroRecordWriter) {');
      for (final f in rt.fields) {
        _swiftWriteStmt(s, f);
      }
      s.writeln('  }');
      s.writeln();

      s.writeln('  public func toNative() -> UnsafeMutablePointer<UInt8>? {');
      s.writeln('    let writer = NitroRecordWriter()');
      s.writeln('    writeFields(writer)');
      s.writeln('    return writer.toNative()');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }

    if (emitBoilerplate) {
      s.writeln(_swiftRecordWriterReader);
    }
    return s.toString();
  }

  static String _swiftType(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _swiftBase(f.dartType);
      case RecordFieldKind.enumValue:
        return f.dartType.replaceFirst('?', '');
      case RecordFieldKind.recordObject:
        return f.dartType.replaceFirst('?', '');
      case RecordFieldKind.listPrimitive:
        return '[${_swiftBase(f.itemTypeName ?? 'Any')}]';
      case RecordFieldKind.listEnumValue:
        return '[${f.itemTypeName}]';
      case RecordFieldKind.listRecordObject:
        return '[${f.itemTypeName}]';
      case RecordFieldKind.typedData:
        return _swiftTypedDataType(f.dartType.replaceFirst('?', ''));
    }
  }

  static String _swiftTypedDataType(String dartType) {
    switch (dartType) {
      case 'Uint8List':
      case 'Int8List':   return 'Data';
      case 'Int16List':
      case 'Uint16List': return '[Int16]';
      case 'Int32List':
      case 'Uint32List': return '[Int32]';
      case 'Int64List':
      case 'Uint64List': return '[Int64]';
      case 'Float32List': return '[Float]';
      case 'Float64List': return '[Double]';
      default: return 'Data';
    }
  }

  static String _swiftBase(String dartType) {
    final base = dartType.replaceFirst('?', '');
    switch (base) {
      case 'int':
        return 'Int64';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Bool';
      case 'String':
        return 'String';
      default:
        return 'Int64';
    }
  }

  static String _swiftReadCall(String base) {
    switch (base) {
      case 'int':
        return 'r.readInt()';
      case 'double':
        return 'r.readDouble()';
      case 'bool':
        return 'r.readBool()';
      case 'String':
        return 'r.readString()';
      case 'Uint8List':
        return 'r.readBlob()';
      default:
        return 'r.readInt()';
    }
  }

  static String _swiftRead(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) return 'r.readNullTag() ? nil : ${_swiftReadCall(base)}';
        return _swiftReadCall(base);
      case RecordFieldKind.enumValue:
        final base = f.dartType.replaceFirst('?', '');
        final read = '$base(rawValue: r.readInt())!';
        if (f.isNullable) return 'r.readNullTag() ? nil : $read';
        return read;
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) return 'r.readNullTag() ? nil : $base.fromReader(r)';
        return '$base.fromReader(r)';
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        return '(0..<Int(r.readInt32())).map { _ in ${_swiftReadCall(item)} }';
      case RecordFieldKind.listEnumValue:
        final item = f.itemTypeName!;
        return '(0..<Int(r.readInt32())).map { _ in $item(rawValue: r.readInt())! }';
      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        return '(0..<Int(r.readInt32())).map { _ in $item.fromReader(r) }';
      case RecordFieldKind.typedData:
        final base = f.dartType.replaceFirst('?', '');
        final read = _swiftTypedDataRead(base);
        if (f.isNullable) return 'r.readNullTag() ? nil : $read';
        return read;
    }
  }

  static String _swiftTypedDataRead(String dartType) {
    // Note: \$0 uses raw string escaping so the generated Swift gets literal $0.
    const d0 = r'$0';
    switch (dartType) {
      case 'Uint8List':
      case 'Int8List':   return 'r.readBlob()';
      case 'Int16List':
      case 'Uint16List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Int16.self)) } }()';
      case 'Int32List':
      case 'Uint32List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Int32.self)) } }()';
      case 'Int64List':
      case 'Uint64List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Int64.self)) } }()';
      case 'Float32List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Float.self)) } }()';
      case 'Float64List': return '{ let d = r.readBlob(); return d.withUnsafeBytes { Array($d0.bindMemory(to: Double.self)) } }()';
      default: return 'r.readBlob()';
    }
  }

  static void _swiftWriteStmt(CodeWriter s, BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          s.writeln('    writer.writeNullTag(${f.name} == nil)');
          s.writeln('    if let val = ${f.name} { writer.${_swiftWriterCall(base, 'val')} }');
        } else {
          s.writeln('    writer.${_swiftWriterCall(base, f.name)}');
        }
        break;
      case RecordFieldKind.enumValue:
        if (f.isNullable) {
          s.writeln('    writer.writeNullTag(${f.name} == nil)');
          s.writeln('    if let val = ${f.name} { writer.writeInt(val.rawValue) }');
        } else {
          s.writeln('    writer.writeInt(${f.name}.rawValue)');
        }
        break;
      case RecordFieldKind.recordObject:
        if (f.isNullable) {
          s.writeln('    writer.writeNullTag(${f.name} == nil)');
          s.writeln('    if let val = ${f.name} { val.writeFields(writer) }');
        } else {
          s.writeln('    ${f.name}.writeFields(writer)');
        }
        break;
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        s.writeln('    writer.writeInt32(Int32(${f.name}.count))');
        s.writeln('    for e in ${f.name} { writer.${_swiftWriterCall(item, 'e')} }');
        break;
      case RecordFieldKind.listEnumValue:
        s.writeln('    writer.writeInt32(Int32(${f.name}.count))');
        s.writeln('    for e in ${f.name} { writer.writeInt(e.rawValue) }');
        break;
      case RecordFieldKind.listRecordObject:
        s.writeln('    writer.writeInt32(Int32(${f.name}.count))');
        s.writeln('    for e in ${f.name} { e.writeFields(writer) }');
        break;
      case RecordFieldKind.typedData:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          s.writeln('    writer.writeNullTag(${f.name} == nil)');
          s.writeln('    if let val = ${f.name} { ${_swiftTypedDataWrite(base, 'val', 'writer')} }');
        } else {
          s.writeln('    ${_swiftTypedDataWrite(base, f.name, 'writer')}');
        }
        break;
    }
  }

  static String _swiftTypedDataWrite(String dartType, String expr, String writer) {
    switch (dartType) {
      case 'Uint8List':
      case 'Int8List':   return '$writer.writeBlob($expr)';
      case 'Int16List':
      case 'Uint16List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
      case 'Int32List':
      case 'Uint32List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
      case 'Int64List':
      case 'Uint64List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
      case 'Float32List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
      case 'Float64List': return '$expr.withUnsafeBufferPointer { $writer.writeBlob(Data(buffer: \$0)) }';
      default: return '$writer.writeBlob($expr)';
    }
  }

  static String _swiftWriterCall(String base, String expr) {
    switch (base) {
      case 'int':
        return 'writeInt($expr)';
      case 'double':
        return 'writeDouble($expr)';
      case 'bool':
        return 'writeBool($expr)';
      case 'String':
        return 'writeString($expr)';
      case 'Uint8List':
        return 'writeBlob($expr)';
      default:
        return 'writeInt($expr)';
    }
  }

  static String _swiftStructReadExpr(BridgeField f, Set<String> enumNames, Set<String> structNames) {
    final base = f.type.name.replaceFirst('?', '');
    if (enumNames.contains(base)) return '$base(rawValue: Int(r.readInt()))!';
    if (structNames.contains(base)) return '$base.fromReader(r)';
    if (base == 'Uint8List' && f.zeroCopy) {
      return 'r.readBlobAsPointer()';
    }
    return _swiftReadCall(base);
  }

  static void _swiftStructWriteStmt(CodeWriter s, BridgeField f, Set<String> enumNames, Set<String> structNames, BridgeStruct st) {
    final base = f.type.name.replaceFirst('?', '');
    if (enumNames.contains(base)) {
      s.writeln('    writer.writeInt(Int64(${f.name}.rawValue))');
    } else if (structNames.contains(base)) {
      s.writeln('    ${f.name}.writeFields(writer)');
    } else {
      if (base == 'Uint8List' && f.zeroCopy) {
        final countField = st.fields.firstWhere(
          (cf) => ['stride', 'length', 'size', 'count'].contains(cf.name),
          orElse: () => st.fields.first,
        );
        final countExpr = 'Int(${countField.name})';
        s.writeln('    if let ptr = ${f.name} {');
        s.writeln('        writer.writeBlob(Data(bytes: ptr, count: $countExpr))');
        s.writeln('    } else {');
        s.writeln('        writer.writeInt32(0)');
        s.writeln('    }');
      } else {
        s.writeln('    writer.${_swiftWriterCall(base, f.name)}');
      }
    }
  }

  static const _swiftRecordWriterReader = '''
public class NitroRecordWriter {
    public var bytes: [UInt8] = []
    public init() {}
    public func writeInt(_ v: Int64) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeInt32(_ v: Int32) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeDouble(_ v: Double) {
        var val = v.bitPattern.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeBool(_ v: Bool) {
        bytes.append(v ? 1 : 0)
    }
    public func writeString(_ v: String) {
        let utf8 = Array(v.utf8)
        writeInt32(Int32(utf8.count))
        bytes.append(contentsOf: utf8)
    }
    public func writeNullTag(_ isNull: Bool) {
        bytes.append(isNull ? 0 : 1)
    }
    public func writeBlob(_ v: Data) {
        writeInt32(Int32(v.count))
        bytes.append(contentsOf: Array(v))
    }
    public func toNative() -> UnsafeMutablePointer<UInt8>? {
        let total = 4 + bytes.count
        let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
        var length = Int32(bytes.count).littleEndian
        _ = memcpy(ptr, &length, 4)
        if bytes.count > 0 {
            _ = memcpy(ptr.advanced(by: 4), bytes, bytes.count)
        }
        return ptr
    }
    public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
        let w = NitroRecordWriter()
        w.writeInt32(Int32(items.count))
        for item in items { writeItem(w, item) }
        return w.toNative()
    }
    /// Encodes a list with a per-item byte-offset table for O(1) random access.
    /// Wire format (payload after outer 4B length prefix):
    ///   [int32 count][int64 × count offsets from payload start][item bytes...]
    /// Counterpart: Dart LazyRecordList.decode / RecordWriter.encodeIndexedList.
    public static func encodeIndexedList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
        var blobs: [[UInt8]] = []
        for item in items {
            let w = NitroRecordWriter()
            writeItem(w, item)
            blobs.append(w.bytes)
        }
        var pos = 4 + 8 * blobs.count
        var offsets: [Int64] = []
        for blob in blobs {
            offsets.append(Int64(pos))
            pos += blob.count
        }
        let w = NitroRecordWriter()
        w.writeInt32(Int32(blobs.count))
        for off in offsets { w.writeInt(off) }
        for blob in blobs { w.bytes.append(contentsOf: blob) }
        return w.toNative()
    }
}

public class NitroRecordReader {
    public let bytes: UnsafeMutablePointer<UInt8>
    public var pos: Int = 0
    public init(ptr: UnsafeMutablePointer<UInt8>) {
        self.bytes = ptr.advanced(by: 4)
    }
    public init(payload: UnsafeMutablePointer<UInt8>) {
        self.bytes = payload
    }
    public func readInt() -> Int64 {
        var v: Int64 = 0
        _ = memcpy(&v, bytes.advanced(by: pos), 8)
        pos += 8
        return Int64(littleEndian: v)
    }
    public func readInt32() -> Int32 {
        var v: Int32 = 0
        _ = memcpy(&v, bytes.advanced(by: pos), 4)
        pos += 4
        return Int32(littleEndian: v)
    }
    public func readDouble() -> Double {
        var v: UInt64 = 0
        _ = memcpy(&v, bytes.advanced(by: pos), 8)
        pos += 8
        return Double(bitPattern: UInt64(littleEndian: v))
    }
    public func readBool() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v != 0
    }
    public func readString() -> String {
        let len = Int(readInt32())
        guard len > 0 else { return "" }
        let s = String(bytes: UnsafeBufferPointer(start: bytes.advanced(by: pos), count: len), encoding: .utf8) ?? ""
        pos += len
        return s
    }
    public func readNullTag() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v == 0
    }
    public func readBlob() -> Data {
        let len = Int(readInt32())
        let data = Data(bytes: bytes.advanced(by: pos), count: len)
        pos += len
        return data
    }
    public func readBlobAsPointer() -> UnsafeMutablePointer<UInt8>? {
        let len = Int(readInt32())
        if (len == 0) { return nil }
        let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: len)
        ptr.initialize(from: bytes.advanced(by: pos), count: len)
        pos += len
        return ptr
    }
    public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
        let r = NitroRecordReader(ptr: ptr)
        let count = r.readInt32()
        var items: [T] = []
        for _ in 0..<count {
            items.append(readItem(r))
        }
        return items
    }
    /// Decodes a list encoded by Dart's RecordWriter.encodeIndexedList / encodeIndexedPrimitiveList.
    /// Wire format (payload after outer 4B length prefix):
    ///   [int32 count][int64 × count offsets from payload start][item bytes...]
    /// The offset table is skipped; items are read sequentially after it.
    public static func decodeIndexedList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
        let r = NitroRecordReader(ptr: ptr)
        let count = r.readInt32()
        r.pos += Int(count) * 8  // skip Int64 offset table
        var items: [T] = []
        for _ in 0..<count {
            items.append(readItem(r))
        }
        return items
    }
}
''';
}
