import '../bridge_spec.dart';

/// Generates binary encode/decode extension methods for every @HybridRecord
/// type declared in the spec.  The output is written into the `.g.dart` part
/// file and shares the library namespace with the `.native.dart` source.
///
/// Performance design — each type gets an extension named `${TypeName}RecordExt`
/// with four members:
///
///   • `static T fromNative(Pointer<Uint8> ptr)`
///       Top-level decoder: reads the 4-byte length prefix then the fields.
///       Used for a bare return value / property getter.
///
///   • `static T fromReader(RecordReader r)`
///       Inner decoder: reads fields from an already-opened reader.
///       Used when this record is an element inside a list.
///
///   • `void writeFields(RecordWriter w)`
///       Writes fields into an in-progress writer.
///       Used when this record is inside a list param.
///
///   • `Pointer<Uint8> toNative(Allocator alloc)`
///       Top-level encoder: opens a writer, calls writeFields, seals + copies.
///       Used for a bare param / property setter.
///
/// Wire format is identical to [RecordWriter] / [RecordReader]:
///   int    → 8-byte little-endian int64
///   double → 8-byte little-endian float64
///   bool   → 1 byte
///   String → 4-byte length + UTF-8 bytes
///   null   → 1-byte tag (0=null, 1=present) then value if present
///   list   → 4-byte count then elements
///
/// Map<String, T> types are NOT handled here — they continue to use JSON.
class RecordGenerator {
  static String generateDartExtensions(BridgeSpec spec) {
    if (spec.recordTypes.isEmpty) return '';

    final s = StringBuffer();
    s.writeln(
      '// --- @HybridRecord binary extensions (generated by Nitrogen) ---',
    );
    s.writeln();

    for (final rt in spec.recordTypes) {
      s.writeln('extension ${rt.name}RecordExt on ${rt.name} {');

      // ── static fromNative (top-level, with 4-byte length prefix) ──────
      s.writeln(
        '  static ${rt.name} fromNative(Pointer<Uint8> ptr) =>',
      );
      s.writeln('      fromReader(RecordReader.fromNative(ptr));');
      s.writeln();

      // ── static fromReader (inner, for use inside lists) ───────────────
      s.writeln(
        '  static ${rt.name} fromReader(RecordReader r) =>',
      );
      s.writeln('      ${rt.name}(');
      for (final f in rt.fields) {
        s.writeln('        ${f.name}: ${_readExpr(f)},');
      }
      s.writeln('      );');
      s.writeln();

      // ── writeFields (inner, for use inside lists) ─────────────────────
      s.writeln('  void writeFields(RecordWriter w) {');
      for (final f in rt.fields) {
        _writeFieldStmt(s, f);
      }
      s.writeln('  }');
      s.writeln();

      // ── toNative (top-level, allocates native buffer) ─────────────────
      s.writeln('  Pointer<Uint8> toNative(Allocator alloc) {');
      s.writeln('    final w = RecordWriter();');
      s.writeln('    writeFields(w);');
      s.writeln('    return w.toNative(alloc);');
      s.writeln('  }');

      s.writeln('}');
      s.writeln();
    }

    return s.toString();
  }

  // ── Read expression helpers ─────────────────────────────────────────────

  static String _readExpr(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _primitiveReadExpr(f.dartType);

      case RecordFieldKind.recordObject:
        final baseType = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          return 'r.readNullTag() ? null : ${baseType}RecordExt.fromReader(r)';
        }
        return '${baseType}RecordExt.fromReader(r)';

      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'dynamic';
        return 'List.generate(r.readInt32(), (_) => ${_primitiveReadCall(item)})';

      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        return 'List.generate(r.readInt32(), (_) => ${item}RecordExt.fromReader(r))';
    }
  }

  static String _primitiveReadExpr(String dartType) {
    final base = dartType.replaceFirst('?', '');
    final nullable = dartType.endsWith('?');
    if (nullable) {
      return 'r.readNullTag() ? null : ${_primitiveReadCall(base)}';
    }
    return _primitiveReadCall(base);
  }

  static String _primitiveReadCall(String base) {
    switch (base) {
      case 'int':
        return 'r.readInt()';
      case 'double':
        return 'r.readDouble()';
      case 'bool':
        return 'r.readBool()';
      case 'String':
        return 'r.readString()';
      default:
        return 'r.readInt()';
    }
  }

  // ── Write statement helpers ─────────────────────────────────────────────

  static void _writeFieldStmt(StringBuffer s, BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        _writePrimitiveStmt(s, f.dartType, f.name);
        break;

      case RecordFieldKind.recordObject:
        if (f.isNullable) {
          s.writeln('    w.writeNullTag(${f.name} == null);');
          s.writeln('    if (${f.name} != null) ${f.name}!.writeFields(w);');
        } else {
          s.writeln('    ${f.name}.writeFields(w);');
        }
        break;

      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'dynamic';
        final writeCall = _primitiveWriteCall(item, 'e');
        s.writeln('    w.writeInt32(${f.name}.length);');
        s.writeln('    for (final e in ${f.name}) w.$writeCall;');
        break;

      case RecordFieldKind.listRecordObject:
        s.writeln('    w.writeInt32(${f.name}.length);');
        s.writeln('    for (final e in ${f.name}) e.writeFields(w);');
        break;
    }
  }

  static void _writePrimitiveStmt(
    StringBuffer s,
    String dartType,
    String fieldName,
  ) {
    final base = dartType.replaceFirst('?', '');
    final nullable = dartType.endsWith('?');
    if (nullable) {
      s.writeln('    w.writeNullTag($fieldName == null);');
      s.writeln(
        '    if ($fieldName != null) w.${_primitiveWriteCall(base, '$fieldName!')};',
      );
    } else {
      s.writeln('    w.${_primitiveWriteCall(base, fieldName)};');
    }
  }

  static String _primitiveWriteCall(String base, String expr) {
    switch (base) {
      case 'int':
        return 'writeInt($expr)';
      case 'double':
        return 'writeDouble($expr)';
      case 'bool':
        return 'writeBool($expr)';
      case 'String':
        return 'writeString($expr)';
      default:
        return 'writeInt($expr)';
    }
  }

  // ── Native generators ───────────────────────────────────────────────────

  static String generateSwift(BridgeSpec spec) {
    if (spec.recordTypes.isEmpty) return '';

    final s = StringBuffer();
    s.writeln('// --- @HybridRecord binary extensions (generated by Nitrogen) ---');
    s.writeln();

    for (final rt in spec.recordTypes) {
      s.writeln('public struct ${rt.name} {');
      for (final f in rt.fields) {
        final opt = f.isNullable ? '?' : '';
        s.writeln('  public var ${f.name}: ${_swiftType(f)}$opt');
      }
      s.writeln();
      
      final params = rt.fields.map((f) => '${f.name}: ${_swiftType(f)}${f.isNullable ? '?' : ''}').join(', ');
      s.writeln('  public init($params) {');
      for (final f in rt.fields) {
        s.writeln('    self.${f.name} = ${f.name}');
      }
      s.writeln('  }');
      s.writeln();

      s.writeln('  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> ${rt.name} {');
      s.writeln('    return fromReader(NitroRecordReader(ptr: ptr))');
      s.writeln('  }');
      s.writeln();

      s.writeln('  public static func fromReader(_ r: NitroRecordReader) -> ${rt.name} {');
      s.writeln('    return ${rt.name}(');
      for (final f in rt.fields) {
        s.writeln('      ${f.name}: ${_swiftRead(f)},');
      }
      s.writeln('    )');
      s.writeln('  }');
      s.writeln();

      s.writeln('  public func writeFields(_ w: NitroRecordWriter) {');
      for (final f in rt.fields) {
        _swiftWriteStmt(s, f);
      }
      s.writeln('  }');
      s.writeln();

      s.writeln('  public func toNative() -> UnsafeMutablePointer<UInt8>? {');
      s.writeln('    let w = NitroRecordWriter()');
      s.writeln('    writeFields(w)');
      s.writeln('    return w.toNative()');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }

    s.writeln(_swiftRecordWriterReader);
    return s.toString();
  }

  static String _swiftType(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _swiftBase(f.dartType);
      case RecordFieldKind.recordObject:
        return f.dartType.replaceFirst('?', '');
      case RecordFieldKind.listPrimitive:
        return '[${_swiftBase(f.itemTypeName ?? 'Any')}]';
      case RecordFieldKind.listRecordObject:
        return '[${f.itemTypeName}]';
    }
  }

  static String _swiftBase(String dartType) {
    final base = dartType.replaceFirst('?', '');
    switch (base) {
      case 'int': return 'Int64';
      case 'double': return 'Double';
      case 'bool': return 'Bool';
      case 'String': return 'String';
      default: return 'Int64';
    }
  }

  static String _swiftReadCall(String base) {
    switch (base) {
      case 'int': return 'r.readInt()';
      case 'double': return 'r.readDouble()';
      case 'bool': return 'r.readBool()';
      case 'String': return 'r.readString()';
      default: return 'r.readInt()';
    }
  }

  static String _swiftRead(BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) return 'r.readNullTag() ? nil : ${_swiftReadCall(base)}';
        return _swiftReadCall(base);
      case RecordFieldKind.recordObject:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) return 'r.readNullTag() ? nil : ${base}.fromReader(r)';
        return '${base}.fromReader(r)';
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        return '(0..<r.readInt32()).map { _ in ${_swiftReadCall(item)} }';
      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName!;
        return '(0..<r.readInt32()).map { _ in ${item}.fromReader(r) }';
    }
  }

  static void _swiftWriteStmt(StringBuffer s, BridgeRecordField f) {
    switch (f.kind) {
      case RecordFieldKind.primitive:
        final base = f.dartType.replaceFirst('?', '');
        if (f.isNullable) {
          s.writeln('    w.writeNullTag(${f.name} == nil)');
          s.writeln('    if let val = ${f.name} { w.${_swiftWriterCall(base, 'val')} }');
        } else {
          s.writeln('    w.${_swiftWriterCall(base, f.name)}');
        }
        break;
      case RecordFieldKind.recordObject:
        if (f.isNullable) {
          s.writeln('    w.writeNullTag(${f.name} == nil)');
          s.writeln('    if let val = ${f.name} { val.writeFields(w) }');
        } else {
          s.writeln('    ${f.name}.writeFields(w)');
        }
        break;
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        s.writeln('    w.writeInt32(Int32(${f.name}.count))');
        s.writeln('    for e in ${f.name} { w.${_swiftWriterCall(item, 'e')} }');
        break;
      case RecordFieldKind.listRecordObject:
        s.writeln('    w.writeInt32(Int32(${f.name}.count))');
        s.writeln('    for e in ${f.name} { e.writeFields(w) }');
        break;
    }
  }

  static String _swiftWriterCall(String base, String expr) {
    switch (base) {
      case 'int': return 'writeInt($expr)';
      case 'double': return 'writeDouble($expr)';
      case 'bool': return 'writeBool($expr)';
      case 'String': return 'writeString($expr)';
      default: return 'writeInt($expr)';
    }
  }

  static const _swiftRecordWriterReader = '''
public class NitroRecordWriter {
    public var bytes: [UInt8] = []
    public init() {}
    public func writeInt(_ v: Int64) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeInt32(_ v: Int32) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeDouble(_ v: Double) {
        var val = v.bitPattern.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: \$0) }
    }
    public func writeBool(_ v: Bool) {
        bytes.append(v ? 1 : 0)
    }
    public func writeString(_ v: String) {
        let utf8 = Array(v.utf8)
        writeInt32(Int32(utf8.count))
        bytes.append(contentsOf: utf8)
    }
    public func writeNullTag(_ isNull: Bool) {
        bytes.append(isNull ? 0 : 1)
    }
    public func toNative() -> UnsafeMutablePointer<UInt8>? {
        let total = 4 + bytes.count
        let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
        var length = Int32(bytes.count).littleEndian
        withUnsafeBytes(of: &length) { 
            ptr.update(from: \$0.baseAddress!.assumingMemoryBound(to: UInt8.self), count: 4)
        }
        ptr.advanced(by: 4).update(from: bytes, count: bytes.count)
        return ptr
    }
    public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
        let w = NitroRecordWriter()
        w.writeInt32(Int32(items.count))
        for item in items { writeItem(w, item) }
        return w.toNative()
    }
}

public class NitroRecordReader {
    public let bytes: UnsafeMutablePointer<UInt8>
    public var pos: Int = 0
    public init(ptr: UnsafeMutablePointer<UInt8>) {
        self.bytes = ptr.advanced(by: 4)
    }
    public init(payload: UnsafeMutablePointer<UInt8>) {
        self.bytes = payload
    }
    public func readInt() -> Int64 {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: Int64.self)
        pos += 8
        return Int64(littleEndian: v)
    }
    public func readInt32() -> Int32 {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: Int32.self)
        pos += 4
        return Int32(littleEndian: v)
    }
    public func readDouble() -> Double {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: UInt64.self)
        pos += 8
        return Double(bitPattern: UInt64(littleEndian: v))
    }
    public func readBool() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v != 0
    }
    public func readString() -> String {
        let len = Int(readInt32())
        let s = String(bytesNoCopy: UnsafeMutableRawPointer(bytes.advanced(by: pos)), length: len, encoding: .utf8, freeWhenDone: false) ?? ""
        pos += len
        return s
    }
    public func readNullTag() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v == 0
    }
    public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
        let r = NitroRecordReader(ptr: ptr)
        let count = r.readInt32()
        var items: [T] = []
        for _ in 0..<count {
            items.append(readItem(r))
        }
        return items
    }
}
''';

}
