import '../bridge_spec.dart';

/// Field names that are treated as the byte-length of a zero-copy Uint8List sibling.
const _kLengthFieldNames = {
  'length',
  'size',
  'stride',
  'bytelength',
  'bytelen',
  'len',
};

/// Generates Dart extension helpers for HybridStructs.
/// The struct class itself MUST already be declared in the .native.dart spec file.
/// We only emit the FFI conversion extension here (in the generated part).
class StructGenerator {
  /// Called by DartFfiGenerator. Emits FFI Struct representations of HybridStructs.
  static String generateDartExtensions(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final s = StringBuffer();
    s.writeln('// --- Struct FFI representations (generated by Nitrogen) ---');
    s.writeln();
    for (final st in spec.structs) {
      if (st.packed) {
        s.writeln('@Packed(1)');
      }
      s.writeln('final class ${st.name}Ffi extends Struct {');
      for (final f in st.fields) {
        final ffiType = _dartTypeToFfi(f.type.name, enumNames);
        final annotationType = _dartTypeToFfiAnnotation(f.type.name, enumNames);
        if (annotationType.isNotEmpty) {
          s.writeln('  @$annotationType()');
        }
        s.writeln('  external $ffiType ${f.name};');
      }
      s.writeln('}');
      s.writeln();
      s.writeln('extension ${st.name}FfiExt on ${st.name}Ffi {');
      s.writeln('  ${st.name} toDart() {');
      s.writeln('    return ${st.name}(');
      for (final f in st.fields) {
        final typeName = f.type.name.replaceFirst('?', '');
        String value;
        if (f.type.isTypedData) {
          final lenField = st.fields
              .where(
                (sf) => sf.type.name == 'int' && _kLengthFieldNames.contains(sf.name.toLowerCase()),
              )
              .map((sf) => sf.name)
              .firstOrNull;
          value = '${f.name}.asTypedList(${lenField ?? '0'})';
        } else if (f.type.name == 'bool') {
          value = '${f.name} != 0';
        } else if (f.type.name == 'String') {
          value = '${f.name}.toDartString()';
        } else if (enumNames.contains(typeName)) {
          value = '${f.name}.to$typeName()';
        } else {
          value = f.name;
        }
        s.writeln('      ${f.name}: $value,');
      }
      s.writeln('    );');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
      s.writeln('extension ${st.name}Ext on ${st.name} {');
      s.writeln('  Pointer<${st.name}Ffi> toNative(Arena arena) {');
      s.writeln('    final ptr = arena<${st.name}Ffi>();');
      for (final f in st.fields) {
        final typeName = f.type.name.replaceFirst('?', '');
        if (f.type.isTypedData) {
          s.writeln('    ptr.ref.${f.name} = ${f.name}.toPointer(arena);');
        } else if (f.type.name == 'bool') {
          s.writeln('    ptr.ref.${f.name} = ${f.name} ? 1 : 0;');
        } else if (f.type.name == 'String') {
          s.writeln(
            '    ptr.ref.${f.name} = ${f.name}.toNativeUtf8(allocator: arena);',
          );
        } else if (enumNames.contains(typeName)) {
          s.writeln('    ptr.ref.${f.name} = ${f.name}.nativeValue;');
        } else {
          s.writeln('    ptr.ref.${f.name} = ${f.name};');
        }
      }
      s.writeln('    return ptr;');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates a zero-copy [${name}Proxy] class for every HybridStruct.
  ///
  /// The proxy holds a `Pointer<${name}Ffi>` and exposes lazy getters that read
  /// each field directly from native memory without copying.  A [NativeFinalizer]
  /// automatically frees the native buffer when the proxy is GC'd, so the caller
  /// must NOT call `malloc.free` after passing the pointer to the constructor.
  ///
  /// Use [toDartAndRelease] if you need a fully-owned Dart value.
  static String generateDartProxies(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final s = StringBuffer();
    s.writeln('// --- Struct Native Proxies (zero-copy, lazy field access) ---');
    s.writeln();
    for (final st in spec.structs) {
      s.writeln('/// Zero-copy proxy for [${st.name}].');
      s.writeln('/// Fields are read directly from the native heap on access.');
      s.writeln('/// The underlying [Pointer<${st.name}Ffi>] is freed when this object is GC\'d.');
      s.writeln('final class ${st.name}Proxy {');
      s.writeln('  final Pointer<${st.name}Ffi> _native;');
      s.writeln('  static final _finalizer = NativeFinalizer(malloc.nativeFree);');
      s.writeln();
      s.writeln('  /// Takes ownership of [native]; do NOT call [malloc.free] separately.');
      s.writeln('  ${st.name}Proxy(this._native) {');
      s.writeln('    _finalizer.attach(this, _native.cast(), detach: this);');
      s.writeln('  }');
      s.writeln();

      // Lazy field getters
      for (final f in st.fields) {
        final typeName = f.type.name.replaceFirst('?', '');
        final dartFieldType = f.type.name; // e.g. 'int', 'double', 'bool', 'String'
        String readExpr;
        if (f.type.isTypedData) {
          final lenField = st.fields
              .where(
                (sf) =>
                    sf.type.name == 'int' &&
                    _kLengthFieldNames.contains(sf.name.toLowerCase()),
              )
              .map((sf) => sf.name)
              .firstOrNull;
          readExpr = '_native.ref.${f.name}.asTypedList(${lenField != null ? '_native.ref.$lenField' : '0'})';
        } else if (f.type.name == 'bool') {
          readExpr = '_native.ref.${f.name} != 0';
        } else if (f.type.name == 'String') {
          readExpr = '_native.ref.${f.name}.toDartString()';
        } else if (enumNames.contains(typeName)) {
          readExpr = '_native.ref.${f.name}.to$typeName()';
        } else {
          readExpr = '_native.ref.${f.name}';
        }
        s.writeln('  $dartFieldType get ${f.name} => $readExpr;');
      }
      s.writeln();

      // toDartAndRelease — eager copy + detach finalizer
      s.writeln('  /// Eagerly copies all fields to a [${st.name}] value and releases');
      s.writeln('  /// the native buffer.  Must not be called more than once.');
      s.writeln('  ${st.name} toDartAndRelease() {');
      s.writeln('    final v = _native.ref.toDart();');
      s.writeln('    _finalizer.detach(this);');
      s.writeln('    malloc.free(_native);');
      s.writeln('    return v;');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates C structs for the header file.
  ///
  /// Each struct is wrapped in a `#ifndef NITRO_STRUCT_<NAME>_DEFINED` guard so
  /// that the same struct type can appear in multiple generated bridge headers
  /// (e.g. a shared `BenchmarkPoint` in both `benchmark.bridge.g.h` and
  /// `benchmark_cpp.bridge.g.h`) without causing "typedef redefinition" errors
  /// when both headers are compiled into the same translation unit.
  static String generateCStructs(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      final guard = 'NITRO_STRUCT_${st.name.toUpperCase()}_DEFINED';
      s.writeln('#ifndef $guard');
      s.writeln('#define $guard');
      if (st.packed) s.writeln('#pragma pack(push, 1)');
      s.writeln('typedef struct {');
      for (final f in st.fields) {
        final cType = _dartTypeToCType(f.type.name, enumNames);
        s.writeln('  $cType ${f.name}; ${f.zeroCopy ? "/* zero-copy */" : ""}');
      }
      s.writeln('} ${st.name};');
      if (st.packed) s.writeln('#pragma pack(pop)');
      s.writeln('#endif // $guard');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Kotlin @Keep data classes for structs.
  static String generateKotlin(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      s.writeln('@Keep');
      final params = st.fields
          .map(
            (f) => 'val ${f.name}: ${_dartTypeToKotlin(f.type.name, f.zeroCopy, enumNames)}',
          )
          .join(', ');
      s.writeln('data class ${st.name}($params)');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Swift structs.
  static String generateSwift(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final enumNames = spec.enums.map((e) => e.name).toSet();
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      s.writeln('public struct ${st.name} {');
      for (final f in st.fields) {
        final swiftType = _dartTypeToSwift(f.type.name, f.zeroCopy, enumNames);
        s.writeln('  public var ${f.name}: $swiftType');
      }
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  static String _dartTypeToCType(String t, [Set<String> enumNames = const {}]) {
    final base = t.replaceFirst('?', '');
    if (enumNames.contains(base)) return 'int32_t';
    switch (base) {
      case 'int':
        return 'int64_t';
      case 'double':
        return 'double';
      case 'bool':
        return 'int8_t';
      case 'String':
        return 'const char*';
      case 'Uint8List':
        return 'uint8_t*';
      case 'Int8List':
        return 'int8_t*';
      case 'Int16List':
        return 'int16_t*';
      case 'Int32List':
        return 'int32_t*';
      case 'Uint16List':
        return 'uint16_t*';
      case 'Uint32List':
        return 'uint32_t*';
      case 'Float32List':
        return 'float*';
      case 'Float64List':
        return 'double*';
      case 'Int64List':
        return 'int64_t*';
      case 'Uint64List':
        return 'uint64_t*';
      default:
        return 'void*';
    }
  }

  static String _dartTypeToKotlin(String t, [bool isZeroCopy = false, Set<String> enumNames = const {}]) {
    final base = t.replaceFirst('?', '');
    // Enum fields are stored as Long in Kotlin data classes (matches JNI Long
    // bridging used for enum function params/returns).
    if (enumNames.contains(base)) return 'Long';
    switch (base) {
      case 'int':
        return 'Long';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Boolean';
      case 'String':
        return 'String';
      case 'Uint8List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'ByteArray';
      case 'Int8List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'ByteArray';
      case 'Int16List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'ShortArray';
      case 'Int32List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'IntArray';
      case 'Uint16List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'ShortArray';
      case 'Uint32List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'IntArray';
      case 'Float32List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'FloatArray';
      case 'Float64List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'DoubleArray';
      case 'Int64List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'LongArray';
      case 'Uint64List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'LongArray';
      default:
        return 'Any?';
    }
  }

  static String _dartTypeToSwift(String t, [bool isZeroCopy = false, Set<String> enumNames = const {}]) {
    final base = t.replaceFirst('?', '');
    if (enumNames.contains(base)) return base;
    switch (base) {
      case 'int':
        return 'Int64';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Bool';
      case 'String':
        return 'String';
      case 'Uint8List':
      case 'Int8List':
        return isZeroCopy ? 'UnsafeMutablePointer<UInt8>?' : 'Data';
      case 'Int16List':
      case 'Uint16List':
        return isZeroCopy ? 'UnsafeMutablePointer<Int16>?' : '[Int16]';
      case 'Int32List':
      case 'Uint32List':
        return isZeroCopy ? 'UnsafeMutablePointer<Int32>?' : '[Int32]';
      case 'Float32List':
        return isZeroCopy ? 'UnsafeMutablePointer<Float>?' : '[Float]';
      case 'Float64List':
        return isZeroCopy ? 'UnsafeMutablePointer<Double>?' : '[Double]';
      case 'Int64List':
      case 'Uint64List':
        return isZeroCopy ? 'UnsafeMutablePointer<Int64>?' : '[Int64]';
      default:
        return 'Any?';
    }
  }

  /// Returns the Dart field type to use inside a dart:ffi Struct declaration.
  /// dart:ffi rules: int fields → `int`, double fields → `double`, pointers stay.
  static String _dartTypeToFfi(String t, [Set<String> enumNames = const {}]) {
    final base = t.replaceFirst('?', '');
    if (enumNames.contains(base)) return 'int'; // stored as Int32 in C enum
    switch (base) {
      case 'int':
        return 'int';
      case 'double':
        return 'double';
      case 'bool':
        return 'int'; // stored as Int8 in C; use int in Dart
      case 'String':
        return 'Pointer<Utf8>';
      case 'Uint8List':
        return 'Pointer<Uint8>';
      case 'Int8List':
        return 'Pointer<Int8>';
      case 'Int16List':
        return 'Pointer<Int16>';
      case 'Int32List':
        return 'Pointer<Int32>';
      case 'Uint16List':
        return 'Pointer<Uint16>';
      case 'Uint32List':
        return 'Pointer<Uint32>';
      case 'Float32List':
        return 'Pointer<Float>';
      case 'Float64List':
        return 'Pointer<Double>';
      case 'Int64List':
        return 'Pointer<Int64>';
      case 'Uint64List':
        return 'Pointer<Uint64>';
      default:
        return 'Pointer<Void>';
    }
  }

  /// Returns the @XxxSize() annotation class name for scalar numeric fields.
  /// Pointer fields need no annotation; returns '' for them.
  static String _dartTypeToFfiAnnotation(String t, [Set<String> enumNames = const {}]) {
    final base = t.replaceFirst('?', '');
    if (enumNames.contains(base)) return 'Int32'; // C enum is int32-sized
    switch (base) {
      case 'int':
        return 'Int64';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Int8';
      default:
        return ''; // Pointer<X> — no size annotation needed
    }
  }
}
