import '../bridge_spec.dart';

/// Field names that are treated as the byte-length of a zero-copy Uint8List sibling.
const _kLengthFieldNames = {
  'length',
  'size',
  'stride',
  'bytelength',
  'bytelen',
  'len',
};

/// Generates Dart extension helpers for HybridStructs.
/// The struct class itself MUST already be declared in the .native.dart spec file.
/// We only emit the FFI conversion extension here (in the generated part).
class StructGenerator {
  /// Called by DartFfiGenerator. Emits FFI Struct representations of HybridStructs.
  static String generateDartExtensions(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Struct FFI representations (generated by Nitrogen) ---');
    s.writeln();
    for (final st in spec.structs) {
      if (st.packed) {
        s.writeln('@Packed(1)');
      }
      s.writeln('final class ${st.name}Ffi extends Struct {');
      for (final f in st.fields) {
        final ffiType = _dartTypeToFfi(f.type.name);
        final annotationType = _dartTypeToFfiAnnotation(f.type.name);
        if (annotationType.isNotEmpty) {
          s.writeln('  @$annotationType()');
        }
        s.writeln('  external $ffiType ${f.name};');
      }
      s.writeln('}');
      s.writeln();
      s.writeln('extension ${st.name}FfiExt on ${st.name}Ffi {');
      s.writeln('  ${st.name} toDart() {');
      s.writeln('    return ${st.name}(');
      for (final f in st.fields) {
        String value;
        if (f.type.isTypedData && f.zeroCopy) {
          final lenField = st.fields
              .where(
                (sf) =>
                    sf.type.name == 'int' &&
                    _kLengthFieldNames.contains(sf.name.toLowerCase()),
              )
              .map((sf) => sf.name)
              .firstOrNull;
          value = '${f.name}.asTypedList(${lenField ?? '0'})';
        } else if (f.type.name == 'bool') {
          value = '${f.name} != 0';
        } else if (f.type.name == 'String') {
          value = '${f.name}.toDartString()';
        } else {
          value = f.name;
        }
        s.writeln('      ${f.name}: $value,');
      }
      s.writeln('    );');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
      s.writeln('extension ${st.name}Ext on ${st.name} {');
      s.writeln('  Pointer<${st.name}Ffi> toNative(Arena arena) {');
      s.writeln('    final ptr = arena<${st.name}Ffi>();');
      for (final f in st.fields) {
        if (f.type.isTypedData && f.zeroCopy) {
          s.writeln('    ptr.ref.${f.name} = ${f.name}.toPointer(arena);');
        } else if (f.type.name == 'bool') {
          s.writeln('    ptr.ref.${f.name} = ${f.name} ? 1 : 0;');
        } else if (f.type.name == 'String') {
          s.writeln(
            '    ptr.ref.${f.name} = ${f.name}.toNativeUtf8(allocator: arena);',
          );
        } else {
          s.writeln('    ptr.ref.${f.name} = ${f.name};');
        }
      }
      s.writeln('    return ptr;');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates C structs for the header file.
  static String generateCStructs(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      if (st.packed) s.writeln('#pragma pack(push, 1)');
      s.writeln('typedef struct {');
      for (final f in st.fields) {
        final cType = _dartTypeToCType(f.type.name);
        s.writeln('  $cType ${f.name}; ${f.zeroCopy ? "/* zero-copy */" : ""}');
      }
      s.writeln('} ${st.name};');
      if (st.packed) s.writeln('#pragma pack(pop)');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Kotlin @Keep data classes for structs.
  static String generateKotlin(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      s.writeln('@Keep');
      final params = st.fields
          .map(
            (f) =>
                'val ${f.name}: ${_dartTypeToKotlin(f.type.name, f.zeroCopy)}',
          )
          .join(', ');
      s.writeln('data class ${st.name}($params)');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Swift structs.
  static String generateSwift(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      s.writeln('public struct ${st.name} {');
      for (final f in st.fields) {
        final swiftType = _dartTypeToSwift(f.type.name, f.zeroCopy);
        s.writeln('  public var ${f.name}: $swiftType');
      }
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  static String _dartTypeToCType(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'int64_t';
      case 'double':
        return 'double';
      case 'bool':
        return 'int8_t';
      case 'String':
        return 'const char*';
      case 'Uint8List':
        return 'uint8_t*';
      case 'Int8List':
        return 'int8_t*';
      case 'Int16List':
        return 'int16_t*';
      case 'Int32List':
        return 'int32_t*';
      case 'Uint16List':
        return 'uint16_t*';
      case 'Uint32List':
        return 'uint32_t*';
      case 'Float32List':
        return 'float*';
      case 'Float64List':
        return 'double*';
      case 'Int64List':
        return 'int64_t*';
      case 'Uint64List':
        return 'uint64_t*';
      default:
        return 'void*';
    }
  }

  static String _dartTypeToKotlin(String t, [bool isZeroCopy = false]) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'Long';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Boolean';
      case 'String':
        return 'String';
      case 'Uint8List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'ByteArray';
      case 'Int8List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'ByteArray';
      case 'Int16List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'ShortArray';
      case 'Int32List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'IntArray';
      case 'Uint16List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'ShortArray';
      case 'Uint32List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'IntArray';
      case 'Float32List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'FloatArray';
      case 'Float64List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'DoubleArray';
      case 'Int64List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'LongArray';
      case 'Uint64List':
        return isZeroCopy ? 'java.nio.ByteBuffer' : 'LongArray';
      default:
        return 'Any?';
    }
  }

  static String _dartTypeToSwift(String t, [bool isZeroCopy = false]) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'Int64';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Bool';
      case 'String':
        return 'String';
      case 'Uint8List':
        return isZeroCopy ? 'UnsafeMutablePointer<UInt8>?' : 'Data';
      case 'Int8List':
        return isZeroCopy ? 'UnsafeMutablePointer<Int8>?' : 'Data';
      case 'Int16List':
        return isZeroCopy ? 'UnsafeMutablePointer<Int16>?' : 'Data';
      case 'Int32List':
        return isZeroCopy ? 'UnsafeMutablePointer<Int32>?' : 'Data';
      case 'Uint16List':
        return isZeroCopy ? 'UnsafeMutablePointer<UInt16>?' : 'Data';
      case 'Uint32List':
        return isZeroCopy ? 'UnsafeMutablePointer<UInt32>?' : 'Data';
      case 'Float32List':
        return isZeroCopy ? 'UnsafeMutablePointer<Float>?' : 'Data';
      case 'Float64List':
        return isZeroCopy ? 'UnsafeMutablePointer<Double>?' : 'Data';
      case 'Int64List':
        return isZeroCopy ? 'UnsafeMutablePointer<Int64>?' : 'Data';
      case 'Uint64List':
        return isZeroCopy ? 'UnsafeMutablePointer<UInt64>?' : 'Data';
      default:
        return 'Any?';
    }
  }

  /// Returns the Dart field type to use inside a dart:ffi Struct declaration.
  /// dart:ffi rules: int fields → `int`, double fields → `double`, pointers stay.
  static String _dartTypeToFfi(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'int';
      case 'double':
        return 'double';
      case 'bool':
        return 'int'; // stored as Int8 in C; use int in Dart
      case 'String':
        return 'Pointer<Utf8>';
      case 'Uint8List':
        return 'Pointer<Uint8>';
      case 'Int8List':
        return 'Pointer<Int8>';
      case 'Int16List':
        return 'Pointer<Int16>';
      case 'Int32List':
        return 'Pointer<Int32>';
      case 'Uint16List':
        return 'Pointer<Uint16>';
      case 'Uint32List':
        return 'Pointer<Uint32>';
      case 'Float32List':
        return 'Pointer<Float>';
      case 'Float64List':
        return 'Pointer<Double>';
      case 'Int64List':
        return 'Pointer<Int64>';
      case 'Uint64List':
        return 'Pointer<Uint64>';
      default:
        return 'Pointer<Void>';
    }
  }

  /// Returns the @XxxSize() annotation class name for scalar numeric fields.
  /// Pointer fields need no annotation; returns '' for them.
  static String _dartTypeToFfiAnnotation(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int':
        return 'Int64';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Int8';
      default:
        return ''; // Pointer<X> — no size annotation needed
    }
  }
}
