import '../bridge_spec.dart';
import 'struct_generator.dart';
import 'enum_generator.dart';
import 'record_generator.dart';

class SwiftGenerator {
  static String generate(BridgeSpec spec) {
    final s = StringBuffer();
    s.writeln('// Generated by Nitrogen Modules. Do not edit.');
    s.writeln('// Generated from: ${spec.sourceUri.split('/').last}');
    s.writeln('import Foundation');
    s.writeln('import Combine');
    s.writeln();

    final swiftEnums = EnumGenerator.generateSwift(spec);
    if (swiftEnums.isNotEmpty) s.write(swiftEnums);

    final swiftStructs = StructGenerator.generateSwift(spec);
    if (swiftStructs.isNotEmpty) s.write(swiftStructs);

    final swiftRecords = RecordGenerator.generateSwift(spec);
    if (swiftRecords.isNotEmpty) s.write(swiftRecords);

    // ── Protocol ──────────────────────────────────────────────────────────
    s.writeln('/**');
    s.writeln(' * Protocol for the ${spec.dartClassName} module.');
    s.writeln(' * Conform to this in your Swift source code.');
    s.writeln(' */');
    s.writeln(
      'public protocol Hybrid${spec.dartClassName}Protocol: AnyObject {',
    );

    for (final func in spec.functions) {
      final retType = _toSwiftType(spec, func.returnType.name);
      final params = func.params.map((p) => '${p.name}: ${_toSwiftType(spec, p.type.name)}').join(', ');
      if (func.isAsync) {
        s.writeln(
          '    func ${func.dartName}($params) async throws -> $retType',
        );
      } else {
        s.writeln('    func ${func.dartName}($params) -> $retType');
      }
    }

    for (final prop in spec.properties) {
      final swiftType = _toSwiftType(spec, prop.type.name);
      if (prop.hasSetter) {
        s.writeln('    var ${prop.dartName}: $swiftType { get set }');
      } else {
        s.writeln('    var ${prop.dartName}: $swiftType { get }');
      }
    }

    for (final stream in spec.streams) {
      final itemType = _toSwiftType(spec, stream.itemType.name);
      s.writeln(
        '    var ${stream.dartName}: AnyPublisher<$itemType, Never> { get }',
      );
    }

    s.writeln('}');
    s.writeln();

    // ── Registry — pure Swift, no @objc / NSObject needed ─────────────────
    s.writeln('public class ${spec.dartClassName}Registry {');
    s.writeln(
      '    public static var impl: Hybrid${spec.dartClassName}Protocol?',
    );
    s.writeln();
    s.writeln(
      '    public static func register(_ impl: Hybrid${spec.dartClassName}Protocol) {',
    );
    s.writeln('        ${spec.dartClassName}Registry.impl = impl');
    s.writeln('    }');

    for (final stream in spec.streams) {
      s.writeln();
      s.writeln(
        '    // Stream: ${stream.dartName} cancellables keyed by dartPort',
      );
      s.writeln(
        '    public static var _${stream.dartName}Cancellables = [Int64: AnyCancellable]()',
      );
    }

    s.writeln('}');
    s.writeln();

    // ── @_cdecl C bridge stubs ─────────────────────────────────────────────
    // These are exported as plain C symbols and called by the generated .cpp
    // shim via `extern "C"` declarations. @objc is NOT used because Swift
    // structs and Swift-only protocols cannot cross the ObjC boundary.
    s.writeln(
      '// MARK: - C bridge stubs — exported as C symbols called by the generated .cpp shim',
    );
    s.writeln();

    for (final func in spec.functions) {
      final cRetType = _toCDeclReturnType(spec, func);
      // @_cdecl params must use C-ABI-compatible types.
      // Typed list params get an extra `_ <name>_length: Int64` param.
      final params = func.params
          .expand((p) {
            final t = _toCDeclParamType(spec, p.type.name);
            if (p.type.isTypedData) {
              return ['_ ${p.name}: $t', '_ ${p.name}_length: Int64'];
            }
            return ['_ ${p.name}: $t'];
          })
          .join(', ');
      // String params arrive as UnsafePointer<CChar>? — convert to Swift String.
      final stringParams = func.params.where((p) => p.type.name == 'String').toList();
      // Typed list params arrive as raw C pointer + length — convert to Swift Array.
      final typedListParams = func.params.where((p) => p.type.isTypedData).toList();
      // Pass the converted local variables for String/typed-list params.
      final callArgs = func.params
          .map((p) {
            if (p.type.name == 'String') return '${p.name}: ${p.name}Str';
            if (p.type.name == 'bool') return '${p.name}: ${p.name} != 0';
            if (p.type.isTypedData) return '${p.name}: ${p.name}Arr';
            if (spec.structs.any((st) => st.name == p.type.name.replaceFirst('?', ''))) {
              final structName = p.type.name.replaceFirst('?', '');
              return '${p.name}: ${p.name}!.assumingMemoryBound(to: $structName.self).pointee';
            }
            return '${p.name}: ${p.name}';
          })
          .join(', ');
      final isStruct = spec.structs.any(
        (st) => st.name == func.returnType.name,
      );
      final isRecord = spec.recordTypes.any(
        (rt) => rt.name == func.returnType.name,
      );
      final isRecordList = func.returnType.name.startsWith('List<');
      final isBool = func.returnType.name == 'bool';
      final isVoid = func.returnType.name == 'void';
      final isString = func.returnType.name == 'String';
      final isEnumRet = spec.enums.any(
        (en) => en.name == func.returnType.name.replaceFirst('?', ''),
      );

      s.writeln('@_cdecl("_call_${func.dartName}")');
      s.writeln('public func _call_${func.dartName}($params) -> $cRetType {');

      // Emit UnsafePointer<CChar>? → Swift String conversions for each String param.
      for (final p in stringParams) {
        s.writeln(
          '    let ${p.name}Str = ${p.name}.map { String(cString: \$0) } ?? ""',
        );
      }
      // Emit UnsafeMutablePointer<T>? + length → Swift Array for each typed-list param.
      for (final p in typedListParams) {
        s.writeln(
          '    let ${p.name}Arr = ${p.name}.map { Array(UnsafeBufferPointer(start: \$0, count: Int(${p.name}_length))) } ?? []',
        );
      }

      if (func.isAsync) {
        // Async: block the calling thread with a semaphore until the Task
        // completes. Safe because callAsync() always runs on a background isolate.
        if (isStruct) {
          s.writeln(
            '    guard let impl = ${spec.dartClassName}Registry.impl else { return nil }',
          );
          s.writeln('    let sema = DispatchSemaphore(value: 0)');
          s.writeln('    var result: ${func.returnType.name}? = nil');
          s.writeln('    Task.detached {');
          s.writeln(
            '        result = try? await impl.${func.dartName}($callArgs)',
          );
          s.writeln('        sema.signal()');
          s.writeln('    }');
          s.writeln('    sema.wait()');
          s.writeln('    guard let r = result else { return nil }');
          s.writeln(
            '    let ptr = UnsafeMutablePointer<${func.returnType.name}>.allocate(capacity: 1)',
          );
          s.writeln('    ptr.initialize(to: r)');
          s.writeln('    return UnsafeMutableRawPointer(ptr)');
        } else if (isVoid) {
          s.writeln(
            '    guard let impl = ${spec.dartClassName}Registry.impl else { return }',
          );
          s.writeln('    let sema = DispatchSemaphore(value: 0)');
          s.writeln('    Task.detached {');
          s.writeln('        try? await impl.${func.dartName}($callArgs)');
          s.writeln('        sema.signal()');
          s.writeln('    }');
          s.writeln('    sema.wait()');
        } else if (isString) {
          // String result must be malloc'd (strdup) so Dart's free() works.
          s.writeln(
            '    guard let impl = ${spec.dartClassName}Registry.impl else { return strdup("") }',
          );
          s.writeln('    let sema = DispatchSemaphore(value: 0)');
          s.writeln('    var result = ""');
          s.writeln('    Task.detached {');
          s.writeln(
            '        result = (try? await impl.${func.dartName}($callArgs)) ?? ""',
          );
          s.writeln('        sema.signal()');
          s.writeln('    }');
          s.writeln('    sema.wait()');
          s.writeln('    return strdup(result)');
        } else if (isRecord) {
          s.writeln('    guard let impl = ${spec.dartClassName}Registry.impl else { return nil }');
          s.writeln('    let sema = DispatchSemaphore(value: 0)');
          s.writeln('    var result: ${func.returnType.name}? = nil');
          s.writeln('    Task.detached {');
          s.writeln('        result = try? await impl.${func.dartName}($callArgs)');
          s.writeln('        sema.signal()');
          s.writeln('    }');
          s.writeln('    sema.wait()');
          s.writeln('    return result?.toNative()');
        } else if (isRecordList) {
          s.writeln('    guard let impl = ${spec.dartClassName}Registry.impl else { return nil }');
          s.writeln('    let sema = DispatchSemaphore(value: 0)');
          s.writeln('    var result: ${_toSwiftType(spec, func.returnType.name)}? = nil');
          s.writeln('    Task.detached {');
          s.writeln('        result = try? await impl.${func.dartName}($callArgs)');
          s.writeln('        sema.signal()');
          s.writeln('    }');
          s.writeln('    sema.wait()');
          s.writeln('    guard let r = result else { return nil }');

          final itemType = func.returnType.name.substring(5, func.returnType.name.length - 1);
          final isPrim = ['int', 'double', 'bool', 'String'].contains(itemType.replaceAll('?', ''));
          if (isPrim) {
            final base = itemType.replaceAll('?', '');
            String writeCall = 'writeInt(e)';
            if (base == 'int') writeCall = 'writeInt(e)';
            if (base == 'double') writeCall = 'writeDouble(e)';
            if (base == 'bool') writeCall = 'writeBool(e)';
            if (base == 'String') writeCall = 'writeString(e)';
            s.writeln('    return NitroRecordWriter.encodeList(r) { w, e in w.$writeCall }');
          } else {
            s.writeln('    return NitroRecordWriter.encodeList(r) { w, e in e.writeFields(w) }');
          }
        } else {
          final swiftRetType = _toSwiftType(spec, func.returnType.name);
          final defaultVal = _defaultCDeclValue(spec, func.returnType.name);
          s.writeln(
            '    guard let impl = ${spec.dartClassName}Registry.impl else { return $defaultVal }',
          );
          s.writeln('    let sema = DispatchSemaphore(value: 0)');
          s.writeln('    var result: $swiftRetType? = nil');
          s.writeln('    Task.detached {');
          s.writeln(
            '        result = try? await impl.${func.dartName}($callArgs)',
          );
          s.writeln('        sema.signal()');
          s.writeln('    }');
          s.writeln('    sema.wait()');
          if (isEnumRet) {
            s.writeln('    return result?.rawValue ?? $defaultVal');
          } else {
            s.writeln('    return result ?? $defaultVal');
          }
        }
      } else if (isVoid) {
        s.writeln(
          '    ${spec.dartClassName}Registry.impl?.${func.dartName}($callArgs)',
        );
      } else if (isBool) {
        s.writeln(
          '    return (${spec.dartClassName}Registry.impl?.${func.dartName}($callArgs) ?? false) ? 1 : 0',
        );
      } else if (isStruct) {
        s.writeln(
          '    guard let result = ${spec.dartClassName}Registry.impl?.${func.dartName}($callArgs) else { return nil }',
        );
        s.writeln(
          '    let ptr = UnsafeMutablePointer<${func.returnType.name}>.allocate(capacity: 1)',
        );
        s.writeln('    ptr.initialize(to: result)');
        s.writeln('    return UnsafeMutableRawPointer(ptr)');
      } else if (isString) {
        // String result must be malloc'd (strdup) so Dart's free() works.
        s.writeln(
          '    return strdup(${spec.dartClassName}Registry.impl?.${func.dartName}($callArgs) ?? "")',
        );
      } else if (isRecord) {
        s.writeln('    return ${spec.dartClassName}Registry.impl?.${func.dartName}($callArgs)?.toNative()');
      } else if (isRecordList) {
        s.writeln('    guard let r = ${spec.dartClassName}Registry.impl?.${func.dartName}($callArgs) else { return nil }');
        final itemType = func.returnType.name.substring(5, func.returnType.name.length - 1);
        final isPrim = ['int', 'double', 'bool', 'String'].contains(itemType.replaceAll('?', ''));
        if (isPrim) {
          final base = itemType.replaceAll('?', '');
          String writeCall = 'writeInt(e)';
          if (base == 'int') writeCall = 'writeInt(e)';
          if (base == 'double') writeCall = 'writeDouble(e)';
          if (base == 'bool') writeCall = 'writeBool(e)';
          if (base == 'String') writeCall = 'writeString(e)';
          s.writeln('    return NitroRecordWriter.encodeList(r) { w, e in w.$writeCall }');
        } else {
          s.writeln('    return NitroRecordWriter.encodeList(r) { w, e in e.writeFields(w) }');
        }
      } else {
        final defaultVal = _defaultCDeclValue(spec, func.returnType.name);

        s.writeln(
          '    guard let impl = ${spec.dartClassName}Registry.impl else { return $defaultVal }',
        );
        if (isEnumRet) {
          s.writeln('    return impl.${func.dartName}($callArgs).rawValue');
        } else {
          s.writeln('    return impl.${func.dartName}($callArgs)');
        }
      }

      s.writeln('}');
      s.writeln();
    }

    for (final prop in spec.properties) {
      final swiftType = _toSwiftType(spec, prop.type.name);
      final isBool = prop.type.name == 'bool';
      final isString = prop.type.name == 'String';
      if (prop.hasGetter) {
        final isEnumProp = spec.enums.any((en) => en.name == prop.type.name.replaceFirst('?', ''));
        final getRetType = isString
            ? 'UnsafeMutablePointer<CChar>?'
            : isBool
            ? 'Int8'
            : isEnumProp
            ? 'Int64'
            : swiftType;
        s.writeln('@_cdecl("_call_get_${prop.dartName}")');
        s.writeln('public func _call_get_${prop.dartName}() -> $getRetType {');
        if (isString) {
          s.writeln(
            '    return strdup(${spec.dartClassName}Registry.impl?.${prop.dartName} ?? "")',
          );
        } else if (isEnumProp) {
          s.writeln(
            '    return ${spec.dartClassName}Registry.impl?.${prop.dartName}.rawValue ?? ${_defaultCDeclValue(spec, prop.type.name)}',
          );
        } else {
          s.writeln(
            '    return ${spec.dartClassName}Registry.impl?.${prop.dartName} ?? ${_defaultCDeclValue(spec, prop.type.name)}',
          );
        }
        s.writeln('}');
        s.writeln();
      }
      if (prop.hasSetter) {
        final isEnumProp = spec.enums.any((en) => en.name == prop.type.name.replaceFirst('?', ''));
        final isStructProp = spec.structs.any((st) => st.name == prop.type.name.replaceFirst('?', ''));
        final setParamType = isBool
            ? 'Int8'
            : isString
            ? 'UnsafePointer<CChar>?'
            : isEnumProp
            ? 'Int64'
            : isStructProp
            ? 'UnsafeRawPointer?'
            : swiftType;
        s.writeln('@_cdecl("_call_set_${prop.dartName}")');
        s.writeln(
          'public func _call_set_${prop.dartName}(_ value: $setParamType) {',
        );
        if (isBool) {
          s.writeln(
            '    ${spec.dartClassName}Registry.impl?.${prop.dartName} = value != 0',
          );
        } else if (isString) {
          s.writeln(
            '    ${spec.dartClassName}Registry.impl?.${prop.dartName} = value.map { String(cString: \$0) } ?? ""',
          );
        } else if (isEnumProp) {
          s.writeln(
            '    if let actualValue = ${prop.type.name.replaceFirst('?', '')}(rawValue: value) {',
          );
          s.writeln('        ${spec.dartClassName}Registry.impl?.${prop.dartName} = actualValue');
          s.writeln('    }');
        } else if (isStructProp) {
          s.writeln(
            '    if let v = value {',
          );
          s.writeln('        ${spec.dartClassName}Registry.impl?.${prop.dartName} = v.assumingMemoryBound(to: ${prop.type.name}.self).pointee');
          s.writeln('    }');
        } else {
          s.writeln(
            '    ${spec.dartClassName}Registry.impl?.${prop.dartName} = value',
          );
        }
        s.writeln('}');
        s.writeln();
      }
    }

    for (final stream in spec.streams) {
      final cType = _toSwiftCType(spec, stream.itemType.name);
      final isStructItem = spec.structs.any((st) => st.name == stream.itemType.name);
      s.writeln('@_cdecl("_register_${stream.dartName}_stream")');
      s.writeln('public func _register_${stream.dartName}_stream(');
      s.writeln('    _ dartPort: Int64,');
      s.writeln('    _ emitCb: @convention(c) (Int64, $cType) -> Void');
      s.writeln(') {');
      s.writeln(
        '    ${spec.dartClassName}Registry._${stream.dartName}Cancellables[dartPort] =',
      );
      s.writeln(
        '        ${spec.dartClassName}Registry.impl?.${stream.dartName}.sink { item in',
      );
      if (isStructItem) {
        s.writeln(
          '            let ptr = UnsafeMutablePointer<${stream.itemType.name}>.allocate(capacity: 1)',
        );
        s.writeln('            ptr.initialize(to: item)');
        s.writeln('            emitCb(dartPort, UnsafeMutableRawPointer(ptr))');
      } else {
        s.writeln('            emitCb(dartPort, item)');
      }
      s.writeln('        }');
      s.writeln('}');
      s.writeln();
      s.writeln('@_cdecl("_release_${stream.dartName}_stream")');
      s.writeln(
        'public func _release_${stream.dartName}_stream(_ dartPort: Int64) {',
      );
      s.writeln(
        '    ${spec.dartClassName}Registry._${stream.dartName}Cancellables[dartPort]?.cancel()',
      );
      s.writeln(
        '    ${spec.dartClassName}Registry._${stream.dartName}Cancellables.removeValue(forKey: dartPort)',
      );
      s.writeln('}');
    }

    return s.toString();
  }

  /// Return type for a `@_cdecl` function — must be a C-ABI-compatible type.
  /// - `void`   → `Void`
  /// - `bool`   → `Int8`
  /// - `String` → `UnsafeMutablePointer<CChar>?`  (malloc'd; Dart calls free())
  /// - struct   → `UnsafeMutableRawPointer?`       (heap-allocated Swift struct)
  /// - others   → same as `_toSwiftType`
  static String _toCDeclReturnType(BridgeSpec spec, BridgeFunction func) {
    final name = func.returnType.name.replaceFirst('?', '');
    if (name == 'void') return 'Void';
    if (name == 'bool') return 'Int8';
    if (name == 'String') return 'UnsafeMutablePointer<CChar>?';
    if (spec.structs.any((st) => st.name == name)) {
      return 'UnsafeMutableRawPointer?';
    }
    if (spec.recordTypes.any((rt) => rt.name == name) || name.startsWith('List<')) {
      return 'UnsafeMutablePointer<UInt8>?';
    }
    final isEnumRet = spec.enums.any((en) => en.name == name);
    if (isEnumRet) return 'Int64';
    return _toSwiftType(spec, name);
  }

  /// Parameter type for a `@_cdecl` function — must be a C-ABI-compatible type.
  /// - `String`     → `UnsafePointer<CChar>?`  (C `const char*`)
  /// - `bool`       → `Int8`
  /// - typed lists  → `UnsafeMutablePointer<T>?`  (raw C pointer; length passed separately)
  /// - others       → same as `_toSwiftType`
  static String _toCDeclParamType(BridgeSpec spec, String typeName) {
    final name = typeName.replaceFirst('?', '');
    if (name == 'String') return 'UnsafePointer<CChar>?';
    if (name == 'bool') return 'Int8';
    if (spec.recordTypes.any((rt) => rt.name == name) || name.startsWith('List<')) {
      return 'UnsafeMutablePointer<UInt8>?';
    }
    final isEnum = spec.enums.any((en) => en.name == name);
    if (isEnum) return 'Int64';
    if (spec.structs.any((st) => st.name == name)) {
      return 'UnsafeRawPointer?';
    }
    // Typed lists: use C-compatible pointer; length is passed as a separate Int64 param.
    if (BridgeType(name: name).isTypedData) {
      return _toSwiftCType(spec, name, isZeroCopy: true);
    }
    return _toSwiftType(spec, name);
  }

  static String _toSwiftType(BridgeSpec spec, String t) {
    final name = t.replaceFirst('?', '');
    final isOptional = t.endsWith('?');
    String baseType;
    switch (name) {
      case 'int':
        baseType = 'Int64';
        break;
      case 'double':
        baseType = 'Double';
        break;
      case 'bool':
        baseType = 'Bool';
        break;
      case 'String':
        baseType = 'String';
        break;
      case 'void':
        baseType = 'Void';
        break;
      case 'Uint8List':
      case 'Int8List':
        baseType = 'Data';
        break;
      case 'Int16List':
      case 'Uint16List':
        baseType = '[Int16]';
        break;
      case 'Int32List':
      case 'Uint32List':
        baseType = '[Int32]';
        break;
      case 'Float32List':
        baseType = '[Float]';
        break;
      case 'Float64List':
        baseType = '[Double]';
        break;
      case 'Int64List':
      case 'Uint64List':
        baseType = '[Int64]';
        break;
      default:
        if (spec.enums.any((en) => en.name == name)) {
          baseType = name;
        } else if (spec.structs.any((st) => st.name == name)) {
          baseType = name;
        } else if (spec.recordTypes.any((rt) => rt.name == name)) {
          baseType = name;
        } else if (name.startsWith('List<')) {
          final itemType = name.substring(5, name.length - 1);
          baseType = '[${_toSwiftType(spec, itemType)}]';
        } else {
          baseType = 'Any';
        }
    }
    return isOptional ? '$baseType?' : baseType;
  }

  static String _toSwiftCType(BridgeSpec spec, String t, {bool isZeroCopy = false}) {
    final name = t.replaceFirst('?', '');
    switch (name) {
      case 'int':
        return 'Int64';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Int8';
      case 'String':
        return 'UnsafeMutablePointer<Int8>?';
      case 'void':
        return 'Void';
      case 'Uint8List':
        return 'UnsafeMutablePointer<UInt8>?';
      case 'Int8List':
        return 'UnsafeMutablePointer<Int8>?';
      case 'Int16List':
        return 'UnsafeMutablePointer<Int16>?';
      case 'Uint16List':
        return 'UnsafeMutablePointer<UInt16>?';
      case 'Int32List':
        return 'UnsafeMutablePointer<Int32>?';
      case 'Uint32List':
        return 'UnsafeMutablePointer<UInt32>?';
      case 'Float32List':
        return isZeroCopy ? 'UnsafeMutablePointer<Float>?' : '[Float]';
      case 'Float64List':
        return isZeroCopy ? 'UnsafeMutablePointer<Double>?' : '[Double]';
      case 'Int64List':
      case 'Uint64List':
        return isZeroCopy ? 'UnsafeMutablePointer<Int64>?' : '[Int64]';
      default:
        if (spec.enums.any((en) => en.name == name)) return 'Int64';
        if (spec.structs.any((st) => st.name == name)) {
          return 'UnsafeMutableRawPointer?';
        }
        if (spec.recordTypes.any((rt) => rt.name == name) || name.startsWith('List<')) {
          return 'UnsafeMutablePointer<UInt8>?';
        }
        return 'Any?';
    }
  }

  static String _defaultCDeclValue(BridgeSpec spec, String t) {
    final name = t.replaceFirst('?', '');
    switch (name) {
      case 'int':
        return '0';
      case 'double':
        return '0.0';
      case 'bool':
        return '0';
      case 'String':
        return 'strdup("")';
      default:
        if (spec.enums.any((en) => en.name == name)) return '0';
        if (spec.structs.any((st) => st.name == name)) return 'nil';
        return '()';
    }
  }
}
