import '../bridge_spec.dart';
import 'code_writer.dart';

/// Generates binary encode/decode extension methods for every `@NitroVariant`
/// sealed class declared in the spec.
///
/// Wire format: `[1B tag 0..N] [optional field bytes — record codec order]`
/// Tag 0 = first case, tag 1 = second case, etc.
///
/// Each variant gets an extension named `${VariantName}VariantExt` with:
///   • `static T fromNative(Pointer<Uint8> ptr)` — top-level decoder
///   • `static T fromReader(RecordReader r)`     — inner decoder (used in lists)
///   • `void writeFields(RecordWriter writer)`   — encoder
///   • `Pointer<Uint8> toNative(Allocator alloc)` — top-level encoder
class VariantGenerator {
  static String generateDartExtensions(BridgeSpec spec) {
    final localVariants = spec.localVariants;
    if (localVariants.isEmpty) return '';

    final enumNames = spec.enums.map((e) => e.name).toSet();
    final structNames = spec.structs.map((s) => s.name).toSet();

    final s = CodeWriter();
    s.line('// --- @NitroVariant binary extensions (generated by Nitrogen) ---');
    s.blank();

    for (final variant in localVariants) {
      _emitVariantExt(s, variant, enumNames, structNames);
    }

    return s.toString();
  }

  /// Returns true when the variant has a case whose name is literally `'null'`
  /// (case-insensitive). This makes the variant nullable — `fromNative` /
  /// `fromReader` return `VariantName?` and the null-tag decodes to Dart `null`.
  static bool _hasNullCase(BridgeVariant variant) =>
      variant.cases.any((c) => c.name.toLowerCase() == 'null');

  /// Returns the 0-based tag index assigned to the null-marker case, or -1.
  static int _nullCaseTag(BridgeVariant variant) =>
      variant.cases.indexWhere((c) => c.name.toLowerCase() == 'null');

  /// Returns true when the variant's decode can be optimized with a dart:ffi Union
  /// (all cases: unit or exactly one non-nullable primitive field int/double/bool).
  /// This enables zero-copy payload reads via direct pointer cast — no RecordReader.
  ///
  /// Variants with a null case are excluded from the optimization — returning
  /// `null` from a zero-copy union path is not supported.
  static bool _isPrimOnlyVariant(BridgeVariant variant) =>
      !_hasNullCase(variant) &&
      variant.cases.every((c) =>
          c.isUnit ||
          (c.fields.length == 1 &&
           c.fields[0].kind == RecordFieldKind.primitive &&
           !c.fields[0].isNullable &&
           (c.fields[0].dartType == 'int' ||
            c.fields[0].dartType == 'double' ||
            c.fields[0].dartType == 'bool')));

  static void _emitVariantExt(
    CodeWriter s,
    BridgeVariant variant,
    Set<String> enumNames,
    Set<String> structNames,
  ) {
    final name = variant.name;
    final hasNull = _hasNullCase(variant);
    final nullTag = _nullCaseTag(variant);
    final isPrimOnly = _isPrimOnlyVariant(variant);

    // The return type is nullable when there is a null-marker case.
    final returnType = hasNull ? '$name?' : name;

    // Finding 8: For prim-only variants (no null case), emit a dart:ffi Union before
    // the extension to allow zero-copy payload reads via pointer cast.
    if (isPrimOnly) {
      s.line('final class _${name}Payload extends Union {');
      s.line('  @Int64() external int asInt;');
      s.line('  @Double() external double asDouble;');
      s.line('  @Uint8() external int asBool;');
      s.line('}');
      s.blank();
    }

    s.line('extension ${name}VariantExt on $name {');

    // ── fromNative ────────────────────────────────────────────────────────────
    if (isPrimOnly) {
      // Zero-copy decode: direct pointer cast instead of RecordReader allocation.
      // Wire format: [1B tag][payload bytes] — Union covers int(8B), double(8B), bool(1B).
      s.line('  static $returnType fromNative(Pointer<Uint8> ptr) {');
      s.line('    final tag = ptr[0];');
      s.line('    final p = (ptr + 1).cast<_${name}Payload>().ref;');
      s.line('    return switch (tag) {');
      for (var i = 0; i < variant.cases.length; i++) {
        final c = variant.cases[i];
        if (c.isUnit) {
          s.line('      $i => ${c.name}(),');
        } else {
          final f = c.fields[0];
          final readExpr = switch (f.dartType) {
            'int' => 'p.asInt',
            'double' => 'p.asDouble',
            'bool' => 'p.asBool != 0',
            _ => 'p.asInt',
          };
          s.line('      $i => ${c.name}(${f.name}: $readExpr),');
        }
      }
      s.line("      _ => throw ArgumentError('Unknown $name tag: \$tag'),");
      s.line('    };');
      s.line('  }');
    } else {
      s.line('  static $returnType fromNative(Pointer<Uint8> ptr) =>');
      s.line('      fromReader(RecordReader.fromNative(ptr));');
    }
    s.blank();

    // ── fromReader ────────────────────────────────────────────────────────────
    s.line('  static $returnType fromReader(RecordReader r) {');
    s.line('    final tag = r.readInt8();');
    s.line('    return switch (tag) {');
    for (var i = 0; i < variant.cases.length; i++) {
      final c = variant.cases[i];
      // null-marker case decodes to Dart null
      if (c.name.toLowerCase() == 'null') {
        s.line('      $i => null,');
        continue;
      }
      if (c.isUnit) {
        s.line('      $i => ${c.name}(),');
      } else {
        final args = c.fields.map((f) => '${f.name}: ${_fieldReadExpr(f, enumNames, structNames)}').join(', ');
        s.line('      $i => ${c.name}($args),');
      }
    }
    s.line("      _ => throw ArgumentError('Unknown $name tag: \$tag'),");
    s.line('    };');
    s.line('  }');
    s.blank();

    // ── writeFields ───────────────────────────────────────────────────────────
    // The null case is not a real Dart class — it is encoded via encodeNullable.
    // writeFields is only called on non-null instances, so the null tag is excluded.
    s.line('  void writeFields(RecordWriter writer) {');
    s.line('    switch (this) {');
    for (var i = 0; i < variant.cases.length; i++) {
      final c = variant.cases[i];
      if (c.name.toLowerCase() == 'null') continue; // no class named 'null'
      if (c.isUnit) {
        s.line('      case ${c.name}():');
        s.line('        writer.writeInt8($i);');
      } else {
        final pattern = c.fields.map((f) => ':final ${f.name}').join(', ');
        s.line('      case ${c.name}($pattern):');
        s.line('        writer.writeInt8($i);');
        for (final f in c.fields) {
          _writeFieldStmt(s, f, enumNames, structNames, indent: '        ');
        }
      }
    }
    s.line('    }');
    s.line('  }');
    s.blank();

    // ── toNative ──────────────────────────────────────────────────────────────
    s.line('  Pointer<Uint8> toNative(Allocator alloc) {');
    s.line('    final writer = RecordWriter();');
    s.line('    writeFields(writer);');
    s.line('    return writer.toNative(alloc);');
    s.line('  }');

    // ── encodeNullable (only when a null case exists) ─────────────────────────
    // Writes tag=$nullTag with zero payload bytes when [value] is null;
    // delegates to [writeFields] otherwise.
    if (hasNull) {
      s.blank();
      s.line('  static Pointer<Uint8> encodeNullable($name? value, Allocator alloc) {');
      s.line('    final writer = RecordWriter();');
      s.line('    if (value == null) {');
      s.line('      writer.writeInt8($nullTag);');
      s.line('    } else {');
      s.line('      value.writeFields(writer);');
      s.line('    }');
      s.line('    return writer.toNative(alloc);');
      s.line('  }');
    }

    s.line('}');
    s.blank();
  }

  // ── Field read expression (mirrors RecordGenerator._recordFieldReadExpr) ────

  static String _fieldReadExpr(
    BridgeRecordField f,
    Set<String> enumNames,
    Set<String> structNames,
  ) {
    final base = f.dartType.replaceFirst('?', '');
    final nullable = f.isNullable;

    if (nullable) return _nullableReadExpr(f, enumNames, structNames);

    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _primitiveRead(base);
      case RecordFieldKind.enumValue:
        return '$base.values[r.readInt().toInt()]';
      case RecordFieldKind.struct:
      case RecordFieldKind.recordObject:
        return '${base}RecordExt.fromReader(r)';
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        return 'List.generate(r.readInt32(), (_) => ${_primitiveRead(item)})';
      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName ?? base;
        return 'List.generate(r.readInt32(), (_) => ${item}RecordExt.fromReader(r))';
      default:
        return 'r.readString()';
    }
  }

  static String _nullableReadExpr(
    BridgeRecordField f,
    Set<String> enumNames,
    Set<String> structNames,
  ) {
    final base = f.dartType.replaceFirst('?', '');
    final inner = _fieldReadExpr(
      BridgeRecordField(name: f.name, dartType: base, kind: f.kind, itemTypeName: f.itemTypeName),
      enumNames,
      structNames,
    );
    return 'r.readBool() ? $inner : null';
  }

  static String _primitiveRead(String t) => switch (t) {
    'int' => 'r.readInt()',
    'double' => 'r.readDouble()',
    'bool' => 'r.readBool()',
    'String' => 'r.readString()',
    _ => 'r.readInt()',
  };

  // ── Field write statement ─────────────────────────────────────────────────────

  static void _writeFieldStmt(
    CodeWriter s,
    BridgeRecordField f,
    Set<String> enumNames,
    Set<String> structNames, {
    String indent = '    ',
  }) {
    final name = f.name;
    final base = f.dartType.replaceFirst('?', '');
    final nullable = f.isNullable;

    if (nullable) {
      s.line('${indent}writer.writeBool($name != null);');
      s.line('${indent}if ($name != null) {');
      s.line('$indent  ${_fieldWriteStmtForExpr(base, name, f.kind, f.itemTypeName)}');
      s.line('$indent}');
      return;
    }

    s.line('$indent${_fieldWriteStmtForExpr(base, name, f.kind, f.itemTypeName)}');
  }

  static String _fieldWriteStmtForExpr(String base, String expr, RecordFieldKind kind, String? itemType) {
    switch (kind) {
      case RecordFieldKind.primitive:
        return '${_primitiveWriteExpr(base, expr)};';
      case RecordFieldKind.enumValue:
        return 'writer.writeInt($expr.index);';
      case RecordFieldKind.struct:
      case RecordFieldKind.recordObject:
        return '$expr.writeFields(writer);';
      case RecordFieldKind.listPrimitive:
        final item = itemType ?? 'int';
        return 'writer.writeInt32($expr.length); for (final e in $expr) { ${_primitiveWriteExpr(item, 'e')}; }';
      case RecordFieldKind.listRecordObject:
        return 'writer.writeInt32($expr.length); for (final e in $expr) { e.writeFields(writer); }';
      default:
        return 'writer.writeString($expr);';
    }
  }

  static String _primitiveWriteExpr(String t, String varName) => switch (t) {
    'int' => 'writer.writeInt($varName)',
    'double' => 'writer.writeDouble($varName)',
    'bool' => 'writer.writeBool($varName)',
    'String' => 'writer.writeString($varName)',
    _ => 'writer.writeInt($varName)',
  };
}
