import '../bridge_spec.dart';
import 'code_writer.dart';

/// Generates binary encode/decode extension methods for every `@NitroVariant`
/// sealed class declared in the spec.
///
/// Wire format: `[1B tag 0..N] [optional field bytes — record codec order]`
/// Tag 0 = first case, tag 1 = second case, etc.
///
/// Each variant gets an extension named `${VariantName}VariantExt` with:
///   • `static T fromNative(Pointer<Uint8> ptr)` — top-level decoder
///   • `static T fromReader(RecordReader r)`     — inner decoder (used in lists)
///   • `void writeFields(RecordWriter writer)`   — encoder
///   • `Pointer<Uint8> toNative(Allocator alloc)` — top-level encoder
class VariantGenerator {
  static String generateDartExtensions(BridgeSpec spec) {
    final localVariants = spec.localVariants;
    if (localVariants.isEmpty) return '';

    final enumNames = spec.enums.map((e) => e.name).toSet();
    final structNames = spec.structs.map((s) => s.name).toSet();

    final s = CodeWriter();
    s.line('// --- @NitroVariant binary extensions (generated by Nitrogen) ---');
    s.blank();

    for (final variant in localVariants) {
      _emitVariantExt(s, variant, enumNames, structNames);
    }

    return s.toString();
  }

  static void _emitVariantExt(
    CodeWriter s,
    BridgeVariant variant,
    Set<String> enumNames,
    Set<String> structNames,
  ) {
    final name = variant.name;
    s.line('extension ${name}VariantExt on $name {');

    // ── fromNative ────────────────────────────────────────────────────────────
    s.line('  static $name fromNative(Pointer<Uint8> ptr) =>');
    s.line('      fromReader(RecordReader.fromNative(ptr));');
    s.blank();

    // ── fromReader ────────────────────────────────────────────────────────────
    s.line('  static $name fromReader(RecordReader r) {');
    s.line('    final tag = r.readInt8();');
    s.line('    return switch (tag) {');
    for (var i = 0; i < variant.cases.length; i++) {
      final c = variant.cases[i];
      if (c.isUnit) {
        s.line('      $i => ${c.name}(),');
      } else {
        final args = c.fields.map((f) => '${f.name}: ${_fieldReadExpr(f, enumNames, structNames)}').join(', ');
        s.line('      $i => ${c.name}($args),');
      }
    }
    s.line("      _ => throw ArgumentError('Unknown $name tag: \$tag'),");
    s.line('    };');
    s.line('  }');
    s.blank();

    // ── writeFields ───────────────────────────────────────────────────────────
    s.line('  void writeFields(RecordWriter writer) {');
    s.line('    switch (this) {');
    for (var i = 0; i < variant.cases.length; i++) {
      final c = variant.cases[i];
      if (c.isUnit) {
        s.line('      case ${c.name}():');
        s.line('        writer.writeInt8($i);');
      } else {
        final pattern = c.fields.map((f) => ':final ${f.name}').join(', ');
        s.line('      case ${c.name}($pattern):');
        s.line('        writer.writeInt8($i);');
        for (final f in c.fields) {
          _writeFieldStmt(s, f, enumNames, structNames, indent: '        ');
        }
      }
    }
    s.line('    }');
    s.line('  }');
    s.blank();

    // ── toNative ──────────────────────────────────────────────────────────────
    s.line('  Pointer<Uint8> toNative(Allocator alloc) {');
    s.line('    final writer = RecordWriter();');
    s.line('    writeFields(writer);');
    s.line('    return writer.toNative(alloc);');
    s.line('  }');

    s.line('}');
    s.blank();
  }

  // ── Field read expression (mirrors RecordGenerator._recordFieldReadExpr) ────

  static String _fieldReadExpr(
    BridgeRecordField f,
    Set<String> enumNames,
    Set<String> structNames,
  ) {
    final base = f.dartType.replaceFirst('?', '');
    final nullable = f.isNullable;

    if (nullable) return _nullableReadExpr(f, enumNames, structNames);

    switch (f.kind) {
      case RecordFieldKind.primitive:
        return _primitiveRead(base);
      case RecordFieldKind.enumValue:
        return '$base.values[r.readInt().toInt()]';
      case RecordFieldKind.struct:
      case RecordFieldKind.recordObject:
        return '${base}RecordExt.fromReader(r)';
      case RecordFieldKind.listPrimitive:
        final item = f.itemTypeName ?? 'int';
        return 'List.generate(r.readInt32(), (_) => ${_primitiveRead(item)})';
      case RecordFieldKind.listRecordObject:
        final item = f.itemTypeName ?? base;
        return 'List.generate(r.readInt32(), (_) => ${item}RecordExt.fromReader(r))';
      default:
        return 'r.readString()';
    }
  }

  static String _nullableReadExpr(
    BridgeRecordField f,
    Set<String> enumNames,
    Set<String> structNames,
  ) {
    final base = f.dartType.replaceFirst('?', '');
    final inner = _fieldReadExpr(
      BridgeRecordField(name: f.name, dartType: base, kind: f.kind, itemTypeName: f.itemTypeName),
      enumNames,
      structNames,
    );
    return 'r.readBool() ? $inner : null';
  }

  static String _primitiveRead(String t) => switch (t) {
    'int' => 'r.readInt()',
    'double' => 'r.readDouble()',
    'bool' => 'r.readBool()',
    'String' => 'r.readString()',
    _ => 'r.readInt()',
  };

  // ── Field write statement ─────────────────────────────────────────────────────

  static void _writeFieldStmt(
    CodeWriter s,
    BridgeRecordField f,
    Set<String> enumNames,
    Set<String> structNames, {
    String indent = '    ',
  }) {
    final name = f.name;
    final base = f.dartType.replaceFirst('?', '');
    final nullable = f.isNullable;

    if (nullable) {
      s.line('${indent}writer.writeBool($name != null);');
      s.line('${indent}if ($name != null) {');
      s.line('$indent  ${_fieldWriteStmtForExpr(base, name, f.kind, f.itemTypeName)}');
      s.line('$indent}');
      return;
    }

    s.line('$indent${_fieldWriteStmtForExpr(base, name, f.kind, f.itemTypeName)}');
  }

  static String _fieldWriteStmtForExpr(String base, String expr, RecordFieldKind kind, String? itemType) {
    switch (kind) {
      case RecordFieldKind.primitive:
        return '${_primitiveWriteExpr(base, expr)};';
      case RecordFieldKind.enumValue:
        return 'writer.writeInt($expr.index);';
      case RecordFieldKind.struct:
      case RecordFieldKind.recordObject:
        return '$expr.writeFields(writer);';
      case RecordFieldKind.listPrimitive:
        final item = itemType ?? 'int';
        return 'writer.writeInt32($expr.length); for (final e in $expr) { ${_primitiveWriteExpr(item, 'e')}; }';
      case RecordFieldKind.listRecordObject:
        return 'writer.writeInt32($expr.length); for (final e in $expr) { e.writeFields(writer); }';
      default:
        return 'writer.writeString($expr);';
    }
  }

  static String _primitiveWriteExpr(String t, String varName) => switch (t) {
    'int' => 'writer.writeInt($varName)',
    'double' => 'writer.writeDouble($varName)',
    'bool' => 'writer.writeBool($varName)',
    'String' => 'writer.writeString($varName)',
    _ => 'writer.writeInt($varName)',
  };
}
