// Web (WASM) build wiring for `nitrogen init` / `nitrogen link`.
// Part of link_command.dart (all link/ files are parts of that library).
//
// The web target compiles the SAME generated C bridge (+ the plugin's C++
// impl sources) with Emscripten into `assets/web/[lib].js` + `.wasm`, which
// the generated web bridge loads at runtime via the Flutter asset bundle.
part of '../link_command.dart';

/// The em++ invocation per web-targeting module. Flag set verified by the
/// nitro web e2e suite:
///   * -fwasm-exceptions — the bridge's try/catch → NitroError contract
///   * MODULARIZE + EXPORT_NAME `create<LibPascal>Module` — what
///     NitroRuntime.loadWebModule calls (nitroWebExportName convention)
///   * addFunction/wasmMemory/HEAPU8 runtime methods — heap I/O + the post
///     callback replacing Dart_PostCObject
String webBuildScriptTemplate(List<String> webLibs) {
  final b = StringBuffer('''
#!/usr/bin/env bash
# Generated by `nitrogen link`. Module list is kept in sync — re-run
# `nitrogen link` after adding a web-targeting module; edit flags freely.
#
# Builds the plugin's WASM module(s) into assets/web/ (bundled as Flutter
# assets — declared under `flutter: assets:` in pubspec.yaml).
# Requires the Emscripten SDK on PATH: https://emscripten.org/docs/getting_started
set -euo pipefail

cd "\$(dirname "\$0")/.."
GEN="lib/src/generated/cpp"
OUT="assets/web"
mkdir -p "\$OUT"

# The plugin's C++ impl sources: prefer the Hybrid*.cpp convention (only the
# nitro impl files — other modules' native code must not be linked into this
# wasm), falling back to all of src/*.cpp for single-impl layouts.
# dart_api_dl.c is VM-only — never compile it for web (nitro_wasm_compat.h
# shims the Dart API under __EMSCRIPTEN__).
IMPL_SOURCES=\$(ls src/Hybrid*.cpp 2>/dev/null || ls src/*.cpp 2>/dev/null | grep -v dart_api_dl || true)
''');
  for (final lib in webLibs) {
    final pascal = lib.split(RegExp('[_-]+')).where((s) => s.isNotEmpty).map((s) => s[0].toUpperCase() + s.substring(1)).join();
    b.write('''

em++ -O2 --no-entry -fwasm-exceptions \\
  -Isrc -Isrc/native -I"\$GEN" \\
  "\$GEN/$lib.bridge.g.cpp" \$IMPL_SOURCES \\
  -sMODULARIZE=1 -sEXPORT_NAME=create${pascal}Module \\
  -sALLOW_MEMORY_GROWTH=1 -sALLOW_TABLE_GROWTH=1 \\
  -sWASM_BIGINT=1 -sENVIRONMENT=web \\
  -sEXPORTED_RUNTIME_METHODS=addFunction,removeFunction,wasmExports,wasmMemory,HEAPU8 \\
  -sEXPORTED_FUNCTIONS=_malloc,_free \\
  -o "\$OUT/$lib.js"
echo "built \$OUT/$lib.js + \$OUT/$lib.wasm"
''');
  }
  return b.toString();
}

/// Writes/refreshes `web/build_web.sh` for the web-targeting modules and
/// ensures the `assets/web/` asset directory exists. No-op (removes nothing)
/// when no module targets web.
///
/// Returns the number of web-targeting modules wired.
int linkWeb(String pluginName, List<ModuleInfo> moduleInfos, {String? baseDir}) {
  final base = baseDir ?? pluginName;
  final webLibs = moduleInfos.where((m) => m.webIsWasm).map((m) => m.lib).toList();
  if (webLibs.isEmpty) return 0;

  final webDir = Directory(p.join(base, 'web'))..createSync(recursive: true);
  final script = File(p.join(webDir.path, 'build_web.sh'));
  script.writeAsStringSync(webBuildScriptTemplate(webLibs));
  if (!Platform.isWindows) {
    Process.runSync('chmod', ['+x', script.path]);
  }

  final assetsDir = Directory(p.join(base, 'assets', 'web'))..createSync(recursive: true);
  final gitkeep = File(p.join(assetsDir.path, '.gitkeep'));
  if (!gitkeep.existsSync()) {
    gitkeep.writeAsStringSync('# WASM build outputs land here (web/build_web.sh)\n');
  }

  // The .wasm only reaches the browser if Flutter bundles it. `nitrogen init`
  // declares this for projects created WITH web, but a plugin that adds web
  // later would otherwise build the module and never ship it — the failure
  // surfaces at runtime as a 404 from ensure<Class>Ready(), long after the
  // build looked successful. Declaring it here covers both paths.
  final pubspecFile = File(p.join(base, 'pubspec.yaml'));
  _ensureWebAssetsDeclared(pubspecFile);
  _scaffoldWebTests(base, moduleInfos.where((m) => m.webIsWasm).toList(), pubspecFile);
  return webLibs.length;
}

/// Scaffolds the browser-test harness: the hybrid asset server (always
/// refreshed — pure boilerplate) and a per-module starter test (written once,
/// never overwritten, since it is the author's file after that).
///
/// A WASM module cannot be tested from the VM, and `package:test` cannot read
/// a Flutter asset bundle, so the harness serves `assets/web/` over loopback
/// with permissive CORS and hands the port to the browser via a hybrid
/// isolate. Every web-targeting plugin needs the identical rig; generating it
/// keeps the wiring — CORS headers, the wasm MIME type, the dart2wasm
/// number-decoding caveat — out of each project.
void _scaffoldWebTests(String base, List<ModuleInfo> webModules, File pubspecFile) {
  if (webModules.isEmpty) return;
  final testDir = Directory(p.join(base, 'test'))..createSync(recursive: true);

  File(p.join(testDir.path, 'asset_server.dart')).writeAsStringSync(_webAssetServerTemplate);

  // The PACKAGE name, which is not necessarily the module's lib name — the
  // benchmark package is `benchmark` while its module lib is `benchmark_cpp`,
  // and a stub that guessed `package:benchmark_cpp/...` from the lib name
  // simply did not compile.
  final pkgName = _packageNameOf(pubspecFile) ?? p.basename(p.normalize(p.absolute(base)));

  for (final m in webModules) {
    final stub = File(p.join(testDir.path, '${m.lib}_web_test.dart'));
    if (!stub.existsSync()) {
      stub.writeAsStringSync(_webTestStubTemplate(m.lib, m.module, pkgName));
    }
  }
  _ensureWebTestDevDeps(pubspecFile);
}

/// The `name:` field of [pubspecFile], or null when it cannot be read.
String? _packageNameOf(File pubspecFile) {
  if (!pubspecFile.existsSync()) return null;
  final match = RegExp(r'''^name:\s*["']?([A-Za-z_][A-Za-z0-9_]*)["']?\s*$''', multiLine: true)
      .firstMatch(pubspecFile.readAsStringSync());
  return match?.group(1);
}

/// Hybrid isolate (VM side) serving the built module to the browser test.
const _webAssetServerTemplate = r'''
// Generated by `nitrogen link`. Runs on the VM as a hybrid isolate: serves
// assets/web/ to the browser test with permissive CORS and reports the port.
import 'dart:io';

import 'package:stream_channel/stream_channel.dart';

Future<void> hybridMain(StreamChannel<Object?> channel) async {
  final dir = Directory.current.path;
  final server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
  server.listen((req) async {
    final name = req.uri.path.split('/').last;
    final file = File('$dir/assets/web/$name');
    req.response.headers.set('Access-Control-Allow-Origin', '*');
    if (!file.existsSync()) {
      req.response.statusCode = 404;
      await req.response.close();
      return;
    }
    // The .wasm MUST be served as application/wasm or instantiateStreaming
    // refuses it.
    req.response.headers.contentType = name.endsWith('.wasm')
        ? ContentType('application', 'wasm')
        : ContentType('text', 'javascript');
    await req.response.addStream(file.openRead());
    await req.response.close();
  });
  channel.sink.add(server.port);
  await channel.stream.drain<void>();
}
''';

/// Starter browser test — loads the module and proves the bridge is live.
/// Written once; add real cases to it.
String _webTestStubTemplate(String lib, String className, String pkgName) => '''
// Starter browser test generated by `nitrogen link` (not overwritten again).
//
// Build the module first, then run under BOTH web compilers — they differ at
// the js_interop boundary, so a green dart2js run does not imply dart2wasm:
//   web/build_web.sh
//   dart test -p chrome
//   dart test -p chrome -c dart2wasm
@TestOn('browser')
library;

import 'package:test/test.dart';

import 'package:$pkgName/$pkgName.dart';
// ensure${className}Ready lives in the generated platform shim. It is imported
// directly because a package barrel does not necessarily re-export it — add
// `export 'src/$lib.platform.g.dart';` to the barrel if you want callers of
// your package to reach it too (web callers must await it before first use).
import 'package:$pkgName/src/$lib.platform.g.dart';

void main() {
  setUpAll(() async {
    final channel = spawnHybridUri('asset_server.dart');
    // dart2wasm hands JS numbers over as double — never cast with `as int`.
    final port = ((await channel.stream.first)! as num).toInt();
    await ensure${className}Ready(jsUrl: 'http://localhost:\$port/$lib.js');
  });

  test('module loads and the bridge answers', () {
    // Reaching here means the WASM module instantiated and the ABI-version
    // and bridge-checksum checks passed. Add real round-trips below.
    expect($className.instance, isNotNull);
  });
}
''';

/// Browser tests need `test` (the runner) and `stream_channel` (the hybrid
/// isolate channel). flutter_test cannot drive `-p chrome`.
void _ensureWebTestDevDeps(File pubspecFile) {
  if (!pubspecFile.existsSync()) return;
  var pubspec = pubspecFile.readAsStringSync();
  if (!RegExp(r'^dev_dependencies:\s*$', multiLine: true).hasMatch(pubspec)) return;

  final additions = <String>[
    if (!RegExp(r'^  test:', multiLine: true).hasMatch(pubspec)) '  test: ^1.25.8',
    if (!RegExp(r'^  stream_channel:', multiLine: true).hasMatch(pubspec)) '  stream_channel: ^2.1.2',
  ];
  if (additions.isEmpty) return;

  pubspec = pubspec.replaceFirst(
    RegExp(r'^dev_dependencies:\s*$', multiLine: true),
    'dev_dependencies:\n${additions.join('\n')}',
  );
  pubspecFile.writeAsStringSync(pubspec);
}

/// Adds `assets/web/` under the top-level `flutter:` key when absent.
/// Idempotent, and leaves an existing `assets:` list alone apart from adding
/// the one entry.
void _ensureWebAssetsDeclared(File pubspecFile) {
  if (!pubspecFile.existsSync()) return;
  var pubspec = pubspecFile.readAsStringSync();
  if (pubspec.contains('assets/web/')) return;

  final assetsKey = RegExp(r'^  assets:\s*$', multiLine: true);
  final flutterKey = RegExp(r'^flutter:\s*$', multiLine: true);
  if (assetsKey.hasMatch(pubspec)) {
    // Existing list — insert as the first entry so ordering stays stable.
    pubspec = pubspec.replaceFirst(assetsKey, '  assets:\n    - assets/web/');
  } else if (flutterKey.hasMatch(pubspec)) {
    // Insert as the FIRST CHILD of `flutter:`, never appended at end of file.
    // `flutter:` is frequently not the last top-level key — appending would
    // silently attach the entry to whatever section happens to be last
    // (dependency_overrides, say) and make the pubspec unparseable.
    pubspec = pubspec.replaceFirst(flutterKey, 'flutter:\n  assets:\n    - assets/web/');
  } else {
    return; // no flutter: section — not a Flutter package, nothing to wire
  }
  pubspecFile.writeAsStringSync(pubspec);
}
