// Web (WASM) build wiring for `nitrogen init` / `nitrogen link`.
// Part of link_command.dart (all link/ files are parts of that library).
//
// The web target compiles the SAME generated C bridge (+ the plugin's C++
// impl sources) with Emscripten into `assets/web/[lib].js` + `.wasm`, which
// the generated web bridge loads at runtime via the Flutter asset bundle.
part of '../link_command.dart';

/// The em++ invocation per web-targeting module. Flag set verified by the
/// nitro web e2e suite:
///   * -fwasm-exceptions — the bridge's try/catch → NitroError contract
///   * MODULARIZE + EXPORT_NAME `create<LibPascal>Module` — what
///     NitroRuntime.loadWebModule calls (nitroWebExportName convention)
///   * addFunction/wasmMemory/HEAPU8 runtime methods — heap I/O + the post
///     callback replacing Dart_PostCObject
String webBuildScriptTemplate(
  List<String> webLibs, {
  Map<String, String>? bridgeChecksums,
  Set<String> webSpecificImpls = const {},
}) {
  // One line per lib, carrying the GENERATOR's compile-time bridge checksum —
  // the same constant baked into the .bridge.g.cpp and verified at runtime by
  // NitroRuntime.checkLinkChecksum. It hashes the ABI surface, so reformatting
  // a spec does not move it and a real signature change always does.
  final stamp = webLibs
      .map((lib) => '$_bridgeChecksumPrefix$lib ${bridgeChecksums?[lib] ?? 'unavailable'}')
      .join('\n');
  final b = StringBuffer('''
#!/usr/bin/env bash
# Generated by `nitrogen link`. Module list is kept in sync — re-run
# `nitrogen link` after adding a web-targeting module; edit flags freely.
#
# Builds the plugin's WASM module(s) into assets/web/ (bundled as Flutter
# assets — declared under `flutter: assets:` in pubspec.yaml).
# Requires the Emscripten SDK on PATH: https://emscripten.org/docs/getting_started
#
# Records the generated bridge each module was built against; `nitrogen doctor`
# warns when a bridge has been regenerated since this script was written.
$stamp
set -euo pipefail

cd "\$(dirname "\$0")/.."
GEN="lib/src/generated/cpp"
OUT="assets/web"
mkdir -p "\$OUT"

# The plugin's C++ impl sources: prefer the Hybrid*.cpp convention (only the
# nitro impl files — other modules' native code must not be linked into this
# wasm), falling back to all of src/*.cpp for single-impl layouts.
# dart_api_dl.c is VM-only — never compile it for web (nitro_wasm_compat.h
# shims the Dart API under __EMSCRIPTEN__).
IMPL_SOURCES=\$(ls src/Hybrid*.cpp 2>/dev/null || ls src/*.cpp 2>/dev/null | grep -v dart_api_dl || true)

# NITRO_WEB_THREADS=1 builds with wasm threads: impls may spawn std::thread and
# native-async work leaves the main thread. Needs SharedArrayBuffer — serve the
# app cross-origin isolated (COOP/COEP), or test in Chrome with
# --enable-features=SharedArrayBuffer. Workers are same-origin: the module must
# be served from the app's own origin.
THREAD_FLAGS=""
if [ "\${NITRO_WEB_THREADS:-0}" = "1" ]; then
  THREAD_FLAGS="-pthread -sPTHREAD_POOL_SIZE=4 -sPTHREAD_POOL_SIZE_STRICT=0 -sMAXIMUM_MEMORY=1gb"
fi
''');
  for (final lib in webLibs) {
    final pascal = lib.split(RegExp('[_-]+')).where((s) => s.isNotEmpty).map((s) => s[0].toUpperCase() + s.substring(1)).join();
    // Decided at link time, like the desktop CMakeLists: a web/src/ file with
    // real code replaces the shared impl for THIS module only.
    final (impl, implNote) = webSpecificImpls.contains(lib)
        ? ('web/src/Hybrid$pascal.cpp', 'web-specific impl')
        : ('\$IMPL_SOURCES', 'shared src/ impl');
    b.write('''

# $lib: $implNote
em++ -O2 --no-entry -fwasm-exceptions \$THREAD_FLAGS \\
  -Isrc -Isrc/native -I"\$GEN" \\
  "\$GEN/$lib.bridge.g.cpp" $impl \\
  -sMODULARIZE=1 -sEXPORT_NAME=create${pascal}Module \\
  -sALLOW_MEMORY_GROWTH=1 -sALLOW_TABLE_GROWTH=1 \\
  -sWASM_BIGINT=1 -sENVIRONMENT=web \\
  -sEXPORTED_RUNTIME_METHODS=addFunction,removeFunction,wasmExports,wasmMemory,HEAPU8 \\
  -sEXPORTED_FUNCTIONS=_malloc,_free \\
  -o "\$OUT/$lib.js"
echo "built \$OUT/$lib.js + \$OUT/$lib.wasm"
''');
  }
  return b.toString();
}

/// Writes/refreshes `web/build_web.sh` for the web-targeting modules and
/// ensures the `assets/web/` asset directory exists. No-op (removes nothing)
/// when no module targets web.
///
/// Returns the number of web-targeting modules wired.
int linkWeb(String pluginName, List<ModuleInfo> moduleInfos, {String? baseDir}) {
  final base = baseDir ?? pluginName;
  final webLibs = moduleInfos.where((m) => m.webIsWasm).map((m) => m.lib).toList();
  if (webLibs.isEmpty) return 0;

  final webDir = Directory(p.join(base, 'web'))..createSync(recursive: true);

  // Same shape as linux/src: an inert starter sits beside the shared impl as
  // an option. Both `web:` spellings mean "shared" (every existing plugin
  // writes the specific one), so — unlike desktop — no annotation form ever
  // triggers migration; only real code in the file opts web out of sharing.
  for (final lib in webLibs) {
    _writeOrMigratePlatformImplStub(
      baseDir: base,
      platform: 'web',
      lib: lib,
      requestsSeparateImpl: false,
      genericStubContent: webImplStarterContent(base, lib),
    );
  }

  final script = File(p.join(webDir.path, 'build_web.sh'));
  script.writeAsStringSync(webBuildScriptTemplate(
    webLibs,
    bridgeChecksums: {
      for (final lib in webLibs) lib: ?readBridgeChecksum(base, lib),
    },
    webSpecificImpls: {for (final lib in webLibs) if (webUsesSpecificImpl(base, lib)) lib},
  ));
  if (!Platform.isWindows) {
    Process.runSync('chmod', ['+x', script.path]);
  }

  final assetsDir = Directory(p.join(base, 'assets', 'web'))..createSync(recursive: true);
  final gitkeep = File(p.join(assetsDir.path, '.gitkeep'));
  if (!gitkeep.existsSync()) {
    gitkeep.writeAsStringSync('# WASM build outputs land here (web/build_web.sh)\n');
  }

  // The .wasm only reaches the browser if Flutter bundles it. `nitrogen init`
  // declares this for projects created WITH web, but a plugin that adds web
  // later would otherwise build the module and never ship it — the failure
  // surfaces at runtime as a 404 from ensure<Class>Ready(), long after the
  // build looked successful. Declaring it here covers both paths.
  final pubspecFile = File(p.join(base, 'pubspec.yaml'));
  _ensureWebAssetsDeclared(pubspecFile);
  _scaffoldWebTests(base, moduleInfos.where((m) => m.webIsWasm).toList(), pubspecFile);
  return webLibs.length;
}

/// Scaffolds the browser-test harness: the hybrid asset server and a
/// per-module starter test. BOTH are written once and never overwritten —
/// authors extend the server (auth headers, extra routes, fixture files) just
/// as they extend the test, so refreshing it would discard their work.
///
/// A WASM module cannot be tested from the VM, and `package:test` cannot read
/// a Flutter asset bundle, so the harness serves `assets/web/` over loopback
/// with permissive CORS and hands the port to the browser via a hybrid
/// isolate. Every web-targeting plugin needs the identical rig; generating it
/// keeps the wiring — CORS headers, the wasm MIME type, the dart2wasm
/// number-decoding caveat — out of each project.
void _scaffoldWebTests(String base, List<ModuleInfo> webModules, File pubspecFile) {
  if (webModules.isEmpty) return;
  final testDir = Directory(p.join(base, 'test'))..createSync(recursive: true);

  final server = File(p.join(testDir.path, 'asset_server.dart'));
  if (!server.existsSync()) server.writeAsStringSync(_webAssetServerTemplate);

  // The PACKAGE name, not the module lib name — they differ (`benchmark` vs
  // `benchmark_cpp`), and guessing from the lib name does not compile.
  final pkgName = _packageNameOf(pubspecFile) ?? p.basename(p.normalize(p.absolute(base)));

  for (final m in webModules) {
    final stub = File(p.join(testDir.path, '${m.lib}_web_test.dart'));
    if (!stub.existsSync()) {
      stub.writeAsStringSync(_webTestStubTemplate(m.lib, m.module, pkgName));
    }
  }
  _ensureWebTestDevDeps(pubspecFile);
}

/// The `name:` field of [pubspecFile], or null when it cannot be read.
String? _packageNameOf(File pubspecFile) {
  if (!pubspecFile.existsSync()) return null;
  final match = RegExp(r'''^name:\s*["']?([A-Za-z_][A-Za-z0-9_]*)["']?\s*$''', multiLine: true)
      .firstMatch(pubspecFile.readAsStringSync());
  return match?.group(1);
}

/// Hybrid isolate (VM side) serving the built module to the browser test.
const _webAssetServerTemplate = r'''
// Generated by `nitrogen link`. Runs on the VM as a hybrid isolate: serves
// assets/web/ to the browser test with permissive CORS and reports the port.
import 'dart:io';

import 'package:stream_channel/stream_channel.dart';

Future<void> hybridMain(StreamChannel<Object?> channel) async {
  final dir = Directory.current.path;
  final server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
  server.listen((req) async {
    final name = req.uri.path.split('/').last;
    final file = File('$dir/assets/web/$name');
    req.response.headers.set('Access-Control-Allow-Origin', '*');
    if (!file.existsSync()) {
      req.response.statusCode = 404;
      await req.response.close();
      return;
    }
    // The .wasm MUST be served as application/wasm or instantiateStreaming
    // refuses it.
    req.response.headers.contentType = name.endsWith('.wasm')
        ? ContentType('application', 'wasm')
        : ContentType('text', 'javascript');
    await req.response.addStream(file.openRead());
    await req.response.close();
  });
  channel.sink.add(server.port);
  await channel.stream.drain<void>();
}
''';

/// Starter browser test — loads the module and proves the bridge is live.
/// Written once; add real cases to it.
String _webTestStubTemplate(String lib, String className, String pkgName) => '''
// Starter browser test generated by `nitrogen link` (not overwritten again).
//
// Build the module first, then run under BOTH web compilers — they differ at
// the js_interop boundary, so a green dart2js run does not imply dart2wasm:
//   web/build_web.sh
//   dart test -p chrome
//   dart test -p chrome -c dart2wasm
@TestOn('browser')
library;

import 'package:test/test.dart';

import 'package:$pkgName/$pkgName.dart';
// ensure${className}Ready lives in the generated platform shim. It is imported
// directly because a package barrel does not necessarily re-export it — add
// `export 'src/$lib.platform.g.dart';` to the barrel if you want callers of
// your package to reach it too (web callers must await it before first use).
import 'package:$pkgName/src/$lib.platform.g.dart';

void main() {
  setUpAll(() async {
    final channel = spawnHybridUri('asset_server.dart');
    // dart2wasm hands JS numbers over as double — never cast with `as int`.
    final port = ((await channel.stream.first)! as num).toInt();
    await ensure${className}Ready(jsUrl: 'http://localhost:\$port/$lib.js');
  });

  test('module loads and the bridge answers', () {
    // Reaching here means the WASM module instantiated and the ABI-version
    // and bridge-checksum checks passed. Add real round-trips below.
    expect($className.instance, isNotNull);
  });
}
''';

/// Browser tests need `test` (the runner) and `stream_channel` (the hybrid
/// isolate channel). flutter_test cannot drive `-p chrome`.
void _ensureWebTestDevDeps(File pubspecFile) {
  if (!pubspecFile.existsSync()) return;
  var pubspec = pubspecFile.readAsStringSync();
  if (!RegExp(r'^dev_dependencies:\s*$', multiLine: true).hasMatch(pubspec)) return;

  final additions = <String>[
    if (!RegExp(r'^  test:', multiLine: true).hasMatch(pubspec)) '  test: ^1.25.8',
    if (!RegExp(r'^  stream_channel:', multiLine: true).hasMatch(pubspec)) '  stream_channel: ^2.1.2',
  ];
  if (additions.isEmpty) return;

  pubspec = pubspec.replaceFirst(
    RegExp(r'^dev_dependencies:\s*$', multiLine: true),
    'dev_dependencies:\n${additions.join('\n')}',
  );
  pubspecFile.writeAsStringSync(pubspec);
}

/// Adds `assets/web/` under the top-level `flutter:` key when absent.
/// Idempotent, and leaves an existing `assets:` list alone apart from adding
/// the one entry.
void _ensureWebAssetsDeclared(File pubspecFile) {
  if (!pubspecFile.existsSync()) return;
  var pubspec = pubspecFile.readAsStringSync();
  if (pubspec.contains('assets/web/')) return;

  final assetsKey = RegExp(r'^  assets:\s*$', multiLine: true);
  final flutterKey = RegExp(r'^flutter:\s*$', multiLine: true);
  if (assetsKey.hasMatch(pubspec)) {
    // Existing list — insert as the first entry so ordering stays stable.
    pubspec = pubspec.replaceFirst(assetsKey, '  assets:\n    - assets/web/');
  } else if (flutterKey.hasMatch(pubspec)) {
    // Insert as the FIRST CHILD of `flutter:`, never appended at end of file.
    // `flutter:` is frequently not the last top-level key — appending would
    // silently attach the entry to whatever section happens to be last
    // (dependency_overrides, say) and make the pubspec unparseable.
    pubspec = pubspec.replaceFirst(flutterKey, 'flutter:\n  assets:\n    - assets/web/');
  } else {
    return; // no flutter: section — not a Flutter package, nothing to wire
  }
  pubspecFile.writeAsStringSync(pubspec);
}

const String _bridgeChecksumPrefix = '# NITRO_BRIDGE_CHECKSUM ';

/// The generator's compile-time bridge checksum for [lib], read out of the
/// generated C++ that em++ compiles. Deliberately READ rather than recomputed:
/// a second implementation of `bridgeSpecChecksum` in the CLI would drift from
/// the generator's and report mismatches that do not exist.
String? readBridgeChecksum(String baseDir, String lib) {
  final bridge = File(p.join(baseDir, 'lib', 'src', 'generated', 'cpp', '$lib.bridge.g.cpp'));
  if (!bridge.existsSync()) return null;
  return RegExp('${lib}_nitro_bridge_checksum\\(void\\)\\s*\\{\\s*return\\s*"([0-9a-f]+)"')
      .firstMatch(bridge.readAsStringSync())
      ?.group(1);
}

/// The checksums [scriptContent] was stamped with, keyed by lib.
Map<String, String> stampedBridgeChecksums(String scriptContent) => {
      for (final m in RegExp('^$_bridgeChecksumPrefix(\\S+) (\\S+)\$', multiLine: true).allMatches(scriptContent))
        m.group(1)!: m.group(2)!,
    };

/// Relative path of the module's web-specific impl, as `build_web.sh` spells it.
String webSpecificImplPath(String lib) => 'web/src/Hybrid${_toPascalCase(lib)}.cpp';

/// True when [webSpecificImplPath] holds real code — the same on-disk test the
/// desktop CMakeLists use, so an untouched or comments-only stub keeps sharing.
bool webUsesSpecificImpl(String baseDir, String lib) => hasCustomPlatformImpl(baseDir, 'web', _toPascalCase(lib));

/// Content for a NEW `web/src/Hybrid<Class>.cpp`: the generator's starter
/// (`<lib>.impl.g.cpp` — every method with its signature) when `generate` has
/// produced one, the bare class otherwise. Both carry the shared-impl marker.
String webImplStarterContent(String baseDir, String lib) {
  final className = _toPascalCase(lib);
  final starter = File(p.join(baseDir, 'lib', 'src', 'generated', 'cpp', '$lib.impl.g.cpp'));
  if (!starter.existsSync()) return t.webCppStubContent(lib: lib, className: className);
  final body = starter.readAsStringSync();
  final implClass = RegExp(r'class (\w+) final : public Hybrid').firstMatch(body)?.group(1) ?? '${className}Impl';
  final keepFrom = body.indexOf('// Ownership conventions:');
  final include = body.indexOf('#include');
  final kept = body.substring(keepFrom >= 0 ? keepFrom : (include >= 0 ? include : 0));
  return t.webCppSeededContent(lib: lib, className: className, implClass: implClass, starterBody: kept);
}
