// Web (WASM) build wiring for `nitrogen init` / `nitrogen link`.
// Part of link_command.dart (all link/ files are parts of that library).
//
// The web target compiles the SAME generated C bridge (+ the plugin's C++
// impl sources) with Emscripten into `assets/web/[lib].js` + `.wasm`, which
// the generated web bridge loads at runtime via the Flutter asset bundle.
part of '../link_command.dart';

/// The em++ invocation per web-targeting module. Flag set verified by the
/// nitro web e2e suite:
///   * -fwasm-exceptions — the bridge's try/catch → NitroError contract
///   * MODULARIZE + EXPORT_NAME `create<LibPascal>Module` — what
///     NitroRuntime.loadWebModule calls (nitroWebExportName convention)
///   * addFunction/wasmMemory/HEAPU8 runtime methods — heap I/O + the post
///     callback replacing Dart_PostCObject
String webBuildScriptTemplate(List<String> webLibs) {
  final b = StringBuffer('''
#!/usr/bin/env bash
# Generated by `nitrogen link`. Module list is kept in sync — re-run
# `nitrogen link` after adding a web-targeting module; edit flags freely.
#
# Builds the plugin's WASM module(s) into assets/web/ (bundled as Flutter
# assets — declared under `flutter: assets:` in pubspec.yaml).
# Requires the Emscripten SDK on PATH: https://emscripten.org/docs/getting_started
set -euo pipefail

cd "\$(dirname "\$0")/.."
GEN="lib/src/generated/cpp"
OUT="assets/web"
mkdir -p "\$OUT"

# The plugin's C++ impl sources: prefer the Hybrid*.cpp convention (only the
# nitro impl files — other modules' native code must not be linked into this
# wasm), falling back to all of src/*.cpp for single-impl layouts.
# dart_api_dl.c is VM-only — never compile it for web (nitro_wasm_compat.h
# shims the Dart API under __EMSCRIPTEN__).
IMPL_SOURCES=\$(ls src/Hybrid*.cpp 2>/dev/null || ls src/*.cpp 2>/dev/null | grep -v dart_api_dl || true)
''');
  for (final lib in webLibs) {
    final pascal = lib.split(RegExp('[_-]+')).where((s) => s.isNotEmpty).map((s) => s[0].toUpperCase() + s.substring(1)).join();
    b.write('''

em++ -O2 --no-entry -fwasm-exceptions \\
  -Isrc -Isrc/native -I"\$GEN" \\
  "\$GEN/$lib.bridge.g.cpp" \$IMPL_SOURCES \\
  -sMODULARIZE=1 -sEXPORT_NAME=create${pascal}Module \\
  -sALLOW_MEMORY_GROWTH=1 -sALLOW_TABLE_GROWTH=1 \\
  -sWASM_BIGINT=1 -sENVIRONMENT=web \\
  -sEXPORTED_RUNTIME_METHODS=addFunction,wasmExports,wasmMemory,HEAPU8 \\
  -sEXPORTED_FUNCTIONS=_malloc,_free \\
  -o "\$OUT/$lib.js"
echo "built \$OUT/$lib.js + \$OUT/$lib.wasm"
''');
  }
  return b.toString();
}

/// Writes/refreshes `web/build_web.sh` for the web-targeting modules and
/// ensures the `assets/web/` asset directory exists. No-op (removes nothing)
/// when no module targets web.
///
/// Returns the number of web-targeting modules wired.
int linkWeb(String pluginName, List<ModuleInfo> moduleInfos, {String? baseDir}) {
  final base = baseDir ?? pluginName;
  final webLibs = moduleInfos.where((m) => m.webIsWasm).map((m) => m.lib).toList();
  if (webLibs.isEmpty) return 0;

  final webDir = Directory(p.join(base, 'web'))..createSync(recursive: true);
  final script = File(p.join(webDir.path, 'build_web.sh'));
  script.writeAsStringSync(webBuildScriptTemplate(webLibs));
  if (!Platform.isWindows) {
    Process.runSync('chmod', ['+x', script.path]);
  }

  final assetsDir = Directory(p.join(base, 'assets', 'web'))..createSync(recursive: true);
  final gitkeep = File(p.join(assetsDir.path, '.gitkeep'));
  if (!gitkeep.existsSync()) {
    gitkeep.writeAsStringSync('# WASM build outputs land here (web/build_web.sh)\n');
  }
  return webLibs.length;
}
