// Generated by Nitrogen Modules. Do not edit.
// Generated from: nitro_battery.native.dart
import Foundation
import Combine

// --- Enums ---
public enum ChargingState: Int64 {
  case unknown = 0
  case charging = 1
  case discharging = 2
  case full = 3
}

// --- Structs ---
public struct BatteryInfo {
  public var level: Int64
  public var chargingState: Int64
  public var voltage: Double
  public var temperature: Double
}

/**
 * Protocol for the NitroBattery module.
 * Conform to this in your Swift source code.
 */
public protocol HybridNitroBatteryProtocol: AnyObject {
    func getBatteryLevel() -> Int64
    func isCharging() -> Bool
    func getChargingState() -> ChargingState
    func getBatteryInfo() async throws -> BatteryInfo
    var lowPowerThreshold: Int64 { get set }
    var batteryLevelChanges: AnyPublisher<Int64, Never> { get }
}

public class NitroBatteryRegistry {
    public static var impl: HybridNitroBatteryProtocol?

    public static func register(_ impl: HybridNitroBatteryProtocol) {
        NitroBatteryRegistry.impl = impl
    }

    // Stream: batteryLevelChanges cancellables keyed by dartPort
    public static var _batteryLevelChangesCancellables = [Int64: AnyCancellable]()
}

// MARK: - C bridge stubs — exported as C symbols called by the generated .cpp shim

@_cdecl("_call_getBatteryLevel")
public func _call_getBatteryLevel() -> Int64 {
    guard let impl = NitroBatteryRegistry.impl else { return 0 }
    return impl.getBatteryLevel()
}

@_cdecl("_call_isCharging")
public func _call_isCharging() -> Int8 {
    return (NitroBatteryRegistry.impl?.isCharging() ?? false) ? 1 : 0
}

@_cdecl("_call_getChargingState")
public func _call_getChargingState() -> Int64 {
    guard let impl = NitroBatteryRegistry.impl else { return 0 }
    return impl.getChargingState().rawValue
}

@_cdecl("_call_getBatteryInfo")
public func _call_getBatteryInfo() -> UnsafeMutableRawPointer? {
    guard let impl = NitroBatteryRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: BatteryInfo? = nil
    Task.detached {
        result = try? await impl.getBatteryInfo()
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<BatteryInfo>.allocate(capacity: 1)
    ptr.initialize(to: r)
    return UnsafeMutableRawPointer(ptr)
}

@_cdecl("_call_get_lowPowerThreshold")
public func _call_get_lowPowerThreshold() -> Int64 {
    return NitroBatteryRegistry.impl?.lowPowerThreshold ?? 0
}

@_cdecl("_call_set_lowPowerThreshold")
public func _call_set_lowPowerThreshold(_ value: Int64) {
    NitroBatteryRegistry.impl?.lowPowerThreshold = value
}

@_cdecl("_register_batteryLevelChanges_stream")
public func _register_batteryLevelChanges_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, Int64) -> Void
) {
    NitroBatteryRegistry._batteryLevelChangesCancellables[dartPort] =
        NitroBatteryRegistry.impl?.batteryLevelChanges.sink { item in
            emitCb(dartPort, item)
        }
}

@_cdecl("_release_batteryLevelChanges_stream")
public func _release_batteryLevelChanges_stream(_ dartPort: Int64) {
    NitroBatteryRegistry._batteryLevelChangesCancellables[dartPort]?.cancel()
    NitroBatteryRegistry._batteryLevelChangesCancellables.removeValue(forKey: dartPort)
}
