// Generated by Nitrogen Modules. Do not edit.
part of 'nitro_battery.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension ChargingStateNativeExt on ChargingState {
  int get nativeValue => index + 0;
}

extension ChargingStateFromNativeExt on int {
  ChargingState toChargingState() => ChargingState.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

final class BatteryInfoFfi extends Struct {
  @Int64()
  external int level;
  @Int64()
  external int chargingState;
  @Double()
  external double voltage;
  @Double()
  external double temperature;
}

extension BatteryInfoFfiExt on BatteryInfoFfi {
  BatteryInfo toDart() {
    return BatteryInfo(
      level: level,
      chargingState: chargingState,
      voltage: voltage,
      temperature: temperature,
    );
  }
}

extension BatteryInfoExt on BatteryInfo {
  Pointer<BatteryInfoFfi> toNative(Arena arena) {
    final ptr = arena<BatteryInfoFfi>();
    ptr.ref.level = level;
    ptr.ref.chargingState = chargingState;
    ptr.ref.voltage = voltage;
    ptr.ref.temperature = temperature;
    return ptr;
  }
}

class _NitroBatteryImpl extends NitroBattery {
  final DynamicLibrary _dylib;

  _NitroBatteryImpl() : _dylib = NitroRuntime.loadLib('nitro_battery') {
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('InitDartApiDL');
    initFunc(NativeApi.initializeApiDLData);
  }

  late final int Function() _getBatteryLevelPtr = _dylib
      .lookupFunction<Int64 Function(), int Function()>(
        'nitro_battery_get_battery_level',
      );
  late final int Function() _isChargingPtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_battery_is_charging',
      );
  late final int Function() _getChargingStatePtr = _dylib
      .lookupFunction<Int64 Function(), int Function()>(
        'nitro_battery_get_charging_state',
      );
  late final Pointer<Void> Function() _getBatteryInfoPtr = _dylib
      .lookupFunction<Pointer<Void> Function(), Pointer<Void> Function()>(
        'nitro_battery_get_battery_info',
      );
  late final int Function() _getLowPowerThresholdPtr = _dylib
      .lookupFunction<Int64 Function(), int Function()>(
        'nitro_battery_get_low_power_threshold',
      );
  late final void Function(int) _setLowPowerThresholdPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_battery_set_low_power_threshold',
      );
  late final void Function(int) _registerBatteryLevelChangesPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_battery_register_battery_level_changes_stream',
      );
  late final void Function(int) _releaseBatteryLevelChangesPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_battery_release_battery_level_changes_stream',
      );
  @override
  // ignore: unnecessary_overrides
  void dispose() {
    super.dispose(); // sets isDisposed = true, calls onDestroy()
  }

  @override
  int getBatteryLevel() {
    checkDisposed();
    return _getBatteryLevelPtr();
  }

  @override
  bool isCharging() {
    checkDisposed();
    return _isChargingPtr() != 0;
  }

  @override
  ChargingState getChargingState() {
    checkDisposed();
    return (_getChargingStatePtr()).toChargingState();
  }

  @override
  Future<BatteryInfo> getBatteryInfo() async {
    checkDisposed();
    final asyncResult = await NitroRuntime.callAsync(_getBatteryInfoPtr, []);
    return Pointer<BatteryInfoFfi>.fromAddress(
      (asyncResult as Pointer<Void>).address,
    ).ref.toDart();
  }

  @override
  int get lowPowerThreshold {
    checkDisposed();
    return _getLowPowerThresholdPtr();
  }

  @override
  set lowPowerThreshold(int value) {
    checkDisposed();
    _setLowPowerThresholdPtr(value);
  }

  @override
  Stream<int> get batteryLevelChanges {
    checkDisposed();
    return NitroRuntime.openStream<int>(
      register: (port) => _registerBatteryLevelChangesPtr(port),
      unpack: (rawPtr) => rawPtr as int,
      release: (port) => _releaseBatteryLevelChangesPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }
}
