// Generated by nitrogen link — do not edit.
// Compiled as C (not C++) so the void*/function-pointer casts
// in dart_api_dl.c are accepted by the compiler.
#include "../../packages/nitro/src/native/dart_api_dl.c"
