name: nitrogen_cli
description: "CLI for Nitrogen Modules. Scaffold new Flutter FFI plugins and generate native bridge code."
version: 0.1.4
homepage: https://github.com/Shreemanarjun/nitro_ecosystem
repository: https://github.com/Shreemanarjun/nitro_ecosystem/tree/main/packages/nitrogen_cli
issue_tracker: https://github.com/Shreemanarjun/nitro_ecosystem/issues

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  nocterm: ^0.5.1
  nocterm_unrouter: ^0.1.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  nitrogen: nitrogen
