name: nitrogen_cli
description: "CLI for Nitrogen Modules. Scaffold new Flutter FFI plugins and generate native bridge code."
version: 0.3.0
homepage: https://nitro.shreeman.dev
repository: https://github.com/Shreemanarjun/nitro_ecosystem
issue_tracker: https://github.com/Shreemanarjun/nitro_ecosystem/issues
documentation: https://nitro.shreeman.dev/
funding:
  - https://buymeacoffee.com/shreemanarjun
topics:
  - cli
  - codegen
  - ffi
  - flutter
  - native

environment:
  sdk: ^3.11.3
resolution: workspace

dependencies:
  args: ^2.5.0
  nocterm: ^0.5.1
  nocterm_unrouter: ^0.1.0
  path: ^1.9.0
  watcher: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

executables:
  nitrogen: nitrogen
