import 'package:nitro_generator/src/generators/cmake_generator.dart';
import 'package:test/test.dart';
import 'test_utils.dart';

void main() {
  group('CMakeGenerator', () {
    test('emits cmake_minimum_required', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('cmake_minimum_required'));
    });

    test('sets NITRO_MODULE_NAME to lib name', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('set(NITRO_MODULE_NAME my_camera)'));
    });

    test('emits add_library with module name variable', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('add_library('));
    });

    test('links android and log', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('android'));
      expect(out, contains('log'));
    });

    test('lib name in NITRO_MODULE_NAME matches spec.lib', () {
      final out = CMakeGenerator.generate(enumSpec());
      expect(out, contains('set(NITRO_MODULE_NAME complex)'));
    });

    test('emits generated-file attribution comment', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('# Generated by Nitrogen Modules'));
      expect(out, contains('# Generated from: my_camera.native.dart'));
    });

    test('references bridge header via cmake variable in add_library', () {
      final out = CMakeGenerator.generate(simpleSpec());
      // CMake uses ${${NITRO_MODULE_NAME}}_bridge.g.h (variable indirection)
      expect(out, contains('\${NITRO_MODULE_NAME}}_bridge.g.h'));
    });

    test('target_link_libraries uses module name variable', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('target_link_libraries(\${\${NITRO_MODULE_NAME}}'));
    });

    test('iOS-only spec generates same valid CMake structure', () {
      final out = CMakeGenerator.generate(iosOnlySpec());
      expect(out, contains('cmake_minimum_required'));
      expect(out, contains('set(NITRO_MODULE_NAME ios_camera)'));
      expect(out, contains('add_library('));
    });

    test('Android-only spec generates same valid CMake structure', () {
      final out = CMakeGenerator.generate(androidOnlySpec());
      expect(out, contains('cmake_minimum_required'));
      expect(out, contains('set(NITRO_MODULE_NAME android_sensor)'));
    });

    test('cpp spec generates same CMake as swift/kotlin spec', () {
      final cppOut = CMakeGenerator.generate(cppSpec());
      final swiftOut = CMakeGenerator.generate(simpleSpec());
      // Both should have same structure — only module name differs
      expect(cppOut, contains('cmake_minimum_required'));
      expect(cppOut, contains('add_library('));
      expect(cppOut, contains('target_link_libraries('));
      // structure should match
      expect(cppOut.split('\n').length, equals(swiftOut.split('\n').length));
    });
  });
}
