import 'package:nitro_annotations/nitro_annotations.dart';
import 'package:nitro_generator/src/bridge_spec.dart';
import 'package:nitro_generator/src/generators/languages/cmake/cmake_generator.dart';
import 'package:test/test.dart';
import 'test_utils.dart';

void main() {
  group('CMakeGenerator', () {
    test('emits cmake_minimum_required', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('cmake_minimum_required'));
    });

    test('sets NITRO_MODULE_NAME to lib name', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('set(NITRO_MODULE_NAME my_camera)'));
    });

    test('emits add_library with module name variable', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('add_library('));
    });

    test('emits generated-file attribution comment', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('# Generated by Nitrogen Modules'));
      expect(out, contains('# Generated from: my_camera.native.dart'));
    });

    test('Android spec: links android + log', () {
      final out = CMakeGenerator.generate(simpleSpec()); // android+ios
      expect(out, contains('android'));
      expect(out, contains('log'));
    });

    test('Android section uses if(ANDROID)', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('if(ANDROID)'));
      expect(out, contains('target_link_libraries(\${NITRO_MODULE_NAME} PRIVATE android log)'));
    });

    test('Windows section: MSVC C flag for dart_api_dl.c', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('elseif(WIN32)'));
      expect(out, contains('PROPERTIES LANGUAGE C'));
    });

    test('Linux section: links dl + pthread', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('elseif(UNIX AND NOT APPLE)'));
      expect(out, contains('target_link_libraries(\${NITRO_MODULE_NAME} PRIVATE dl pthread)'));
    });

    test('CXX_STANDARD 17 is enforced', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('CXX_STANDARD 17'));
      expect(out, contains('CXX_STANDARD_REQUIRED ON'));
    });

    test('DART_SHARED_LIB compile definition is emitted', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('DART_SHARED_LIB'));
    });

    test('NITRO_NATIVE and GENERATED_CPP variables are defined', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('set(NITRO_NATIVE'));
      expect(out, contains('set(GENERATED_CPP'));
    });

    test('target_include_directories contains NITRO_NATIVE and GENERATED_CPP', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('target_include_directories(\${NITRO_MODULE_NAME} PRIVATE'));
      expect(out, contains('\${NITRO_NATIVE}'));
      expect(out, contains('\${GENERATED_CPP}'));
    });

    test('bridge.g.cpp is included in add_library sources', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('my_camera.bridge.g.cpp'));
    });

    test('dart_api_dl.c is included in add_library sources', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('dart_api_dl.c'));
    });

    test('lib name in NITRO_MODULE_NAME matches spec.lib', () {
      final out = CMakeGenerator.generate(enumSpec());
      expect(out, contains('set(NITRO_MODULE_NAME complex)'));
    });

    test('iOS-only spec generates valid CMake structure', () {
      final out = CMakeGenerator.generate(iosOnlySpec());
      expect(out, contains('cmake_minimum_required'));
      expect(out, contains('set(NITRO_MODULE_NAME ios_camera)'));
      expect(out, contains('add_library('));
      expect(out, contains('CXX_STANDARD 17'));
    });

    test('Android-only spec generates valid CMake structure', () {
      final out = CMakeGenerator.generate(androidOnlySpec());
      expect(out, contains('cmake_minimum_required'));
      expect(out, contains('set(NITRO_MODULE_NAME android_sensor)'));
    });

    test('Windows-only spec generates valid CMake structure', () {
      final spec = BridgeSpec(
        dartClassName: 'Desktop',
        lib: 'desktop',
        namespace: 'desktop',
        windowsImpl: NativeImpl.cpp,
        sourceUri: 'desktop.native.dart',
        functions: [],
      );
      final out = CMakeGenerator.generate(spec);
      expect(out, contains('set(NITRO_MODULE_NAME desktop)'));
      expect(out, contains('elseif(WIN32)'));
      expect(out, contains('PROPERTIES LANGUAGE C'));
    });

    test('Linux-only spec generates valid CMake structure', () {
      final spec = BridgeSpec(
        dartClassName: 'Linux',
        lib: 'linux_mod',
        namespace: 'linux_mod',
        linuxImpl: NativeImpl.cpp,
        sourceUri: 'linux.native.dart',
        functions: [],
      );
      final out = CMakeGenerator.generate(spec);
      expect(out, contains('set(NITRO_MODULE_NAME linux_mod)'));
      expect(out, contains('elseif(UNIX AND NOT APPLE)'));
      expect(out, contains('dl pthread'));
    });

    test('cpp spec generates same structural sections as swift/kotlin spec', () {
      final cppOut = CMakeGenerator.generate(cppSpec());
      final swiftOut = CMakeGenerator.generate(simpleSpec());
      expect(cppOut, contains('cmake_minimum_required'));
      expect(cppOut, contains('add_library('));
      expect(cppOut, contains('if(ANDROID)'));
      expect(swiftOut, contains('if(ANDROID)'));
    });

    test('emits bridge checksum in comment', () {
      final out = CMakeGenerator.generate(simpleSpec());
      expect(out, contains('# nitro bridge checksum:'));
    });
  });
}
