import 'dart:io';

import 'package:nitro_annotations/nitro_annotations.dart';
import 'package:nitro_generator/src/bridge_spec.dart';
import 'package:nitro_generator/src/generators/generator_metadata.dart';
import 'package:nitro_generator/src/generators/languages/c_bridge/cpp_bridge_generator.dart';
import 'package:nitro_generator/src/generators/languages/c_bridge/cpp_header_generator.dart';
import 'package:nitro_generator/src/generators/languages/cmake/cmake_generator.dart';
import 'package:nitro_generator/src/generators/languages/cpp_native/cpp_interface_generator.dart';
import 'package:nitro_generator/src/generators/languages/cpp_native/cpp_mock_generator.dart';
import 'package:nitro_generator/src/generators/languages/dart/dart_ffi_generator.dart';
import 'package:nitro_generator/src/generators/languages/kotlin/kotlin_generator.dart';
import 'package:nitro_generator/src/generators/languages/swift/swift_generator.dart';
import 'package:test/test.dart';

void main() {
  group('generated metadata headers', () {
    test('all generator outputs include the shared nitro_generator version marker', () {
      final swiftKotlinSpec = _spec(
        iosImpl: NativeImpl.swift,
        androidImpl: NativeImpl.kotlin,
      );
      final cppSpec = _spec(
        iosImpl: NativeImpl.cpp,
        androidImpl: NativeImpl.cpp,
      );

      final outputs = <String, String>{
        'dart': DartFfiGenerator.generate(swiftKotlinSpec),
        'swift': SwiftGenerator.generate(swiftKotlinSpec),
        'kotlin': KotlinGenerator.generate(swiftKotlinSpec),
        'c_bridge': CppBridgeGenerator.generate(swiftKotlinSpec),
        'c_header': CppHeaderGenerator.generate(swiftKotlinSpec),
        'cmake': CMakeGenerator.generate(swiftKotlinSpec),
        'cpp_interface': CppInterfaceGenerator.generate(cppSpec),
        'cpp_mock': CppMockGenerator.generateMockHeader(cppSpec),
        'cpp_test': CppMockGenerator.generateTestStarter(cppSpec),
      };

      for (final entry in outputs.entries) {
        expect(
          entry.value,
          contains('nitro_generator: $nitroGeneratorVersion'),
          reason: '${entry.key} output must carry stale-generation metadata',
        );
        expect(
          entry.value,
          isNot(contains('Generator version: 0.3.5')),
          reason: '${entry.key} output must not use the old hardcoded Swift version',
        );
      }
    });

    test('CMake output uses CMake comments for metadata', () {
      final out = CMakeGenerator.generate(_spec());
      expect(out, startsWith('# Generated by Nitrogen Modules. Do not edit.\n'));
      expect(out, contains('# nitro_generator: $nitroGeneratorVersion\n'));
      expect(out, contains('# Generated from: camera.native.dart\n'));
    });

    test('shared metadata version matches pubspec package version', () {
      final repoRoot = _findRepoRoot();
      final pubspec = File('$repoRoot/packages/nitro_generator/pubspec.yaml').readAsStringSync();
      expect(pubspec, contains('version: $nitroGeneratorVersion'));
    });
  });
}

String _findRepoRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/pubspec.yaml').existsSync() &&
        File('${dir.path}/pubspec.yaml').readAsStringSync().contains('workspace:')) {
      return dir.path;
    }
    final parent = dir.parent;
    if (parent.path == dir.path) break;
    dir = parent;
  }
  return Directory.current.path;
}

BridgeSpec _spec({
  NativeImpl iosImpl = NativeImpl.swift,
  NativeImpl androidImpl = NativeImpl.kotlin,
}) {
  return BridgeSpec(
    dartClassName: 'Camera',
    lib: 'camera',
    namespace: 'camera',
    iosImpl: iosImpl,
    androidImpl: androidImpl,
    sourceUri: 'lib/src/camera.native.dart',
    functions: [
      BridgeFunction(
        dartName: 'ping',
        cSymbol: 'camera_ping',
        isAsync: false,
        returnType: BridgeType(name: 'int'),
        params: const [],
      ),
    ],
  );
}
