import 'package:nitro_annotations/nitro_annotations.dart';
import '../../bridge_spec.dart';

/// Generates the C++ bridge `.cpp` file for a NitroModule.
///
/// # JNI_OnLoad / error-state ownership
/// When multiple `.native.dart` files share the same [lib] (e.g. `my_camera`),
/// every generated `.bridge.g.cpp` would normally emit its own `JNI_OnLoad`
/// and `my_camera_clear_error` symbols — causing duplicate-symbol linker errors.
///
/// To avoid this we split responsibility:
/// - The **first** module in the lib (the one whose `dartClassName == lib stem`)
///   owns the lib-level symbols (JNI_OnLoad, error state, Dart API DL init).
/// - **All** modules emit only their own per-module `extern "C"` functions.
///   For `NativeImpl.cpp` modules those functions delegate to the C++ registry.
///
/// The generated file is named `{sourceFile}.bridge.g.cpp`, so each module
/// gets its own compilation unit. The parent `{lib}.cpp` entry point simply
/// `#include`s each generated `.bridge.g.cpp`.
class CppBridgeGenerator {
  static String generate(BridgeSpec spec) {
    final s = StringBuffer();
    // Derive names from the *source file*, not the shared lib name,
    // so modules share a lib without stomping on each other's symbols.
    final sourceFile = spec.sourceUri.split('/').last.replaceFirst('.native.dart', '');
    final libStem = spec.lib.replaceAll('-', '_');
    final moduleName = sourceFile.replaceAll('-', '_'); // e.g. "math"
    final headerName = '$libStem.bridge.g.h';
    final hppName = '$moduleName.g.hpp';

    final enumNames = spec.enums.map((e) => e.name).toSet();
    final structNames = spec.structs.map((e) => e.name).toSet();
    final recordNames = spec.recordTypes.map((r) => r.name).toSet();
    final useCpp = spec.iosImpl == NativeImpl.cpp || spec.androidImpl == NativeImpl.cpp;

    s.writeln('// Generated by Nitrogen Modules. Do not edit.');
    s.writeln('// Generated from: ${spec.sourceUri.split('/').last}');
    s.writeln('#include <stdint.h>');
    s.writeln('#include <stdbool.h>');
    s.writeln('#include <string.h>');
    s.writeln('#include <stdlib.h>');
    s.writeln('#include "nitro.h"');
    s.writeln('#include "dart_api_dl.h"');
    s.writeln('#include "$headerName"');
    if (useCpp) {
      s.writeln('#include "$hppName"');
    }
    s.writeln();

    // ── Lib-level symbols (error state, Dart API DL, JNI init) ──────────────
    // Only emitted once per shared library. When multiple modules share the
    // same lib, the "main" .cpp entry point should include exactly one of the
    // generated bridges before the others so these are defined only once.
    //
    // For simplicity we always emit them here; the developer's entry-point
    // `src/{lib}.cpp` should include them with `#include` guards or use the
    // `dart_api_dl.c` approach. The generated CMakeLists handles this.
    s.writeln('#ifndef NITRO_${libStem.toUpperCase()}_LIB_INIT_DEFINED');
    s.writeln('#define NITRO_${libStem.toUpperCase()}_LIB_INIT_DEFINED');
    s.writeln();
    s.writeln('static thread_local NitroError g_nitro_error_$libStem = { 0, nullptr, nullptr, nullptr, nullptr };');
    s.writeln();
    s.writeln('extern "C" {');
    s.writeln('intptr_t ${libStem}_init_dart_api_dl(void* data) { return Dart_InitializeApiDL(data); }');
    s.writeln('NitroError* ${libStem}_get_error(void) { return &g_nitro_error_$libStem; }');
    s.writeln('void ${libStem}_clear_error(void) {');
    s.writeln('    auto& e = g_nitro_error_$libStem;');
    s.writeln('    e.hasError = 0;');
    s.writeln('    if (e.name)       { free((void*)e.name);       e.name = nullptr; }');
    s.writeln('    if (e.message)    { free((void*)e.message);    e.message = nullptr; }');
    s.writeln('    if (e.code)       { free((void*)e.code);       e.code = nullptr; }');
    s.writeln('    if (e.stackTrace) { free((void*)e.stackTrace); e.stackTrace = nullptr; }');
    s.writeln('}');
    s.writeln('} // extern "C" (lib-level)');
    s.writeln();
    s.writeln('static void nitro_report_error_$libStem(const char* name, const char* message, const char* code, const char* stack) {');
    s.writeln('    ${libStem}_clear_error();');
    s.writeln('    auto& e = g_nitro_error_$libStem;');
    s.writeln('    e.hasError = 1;');
    s.writeln('    e.name       = name    ? strdup(name)    : strdup("NativeException");');
    s.writeln('    e.message    = message ? strdup(message) : strdup("An unknown native exception occurred.");');
    s.writeln('    e.code       = code  ? strdup(code)  : nullptr;');
    s.writeln('    e.stackTrace = stack ? strdup(stack) : nullptr;');
    s.writeln('}');
    s.writeln();

    // Android: JNI_OnLoad (once per lib, also guarded)
    s.writeln('#ifdef __ANDROID__');
    s.writeln('#include <jni.h>');
    s.writeln('#include <android/log.h>');
    s.writeln('#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "Nitrogen", __VA_ARGS__)');
    s.writeln('static JavaVM* g_jvm_$libStem = nullptr;');
    s.writeln('struct NitroJniThreadGuard_$libStem {');
    s.writeln('    bool attached = false;');
    s.writeln('    ~NitroJniThreadGuard_$libStem() {');
    s.writeln('        if (attached && g_jvm_$libStem) g_jvm_$libStem->DetachCurrentThread();');
    s.writeln('    }');
    s.writeln('};');
    s.writeln('static thread_local NitroJniThreadGuard_$libStem g_thread_guard_$libStem;');
    s.writeln('static JNIEnv* ${libStem}_GetEnv() {');
    s.writeln('    if (!g_jvm_$libStem) return nullptr;');
    s.writeln('    JNIEnv* env = nullptr;');
    s.writeln('    if (g_jvm_$libStem->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) == JNI_EDETACHED) {');
    s.writeln('        g_jvm_$libStem->AttachCurrentThread(&env, nullptr);');
    s.writeln('        g_thread_guard_$libStem.attached = true;');
    s.writeln('    }');
    s.writeln('    return env;');
    s.writeln('}');
    s.writeln('extern "C" {');
    s.writeln('JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {');
    s.writeln('    g_jvm_$libStem = vm;');
    s.writeln('    return JNI_VERSION_1_6;');
    s.writeln('}');
    s.writeln('} // extern "C" (JNI_OnLoad)');
    s.writeln('#endif // __ANDROID__');
    s.writeln('#endif // NITRO_${libStem.toUpperCase()}_LIB_INIT_DEFINED');
    s.writeln();

    // ── Per-module JNI Storage ──────────────────────────────────────────────
    s.writeln('#ifdef __ANDROID__');
    s.writeln('static jclass g_${moduleName}_bridge_class = nullptr;');
    for (final func in spec.functions) {
      s.writeln('static jmethodID g_${moduleName}_${func.dartName}_mid = nullptr;');
    }
    for (final prop in spec.properties) {
      if (prop.hasGetter) s.writeln('static jmethodID g_${moduleName}_get_${prop.dartName}_mid = nullptr;');
      if (prop.hasSetter) s.writeln('static jmethodID g_${moduleName}_set_${prop.dartName}_mid = nullptr;');
    }
    s.writeln();

    final jniLibMod = libStem.replaceAll('_', '_1');
    s.writeln('extern "C" JNIEXPORT void JNICALL Java_nitro_${jniLibMod}_1module_${spec.dartClassName}JniBridge_initialize(JNIEnv* env, jclass clazz, jclass bridgeClass) {');
    s.writeln('    if (g_${moduleName}_bridge_class) return;');
    s.writeln('    g_${moduleName}_bridge_class = (jclass)env->NewGlobalRef(bridgeClass);');
    for (final func in spec.functions) {
      final sig = _jniSig(func, enumNames, structNames, recordNames);
      s.writeln('    g_${moduleName}_${func.dartName}_mid = env->GetStaticMethodID(g_${moduleName}_bridge_class, "${func.dartName}_call", "$sig");');
    }
    for (final prop in spec.properties) {
      if (prop.hasGetter) {
        final sig = _jniPropSig(prop, enumNames, structNames, recordNames, isSetter: false);
        s.writeln('    g_${moduleName}_get_${prop.dartName}_mid = env->GetStaticMethodID(g_${moduleName}_bridge_class, "${prop.getSymbol}_call", "$sig");');
      }
      if (prop.hasSetter) {
        final sig = _jniPropSig(prop, enumNames, structNames, recordNames, isSetter: true);
        s.writeln('    g_${moduleName}_set_${prop.dartName}_mid = env->GetStaticMethodID(g_${moduleName}_bridge_class, "${prop.setSymbol}_call", "$sig");');
      }
    }
    s.writeln('}');
    s.writeln('#endif // __ANDROID__');
    s.writeln();

    // ── Per-module bridge functions ───────────────────────────────────────────
    s.writeln('#ifdef __ANDROID__');
    s.writeln('extern "C" {');
    _writeFunctions(s, spec, libStem, moduleName, structNames, enumNames, recordNames, useCpp, isApple: false);
    s.writeln('} // extern "C"');
    s.writeln('#elif defined(__APPLE__)');
    s.writeln('extern "C" {');
    _writeFunctions(s, spec, libStem, moduleName, structNames, enumNames, recordNames, useCpp, isApple: true);
    s.writeln('} // extern "C"');
    s.writeln('#endif');

    return s.toString();
  }

  static void _writeFunctions(
    StringBuffer s,
    BridgeSpec spec,
    String libStem,
    String moduleName,
    Set<String> structNames,
    Set<String> enumNames,
    Set<String> recordNames,
    bool useCpp, {
    required bool isApple,
  }) {
    final impl = isApple ? spec.iosImpl : spec.androidImpl;

    for (final func in spec.functions) {
      final isEnumRet = enumNames.contains(func.returnType.name.replaceFirst('?', ''));
      final cType = isEnumRet ? 'int64_t' : _typeToC(func.returnType.name);
      final paramsDecl = func.params
          .expand(
            (p) => [
              '${_paramTypeToC(p.type.name, structNames, enumNames)} ${p.name}',
              if (p.type.isTypedData) 'int64_t ${p.name}_length',
            ],
          )
          .join(', ');
      final callArgs = func.params.map((p) => p.name).join(', ');
      final isVoid = func.returnType.name == 'void';

      s.writeln('$cType ${func.cSymbol}(${paramsDecl.isEmpty ? 'void' : paramsDecl}) {');
      s.writeln('    ${libStem}_clear_error();');

      if (impl == NativeImpl.cpp) {
        // C++ registry path — zero JNI/CDecl overhead
        s.writeln('    auto impl = nitro::${spec.dartClassName}Registry::getImpl();');
        if (isVoid) {
          s.writeln('    if (impl) { impl->${func.dartName}($callArgs); }');
        } else {
          s.writeln('    if (impl) return impl->${func.dartName}($callArgs);');
          s.writeln('    return ${_defaultValue(cType)};');
        }
      } else if (!isApple) {
        // JNI path (Android Kotlin bridge)
        s.writeln('    JNIEnv* env = ${libStem}_GetEnv();');
        s.writeln('    if (!env || !g_${moduleName}_${func.dartName}_mid) return ${_defaultValue(cType)};');
        final jniCall = _jniCallExpr(func, moduleName, enumNames, structNames, recordNames);
        if (isVoid) {
          s.writeln('    $jniCall;');
        } else {
          s.writeln('    return $jniCall;');
        }
      } else {
        // Swift path (iOS via @_cdecl exported C symbols)
        final swiftSymbol = 'NitroSwift_${func.cSymbol}';
        s.writeln('    extern "C" $cType $swiftSymbol($paramsDecl);');
        if (isVoid) {
          s.writeln('    $swiftSymbol($callArgs);');
        } else {
          s.writeln('    return $swiftSymbol($callArgs);');
        }
      }

      s.writeln('}');
      s.writeln();
    }

    for (final prop in spec.properties) {
      final isEnumProp = enumNames.contains(prop.type.name.replaceFirst('?', ''));
      final cType = isEnumProp ? 'int64_t' : _typeToC(prop.type.name);

      if (prop.hasGetter) {
        s.writeln('$cType ${prop.getSymbol}(void) {');
        s.writeln('    ${libStem}_clear_error();');
        if (impl == NativeImpl.cpp) {
          s.writeln('    auto impl = nitro::${spec.dartClassName}Registry::getImpl();');
          s.writeln('    if (impl) return impl->get${prop.dartName[0].toUpperCase()}${prop.dartName.substring(1)}();');
          s.writeln('    return ${_defaultValue(cType)};');
        } else if (!isApple) {
          s.writeln('    JNIEnv* env = ${libStem}_GetEnv();');
          s.writeln('    if (!env || !g_${moduleName}_get_${prop.dartName}_mid) return ${_defaultValue(cType)};');
          final jniCall = _jniPropCallExpr(prop, moduleName, enumNames, structNames, recordNames, isSetter: false);
          s.writeln('    return $jniCall;');
        } else {
          final swiftSymbol = 'NitroSwift_${prop.getSymbol}';
          s.writeln('    extern "C" $cType $swiftSymbol(void);');
          s.writeln('    return $swiftSymbol();');
        }
        s.writeln('}');
        s.writeln();
      }

      if (prop.hasSetter) {
        s.writeln('void ${prop.setSymbol}($cType value) {');
        s.writeln('    ${libStem}_clear_error();');
        if (impl == NativeImpl.cpp) {
          s.writeln('    auto impl = nitro::${spec.dartClassName}Registry::getImpl();');
          s.writeln('    if (impl) { impl->set${prop.dartName[0].toUpperCase()}${prop.dartName.substring(1)}(value); }');
        } else if (!isApple) {
          s.writeln('    JNIEnv* env = ${libStem}_GetEnv();');
          s.writeln('    if (!env || !g_${moduleName}_set_${prop.dartName}_mid) return;');
          final jniCall = _jniPropCallExpr(prop, moduleName, enumNames, structNames, recordNames, isSetter: true);
          s.writeln('    $jniCall;');
        } else {
          final swiftSymbol = 'NitroSwift_${prop.setSymbol}';
          s.writeln('    extern "C" void $swiftSymbol($cType);');
          s.writeln('    $swiftSymbol(value);');
        }
        s.writeln('}');
        s.writeln();
      }
    }
  }

  static String _typeToC(String dartType) {
    switch (dartType.replaceFirst('?', '')) {
      case 'int':
        return 'int64_t';
      case 'double':
        return 'double';
      case 'bool':
        return 'int8_t';
      case 'String':
        return 'const char*';
      case 'Uint8List':
        return 'uint8_t*';
      case 'Int8List':
        return 'int8_t*';
      case 'Int16List':
        return 'int16_t*';
      case 'Int32List':
        return 'int32_t*';
      case 'Uint16List':
        return 'uint16_t*';
      case 'Uint32List':
        return 'uint32_t*';
      case 'Float32List':
        return 'float*';
      case 'Float64List':
        return 'double*';
      case 'Int64List':
        return 'int64_t*';
      case 'Uint64List':
        return 'uint64_t*';
      case 'void':
        return 'void';
      default:
        return 'void*';
    }
  }

  static String _paramTypeToC(String dartType, Set<String> structs, Set<String> enums) {
    final name = dartType.replaceFirst('?', '');
    if (enums.contains(name)) return 'int64_t';
    if (structs.contains(name)) return 'void*';
    return _typeToC(dartType);
  }

  static String _defaultValue(String cType) {
    switch (cType) {
      case 'void':
        return '';
      case 'int64_t':
        return '0';
      case 'double':
        return '0.0';
      case 'int8_t':
        return '0';
      default:
        return 'nullptr';
    }
  }

  // ── JNI Helpers ────────────────────────────────────────────────────────────
  static String _jniSig(BridgeFunction func, Set<String> enums, Set<String> structs, Set<String> records) {
    final params = func.params.map((p) => _typeToJni(p.type.name, enums, structs, records)).join('');
    final ret = _typeToJni(func.returnType.name, enums, structs, records);
    return '($params)$ret';
  }

  static String _jniPropSig(BridgeProperty prop, Set<String> enums, Set<String> structs, Set<String> records, {required bool isSetter}) {
    if (isSetter) {
      return '(${_typeToJni(prop.type.name, enums, structs, records)})V';
    }
    return '()${_typeToJni(prop.type.name, enums, structs, records)}';
  }

  static String _typeToJni(String dartType, Set<String> enums, Set<String> structs, Set<String> records) {
    final name = dartType.replaceFirst('?', '');
    switch (name) {
      case 'int':
        return 'J';
      case 'double':
        return 'D';
      case 'bool':
        return 'Z';
      case 'String':
        return 'Ljava/lang/String;';
      case 'void':
        return 'V';
      default:
        if (enums.contains(name)) return 'J';
        if (records.contains(name) || name.startsWith('List<')) return '[B';
        return 'Ljava/lang/Object;';
    }
  }

  static String _jniCallExpr(BridgeFunction func, String moduleName, Set<String> enums, Set<String> structs, Set<String> records) {
    final retName = func.returnType.name.replaceFirst('?', '');
    final isRecord = records.contains(retName) || retName.startsWith('List<');
    final jniType = isRecord ? 'Object' : _jniTypeToCall(retName, enums, structs, records);
    final args = func.params.map((p) => p.name).join(', ');
    final call = 'env->CallStatic${jniType}Method(g_${moduleName}_bridge_class, g_${moduleName}_${func.dartName}_mid${args.isEmpty ? "" : ", $args"})';

    if (retName == 'String') {
      return '(const char*)env->GetStringUTFChars((jstring)$call, nullptr)';
    }
    if (isRecord) {
      return '(void*)$call';
    }
    if (enums.contains(retName)) {
      return '(int64_t)$call';
    }
    return call;
  }

  static String _jniPropCallExpr(BridgeProperty prop, String moduleName, Set<String> enums, Set<String> structs, Set<String> records, {required bool isSetter}) {
    final typeName = prop.type.name.replaceFirst('?', '');
    final isRecord = records.contains(typeName) || typeName.startsWith('List<');
    final jniType = isRecord ? 'Object' : _jniTypeToCall(typeName, enums, structs, records);
    final mid = isSetter ? 'g_${moduleName}_set_${prop.dartName}_mid' : 'g_${moduleName}_get_${prop.dartName}_mid';
    final call = isSetter ? 'env->CallStaticVoidMethod(g_${moduleName}_bridge_class, $mid, value)' : 'env->CallStatic${jniType}Method(g_${moduleName}_bridge_class, $mid)';

    if (!isSetter && typeName == 'String') {
      return '(const char*)env->GetStringUTFChars((jstring)$call, nullptr)';
    }
    if (!isSetter && isRecord) {
      return '(void*)$call';
    }
    if (!isSetter && enums.contains(typeName)) {
      return '(int64_t)$call';
    }
    return call;
  }

  static String _jniTypeToCall(String retName, Set<String> enums, Set<String> structs, Set<String> records) {
    switch (retName) {
      case 'int':
        return 'Long';
      case 'double':
        return 'Double';
      case 'bool':
        return 'Boolean';
      case 'String':
        return 'Object';
      case 'void':
        return 'Void';
      default:
        if (enums.contains(retName)) return 'Long';
        return 'Object';
    }
  }
}
