// Templates for C++ implementation stub files generated by `nitrogen link`.

/// Builds the `#if` guard condition for the auto-register call inside a
/// `src/HybridXxx.cpp` stub.
///
/// The guard ensures `${lib}_register_impl` is only called on platforms where
/// the C++ bridge is actually compiled — even if the stub file is accidentally
/// included on a platform that uses a Swift or Kotlin bridge instead.
///
/// Returns an empty string when no guard is needed (all compiled platforms are C++).
String autoRegisterPlatformGuard({
  required bool isNativeCpp,
  required bool isAndroidCpp,
  required bool iosIsCpp,
  required bool macosIsCpp,
  bool windowsIsCpp = false,
}) {
  // All apple + android/linux + windows → no guard needed
  if (isNativeCpp && macosIsCpp && iosIsCpp && windowsIsCpp) return '';

  final conditions = <String>[];
  if (windowsIsCpp) {
    // windows/CMakeLists.txt delegates to the shared src/ directory, so the
    // stub is compiled on Windows too — the guard must include _WIN32 or the
    // impl silently never registers on Windows.
    conditions.add('defined(_WIN32)');
  }
  if (isNativeCpp) {
    // isNativeCpp is true when Android OR Linux (or both) use C++.
    // When only Linux uses C++ (isAndroidCpp is false), Android must be excluded:
    // __linux__ is defined on Android NDK too, so `!defined(__APPLE__)` would
    // incorrectly compile the auto-register on Android where register_impl is absent.
    if (isAndroidCpp) {
      conditions.add('!defined(__APPLE__)'); // android + linux + windows
    } else {
      conditions.add('(defined(__linux__) && !defined(__ANDROID__))'); // linux only
    }
  }
  if (macosIsCpp && iosIsCpp) {
    conditions.add('defined(__APPLE__)');
  } else if (macosIsCpp) {
    conditions.add('(defined(__APPLE__) && TARGET_OS_OSX)');
  } else if (iosIsCpp) {
    conditions.add('(defined(__APPLE__) && TARGET_OS_IOS)');
  }
  return conditions.join(' || ');
}

/// Returns the content of a `src/Hybrid${className}.cpp` implementation stub.
///
/// [lib] is the snake_case library name (e.g. `nitro_bench`).
/// [className] is the PascalCase class name (e.g. `NitroBench`).
/// [isNativeCpp] true when android/linux uses C++ through `src/CMakeLists.txt`.
/// [iosIsCpp] / [macosIsCpp] per-Apple-platform C++ flags.
String cppImplStubContent({
  required String lib,
  required String className,
  required bool isNativeCpp,
  bool isAndroidCpp = false,
  required bool iosIsCpp,
  required bool macosIsCpp,
  bool windowsIsCpp = false,
}) {
  final guard = autoRegisterPlatformGuard(
    isNativeCpp: isNativeCpp,
    isAndroidCpp: isAndroidCpp,
    iosIsCpp: iosIsCpp,
    macosIsCpp: macosIsCpp,
    windowsIsCpp: windowsIsCpp,
  );
  final needsTargetConditionals = iosIsCpp || macosIsCpp;

  final buf = StringBuffer()
    ..writeln('// Hybrid$className — NativeImpl.cpp implementation.')
    ..writeln('// Generated by nitrogen link. Fill in the method bodies.')
    ..writeln('#include "../lib/src/generated/cpp/$lib.native.g.h"')
    ..writeln()
    ..writeln('#include <string>')
    ..writeln()
    ..writeln('class Hybrid${className}Impl final : public Hybrid$className {')
    ..writeln('public:')
    ..writeln('    // TODO: implement all pure-virtual methods declared in Hybrid$className')
    ..writeln('};')
    ..writeln()
    ..writeln('static Hybrid${className}Impl g_impl;')
    ..writeln()
    ..writeln('// Auto-register on shared library load — no manual init call needed.');

  if (needsTargetConditionals) {
    buf
      ..writeln('#if defined(__APPLE__)')
      ..writeln('  #include <TargetConditionals.h>')
      ..writeln('#endif')
      ..writeln();
  }

  if (guard.isNotEmpty) buf.writeln('#if $guard');
  buf
    ..writeln('#if defined(_WIN32)')
    ..writeln('namespace {')
    ..writeln('  struct _AutoRegister {')
    ..writeln('    _AutoRegister() { ${lib}_register_impl(&g_impl); }')
    ..writeln('  };')
    ..writeln('  _AutoRegister _auto_register_instance;')
    ..writeln('}')
    ..writeln('#else')
    ..writeln('__attribute__((constructor))')
    ..writeln('static void ${lib}_auto_register() {')
    ..writeln('    ${lib}_register_impl(&g_impl);')
    ..writeln('}')
    ..writeln('#endif');
  if (guard.isNotEmpty) buf.writeln('#endif // auto-register on C++ platforms');

  return buf.toString();
}

/// Returns the content of a `windows/src/Hybrid${className}.cpp` stub.
///
/// Windows always uses MSVC-compatible static-initializer registration because
/// `__attribute__((constructor))` is not available on MSVC.
String windowsCppStubContent({
  required String lib,
  required String className,
}) =>
    '// Hybrid$className — WindowsNativeImpl.cpp implementation.\n'
    '// Generated by nitrogen link. Fill in the method bodies.\n'
    '#include "../../lib/src/generated/cpp/$lib.native.g.h"\n'
    '\n'
    '#include <string>\n'
    '\n'
    'class Hybrid${className}Impl final : public Hybrid$className {\n'
    'public:\n'
    '    // TODO: implement all pure-virtual methods declared in Hybrid$className\n'
    '};\n'
    '\n'
    '// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).\n'
    'namespace {\n'
    '  struct _AutoRegister {\n'
    '    _AutoRegister() { ${lib}_register_impl(new Hybrid${className}Impl()); }\n'
    '  };\n'
    '  static _AutoRegister _auto_register_instance;\n'
    '}\n';

/// Returns the content of a `linux/src/Hybrid${className}.cpp` stub.
///
/// Linux uses `__attribute__((constructor))` (GCC/Clang extension) to
/// auto-register the implementation when the shared library is loaded.
/// This is identical to the shared `src/HybridXxx.cpp` pattern but lives
/// in the platform-specific `linux/src/` directory so that the desktop
/// CMake target can link it directly.
String linuxCppStubContent({
  required String lib,
  required String className,
}) =>
    '// Hybrid$className — LinuxNativeImpl.cpp implementation.\n'
    '// Generated by nitrogen init. Fill in the method bodies.\n'
    '#include "../../lib/src/generated/cpp/$lib.native.g.h"\n'
    '\n'
    '#include <string>\n'
    '\n'
    'class Hybrid${className}Impl final : public Hybrid$className {\n'
    'public:\n'
    '    // TODO: implement all pure-virtual methods declared in Hybrid$className\n'
    '};\n'
    '\n'
    '// GCC/Clang auto-registration via constructor attribute.\n'
    '__attribute__((constructor))\n'
    'static void nitro_auto_register() {\n'
    '    ${lib}_register_impl(new Hybrid${className}Impl());\n'
    '}\n';

/// Web-specific C++ impl starter (`web/src/Hybrid<Class>.cpp`). Inert until it
/// holds real code — then `nitrogen link` compiles it for the wasm instead of
/// the shared `src/Hybrid<Class>.cpp`. Static-object registration: em++ is
/// clang, but this form needs no attribute and matches the shared starter.
String webCppStubContent({
  required String lib,
  required String className,
}) =>
    '// Hybrid$className — web (WASM) implementation.\n'
    '// Generated by nitrogen link. Leave as-is to keep sharing src/Hybrid$className.cpp;\n'
    '// fill in the method bodies to give web its own implementation instead.\n'
    '// The module is single-threaded: never block, and post async results from\n'
    '// emscripten_async_call or a JS callback, not from a std::thread.\n'
    '#include "../../lib/src/generated/cpp/$lib.native.g.h"\n'
    '\n'
    '#include <string>\n'
    '\n'
    'class Hybrid${className}Impl final : public Hybrid$className {\n'
    'public:\n'
    '    // TODO: implement all pure-virtual methods declared in Hybrid$className\n'
    '};\n'
    '\n'
    'namespace {\n'
    '  struct _AutoRegister {\n'
    '    _AutoRegister() { ${lib}_register_impl(new Hybrid${className}Impl()); }\n'
    '  };\n'
    '  static _AutoRegister _auto_register_instance;\n'
    '}\n';

/// `web/src/Hybrid<Class>.cpp` seeded from the generator's interface-complete
/// starter (`<lib>.impl.g.cpp`). [starterBody] is that file from its ownership
/// conventions onward — its quick-start (CMakeLists, plugin-init registration)
/// does not apply to a wasm module, so the header here replaces it. The
/// shared-impl marker line keeps web on `src/` until the author deletes it.
String webCppSeededContent({
  required String lib,
  required String className,
  required String implClass,
  required String starterBody,
}) =>
    '// Hybrid$className — web (WASM) implementation. Seeded once by nitrogen link\n'
    '// from lib/src/generated/cpp/$lib.impl.g.cpp; never overwritten.\n'
    '//\n'
    '// TODO: implement all pure-virtual methods declared in Hybrid$className\n'
    '//   While the line above exists, web keeps compiling the shared\n'
    '//   src/Hybrid$className.cpp. Implement the methods, delete that line, and\n'
    '//   re-run `nitrogen link` to build the module from this file instead.\n'
    '//   The module is single-threaded: never block; post async results from\n'
    '//   emscripten_async_call or a JS callback, not from a std::thread.\n'
    '//\n'
    '$starterBody'
    '\n'
    '// Registered when the wasm module instantiates.\n'
    'namespace {\n'
    '  struct _AutoRegister {\n'
    '    _AutoRegister() { ${lib}_register_impl(new $implClass()); }\n'
    '  };\n'
    '  static _AutoRegister _auto_register_instance;\n'
    '}\n';
