/// Scaffold template strings for `nitrogen init`.
///
/// Every file that `nitrogen init` writes is defined here as a named function.
/// This keeps [init_command.dart] focused on logic and makes templates easy
/// to find, review, and update independently.
library;

// ── C / C++ / CMake templates ─────────────────────────────────────────────────

String pluginCppTemplate(String pluginName) =>
    '''
#include <stdint.h>
#include <stdbool.h>
#include "nitro.h"

#include "../lib/src/generated/cpp/$pluginName.bridge.g.h"

extern "C" {
}
''';

String cmakeListsTemplate(String pluginName) =>
    '''
cmake_minimum_required(VERSION 3.10)
project(${pluginName}_library VERSION 0.0.1 LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(NITRO_NATIVE "\${CMAKE_CURRENT_SOURCE_DIR}/../../packages/nitro/src/native")
set(GENERATED_CPP "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp")

add_library($pluginName SHARED
  "$pluginName.cpp"
  "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp/$pluginName.bridge.g.cpp"
  "dart_api_dl.c"
)

target_include_directories($pluginName PRIVATE
  "\${CMAKE_CURRENT_SOURCE_DIR}"
  "\${GENERATED_CPP}"
  "\${NITRO_NATIVE}"
)

target_compile_definitions($pluginName PUBLIC DART_SHARED_LIB)

if(ANDROID)
  target_link_libraries($pluginName PRIVATE android log)
  target_link_options($pluginName PRIVATE "-Wl,-z,max-page-size=16384")
endif()
''';

// ── iOS templates ─────────────────────────────────────────────────────────────

String iosSwiftPluginTemplate(String className) =>
    '''
import Flutter
import UIKit

public class Swift${className}Plugin: NSObject, FlutterPlugin {
    public static func register(with registrar: FlutterPluginRegistrar) {
        ${className}Registry.register(${className}Impl())
    }
}
''';

String iosSwiftImplTemplate(String className) =>
    '''
import Foundation

/// Native implementation of Hybrid${className}Protocol.
/// This file is yours to edit — the protocol is generated by `nitrogen generate`.
public class ${className}Impl: NSObject, Hybrid${className}Protocol {

    public func add(a: Double, b: Double) -> Double {
        return a + b
    }

    public func getGreeting(name: String) async throws -> String {
        return "Hello, \\(name)!"
    }
}
''';

// ── macOS templates ───────────────────────────────────────────────────────────

String macosSwiftPluginTemplate(String className) =>
    '''
import FlutterMacOS
import AppKit

public class Swift${className}Plugin: NSObject, FlutterPlugin {
    public static func register(with registrar: FlutterPluginRegistrar) {
        ${className}Registry.register(${className}Impl())
    }
}
''';

String macosSwiftImplTemplate(String className) =>
    '''
import Foundation

/// Native implementation of Hybrid${className}Protocol on macOS.
public class ${className}Impl: NSObject, Hybrid${className}Protocol {

    public func add(a: Double, b: Double) -> Double {
        return a + b
    }

    public func getGreeting(name: String) async throws -> String {
        return "Hello, \\(name) from macOS!"
    }
}
''';

// ── Package.swift template ────────────────────────────────────────────────────

/// Generates the SPM [Package.swift] for [pluginName].
///
/// [platformSpec] is e.g. `'iOS(.v13)'` or `'macOS(.v10_15)'`.
/// [isMacos] switches the Xcode flag path between iOS and macOS conventions.
String packageSwiftTemplate(
  String pluginName,
  String className,
  String platformSpec, {
  bool isMacos = false,
}) {
  return '''
// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "$pluginName",
    platforms: [.$platformSpec],
    products: [
        .library(name: "${pluginName.replaceAll('_', '-')}", targets: ["$pluginName"]),
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
    ],
    targets: [
        // C/C++ bridge — SPM requires Swift and C++ in separate targets.
        // nitro headers (nitro.h, dart_api_dl.h …) are copied into include/
        // by `nitrogen link`, so no extra header search path is needed.
        .target(
            name: "${className}Cpp",
            path: "Sources/${className}Cpp",
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .unsafeFlags(["-std=c++17"])
            ]
        ),
        // Swift implementation + generated bridge.
        .target(
            name: "$pluginName",
            dependencies: [
                "${className}Cpp",
                .product(name: "FlutterFramework", package: "FlutterFramework"),
            ],
            path: "Sources/$className"
        ),
    ]
)
''';
}

// ── Android templates ─────────────────────────────────────────────────────────

/// Generates `android/build.gradle` using the modern `plugins {}` DSL.
///
/// Uses [plugins {}] at the very top as required by Gradle 7+ — no legacy
/// `buildscript {}` or `apply plugin` blocks which break AGP 8/9+.
String androidBuildGradleTemplate(String org, String pluginName) =>
    '''
plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

group = "$org.$pluginName"
version = "1.0"

android {
    namespace = "$org.$pluginName"
    compileSdk = 36
    ndkVersion = "27.0.12077973"

    externalNativeBuild {
        cmake { path = "../src/CMakeLists.txt" }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions { jvmTarget = "17" }

    defaultConfig { minSdk = 24 }

    sourceSets {
        main {
            // Do NOT add to java.srcDirs — in AGP 8.x that routes .kt files
            // through the Java compiler and causes "Unresolved reference" errors.
            kotlin.srcDirs += "\${project.projectDir}/../lib/src/generated/kotlin"
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
}
''';

String androidPluginKtTemplate(
  String org,
  String pluginName,
  String className,
  String moduleName,
) =>
    '''
package $org.$pluginName

import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import nitro.$moduleName.${className}JniBridge

class ${className}Plugin : FlutterPlugin, ActivityAware {

    companion object {
        init { System.loadLibrary("$pluginName") }
    }

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        ${className}JniBridge.register(${className}Impl(), binding.applicationContext)
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        ${className}JniBridge.onDetached()
    }

    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        ${className}JniBridge.onActivityAttached(binding.activity)
    }

    override fun onDetachedFromActivityForConfigChanges() {
        ${className}JniBridge.onActivityDetached()
    }

    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
        ${className}JniBridge.onActivityAttached(binding.activity)
    }

    override fun onDetachedFromActivity() {
        ${className}JniBridge.onActivityDetached()
    }
}''';

String androidImplKtTemplate(
  String org,
  String pluginName,
  String className,
  String moduleName,
) =>
    '''
package $org.$pluginName

import nitro.$moduleName.Hybrid${className}Spec

/// Native implementation of Hybrid${className}Spec.
/// This file is yours to edit — the interface is generated by `nitrogen generate`.
/// Use `applicationContext` (from the interface) to access the Android context.
class ${className}Impl : Hybrid${className}Spec {

    override fun add(a: Double, b: Double): Double = a + b

    override suspend fun getGreeting(name: String): String = "Hello, \$name!"
}
''';

// ── Dart / Flutter templates ──────────────────────────────────────────────────

String nativeDartTemplate(String pluginName, String className, String annotation) =>
    '''
import 'package:nitro/nitro.dart';

part '$pluginName.g.dart';

$annotation
abstract class $className extends HybridObject {
  static final $className instance = _${className}Impl();

  double add(double a, double b);

  @nitroAsync
  Future<String> getGreeting(String name);
}
''';

String exampleMainDartTemplate(String pluginName, String className) =>
    '''
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:$pluginName/$pluginName.dart' as plugin;

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '$className Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.deepPurple),
      home: const _DemoPage(),
    );
  }
}

class _DemoPage extends StatefulWidget {
  const _DemoPage();
  @override
  State<_DemoPage> createState() => _DemoPageState();
}

class _DemoPageState extends State<_DemoPage> {
  String _result = '—';
  bool _loading = false;

  Future<void> _runAdd() async {
    setState(() { _loading = true; _result = '—'; });
    try {
      final v = plugin.$className.instance.add(3, 4);
      setState(() => _result = 'add(3, 4) = \$v');
    } catch (e) {
      setState(() => _result = 'Error: \$e');
    } finally {
      setState(() => _loading = false);
    }
  }

  Future<void> _runGreeting() async {
    setState(() { _loading = true; _result = '—'; });
    try {
      final s = await plugin.$className.instance.getGreeting('World');
      setState(() => _result = s);
    } catch (e) {
      setState(() => _result = 'Error: \$e');
    } finally {
      setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('$className Demo')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(_result, style: Theme.of(context).textTheme.headlineSmall),
            const SizedBox(height: 24),
            if (_loading) const CircularProgressIndicator(),
            if (!_loading) ...[
              ElevatedButton(onPressed: _runAdd, child: const Text('add(3, 4)')),
              const SizedBox(height: 12),
              ElevatedButton(onPressed: _runGreeting, child: const Text('getGreeting("World")')),
            ],
          ],
        ),
      ),
    );
  }
}
''';

// ── build.yaml template ───────────────────────────────────────────────────────

String buildYamlTemplate() => r'''
# Optimized Nitrogen configuration.
# Restricts the generator to lib/src/**/*.native.dart for faster builds.
targets:
  $default:
    builders:
      nitro_generator:
        generate_for:
          - lib/src/**.native.dart
''';
