// Generated by Nitrogen Modules. Do not edit.
// Generated from: math.native.dart
part of 'math.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension RoundingNativeExt on Rounding {
  int get nativeValue => index + 1;
}

extension RoundingFromNativeExt on int {
  Rounding toRounding() => Rounding.values[this - 1];
}

class _MathImpl extends Math {
  final DynamicLibrary _dylib;

  _MathImpl() : _dylib = NitroRuntime.loadLib('math') {
    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>),
        int Function(Pointer<Void>)>('math_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
          'math: Dart API DL initialization failed with code $initCode.');
    }
  }

  late final double Function(double, double) _addPtr = _dylib.lookupFunction<
      Double Function(Double, Double),
      double Function(double, double)>('math_add');
  late final double Function(double, double) _multiplyPtr =
      _dylib.lookupFunction<Double Function(Double, Double),
          double Function(double, double)>('math_multiply');
  late final void Function(Pointer<Uint8>, int) _processBufferPtr =
      _dylib.lookupFunction<Void Function(Pointer<Uint8>, Int64),
          void Function(Pointer<Uint8>, int)>('math_process_buffer');
  late final double Function() _getScaleFactorPtr =
      _dylib.lookupFunction<Double Function(), double Function()>(
          'math_get_scale_factor');
  late final int Function() _getPrecisionPtr = _dylib
      .lookupFunction<Int64 Function(), int Function()>('math_get_precision');
  late final void Function(int) _setPrecisionPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'math_set_precision');
  late final void Function(int) _registerUpdatesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'math_register_updates_stream');
  late final void Function(int) _releaseUpdatesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'math_release_updates_stream');
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr =
      _dylib.lookupFunction<Pointer<NitroErrorFfi> Function(),
          Pointer<NitroErrorFfi> Function()>('math_get_error');
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>('math_clear_error');
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
      _getErrorNativePtr = _dylib.lookup('math_get_error');
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('math_clear_error');

  @override
  // ignore: unnecessary_overrides
  void dispose() {
    super.dispose(); // sets isDisposed = true, calls onDestroy()
  }

  @override
  double add(double a, double b) {
    checkDisposed();
    final res = _addPtr(a, b);
    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
    return res;
  }

  @override
  Future<double> multiply(double a, double b) async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<double>(_multiplyPtr, [a, b],
        getError: _getErrorNativePtr, clearError: _clearErrorNativePtr);
    return res;
  }

  @override
  void processBuffer(Uint8List data) {
    checkDisposed();
    return withArena((arena) {
      _processBufferPtr(data.toPointer(arena), data.length);
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      return;
    });
  }

  @override
  double get scaleFactor {
    checkDisposed();
    final res = _getScaleFactorPtr();
    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
    return res;
  }

  @override
  int get precision {
    checkDisposed();
    final res = _getPrecisionPtr();
    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
    return res;
  }

  @override
  set precision(int value) {
    checkDisposed();
    _setPrecisionPtr(value);
    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
  }

  @override
  Stream<double> get updates {
    checkDisposed();
    return NitroRuntime.openStream<double>(
      register: (port) => _registerUpdatesPtr(port),
      unpack: (rawPtr) => rawPtr as double,
      release: (port) => _releaseUpdatesPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }
}
