import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';
import 'src/spec_extractor.dart';
import 'src/generators/dart_ffi_generator.dart';
import 'src/generators/cpp_header_generator.dart';
import 'src/generators/kotlin_generator.dart';
import 'src/generators/swift_generator.dart';
import 'src/generators/cmake_generator.dart';

Builder nitrogenBuilder(BuilderOptions options) {
  return NitrogenBuilder();
}

class NitrogenBuilder implements Builder {
  // The correct format to use capture groups in code is:
  @override
  Map<String, List<String>> get buildExtensions => {
    '^lib/{{dir}}/{{file}}.native.dart': [
      'lib/{{dir}}/{{file}}.g.dart',
      'lib/{{dir}}/generated/kotlin/{{file}}.bridge.g.kt',
      'lib/{{dir}}/generated/swift/{{file}}.bridge.g.swift',
      'lib/{{dir}}/generated/cpp/{{file}}.bridge.g.h',
      'lib/{{dir}}/generated/cmake/{{file}}.CMakeLists.g.txt',
    ]
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final libraryElement = await buildStep.inputLibrary;
    final library = LibraryReader(libraryElement);

    try {
      final spec = SpecExtractor.extract(library);
      
      // We can use buildStep.allowedOutputs to find the EXACT output paths
      // generated by build_runner based on our map.
      final outputs = buildStep.allowedOutputs;
      
      for (final outId in outputs) {
        if (outId.path.endsWith('.g.dart')) {
          await buildStep.writeAsString(outId, DartFfiGenerator.generate(spec));
        } else if (outId.path.endsWith('.bridge.g.kt')) {
          await buildStep.writeAsString(outId, KotlinGenerator.generate(spec));
        } else if (outId.path.endsWith('.bridge.g.swift')) {
          await buildStep.writeAsString(outId, SwiftGenerator.generate(spec));
        } else if (outId.path.endsWith('.bridge.g.h')) {
          await buildStep.writeAsString(outId, CppHeaderGenerator.generate(spec));
        } else if (outId.path.endsWith('.CMakeLists.g.txt')) {
          await buildStep.writeAsString(outId, CMakeGenerator.generate(spec));
        }
      }

    } catch (e, st) {
      log.warning('nitrogen: Could not process ${buildStep.inputId}:\n$e\n$st');
    }
  }
}
