builders:
  nitro_generator:
    import: 'package:nitro_generator/builder.dart'
    builder_factories: ['nitroGeneratorBuilder']
    build_extensions:
      '^lib/{{dir}}/{{file}}.native.dart':
        - 'lib/{{dir}}/{{file}}.g.dart'
        - 'lib/{{dir}}/generated/kotlin/{{file}}.bridge.g.kt'
        - 'lib/{{dir}}/generated/swift/{{file}}.bridge.g.swift'
        - 'lib/{{dir}}/generated/cpp/{{file}}.bridge.g.h'
        - 'lib/{{dir}}/generated/cpp/{{file}}.bridge.g.cpp'
        - 'lib/{{dir}}/generated/cmake/{{file}}.CMakeLists.g.txt'
        - 'lib/{{dir}}/generated/cpp/{{file}}.native.g.h'
        - 'lib/{{dir}}/generated/cpp/test/{{file}}.mock.g.h'
        - 'lib/{{dir}}/generated/cpp/test/{{file}}.test.g.cpp'
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        - lib/src/**.native.dart
