name: nitro_generator
description: >
  Code generator for Nitro Modules (Nitrogen).
  Converts *.native.dart specs to Dart FFI, Kotlin, Swift, and C++ bindings.
version: 0.4.1
homepage: https://nitro.shreeman.dev
repository: https://github.com/Shreemanarjun/nitro_ecosystem
issue_tracker: https://github.com/Shreemanarjun/nitro_ecosystem/issues
documentation: https://nitro.shreeman.dev/
funding:
  - https://buymeacoffee.com/shreemanarjun
topics:
  - codegen
  - ffi
  - flutter
  - native
  - bridge

environment:
  sdk: ^3.11.3
resolution: workspace

dependencies:
  analyzer: '>=8.1.1 <14.0.0'
  build: ^4.0.6
  source_gen: ^4.2.3
  dart_style: ^3.1.7
  path: ^1.9.0
  nitro_annotations: ^0.4.1

dev_dependencies:
  build_test: ^3.5.0
  build_runner: ^2.15.0
  test: ^1.25.0
  lints: ^6.0.0
  nitro: ^0.4.1
  ffi: ^2.1.3
