import 'dart:io';

import 'package:crypto/crypto.dart';

import 'package:args/command_runner.dart';
import 'package:nitrogen_cli/commands/generate_command.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('GenerateCommand planning modes', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('nitrogen_generate_dry_run_');
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    test('--dry-run prints the generation plan without creating build or generated files', () async {
      _writePluginFixture(tempDir);
      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);

      await runner.run(['generate', '--dry-run', '--no-ui', '--directory=${tempDir.path}']);

      expect(command.exitCode, 0);
      expect(Directory(p.join(tempDir.path, '.dart_tool')).existsSync(), isFalse);
      expect(Directory(p.join(tempDir.path, 'lib', 'src', 'generated')).existsSync(), isFalse);
      expect(File(p.join(tempDir.path, 'lib', 'src', 'camera.g.dart')).existsSync(), isFalse);
    });

    test('--check returns 3 when generated files are missing', () async {
      _writePluginFixture(tempDir);
      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);

      await runner.run(['generate', '--check', '--no-ui', '--directory=${tempDir.path}']);

      expect(command.exitCode, 3);
      expect(Directory(p.join(tempDir.path, '.dart_tool')).existsSync(), isFalse);
      expect(Directory(p.join(tempDir.path, 'lib', 'src', 'generated')).existsSync(), isFalse);
    });

    test('--check returns 0 when every output carries the current spec hash', () async {
      final specFile = _writePluginFixture(tempDir);
      for (final output in _expectedGeneratedOutputs(tempDir)) {
        output.parent.createSync(recursive: true);
        output.writeAsStringSync(_generatedHeader(specFile));
      }

      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);

      await runner.run(['generate', '--check', '--no-ui', '--directory=${tempDir.path}']);

      expect(command.exitCode, 0);
    });

    // #42: an output build_runner did not need to rewrite keeps its old mtime.
    // Under the mtime rule that file was stale forever; content decides now.
    test('--check returns 0 for an output OLDER than the spec whose hash matches', () async {
      final specFile = _writePluginFixture(tempDir);
      final older = specFile.lastModifiedSync().subtract(const Duration(hours: 1));
      for (final output in _expectedGeneratedOutputs(tempDir)) {
        output.parent.createSync(recursive: true);
        output.writeAsStringSync(_generatedHeader(specFile));
        output.setLastModifiedSync(older);
      }
      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);
      await runner.run(['generate', '--check', '--no-ui', '--directory=${tempDir.path}']);
      expect(command.exitCode, 0);
    });

    test('--check returns 3 when the spec changed after generation, whatever the mtimes say', () async {
      final specFile = _writePluginFixture(tempDir);
      for (final output in _expectedGeneratedOutputs(tempDir)) {
        output.parent.createSync(recursive: true);
        output.writeAsStringSync(_generatedHeader(specFile));
      }
      specFile.writeAsStringSync('${specFile.readAsStringSync()}\n// edited');
      // Outputs newer than the spec — the old rule would have called this fresh.
      final newer = specFile.lastModifiedSync().add(const Duration(hours: 1));
      for (final output in _expectedGeneratedOutputs(tempDir)) {
        output.setLastModifiedSync(newer);
      }
      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);
      await runner.run(['generate', '--check', '--no-ui', '--directory=${tempDir.path}']);
      expect(command.exitCode, 3);
    });

    test('--check returns 3 for outputs without a spec-sha256 stamp (pre-0.7.4 generator)', () async {
      final specFile = _writePluginFixture(tempDir);
      for (final output in _expectedGeneratedOutputs(tempDir)) {
        output.parent.createSync(recursive: true);
        output.writeAsStringSync('// Generated by Nitrogen Modules. Do not edit.\n// nitro_generator: 0.7.3\n');
      }
      expect(specFile.existsSync(), isTrue);
      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);
      await runner.run(['generate', '--check', '--no-ui', '--directory=${tempDir.path}']);
      expect(command.exitCode, 3);
    });

    test('--check --targets=dart ignores stale native outputs outside the target set', () async {
      final specFile = _writePluginFixture(tempDir);
      final dartOutput = File(p.join(tempDir.path, 'lib', 'src', 'camera.g.dart'));
      dartOutput.parent.createSync(recursive: true);
      dartOutput.writeAsStringSync(_generatedHeader(specFile));

      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);

      await runner.run(['generate', '--check', '--targets=dart', '--no-ui', '--directory=${tempDir.path}']);

      expect(command.exitCode, 0);
      expect(Directory(p.join(tempDir.path, 'lib', 'src', 'generated')).existsSync(), isFalse);
    });

    test('--check --targets=swift returns 3 when only Swift output is missing', () async {
      _writePluginFixture(tempDir);
      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);

      await runner.run(['generate', '--check', '--targets=swift', '--no-ui', '--directory=${tempDir.path}']);

      expect(command.exitCode, 3);
    });

    test('--targets rejects unknown target names', () async {
      _writePluginFixture(tempDir);
      final command = _TestGenerateCommand();
      final runner = CommandRunner<void>('nitrogen', 'test')..addCommand(command);

      await runner.run(['generate', '--check', '--targets=bogus', '--no-ui', '--directory=${tempDir.path}']);

      expect(command.exitCode, 1);
    });
  });

  group('IncrementalGenerationCache', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('nitrogen_incremental_cache_');
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    test('treats every spec as changed when no manifest exists', () {
      final spec = _writePluginFixture(tempDir);
      final output = File(p.join(tempDir.path, 'lib', 'src', 'camera.g.dart'));
      output.parent.createSync(recursive: true);
      output.writeAsStringSync('// generated');

      final cache = IncrementalGenerationCache(tempDir.path);
      final plan = cache.plan(
        specs: [spec],
        outputPathsForSpec: (_) => [output.path],
      );

      expect(plan.changedSpecs, equals([spec]));
    });

    test('uses a stable SHA-256 content hash', () {
      final spec = File(p.join(tempDir.path, 'lib', 'src', 'hash.native.dart'));
      spec.parent.createSync(recursive: true);
      spec.writeAsStringSync('abc');

      expect(
        IncrementalGenerationCache.contentHash(spec),
        'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
      );
    });

    test('re-generates an unchanged spec when the generator changed', () {
      // Hashing the spec alone left a nitro_generator upgrade silently skipped:
      // same spec, different output, and the stale files were kept.
      final spec = _writePluginFixture(tempDir);
      final output = File(p.join(tempDir.path, 'lib', 'src', 'camera.g.dart'));
      output.parent.createSync(recursive: true);
      output.writeAsStringSync('// generated');

      final genLib = Directory(p.join(tempDir.path, 'gen', 'lib'))..createSync(recursive: true);
      final genSrc = File(p.join(genLib.path, 'g.dart'))..writeAsStringSync('// v1');
      final cfg = File(p.join(tempDir.path, '.dart_tool', 'package_config.json'));
      cfg.parent.createSync(recursive: true);
      cfg.writeAsStringSync('{"packages":[{"name":"nitro_generator","rootUri":"../gen"}]}');

      final cache = IncrementalGenerationCache(tempDir.path);
      cache.write(specs: [spec], outputPathsForSpec: (_) => [output.path]);
      expect(cache.plan(specs: [spec], outputPathsForSpec: (_) => [output.path]).changedSpecs, isEmpty);

      genSrc.writeAsStringSync('// v2');
      genSrc.setLastModifiedSync(DateTime.now().add(const Duration(minutes: 1)));

      expect(
        cache.plan(specs: [spec], outputPathsForSpec: (_) => [output.path]).changedSpecs,
        equals([spec]),
      );
    });

    test('finds the generator stamp at the pub-workspace root', () {
      // A workspace member has no .dart_tool of its own; the resolved
      // package_config.json lives at the root. Reading only the member's dir
      // made the stamp 'unknown' on both sides, so a generator upgrade never
      // invalidated the cache (benchmark kept 0.7.1 output through two bumps).
      final member = Directory(p.join(tempDir.path, 'packages', 'app'))..createSync(recursive: true);
      final spec = _writeSpec(member, 'camera');
      final output = File(p.join(member.path, 'lib', 'src', 'camera.g.dart'))..writeAsStringSync('// generated');
      final genSrc = File(p.join(tempDir.path, 'gen', 'lib', 'g.dart'))
        ..parent.createSync(recursive: true)
        ..writeAsStringSync('// v1');
      File(p.join(tempDir.path, '.dart_tool', 'package_config.json'))
        ..parent.createSync(recursive: true)
        ..writeAsStringSync('{"packages":[{"name":"nitro_generator","rootUri":"../gen"}]}');

      final cache = IncrementalGenerationCache(member.path);
      cache.write(specs: [spec], outputPathsForSpec: (_) => [output.path]);
      expect(cache.plan(specs: [spec], outputPathsForSpec: (_) => [output.path]).changedSpecs, isEmpty);

      genSrc.writeAsStringSync('// v2');
      genSrc.setLastModifiedSync(DateTime.now().add(const Duration(minutes: 1)));
      expect(
        cache.plan(specs: [spec], outputPathsForSpec: (_) => [output.path]).changedSpecs,
        equals([spec]),
        reason: 'the generator changed; a workspace member must notice',
      );
    });

    test('stamps a path-dep generator given as an absolute file: rootUri', () {
      // pub writes an absolute file: URI for a path dep OUTSIDE the project
      // (a local generator checkout). Joining that onto .dart_tool produced
      // '.dart_tool/file:/…', which never exists, so the stamp was the constant
      // 'path' and editing the generator never invalidated the cache.
      final spec = _writeSpec(tempDir, 'camera');
      final output = File(p.join(tempDir.path, 'lib', 'src', 'camera.g.dart'))..writeAsStringSync('// generated');
      final genSrc = File(p.join(tempDir.path, 'elsewhere', 'gen', 'lib', 'g.dart'))
        ..parent.createSync(recursive: true)
        ..writeAsStringSync('// v1');
      final rootUri = genSrc.parent.parent.uri.toString().replaceAll(RegExp(r'/$'), '');
      File(p.join(tempDir.path, '.dart_tool', 'package_config.json'))
        ..parent.createSync(recursive: true)
        ..writeAsStringSync('{"packages":[{"name":"nitro_generator","rootUri":"$rootUri"}]}');

      final cache = IncrementalGenerationCache(tempDir.path);
      cache.write(specs: [spec], outputPathsForSpec: (_) => [output.path]);
      expect(cache.plan(specs: [spec], outputPathsForSpec: (_) => [output.path]).changedSpecs, isEmpty);

      genSrc.writeAsStringSync('// v2');
      genSrc.setLastModifiedSync(DateTime.now().add(const Duration(minutes: 1)));
      expect(
        cache.plan(specs: [spec], outputPathsForSpec: (_) => [output.path]).changedSpecs,
        equals([spec]),
        reason: 'the generator changed; an absolute rootUri must still be followed',
      );
    });

    test('skips unchanged specs when hashes and outputs match the manifest', () {
      final spec = _writePluginFixture(tempDir);
      final output = File(p.join(tempDir.path, 'lib', 'src', 'camera.g.dart'));
      output.parent.createSync(recursive: true);
      output.writeAsStringSync('// generated');

      final cache = IncrementalGenerationCache(tempDir.path);
      cache.write(
        specs: [spec],
        outputPathsForSpec: (_) => [output.path],
      );

      final plan = cache.plan(
        specs: [spec],
        outputPathsForSpec: (_) => [output.path],
      );

      expect(plan.changedSpecs, isEmpty);
    });

    test('marks only edited specs as changed', () {
      final camera = _writePluginFixture(tempDir);
      final audio = _writeSpec(tempDir, 'audio');
      final cameraOutput = File(p.join(tempDir.path, 'lib', 'src', 'camera.g.dart'));
      final audioOutput = File(p.join(tempDir.path, 'lib', 'src', 'audio.g.dart'));
      for (final output in [cameraOutput, audioOutput]) {
        output.parent.createSync(recursive: true);
        output.writeAsStringSync('// generated');
      }

      final cache = IncrementalGenerationCache(tempDir.path);
      cache.write(
        specs: [camera, audio],
        outputPathsForSpec: (spec) => [
          p.join(tempDir.path, 'lib', 'src', '${p.basenameWithoutExtension(p.basenameWithoutExtension(spec.path))}.g.dart'),
        ],
      );

      audio.writeAsStringSync('${audio.readAsStringSync()}\n// changed\n');

      final plan = cache.plan(
        specs: [camera, audio],
        outputPathsForSpec: (spec) => [
          p.join(tempDir.path, 'lib', 'src', '${p.basenameWithoutExtension(p.basenameWithoutExtension(spec.path))}.g.dart'),
        ],
      );

      expect(plan.changedSpecs, equals([audio]));
    });
  });

  group('build_runner cache cleanup', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('nitrogen_build_cache_');
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    test('generate deletes stale lock without deleting asset graph', () {
      final buildDir = Directory(p.join(tempDir.path, '.dart_tool', 'build'))..createSync(recursive: true);
      final lock = File(p.join(buildDir.path, 'lock'))..writeAsStringSync('locked');
      final assetGraph = File(p.join(buildDir.path, 'asset_graph.json'))..writeAsStringSync('{}');

      final deleted = deleteBuildRunnerLock(tempDir.path);

      expect(deleted, isTrue);
      expect(lock.existsSync(), isFalse);
      expect(assetGraph.existsSync(), isTrue);
    });
  });
}

class _TestGenerateCommand extends GenerateCommand {
  int? exitCode;

  @override
  Future<void> run() async {
    exitCode = await execute();
  }
}

File _writePluginFixture(Directory root) {
  File(p.join(root.path, 'pubspec.yaml')).writeAsStringSync('''
name: dry_run_plugin
dependencies:
  nitro: any
dev_dependencies:
  nitro_generator: any
  build_runner: any
''');
  final specDir = Directory(p.join(root.path, 'lib', 'src'))..createSync(recursive: true);
  return File(p.join(specDir.path, 'camera.native.dart'))..writeAsStringSync('''
import 'package:nitro/nitro.dart';

@NitroModule(lib: 'camera')
abstract class CameraSpec {}
''');
}

File _writeSpec(Directory root, String stem) {
  final specDir = Directory(p.join(root.path, 'lib', 'src'))..createSync(recursive: true);
  return File(p.join(specDir.path, '$stem.native.dart'))..writeAsStringSync('''
import 'package:nitro/nitro.dart';

@NitroModule(lib: '$stem')
abstract class ${stem[0].toUpperCase()}${stem.substring(1)}Spec {}
''');
}

List<File> _expectedGeneratedOutputs(Directory root) {
  final base = p.join(root.path, 'lib', 'src');
  return [
    File(p.join(base, 'camera.g.dart')),
    File(p.join(base, 'generated', 'kotlin', 'camera.bridge.g.kt')),
    File(p.join(base, 'generated', 'swift', 'camera.bridge.g.swift')),
    File(p.join(base, 'generated', 'cpp', 'camera.bridge.g.h')),
    File(p.join(base, 'generated', 'cpp', 'camera.bridge.g.cpp')),
    File(p.join(base, 'generated', 'cmake', 'camera.CMakeLists.g.txt')),
    File(p.join(base, 'generated', 'cpp', 'camera.native.g.h')),
    File(p.join(base, 'generated', 'cpp', 'test', 'camera.mock.g.h')),
    File(p.join(base, 'generated', 'cpp', 'test', 'camera.test.g.cpp')),
  ];
}

/// The header nitro_generator 0.7.4+ writes: --check reads the spec hash from it.
String _generatedHeader(File spec) {
  final hash = sha256.convert(spec.readAsBytesSync()).toString();
  return '// Generated by Nitrogen Modules. Do not edit.\n// nitro_generator: 0.7.4\n// Generated from: ${p.basename(spec.path)}\n// spec-sha256: $hash\n';
}
