import 'package:build/build.dart';
import 'package:crypto/crypto.dart';
import 'package:dart_style/dart_style.dart';
import 'package:glob/glob.dart';
import 'package:source_gen/source_gen.dart';
import 'src/bridge_spec.dart';
import 'src/build_extensions.dart';
import 'src/spec_extractor.dart';
import 'src/spec_validator.dart';
import 'src/generators/native_generator_facade.dart';

Builder nitroGeneratorBuilder(BuilderOptions options) {
  return NitroGeneratorBuilder();
}

class NitroGeneratorBuilder implements Builder {
  static final _formatter = DartFormatter(languageVersion: DartFormatter.latestLanguageVersion);
  static final _nativeGenerators = NativeGeneratorFacade.defaults();

  @override
  Map<String, List<String>> get buildExtensions => nitroBuilderExtensions;

  @override
  Future<void> build(BuildStep buildStep) async {
    final libraryElement = await buildStep.inputLibrary;
    final library = LibraryReader(libraryElement);

    try {
      // extractAny handles both @NitroModule files and type-only files.
      // Returns null when the file has no Nitrogen-relevant content.
      final spec = SpecExtractor.extractAny(library);
      if (spec == null) return;
      spec.assetPackage = buildStep.inputId.package;
      spec.sourceHash = sha256.convert(await buildStep.readAsBytes(buildStep.inputId)).toString();
      if (spec.isTypeOnly && !await _typeFileLayoutOk(buildStep, spec)) return;

      // ── Validate before generating (module files only) ─────────────────
      if (!spec.isTypeOnly) {
        final issues = SpecValidator.validate(spec);
        for (final issue in issues) {
          if (issue.isError) {
            log.severe('nitrogen: ${buildStep.inputId.path}\n  $issue');
          } else {
            log.warning('nitrogen: ${buildStep.inputId.path}\n  $issue');
          }
        }
        if (issues.any((i) => i.isError)) {
          log.severe(
            'nitrogen: Aborting generation for ${buildStep.inputId.path} due to validation errors above.',
          );
          return;
        }
      }

      // We can use buildStep.allowedOutputs to find the EXACT output paths
      // generated by build_runner based on our map.
      final outputs = buildStep.allowedOutputs;

      for (final outId in outputs) {
        // Type-only files skip implementation outputs (no bridge class, no CMake, etc.).
        if (spec.isTypeOnly) {
          if (outId.path.endsWith('.bridge.g.cpp') || outId.path.endsWith('.CMakeLists.g.txt') || outId.path.endsWith('.native.g.h') || outId.path.endsWith('.mock.g.h') || outId.path.endsWith('.test.g.cpp')) {
            // Write a minimal placeholder so build_runner is satisfied.
            await buildStep.writeAsString(outId, '// Type-only file — no bridge implementation generated.\n');
            continue;
          }
        }

        final target = _nativeGenerators.targetForOutputPath(outId.path);
        if (target == null) continue;

        if (target == NativeGeneratorTarget.dartFfi || target == NativeGeneratorTarget.webBridge || target == NativeGeneratorTarget.dartFfiLibrary || target == NativeGeneratorTarget.dartPlatformShim) {
          // All Dart-producing generators format for readability.
          final rawCode = _nativeGenerators.generate(target, spec);
          String formattedCode;
          try {
            formattedCode = _formatter.format(rawCode);
          } catch (e) {
            log.warning('nitrogen: Could not format ${outId.path}:\n$e');
            formattedCode = rawCode;
          }
          await buildStep.writeAsString(outId, formattedCode);
        } else {
          await buildStep.writeAsString(outId, _nativeGenerators.generate(target, spec));
        }
      }
    } catch (e, st) {
      log.severe('nitrogen: Could not process ${buildStep.inputId}:\n$e\n$st');
    }
  }

  /// A type-only file's Dart layout follows its importers: split (dart:ffi in
  /// the native-only library) when a web-targeting module imports it, so that
  /// module's web build never compiles dart:ffi. A native-only module that
  /// imports a split file cannot reach the moved pieces (its generated code is
  /// a `part`), so that mix is reported instead of generating broken code.
  static Future<bool> _typeFileLayoutOk(BuildStep buildStep, BridgeSpec spec) async {
    final self = buildStep.inputId;
    final web = <String>[];
    final nativeOnly = <String>[];
    await for (final id in buildStep.findAssets(Glob('lib/**.native.dart'))) {
      if (id == self) continue;
      final src = await buildStep.readAsString(id);
      // Up to the annotated class: the arguments may hold comments with parentheses.
      final module = RegExp(r'@NitroModule\s*\((.*?)\)\s*abstract\s+class', dotAll: true).firstMatch(src);
      if (module == null) continue;
      final imports = [
        for (final m in RegExp(r"""^import\s+['"]([^'"]+)['"]""", multiLine: true).allMatches(src))
          if (Uri.parse(m.group(1)!) case final uri when uri.scheme == 'package' || !uri.hasScheme)
            uri.scheme == 'package' ? AssetId.resolve(uri) : AssetId.resolve(uri, from: id),
      ];
      if (!imports.contains(self)) continue;
      (RegExp(r'\bweb\s*:').hasMatch(module.group(1)!) ? web : nativeOnly).add(id.path);
    }
    if (web.isNotEmpty && nativeOnly.isNotEmpty) {
      log.severe(
        'nitrogen: ${self.path} is shared by web modules (${web.join(', ')}) and '
        'native-only modules (${nativeOnly.join(', ')}). Target web from every '
        'module that imports it, or give the native-only modules their own type file.',
      );
      return false;
    }
    spec.typeOnlyForWeb = web.isNotEmpty;
    return true;
  }
}

