import 'package:build/build.dart';
import 'package:dart_style/dart_style.dart';
import 'package:source_gen/source_gen.dart';
import 'src/build_extensions.dart';
import 'src/spec_extractor.dart';
import 'src/spec_validator.dart';
import 'src/generators/native_generator_facade.dart';

Builder nitroGeneratorBuilder(BuilderOptions options) {
  return NitroGeneratorBuilder();
}

class NitroGeneratorBuilder implements Builder {
  static final _formatter = DartFormatter(languageVersion: DartFormatter.latestLanguageVersion);
  static final _nativeGenerators = NativeGeneratorFacade.defaults();

  @override
  Map<String, List<String>> get buildExtensions => nitroBuilderExtensions;

  @override
  Future<void> build(BuildStep buildStep) async {
    final libraryElement = await buildStep.inputLibrary;
    final library = LibraryReader(libraryElement);

    try {
      // extractAny handles both @NitroModule files and type-only files.
      // Returns null when the file has no Nitrogen-relevant content.
      final spec = SpecExtractor.extractAny(library);
      if (spec == null) return;

      // ── Validate before generating (module files only) ─────────────────
      if (!spec.isTypeOnly) {
        final issues = SpecValidator.validate(spec);
        for (final issue in issues) {
          if (issue.isError) {
            log.severe('nitrogen: ${buildStep.inputId.path}\n  $issue');
          } else {
            log.warning('nitrogen: ${buildStep.inputId.path}\n  $issue');
          }
        }
        if (issues.any((i) => i.isError)) {
          log.severe(
            'nitrogen: Aborting generation for ${buildStep.inputId.path} due to validation errors above.',
          );
          return;
        }
      }

      // We can use buildStep.allowedOutputs to find the EXACT output paths
      // generated by build_runner based on our map.
      final outputs = buildStep.allowedOutputs;

      for (final outId in outputs) {
        // Type-only files skip implementation outputs (no bridge class, no CMake, etc.).
        if (spec.isTypeOnly) {
          if (outId.path.endsWith('.bridge.g.cpp') || outId.path.endsWith('.CMakeLists.g.txt') || outId.path.endsWith('.native.g.h') || outId.path.endsWith('.mock.g.h') || outId.path.endsWith('.test.g.cpp')) {
            // Write a minimal placeholder so build_runner is satisfied.
            await buildStep.writeAsString(outId, '// Type-only file — no bridge implementation generated.\n');
            continue;
          }
        }

        final target = _nativeGenerators.targetForOutputPath(outId.path);
        if (target == null) continue;

        if (target == NativeGeneratorTarget.dartFfi) {
          final rawCode = _nativeGenerators.generate(target, spec);
          String formattedCode;
          try {
            formattedCode = _formatter.format(rawCode);
          } catch (e) {
            log.warning('nitrogen: Could not format ${outId.path}:\n$e');
            formattedCode = rawCode;
          }
          await buildStep.writeAsString(outId, formattedCode);
        } else {
          await buildStep.writeAsString(outId, _nativeGenerators.generate(target, spec));
        }
      }
    } catch (e, st) {
      log.severe('nitrogen: Could not process ${buildStep.inputId}:\n$e\n$st');
    }
  }
}
