import 'package:build/build.dart';
import 'package:dart_style/dart_style.dart';
import 'package:source_gen/source_gen.dart';
import 'src/spec_extractor.dart';
import 'src/spec_validator.dart';
import 'src/generators/dart_ffi_generator.dart';
import 'src/generators/cpp_header_generator.dart';
import 'src/generators/kotlin_generator.dart';
import 'src/generators/swift_generator.dart';
import 'src/generators/cmake_generator.dart';
import 'src/generators/cpp_bridge_generator.dart';
import 'src/generators/cpp_interface_generator.dart';
import 'src/generators/cpp_mock_generator.dart';

Builder nitroGeneratorBuilder(BuilderOptions options) {
  return NitroGeneratorBuilder();
}

class NitroGeneratorBuilder implements Builder {
  @override
  Map<String, List<String>> get buildExtensions => {
    '^lib/{{dir}}/{{file}}.native.dart': [
      'lib/{{dir}}/{{file}}.g.dart',
      'lib/{{dir}}/generated/kotlin/{{file}}.bridge.g.kt',
      'lib/{{dir}}/generated/swift/{{file}}.bridge.g.swift',
      'lib/{{dir}}/generated/cpp/{{file}}.bridge.g.h',
      'lib/{{dir}}/generated/cpp/{{file}}.bridge.g.cpp',
      'lib/{{dir}}/generated/cmake/{{file}}.CMakeLists.g.txt',
      // NativeImpl.cpp — direct C++ implementation support
      'lib/{{dir}}/generated/cpp/{{file}}.native.g.h',
      'lib/{{dir}}/generated/cpp/test/{{file}}.mock.g.h',
      'lib/{{dir}}/generated/cpp/test/{{file}}.test.g.cpp',
    ],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final libraryElement = await buildStep.inputLibrary;
    final library = LibraryReader(libraryElement);

    try {
      final spec = SpecExtractor.extract(library);

      // ── Validate before generating ─────────────────────────────────────
      final issues = SpecValidator.validate(spec);
      for (final issue in issues) {
        if (issue.isError) {
          log.severe('nitrogen: ${buildStep.inputId.path}\n  $issue');
        } else {
          log.warning('nitrogen: ${buildStep.inputId.path}\n  $issue');
        }
      }
      if (issues.any((i) => i.isError)) {
        log.severe(
          'nitrogen: Aborting generation for ${buildStep.inputId.path} due to validation errors above.',
        );
        return;
      }

      // We can use buildStep.allowedOutputs to find the EXACT output paths
      // generated by build_runner based on our map.
      final outputs = buildStep.allowedOutputs;

      for (final outId in outputs) {
        if (outId.path.endsWith('.g.dart')) {
          final rawCode = DartFfiGenerator.generate(spec);
          String formattedCode;
          try {
            formattedCode = DartFormatter().format(rawCode);
          } catch (e) {
            log.warning('nitrogen: Could not format ${outId.path}:\n$e');
            formattedCode = rawCode;
          }
          await buildStep.writeAsString(outId, formattedCode);
        } else if (outId.path.endsWith('.bridge.g.kt')) {
          await buildStep.writeAsString(outId, KotlinGenerator.generate(spec));
        } else if (outId.path.endsWith('.bridge.g.swift')) {
          await buildStep.writeAsString(outId, SwiftGenerator.generate(spec));
        } else if (outId.path.endsWith('.bridge.g.h')) {
          await buildStep.writeAsString(outId, CppHeaderGenerator.generate(spec));
        } else if (outId.path.endsWith('.bridge.g.cpp')) {
          await buildStep.writeAsString(outId, CppBridgeGenerator.generate(spec));
        } else if (outId.path.endsWith('.CMakeLists.g.txt')) {
          await buildStep.writeAsString(outId, CMakeGenerator.generate(spec));
        // ── NativeImpl.cpp outputs ─────────────────────────────────────
        } else if (outId.path.endsWith('.native.g.h')) {
          await buildStep.writeAsString(outId, CppInterfaceGenerator.generate(spec));
        } else if (outId.path.endsWith('.mock.g.h')) {
          await buildStep.writeAsString(outId, CppMockGenerator.generateMockHeader(spec));
        } else if (outId.path.endsWith('.test.g.cpp')) {
          await buildStep.writeAsString(outId, CppMockGenerator.generateTestStarter(spec));
        }
      }
    } catch (e, st) {
      log.warning('nitrogen: Could not process ${buildStep.inputId}:\n$e\n$st');
    }
  }
}
