import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;
import '../ui.dart';

class InitCommand extends Command {
  @override
  final String name = 'init';

  @override
  final String description =
      'Scaffolds a new Nitrogen FFI plugin project with optimized native configs.';

  InitCommand() {
    argParser.addOption('org',
        defaultsTo: 'com.example',
        help: 'The organization (e.g., com.mycompany) for the plugin.');
  }

  @override
  void run() async {
    if (argResults!.rest.isEmpty) {
      stderr.writeln('❌ Please provide a plugin name: nitrogen init <plugin_name>');
      exit(1);
    }

    final pluginName = argResults!.rest.first;
    final org = argResults!['org'] as String;
    final dir = Directory(pluginName);

    if (dir.existsSync()) {
      stderr.writeln('❌ Directory $pluginName already exists.');
      exit(1);
    }

    printBanner('nitrogen init — $pluginName');
    printSection('Scaffolding Flutter plugin');
    stdout.writeln('');
    final createResult = Process.runSync('flutter', [
      'create',
      '--template=plugin_ffi',
      '--platforms=android,ios',
      '--org=$org',
      pluginName,
    ]);

    if (createResult.exitCode != 0) {
      stderr.writeln(createResult.stderr);
      exit(createResult.exitCode);
    }

    final className = _toClassName(pluginName);

    printSection('Native src/ directory');
    _setupSrc(pluginName);
    printOk('src/CMakeLists.txt and $pluginName.cpp created');

    printSection('iOS — podspec + Swift plugin');
    _configureIos(pluginName, className);

    printSection('Android — build.gradle + Plugin.kt');
    _configureAndroid(pluginName, className, org);

    printSection('pubspec.yaml');
    _updatePubspec(pluginName, className, org);
    printOk('nitro, build_runner, nitrogen, pluginClass entries added');

    printSection('Dart bridge spec');
    _writeBridgeSpec(pluginName, className);
    printOk('lib/src/$pluginName.native.dart created');

    stdout.writeln('');
    stdout.writeln(bold(green('  ✨ $pluginName is ready!')));
    stdout.writeln('');
    stdout.writeln(dim('  Next steps:'));
    stdout.writeln(dim('    1. Edit lib/src/$pluginName.native.dart — define your API'));
    stdout.writeln(dim('    2. Run: nitrogen generate'));
    stdout.writeln(dim('    3. Run: nitrogen link'));
    stdout.writeln(dim('    4. Implement Hybrid${className}Spec in Kotlin & Swift'));
    stdout.writeln(dim('    5. Run: nitrogen doctor  — verify everything is wired up'));
    stdout.writeln('');
  }

  // ── src/ ──────────────────────────────────────────────────────────────────

  void _setupSrc(String pluginName) {
    final srcDir = Directory(p.join(pluginName, 'src'));
    if (!srcDir.existsSync()) srcDir.createSync(recursive: true);

    // Main C++ entry point
    File(p.join(srcDir.path, '$pluginName.cpp')).writeAsStringSync('''
#include <stdint.h>
#include <stdbool.h>

// Generated Nitrogen bridge (header + impl included together for the main target)
#include "../lib/src/generated/cpp/$pluginName.bridge.g.h"
#include "../lib/src/generated/cpp/$pluginName.bridge.g.cpp"

extern "C" {
    // Add manual non-Nitrogen FFI functions here.
}
''');

    // src/CMakeLists.txt — uses NITRO_NATIVE variable so the path is correct
    // regardless of where the src/ directory is relative to the workspace root.
    File(p.join(srcDir.path, 'CMakeLists.txt')).writeAsStringSync('''
cmake_minimum_required(VERSION 3.10)
project(${pluginName}_library VERSION 0.0.1 LANGUAGES C CXX)

set(NITRO_NATIVE "\${CMAKE_CURRENT_SOURCE_DIR}/../../packages/nitro/src/native")
set(GENERATED_CPP "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp")

add_library($pluginName SHARED
  "$pluginName.cpp"
  "\${NITRO_NATIVE}/dart_api_dl.c"
)

target_include_directories($pluginName PRIVATE
  "\${CMAKE_CURRENT_SOURCE_DIR}"
  "\${GENERATED_CPP}"
  "\${NITRO_NATIVE}"
)

target_compile_definitions($pluginName PUBLIC DART_SHARED_LIB)

if(ANDROID)
  target_link_libraries($pluginName PRIVATE android log)
  target_link_options($pluginName PRIVATE "-Wl,-z,max-page-size=16384")
endif()
''');
  }

  // ── iOS ───────────────────────────────────────────────────────────────────

  void _configureIos(String pluginName, String className) {
    final classesDir = Directory(p.join(pluginName, 'ios', 'Classes'));
    if (!classesDir.existsSync()) classesDir.createSync(recursive: true);

    // Remove old .c stub generated by flutter create
    final oldC = File(p.join(classesDir.path, '$pluginName.c'));
    if (oldC.existsSync()) oldC.deleteSync();

    // Remove any auto-generated Swift plugin so ours is the only one
    for (final f in classesDir.listSync().whereType<File>()) {
      if (f.path.endsWith('Plugin.swift')) f.deleteSync();
    }

    // C++ forwarder (iOS CocoaPods compiles everything in ios/Classes/)
    File(p.join(classesDir.path, '$pluginName.cpp'))
        .writeAsStringSync('#include "../../src/$pluginName.cpp"\n');

    // dart_api_dl forwarder
    File(p.join(classesDir.path, 'dart_api_dl.cpp')).writeAsStringSync(
        '// Forwarder — compiled by CocoaPods so Dart DL API is available in the dylib.\n'
        '#include "../../../packages/nitro/src/native/dart_api_dl.c"\n');

    // Swift plugin class — registers the native impl with Nitrogen's registry
    File(p.join(classesDir.path, 'Swift${className}Plugin.swift'))
        .writeAsStringSync('''import Flutter
import UIKit

public class Swift${className}Plugin: NSObject, FlutterPlugin {
    public static func register(with registrar: FlutterPluginRegistrar) {
        ${className}Registry.register(${className}Impl())
    }
}
''');

    // Podspec
    final podspecFile = File(p.join(pluginName, 'ios', '$pluginName.podspec'));
    if (podspecFile.existsSync()) {
      var content = podspecFile.readAsStringSync();

      content = content.replaceFirst(
          RegExp(r"s\.platform = :ios, '[\d.]+'"), "s.platform = :ios, '13.0'");
      content = content.replaceFirst(
          RegExp(r"s\.swift_version = '[\d.]+'"), "s.swift_version = '5.9'");

      // Replace pod_target_xcconfig wholesale to avoid duplicate-key issues
      // when init + link are both run.
      const xcconfig = '''s.pod_target_xcconfig = {
    'CLANG_CXX_LANGUAGE_STANDARD' => 'c++17',
    'CLANG_CXX_LIBRARY' => 'libc++',
    'HEADER_SEARCH_PATHS' => '\$(inherited) "\${PODS_TARGET_SRCROOT}/../../../packages/nitro/src/native"'
  }''';
      content = content.replaceFirst(
          RegExp(r's\.pod_target_xcconfig\s*=\s*\{[^}]*\}'), xcconfig);

      podspecFile.writeAsStringSync(content);
      stdout.writeln('  ✅ Updated ios/$pluginName.podspec');
    }
  }

  // ── Android ───────────────────────────────────────────────────────────────

  void _configureAndroid(String pluginName, String className, String org) {
    // Overwrite build.gradle with full Kotlin + coroutines + generated sourceSets
    File(p.join(pluginName, 'android', 'build.gradle')).writeAsStringSync('''
// The Android Gradle Plugin builds the native code with the Android NDK.

group = "$org.$pluginName"
version = "1.0"

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.11.1")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"

android {
    namespace = "$org.$pluginName"
    compileSdk = 36
    ndkVersion = android.ndkVersion

    externalNativeBuild {
        cmake {
            path = "../src/CMakeLists.txt"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    defaultConfig {
        minSdk = 24
    }

    sourceSets {
        main {
            // Include Nitrogen-generated Kotlin bridge files automatically
            kotlin.srcDirs += "\${project.projectDir}/../lib/src/generated/kotlin"
            java.srcDirs += "\${project.projectDir}/../lib/src/generated/kotlin"
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
}
''');
    stdout.writeln('  ✅ Wrote android/build.gradle with Kotlin + coroutines');

    // Create Plugin.kt — registers the native impl with the JNI bridge.
    // The Impl class (${className}Impl.kt) is left for the developer to fill in.
    final moduleName = '${pluginName}_module';
    final orgPath = org.replaceAll('.', p.separator);
    final kotlinDir = Directory(
        p.join(pluginName, 'android', 'src', 'main', 'kotlin', orgPath, pluginName));
    if (!kotlinDir.existsSync()) kotlinDir.createSync(recursive: true);

    File(p.join(kotlinDir.path, '${className}Plugin.kt')).writeAsStringSync('''
package $org.$pluginName

import io.flutter.embedding.engine.plugins.FlutterPlugin
import nitro.${moduleName}.${className}JniBridge

class ${className}Plugin : FlutterPlugin {

    companion object {
        init {
            System.loadLibrary("$pluginName")
        }
    }

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        ${className}JniBridge.register(
            ${className}Impl(binding.applicationContext)
        )
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {}
}
''');
    stdout.writeln('  ✅ Created android/.../kotlin/${className}Plugin.kt');
  }

  // ── pubspec.yaml ──────────────────────────────────────────────────────────

  void _updatePubspec(String pluginName, String className, String org) {
    final pubspecFile = File(p.join(pluginName, 'pubspec.yaml'));
    var pubspec = pubspecFile.readAsStringSync();

    // Add nitro runtime dependency
    pubspec = pubspec.replaceFirst(
        'dependencies:\n  flutter:\n    sdk: flutter',
        'dependencies:\n  flutter:\n    sdk: flutter\n  nitro: { path: ../packages/nitro }');

    // Add build tooling dev-dependencies (match any flutter_lints version)
    pubspec = pubspec.replaceFirst(
        RegExp(r'  flutter_lints: \^\S+'),
        '  flutter_lints: ^6.0.0\n'
        '  build_runner: ^2.4.0\n'
        '  nitrogen: { path: ../packages/nitrogen }');

    // Replace the plain ffiPlugin-only block that flutter create emits with a
    // full block that includes pluginClass + package so Flutter can register
    // the plugin class at startup (needed to call NitroBatteryRegistry.register).
    pubspec = pubspec.replaceFirst(
        RegExp(
            r'    platforms:\s*\n'
            r'      android:\s*\n'
            r'        ffiPlugin: true\s*\n'
            r'      ios:\s*\n'
            r'        ffiPlugin: true'),
        '    platforms:\n'
        '      android:\n'
        '        pluginClass: ${className}Plugin\n'
        '        package: $org.$pluginName\n'
        '        ffiPlugin: true\n'
        '      ios:\n'
        '        pluginClass: Swift${className}Plugin\n'
        '        ffiPlugin: true');

    pubspecFile.writeAsStringSync(pubspec);
  }

  // ── Bridge spec ───────────────────────────────────────────────────────────

  void _writeBridgeSpec(String pluginName, String className) {
    final libSrcDir = Directory(p.join(pluginName, 'lib', 'src'));
    libSrcDir.createSync(recursive: true);

    // Note: _${className}Impl() is Dart string interpolation — produces e.g.
    // _NitroBatteryImpl() in the written file.
    File(p.join(libSrcDir.path, '$pluginName.native.dart'))
        .writeAsStringSync('''import 'package:nitro/nitro.dart';

part '${pluginName}.g.dart';

@NitroModule(ios: NativeImpl.swift, android: NativeImpl.kotlin)
abstract class $className extends HybridObject {
  static final $className instance = _${className}Impl();

  double add(double a, double b);

  @nitroAsync
  Future<String> getGreeting(String name);
}
''');

    File(p.join(pluginName, 'lib', '$pluginName.dart'))
        .writeAsStringSync("export 'src/$pluginName.native.dart';\n");
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  String _toClassName(String pluginName) {
    return pluginName
        .split('_')
        .map((w) => w.isEmpty ? '' : w[0].toUpperCase() + w.substring(1))
        .join('');
  }
}
