import 'dart:convert';
import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:nocterm/nocterm.dart';
import 'package:path/path.dart' as p;
import '../ui.dart';
import '../utils.dart';

// ── Package-level helpers (also used in tests) ─────────────────────────────

/// Resolves the absolute path to the installed `nitro` package's `src/native`
/// directory by reading `.dart_tool/package_config.json` inside [pluginDir].
String resolveNitroNativePath(String pluginDir) {
  final configFile = File(p.join(pluginDir, '.dart_tool', 'package_config.json'));
  if (configFile.existsSync()) {
    try {
      final config = jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
      final packages = (config['packages'] as List<dynamic>?) ?? [];
      for (final pkg in packages) {
        final pkgMap = pkg as Map<String, dynamic>;
        if (pkgMap['name'] == 'nitro') {
          final rootUri = pkgMap['rootUri'] as String;
          final uri = Uri.parse(rootUri);
          if (uri.scheme == 'file') {
            return p.join(uri.toFilePath(), 'src', 'native');
          } else {
            final dartToolDir = p.join(pluginDir, '.dart_tool');
            final resolved = p.normalize(p.join(dartToolDir, rootUri));
            return p.join(resolved, 'src', 'native');
          }
        }
      }
    } catch (_) {}
  }
  return p.normalize(p.absolute(p.join(pluginDir, '..', 'packages', 'nitro', 'src', 'native')));
}

bool nitroNativePathExists(String cmakeNitroNative, String srcDir) {
  final resolved = cmakeNitroNative.replaceAll(r'${CMAKE_CURRENT_SOURCE_DIR}', srcDir);
  return File(p.join(resolved, 'dart_api_dl.h')).existsSync();
}

String dartApiDlForwarderContent(String nitroNativePath) {
  final includePath = p.join(nitroNativePath, 'dart_api_dl.c').replaceAll(r'\', '/');
  return '// Generated by nitrogen link — do not edit.\n'
      '// Compiled as C (not C++) so the void*/function-pointer casts\n'
      '// in dart_api_dl.c are accepted by the compiler.\n'
      '#include "$includePath"\n';
}

String? extractLibNameFromSpec(File specFile) {
  final content = specFile.readAsStringSync();
  final match = RegExp(r'''@NitroModule\s*\([^)]*lib\s*:\s*['"]([^'"]+)['"]''').firstMatch(content);
  return match?.group(1);
}

/// Returns true when the spec file declares both platforms as NativeImpl.cpp —
/// meaning it uses a direct C++ implementation instead of Kotlin/Swift bridges.
bool isCppModule(File specFile) {
  final content = specFile.readAsStringSync();
  final match = RegExp(r'@NitroModule\s*\(([^)]+)\)').firstMatch(content);
  if (match == null) return false;
  final annotation = match.group(1)!;
  return annotation.contains('NativeImpl.cpp') && annotation.replaceFirst('NativeImpl.cpp', '').contains('NativeImpl.cpp');
}

/// Module descriptor. `isCpp` indicates a direct C++ implementation (no JNI/Swift bridge).
class ModuleInfo {
  final String lib;
  final String module;
  final bool isCpp;
  const ModuleInfo({required this.lib, required this.module, required this.isCpp});
  Map<String, String> toMap() => {'lib': lib, 'module': module};
}

List<ModuleInfo> discoverModuleInfos(String pluginName, {String baseDir = '.'}) {
  final libDir = Directory(p.join(baseDir, 'lib'));
  if (!libDir.existsSync()) {
    return [ModuleInfo(lib: pluginName, module: pluginName, isCpp: false)];
  }
  final specs = libDir.listSync(recursive: true).whereType<File>().where((f) => f.path.endsWith('.native.dart')).toList();
  if (specs.isEmpty) {
    return [ModuleInfo(lib: pluginName, module: pluginName, isCpp: false)];
  }

  final modules = <ModuleInfo>[];
  for (final spec in specs) {
    final content = spec.readAsStringSync();
    final stem = p.basename(spec.path).replaceAll(RegExp(r'\.native\.dart$'), '');
    final libName = extractLibNameFromSpec(spec) ?? stem.replaceAll('-', '_');
    final moduleMatch = RegExp(r'abstract class (\w+) extends HybridObject').firstMatch(content);
    final moduleName = moduleMatch?.group(1) ?? _toPascalCase(stem);

    if (!modules.any((m) => m.module == moduleName)) {
      modules.add(ModuleInfo(lib: libName, module: moduleName, isCpp: isCppModule(spec)));
    }
  }
  return modules;
}

// Keep legacy signature for external callers
List<Map<String, String>> discoverModules(String pluginName, {String baseDir = '.'}) {
  return discoverModuleInfos(pluginName, baseDir: baseDir).map((m) => m.toMap()).toList();
}

// ── Progress model ──────────────────────────────

enum LinkStepState { pending, running, done, failed, skipped }

class LinkStep {
  final String label;
  LinkStepState state;
  String? detail;
  LinkStep(this.label) : state = LinkStepState.pending;
}

class LinkStepRow extends StatelessComponent {
  const LinkStepRow(this.step, {super.key});
  final LinkStep step;

  @override
  Component build(BuildContext context) {
    final String icon;
    final Color color;
    switch (step.state) {
      case LinkStepState.pending:
        icon = '○';
        color = Colors.gray;
      case LinkStepState.running:
        icon = '◉';
        color = Colors.cyan;
      case LinkStepState.done:
        icon = '✔';
        color = Colors.green;
      case LinkStepState.failed:
        icon = '✘';
        color = Colors.red;
      case LinkStepState.skipped:
        icon = '–';
        color = Colors.gray;
    }
    return Padding(
      padding: const EdgeInsets.only(left: 2),
      child: Column(
        children: [
          Row(
            children: [
              Text(
                icon,
                style: TextStyle(color: color, fontWeight: FontWeight.bold),
              ),
              const Text(' '),
              Expanded(
                child: Text(
                  step.label,
                  style: TextStyle(color: step.state == LinkStepState.running ? Colors.cyan : null, fontWeight: step.state == LinkStepState.running ? FontWeight.bold : null),
                ),
              ),
            ],
          ),
          if (step.detail != null)
            Padding(
              padding: const EdgeInsets.only(left: 4),
              child: Text(
                step.detail!,
                style: const TextStyle(color: Colors.gray, fontWeight: FontWeight.dim),
              ),
            ),
        ],
      ),
    );
  }
}

class LinkResult {
  bool success = false;
}

class LinkView extends StatefulComponent {
  const LinkView({required this.pluginName, required this.result, this.onExit, super.key});
  final String pluginName;
  final LinkResult result;
  final VoidCallback? onExit;

  @override
  State<LinkView> createState() => _LinkViewState();
}

class _LinkViewState extends State<LinkView> {
  late final List<LinkStep> _steps = [
    LinkStep('Discovering modules'),
    LinkStep('Updating src/CMakeLists.txt'),
    LinkStep('Updating iOS podspec'),
    LinkStep('Updating Swift Plugin.swift (Kotlin/Swift modules)'),
    LinkStep('Updating Kotlin Plugin.kt (Kotlin/Swift modules)'),
    LinkStep('Updating .clangd'),
  ];

  bool _finished = false;
  bool _failed = false;
  String? _errorMessage;
  final List<String> _nextSteps = [];

  @override
  void initState() {
    super.initState();
    Future<void>.delayed(Duration.zero, _run);
  }

  Future<void> _setRunning(int i) async {
    setState(() => _steps[i].state = LinkStepState.running);
  }

  Future<void> _setDone(int i, {String? detail}) async {
    setState(() {
      _steps[i].state = LinkStepState.done;
      _steps[i].detail = detail;
    });
  }

  Future<void> _setSkipped(int i, {String? detail}) async {
    setState(() {
      _steps[i].state = LinkStepState.skipped;
      _steps[i].detail = detail;
    });
  }

  Future<void> _run() async {
    final pluginName = component.pluginName;
    try {
      await _setRunning(0);
      final moduleInfos = discoverModuleInfos(pluginName, baseDir: Directory.current.path);
      final allCpp = moduleInfos.every((m) => m.isCpp);
      final hasCpp = moduleInfos.any((m) => m.isCpp);
      final hasNonCpp = moduleInfos.any((m) => !m.isCpp);
      final cppLabel = hasCpp ? ' (${moduleInfos.where((m) => m.isCpp).map((m) => m.module).join(', ')} → C++)' : '';
      await _setDone(0, detail: '${moduleInfos.length} module(s): ${moduleInfos.map((m) => m.module).join(', ')}$cppLabel');

      await _setRunning(1);
      final nitroNativePath = resolveNitroNativePath(Directory.current.path);
      linkCMake(pluginName, moduleInfos.map((m) => m.lib).toList(), nitroNativePath, baseDir: Directory.current.path, moduleInfos: moduleInfos);
      linkCppImplStubs(moduleInfos, baseDir: Directory.current.path);
      await _setDone(1);

      await _setRunning(2);
      if (Directory(p.join(Directory.current.path, 'ios')).existsSync()) {
        linkPodspec(pluginName, moduleInfos.map((m) => m.lib).toList(), baseDir: Directory.current.path, moduleInfos: moduleInfos);
        await _setDone(2);
      } else {
        await _setSkipped(2, detail: 'ios/ not present');
      }

      await _setRunning(3);
      if (!hasNonCpp) {
        await _setSkipped(3, detail: 'all modules use NativeImpl.cpp — no Swift bridge needed');
      } else if (Directory(p.join(Directory.current.path, 'ios')).existsSync()) {
        // Only wire non-cpp modules into Swift plugin
        final nonCppModules = moduleInfos.where((m) => !m.isCpp).map((m) => m.toMap()).toList();
        linkSwiftPlugin(pluginName, nonCppModules, baseDir: Directory.current.path);
        await _setDone(3);
      } else {
        await _setSkipped(3, detail: 'ios/ not present');
      }

      await _setRunning(4);
      if (Directory(p.join(Directory.current.path, 'android')).existsSync()) {
        if (hasNonCpp) {
          final nonCppModules = moduleInfos.where((m) => !m.isCpp).map((m) => m.toMap()).toList();
          linkKotlinPlugin(pluginName, nonCppModules, baseDir: Directory.current.path);
        }
        // cpp modules still need System.loadLibrary to trigger __attribute__((constructor))
        if (hasCpp) {
          linkKotlinLoadLibraries(moduleInfos.where((m) => m.isCpp).map((m) => m.lib).toList(), baseDir: Directory.current.path);
        }
        await _setDone(4, detail: hasNonCpp ? null : 'cpp: loadLibrary only (no JniBridge)');
      } else {
        await _setSkipped(4, detail: 'android/ not present');
      }

      await _setRunning(5);
      linkClangd(pluginName, moduleInfos: moduleInfos, baseDir: Directory.current.path);
      await _setDone(5);

      if (allCpp) {
        _nextSteps.addAll([
          'nitrogen generate',
          'Subclass Hybrid<Module> in C++ and call ${pluginName}_register_impl(&impl)',
          'Build and test with ctest (auto-generated test target)',
        ]);
      } else if (hasCpp) {
        _nextSteps.addAll([
          'nitrogen generate',
          'C++ modules: subclass Hybrid<Module>, call ${pluginName}_register_impl(&impl)',
          'Kotlin/Swift modules: implement Hybrid<Module>Spec / HybridProtocol',
        ]);
      } else {
        _nextSteps.addAll(['flutter pub get', 'flutter pub run build_runner build --delete-conflicting-outputs', 'nitrogen generate', 'Implement Specs in Kotlin/Swift']);
      }
    } catch (e) {
      setState(() {
        _failed = true;
        _errorMessage = e.toString();
      });
    }
    component.result.success = !_failed;
    setState(() => _finished = true);
  }

  @override
  Component build(BuildContext context) {
    return Focusable(
      focused: true,
      onKeyEvent: (e) {
        if (e.logicalKey == LogicalKey.escape) {
          if (component.onExit != null) {
            component.onExit!();
            return true;
          }
          shutdownApp(_failed ? 1 : 0);
          return true;
        }
        return false;
      },
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 1, left: 1, right: 1),
            child: Container(
              decoration: BoxDecoration(border: BoxBorder.all(color: Colors.cyan)),
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 2),
                child: Text(
                  ' nitrogen link — ${component.pluginName} ',
                  style: const TextStyle(color: Colors.cyan, fontWeight: FontWeight.bold),
                ),
              ),
            ),
          ),
          const SizedBox(height: 1),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 1),
              child: _errorMessage != null
                  ? Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 2, vertical: 1),
                            decoration: BoxDecoration(border: BoxBorder.all(color: Colors.red)),
                            child: const Text(
                              ' ✘ ERROR ',
                              style: TextStyle(color: Colors.red, fontWeight: FontWeight.bold),
                            ),
                          ),
                          const SizedBox(height: 1),
                          Text(_errorMessage!),
                        ],
                      ),
                    )
                  : Container(
                      decoration: BoxDecoration(border: BoxBorder.all(color: Colors.brightBlack)),
                      child: ListView(children: _steps.map(LinkStepRow.new).toList()),
                    ),
            ),
          ),
          if (_finished)
            Padding(
              padding: const EdgeInsets.all(1),
              child: Column(
                children: [
                  if (!_failed) ...[
                    const Text(
                      '✨ Linked! Next steps:',
                      style: TextStyle(color: Colors.green, fontWeight: FontWeight.bold),
                    ),
                    ..._nextSteps.asMap().entries.map((e) => Text('  ${e.key + 1}. ${e.value}', style: const TextStyle(color: Colors.gray))),
                  ],
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      if (component.onExit != null) ...[
                        HoverButton(label: '‹ Back', onTap: component.onExit!, color: Colors.cyan),
                        const Text('  •  ', style: TextStyle(color: Colors.brightBlack)),
                      ],
                      Text(
                        component.onExit != null ? 'ESC back' : 'ESC exit',
                        style: const TextStyle(color: Colors.gray, fontWeight: FontWeight.dim),
                      ),
                    ],
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

const String nitroHContent = r'''#pragma once

#include <stdint.h>
#include <stdbool.h>

#if _WIN32
#define NITRO_EXPORT __declspec(dllexport)
#else
#define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;

#ifdef __cplusplus
}
#endif
''';

void createSharedHeaders(String nitroNativePath, {String baseDir = '.'}) {
  Directory(p.join(baseDir, 'src')).createSync(recursive: true);
  final srcFile = File(p.join(nitroNativePath, 'nitro.h'));

  // If the source nitro.h is missing the required macros, update it first.
  if (srcFile.existsSync()) {
    final current = srcFile.readAsStringSync();
    if (!current.contains('NITRO_EXPORT')) {
      srcFile.writeAsStringSync(nitroHContent);
    }
  } else {
    // If it doesn't exist in the nitro package at all, create it.
    try {
      srcFile.createSync(recursive: true);
      srcFile.writeAsStringSync(nitroHContent);
    } catch (_) {
      // Might not have write access to pub-cache; that's fine, we'll write to the local project.
    }
  }

  // Always write the correct content to the local project directories.
  File(p.join(baseDir, 'src', 'nitro.h')).writeAsStringSync(nitroHContent);
  if (Directory(p.join(baseDir, 'ios', 'Classes')).existsSync()) {
    File(p.join(baseDir, 'ios', 'Classes', 'nitro.h')).writeAsStringSync(nitroHContent);
  }
  File(p.join(baseDir, 'src', 'dart_api_dl.c')).writeAsStringSync(dartApiDlForwarderContent(nitroNativePath));
}

void linkCMake(String pluginName, List<String> moduleLibs, String nitroNativePath, {String baseDir = '.', List<ModuleInfo>? moduleInfos}) {
  createSharedHeaders(nitroNativePath, baseDir: baseDir);
  final cmakeFile = File(p.join(baseDir, 'src', 'CMakeLists.txt'));
  if (!cmakeFile.existsSync()) {
    generateCMake(pluginName, moduleLibs, nitroNativePath, baseDir: baseDir);
    return;
  }
  var content = cmakeFile.readAsStringSync();
  bool modified = false;
  const defaultCmakeNitro = r'${CMAKE_CURRENT_SOURCE_DIR}/../../packages/nitro/src/native';
  final desiredNitroValue = nitroNativePathExists(defaultCmakeNitro, p.join(baseDir, 'src')) ? defaultCmakeNitro : nitroNativePath.replaceAll(r'\', '/');
  final nitroNativeSetLine = 'set(NITRO_NATIVE "$desiredNitroValue")';
  if (!content.contains('NITRO_NATIVE')) {
    content = '$nitroNativeSetLine\n\n$content';
    modified = true;
  } else {
    final staleMatch = RegExp(r'set\(NITRO_NATIVE\s+"([^"]+)"\)').firstMatch(content);
    if (staleMatch != null && !nitroNativePathExists(staleMatch.group(1)!, p.join(baseDir, 'src')) && staleMatch.group(1) != desiredNitroValue) {
      content = content.replaceFirst(staleMatch.group(0)!, nitroNativeSetLine);
      modified = true;
    }
  }
  if (!content.contains(r'${NITRO_NATIVE}')) {
    content = content.replaceFirst('target_include_directories($pluginName PRIVATE', 'target_include_directories($pluginName PRIVATE\n  "\${NITRO_NATIVE}"');
    modified = true;
  }
  if (!content.contains('dart_api_dl.c')) {
    content = content.replaceFirst('add_library($pluginName SHARED', 'add_library($pluginName SHARED\n  "dart_api_dl.c"');
    modified = true;
  }
  final bridgeRel = '../lib/src/generated/cpp/$pluginName.bridge.g.cpp';
  if (!content.contains(bridgeRel)) {
    content = content.replaceFirst('add_library($pluginName SHARED', 'add_library($pluginName SHARED\n  "\${CMAKE_CURRENT_SOURCE_DIR}/$bridgeRel"');
    modified = true;
  }
  for (final lib in moduleLibs) {
    if (lib != pluginName && !content.contains('add_library($lib ')) {
      final isCpp =
          moduleInfos
              ?.firstWhere(
                (m) => m.lib == lib,
                orElse: () => ModuleInfo(lib: lib, module: lib, isCpp: false),
              )
              .isCpp ??
          false;
      content += _cmakeModuleTarget(lib, isCpp: isCpp);
      modified = true;
    }
  }
  if (modified) cmakeFile.writeAsStringSync(content);
}

void generateCMake(String pluginName, List<String> moduleLibs, String nitroNativePath, {String baseDir = '.'}) {
  final nitroValue = nitroNativePathExists(r'${CMAKE_CURRENT_SOURCE_DIR}/../../packages/nitro/src/native', p.join(baseDir, 'src'))
      ? r'${CMAKE_CURRENT_SOURCE_DIR}/../../packages/nitro/src/native'
      : nitroNativePath.replaceAll(r'\', '/');
  final sb = StringBuffer()
    ..writeln('cmake_minimum_required(VERSION 3.10)')
    ..writeln('project(${pluginName}_library VERSION 0.0.1 LANGUAGES C CXX)')
    ..writeln()
    ..writeln('set(NITRO_NATIVE "$nitroValue")')
    ..writeln()
    ..writeln('add_library($pluginName SHARED')
    ..writeln('  "$pluginName.cpp"')
    ..writeln('  "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp/$pluginName.bridge.g.cpp"')
    ..writeln('  "dart_api_dl.c"')
    ..writeln(')')
    ..writeln('target_include_directories($pluginName PRIVATE')
    ..writeln('  "\${CMAKE_CURRENT_SOURCE_DIR}"')
    ..writeln('  "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp"')
    ..writeln('  "\${NITRO_NATIVE}"')
    ..writeln(')')
    ..writeln('target_compile_definitions($pluginName PUBLIC DART_SHARED_LIB)')
    ..writeln('if(ANDROID)')
    ..writeln('  target_link_libraries($pluginName PRIVATE android log)')
    ..writeln('  target_link_options($pluginName PRIVATE "-Wl,-z,max-page-size=16384")')
    ..writeln('endif()');
  for (final lib in moduleLibs) {
    if (lib != pluginName) sb.write(_cmakeModuleTarget(lib));
  }
  File(p.join(baseDir, 'src', 'CMakeLists.txt')).writeAsStringSync(sb.toString());
}

String _cmakeModuleTarget(String lib, {bool isCpp = false}) {
  final implFile = isCpp ? '\n  "Hybrid${_toPascalCase(lib)}.cpp"' : '';
  return '\nadd_library($lib SHARED\n  "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp/$lib.bridge.g.cpp"$implFile\n  "dart_api_dl.c"\n)\ntarget_include_directories($lib PRIVATE\n  "\${CMAKE_CURRENT_SOURCE_DIR}"\n  "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp"\n  "\${NITRO_NATIVE}"\n)\nset_target_properties($lib PROPERTIES OUTPUT_NAME "$lib")\ntarget_compile_definitions($lib PUBLIC DART_SHARED_LIB)\nif(ANDROID)\n  target_link_libraries($lib PRIVATE android log)\n  target_link_options($lib PRIVATE "-Wl,-z,max-page-size=16384")\nendif()\n';
}

String _toPascalCase(String lib) => lib.split(RegExp(r'[_\-]')).map((w) => w.isEmpty ? '' : w[0].toUpperCase() + w.substring(1)).join('');

/// For each NativeImpl.cpp module, creates a starter `src/Hybrid${Module}.cpp`
/// if one doesn't already exist. The stub includes the generated abstract header
/// and has `__attribute__((constructor))` auto-registration so the user only
/// needs to fill in the method bodies.
void linkCppImplStubs(List<ModuleInfo> moduleInfos, {String baseDir = '.'}) {
  for (final m in moduleInfos.where((m) => m.isCpp)) {
    final className = _toPascalCase(m.lib);
    final stubFile = File(p.join(baseDir, 'src', 'Hybrid$className.cpp'));
    if (stubFile.existsSync()) continue; // never overwrite user code
    stubFile.writeAsStringSync(
      '// Hybrid$className — NativeImpl.cpp implementation.\n'
      '// Generated by nitrogen link. Fill in the method bodies.\n'
      '#include "../lib/src/generated/cpp/${m.lib}.native.g.h"\n'
      '\n'
      '#include <string>\n'
      '\n'
      'class Hybrid${className}Impl final : public Hybrid$className {\n'
      'public:\n'
      '    // TODO: implement all pure-virtual methods declared in Hybrid$className\n'
      '};\n'
      '\n'
      'static Hybrid${className}Impl g_impl;\n'
      '\n'
      '// Auto-register on shared library load — no manual init call needed.\n'
      '__attribute__((constructor))\n'
      'static void ${m.lib}_auto_register() {\n'
      '    ${m.lib}_register_impl(&g_impl);\n'
      '}\n',
    );
  }
}

void linkPodspec(String pluginName, List<String> moduleLibs, {String baseDir = '.', List<ModuleInfo>? moduleInfos}) {
  final podspecFile = File(p.join(baseDir, 'ios', '$pluginName.podspec'));
  if (!podspecFile.existsSync()) return;
  var content = podspecFile.readAsStringSync();
  bool modified = false;
  if (!content.contains("s.swift_version = '5.9'")) {
    content = content.replaceFirst(RegExp(r"s\.swift_version\s*=\s*'.+?'"), "s.swift_version = '5.9'");
    modified = true;
  }
  if (!content.contains("s.platform = :ios, '13.0'")) {
    content = content.replaceFirst(RegExp(r"s\.platform\s*=\s*:ios,\s*'.+?'"), "s.platform = :ios, '13.0'");
    modified = true;
  }
  if (!content.contains('HEADER_SEARCH_PATHS')) {
    content = content.replaceFirst(
      's.pod_target_xcconfig = {',
      "s.pod_target_xcconfig = {\n    'HEADER_SEARCH_PATHS' => '\$(inherited) \"\${PODS_ROOT}/../.symlinks/plugins/nitro/src/native\" \"\${PODS_TARGET_SRCROOT}/../src\" \"\${PODS_TARGET_SRCROOT}/../lib/src/generated/cpp\"',",
    );
    modified = true;
  } else {
    // If it exists, ensure it has the src/ and generated/cpp/ paths.
    if (!content.contains('PODS_TARGET_SRCROOT}/../src') || !content.contains('lib/src/generated/cpp')) {
      final match = RegExp(r"'HEADER_SEARCH_PATHS'\s*=>\s*'([^']+)'").firstMatch(content);
      if (match != null) {
        var paths = match.group(1)!;
        if (!paths.contains('PODS_TARGET_SRCROOT}/../src')) {
          paths += ' "\${PODS_TARGET_SRCROOT}/../src"';
        }
        if (!paths.contains('lib/src/generated/cpp')) {
          paths += ' "\${PODS_TARGET_SRCROOT}/../lib/src/generated/cpp"';
        }
        content = content.replaceFirst(match.group(0)!, "'HEADER_SEARCH_PATHS' => '$paths'");
        modified = true;
      }
    }
  }
  if (!content.contains("'DEFINES_MODULE' => 'YES'")) {
    content = content.replaceFirst('s.pod_target_xcconfig = {', "s.pod_target_xcconfig = {\n    'DEFINES_MODULE' => 'YES',");
    modified = true;
  }
  if (modified) podspecFile.writeAsStringSync(content);
  final nitroNativePath = resolveNitroNativePath(baseDir);
  createSharedHeaders(nitroNativePath, baseDir: baseDir);
  final classesDir = Directory(p.join(baseDir, 'ios', 'Classes'))..createSync(recursive: true);
  File(p.join(classesDir.path, 'dart_api_dl.c')).writeAsStringSync('#include "../../src/dart_api_dl.c"\n');
  syncBridgeFiles(baseDir);

  // Link the main project source files.
  final cppInSrc = File(p.join(baseDir, 'src', '$pluginName.cpp'));
  if (cppInSrc.existsSync()) {
    cleanRedundantIncludes(cppInSrc);
    File(p.join(classesDir.path, '$pluginName.cpp')).writeAsStringSync('// Generated by nitrogen link — do not edit.\n#include "../../src/$pluginName.cpp"\n');
  }
  final cInSrc = File(p.join(baseDir, 'src', '$pluginName.c'));
  if (cInSrc.existsSync()) {
    cleanRedundantIncludes(cInSrc);
    File(p.join(classesDir.path, '$pluginName.c')).writeAsStringSync('#include "../../src/$pluginName.c"\n');
  }

  // Link C++ module implementation files for iOS.
  // On Android, each module is a separate .so via CMake. On iOS, everything is
  // compiled into one binary, so the impl files must be in ios/Classes/.
  if (moduleInfos != null) {
    for (final m in moduleInfos.where((m) => m.isCpp)) {
      final className = _toPascalCase(m.lib);
      final implSrc = File(p.join(baseDir, 'src', 'Hybrid$className.cpp'));
      if (implSrc.existsSync()) {
        File(p.join(classesDir.path, 'Hybrid$className.cpp')).writeAsStringSync('// Generated by nitrogen link — do not edit.\n#include "../../src/Hybrid$className.cpp"\n');
      }
    }
  }

  ensureIosPackageSwift(pluginName, baseDir: baseDir, moduleInfos: moduleInfos);
}

void cleanRedundantIncludes(File file) {
  if (!file.existsSync()) return;
  var content = file.readAsStringSync();
  final regex = RegExp('#include\\s+["\'].*?\\.bridge\\.g\\.(cpp|c|mm)["\']', multiLine: true);
  if (regex.hasMatch(content)) {
    content = content.replaceAll(regex, '');
    file.writeAsStringSync(content);
  }
}

void linkSwiftPlugin(String pluginName, List<Map<String, String>> modules, {String baseDir = '.'}) {
  final iosDir = Directory(p.join(baseDir, 'ios'));
  if (!iosDir.existsSync()) return;
  final pluginFiles = iosDir.listSync(recursive: true).whereType<File>().where((f) => f.path.endsWith('Plugin.swift')).toList();
  if (pluginFiles.isEmpty) return;
  final pluginFile = pluginFiles.first;
  var content = pluginFile.readAsStringSync();
  bool modified = false;
  for (final m in modules) {
    final name = m['module']!;
    final reg = '${name}Registry';
    final impl = name.endsWith('Module') ? '${name}Impl' : '${name}ModuleImpl';
    if (!content.contains('$reg.register')) {
      final match = RegExp(r'\w+Registry\.register\(.*?\)\)').allMatches(content);
      if (match.isNotEmpty) {
        content = content.replaceFirst(match.last.group(0)!, '${match.last.group(0)!}\n        $reg.register($impl())');
        modified = true;
      } else {
        content = content.replaceFirst(
          'public static func register(with registrar: FlutterPluginRegistrar) {',
          'public static func register(with registrar: FlutterPluginRegistrar) {\n        $reg.register($impl())',
        );
        modified = true;
      }
    }
  }
  if (modified) pluginFile.writeAsStringSync(content);
}

void ensureIosPackageSwift(String pluginName, {String baseDir = '.', List<ModuleInfo>? moduleInfos}) {
  final packageSwift = File(p.join(baseDir, 'ios', 'Package.swift'));
  if (packageSwift.existsSync()) {
    // Package.swift already exists — sync C++ module sources into Sources/<MainCpp>/.
    _syncCppModuleSourcesToSpm(pluginName, moduleInfos: moduleInfos, baseDir: baseDir);
    return;
  }
  final className = pluginName.split('_').map((w) => w.isEmpty ? '' : w[0].toUpperCase() + w.substring(1)).join('');
  Directory(p.join(baseDir, 'ios', 'Sources', className)).createSync(recursive: true);
  Directory(p.join(baseDir, 'ios', 'Sources', '${className}Cpp')).createSync(recursive: true);
  packageSwift.writeAsStringSync(
    '// swift-tools-version: 5.9\nimport PackageDescription\nlet package = Package(name: "$pluginName", platforms: [.iOS(.v13)], products: [.library(name: "$pluginName", targets: ["$pluginName"])], targets: [.target(name: "${className}Cpp", path: "Sources/${className}Cpp", publicHeadersPath: "include", cxxSettings: [.headerSearchPath("include"), .unsafeFlags(["-std=c++17", "-I../../.symlinks/plugins/nitro/src/native"])]), .target(name: "$pluginName", dependencies: ["${className}Cpp"], path: "Sources/$className")])',
  );
  _syncCppModuleSourcesToSpm(pluginName, moduleInfos: moduleInfos, baseDir: baseDir);
}

/// Writes forwarder files for C++ module bridges and impl into the SPM target
/// that owns the shared C++ layer (Sources/`<MainCpp>`/). Bridge headers are also
/// copied into its include/ directory so SPM can find them.
void _syncCppModuleSourcesToSpm(String pluginName, {List<ModuleInfo>? moduleInfos, String baseDir = '.'}) {
  if (moduleInfos == null) return;
  final cppModules = moduleInfos.where((m) => m.isCpp).toList();
  if (cppModules.isEmpty) return;

  final className = pluginName.split('_').map((w) => w.isEmpty ? '' : w[0].toUpperCase() + w.substring(1)).join('');
  final cppTargetDir = Directory(p.join(baseDir, 'ios', 'Sources', '${className}Cpp'));
  if (!cppTargetDir.existsSync()) return;

  final includeDir = Directory(p.join(cppTargetDir.path, 'include'))..createSync(recursive: true);

  for (final m in cppModules) {
    final lib = m.lib;
    final hybridClass = _toPascalCase(lib);

    // Forwarder: bridge .cpp -> .mm so SPM compiles it as Obj-C++.
    final bridgeCpp = File(p.join(baseDir, 'lib', 'src', 'generated', 'cpp', '$lib.bridge.g.cpp'));
    if (bridgeCpp.existsSync()) {
      File(
        p.join(cppTargetDir.path, '$lib.bridge.g.mm'),
      ).writeAsStringSync('// Generated by nitrogen link — do not edit.\n#include "../../../../lib/src/generated/cpp/$lib.bridge.g.cpp"\n');
    }

    // Forwarder: C++ impl.
    final implSrc = File(p.join(baseDir, 'src', 'Hybrid$hybridClass.cpp'));
    if (implSrc.existsSync()) {
      File(
        p.join(cppTargetDir.path, 'Hybrid$hybridClass.cpp'),
      ).writeAsStringSync('// Generated by nitrogen link — do not edit.\n#include "../../../../src/Hybrid$hybridClass.cpp"\n');
    }

    // Copy only the C-compatible bridge header into include/. The .native.g.h
    // uses C++ types (std::string, classes) and must NOT be a public module
    // header — CocoaPods would include it in the umbrella and break Swift/ObjC
    // module compilation. It is reachable via HEADER_SEARCH_PATHS instead.
    final bridgeHeader = '$lib.bridge.g.h';
    final hSrc = File(p.join(baseDir, 'lib', 'src', 'generated', 'cpp', bridgeHeader));
    if (hSrc.existsSync()) {
      hSrc.copySync(p.join(includeDir.path, bridgeHeader));
    }
  }
}

/// Ensures `System.loadLibrary("lib")` is present in the Kotlin plugin's
/// companion object init block for each cpp module lib.
/// cpp modules use `__attribute__((constructor))` for auto-registration, so
/// no JniBridge.register call is needed — just loading the .so is enough.
void linkKotlinLoadLibraries(List<String> libs, {String baseDir = '.'}) {
  final kotlinDir = Directory(p.join(baseDir, 'android', 'src', 'main', 'kotlin'));
  if (!kotlinDir.existsSync()) return;
  final pluginFiles = kotlinDir.listSync(recursive: true).whereType<File>().where((f) => f.path.endsWith('Plugin.kt')).toList();
  if (pluginFiles.isEmpty) return;
  final pluginFile = pluginFiles.first;
  var content = pluginFile.readAsStringSync();
  bool modified = false;
  for (final lib in libs) {
    if (!content.contains('loadLibrary("$lib")')) {
      // Insert after the last existing System.loadLibrary call in the init block
      final match = RegExp(r'System\.loadLibrary\("[^"]+"\)').allMatches(content);
      if (match.isNotEmpty) {
        content = content.replaceFirst(match.last.group(0)!, '${match.last.group(0)!}\n            System.loadLibrary("$lib")');
      } else {
        // Fallback: insert a new companion object init block
        final className = p.basenameWithoutExtension(pluginFile.path);
        final classPattern = RegExp('class\\s+$className[^{]*\\{');
        final classMatch = classPattern.firstMatch(content);
        if (classMatch == null) {
          throw Exception(
            'nitrogen link failed: Cannot find opening "{" for class $className in ${p.basename(pluginFile.path)} '
            'to inject System.loadLibrary("$lib"). Please add it manually.',
          );
        }
        content = content.replaceFirst(
          classMatch.group(0)!,
          '${classMatch.group(0)!}\n    companion object {\n        init { System.loadLibrary("$lib") }\n    }\n',
        );
      }
      modified = true;
    }
  }
  if (modified) pluginFile.writeAsStringSync(content);
}

void linkKotlinPlugin(String pluginName, List<Map<String, String>> modules, {String baseDir = '.'}) {
  final kotlinDir = Directory(p.join(baseDir, 'android', 'src', 'main', 'kotlin'));
  if (!kotlinDir.existsSync()) return;
  final pluginFiles = kotlinDir.listSync(recursive: true).whereType<File>().where((f) => f.path.endsWith('Plugin.kt')).toList();
  if (pluginFiles.isEmpty) return;
  final pluginFile = pluginFiles.first;
  var content = pluginFile.readAsStringSync();
  bool modified = false;
  for (final m in modules) {
    final name = m['module']!;
    final reg = '${name}JniBridge';
    final impl = name.endsWith('Module') ? '${name}Impl' : '${name}Impl';
    if (!content.contains('$reg.register')) {
      final match = RegExp(r'\w+JniBridge\.register\(.*?\)\)').allMatches(content);
      if (match.isNotEmpty) {
        content = content.replaceFirst(match.last.group(0)!, '${match.last.group(0)!}\n        $reg.register($impl())');
        modified = true;
      } else {
        content = content.replaceFirst(
          'override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {',
          'override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {\n        $reg.register($impl())',
        );
        modified = true;
      }
    }
  }
  if (modified) pluginFile.writeAsStringSync(content);
}

void linkClangd(String pluginName, {List<ModuleInfo>? moduleInfos, String baseDir = '.'}) {
  final sb = StringBuffer()
    ..writeln('CompileFlags:')
    ..writeln('  Add:')
    ..writeln('    - -I\${PWD}/src')
    ..writeln('    - -I\${PWD}/lib/src/generated/cpp')
    ..writeln('    - -I\${PWD}/../packages/nitro/src/native');

  // For C++ modules also expose the test/ directory so IDEs resolve mock headers
  if (moduleInfos != null && moduleInfos.any((m) => m.isCpp)) {
    sb.writeln('    - -I\${PWD}/lib/src/generated/cpp/test');
  }
  File(p.join(baseDir, '.clangd')).writeAsStringSync(sb.toString());
}

class LinkCommand extends Command {
  @override
  final String name = 'link';
  @override
  final String description = 'Wires all Nitrogen-generated native bridges into the build system.';
  @override
  Future<void> run() async {
    final projectDir = findNitroProjectRoot();
    if (projectDir == null) {
      stderr.writeln('❌ No Nitro project found.');
      exit(1);
    }
    final pubspec = File(p.join(projectDir.path, 'pubspec.yaml'));
    String pluginName = 'unknown';
    for (final line in pubspec.readAsLinesSync()) {
      if (line.startsWith('name: ')) {
        pluginName = line.replaceFirst('name: ', '').trim();
        break;
      }
    }
    Directory.current = projectDir;
    final result = LinkResult();
    await runApp(LinkView(pluginName: pluginName, result: result));
    if (result.success) {
      stdout.writeln('\n  \x1B[1;32m✨ $pluginName linked\x1B[0m');
    }
  }
}
