import 'dart:convert';
import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:nocterm/nocterm.dart';
import 'package:path/path.dart' as p;
import '../ui.dart';

// ── Package-level helpers (also used in tests) ─────────────────────────────

/// Resolves the absolute path to the installed `nitro` package's `src/native`
/// directory by reading `.dart_tool/package_config.json` inside [pluginDir].
///
/// Falls back to the monorepo-relative default
/// (`<pluginDir>/../packages/nitro/src/native`) when the file is absent or
/// the `nitro` entry cannot be parsed.
String resolveNitroNativePath(String pluginDir) {
  final configFile =
      File(p.join(pluginDir, '.dart_tool', 'package_config.json'));
  if (configFile.existsSync()) {
    try {
      final config =
          jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
      final packages = (config['packages'] as List<dynamic>?) ?? [];
      for (final pkg in packages) {
        final pkgMap = pkg as Map<String, dynamic>;
        if (pkgMap['name'] == 'nitro') {
          final rootUri = pkgMap['rootUri'] as String;
          final uri = Uri.parse(rootUri);
          if (uri.scheme == 'file') {
            // Absolute file:// URI — pub cache installation.
            return p.join(uri.toFilePath(), 'src', 'native');
          } else {
            // Relative URI — relative to the .dart_tool/ directory.
            final dartToolDir = p.join(pluginDir, '.dart_tool');
            final resolved = p.normalize(p.join(dartToolDir, rootUri));
            return p.join(resolved, 'src', 'native');
          }
        }
      }
    } catch (_) {}
  }
  // Fallback: monorepo layout.
  return p.normalize(p
      .absolute(p.join(pluginDir, '..', 'packages', 'nitro', 'src', 'native')));
}

/// Returns `true` when [cmakeNitroNative] (which may contain
/// `${CMAKE_CURRENT_SOURCE_DIR}`) resolves to a directory that contains
/// `dart_api_dl.h`.
///
/// [srcDir] is the absolute path to the plugin's `src/` directory, used to
/// expand `${CMAKE_CURRENT_SOURCE_DIR}`.
bool nitroNativePathExists(String cmakeNitroNative, String srcDir) {
  final resolved =
      cmakeNitroNative.replaceAll(r'${CMAKE_CURRENT_SOURCE_DIR}', srcDir);
  return File(p.join(resolved, 'dart_api_dl.h')).existsSync();
}

/// Returns the content for a `src/dart_api_dl.c` forwarder file that includes
/// the real `dart_api_dl.c` from [nitroNativePath].
String dartApiDlForwarderContent(String nitroNativePath) {
  final includePath =
      p.join(nitroNativePath, 'dart_api_dl.c').replaceAll(r'\', '/');
  return '// Generated by nitrogen link — do not edit.\n'
      '// Compiled as C (not C++) so the void*/function-pointer casts\n'
      '// in dart_api_dl.c are accepted by the compiler.\n'
      '#include "$includePath"\n';
}

/// Extracts the `lib:` value from a `@NitroModule(...)` annotation in [specFile].
/// Returns null when the annotation has no explicit `lib` parameter.
String? extractLibNameFromSpec(File specFile) {
  final content = specFile.readAsStringSync();
  final match = RegExp(r'''@NitroModule\s*\([^)]*lib\s*:\s*['"]([^'"]+)['"]''')
      .firstMatch(content);
  return match?.group(1);
}

/// Discovers all module lib names by scanning `lib/` for `*.native.dart` files.
/// Falls back to [pluginName] when no specs are found.
List<String> discoverModuleLibs(String pluginName) {
  final libDir = Directory('lib');
  if (!libDir.existsSync()) return [pluginName];
  final specs = libDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.native.dart'))
      .toList();
  if (specs.isEmpty) return [pluginName];
  final libs = <String>[];
  for (final spec in specs) {
    final stem =
        p.basename(spec.path).replaceAll(RegExp(r'\.native\.dart$'), '');
    final libName = extractLibNameFromSpec(spec) ?? stem.replaceAll('-', '_');
    if (!libs.contains(libName)) libs.add(libName);
  }
  return libs.isEmpty ? [pluginName] : libs;
}

// ── Progress model ──────────────────────────────

enum LinkStepState { pending, running, done, failed, skipped }

class LinkStep {
  final String label;
  LinkStepState state;
  String? detail;

  LinkStep(this.label) : state = LinkStepState.pending;
}

class LinkStepRow extends StatelessComponent {
  const LinkStepRow(this.step, {super.key});
  final LinkStep step;

  @override
  Component build(BuildContext context) {
    final String icon;
    final Color color;
    switch (step.state) {
      case LinkStepState.pending:
        icon = '○';
        color = Colors.gray;
      case LinkStepState.running:
        icon = '◉';
        color = Colors.cyan;
      case LinkStepState.done:
        icon = '✔';
        color = Colors.green;
      case LinkStepState.failed:
        icon = '✘';
        color = Colors.red;
      case LinkStepState.skipped:
        icon = '–';
        color = Colors.gray;
    }

    return Padding(
      padding: const EdgeInsets.only(left: 2),
      child: Column(
        children: [
          Row(
            children: [
              Text(icon,
                  style: TextStyle(color: color, fontWeight: FontWeight.bold)),
              const Text(' '),
              Expanded(
                child: Text(
                  step.label,
                  style: TextStyle(
                    color: step.state == LinkStepState.running
                        ? Colors.cyan
                        : null,
                    fontWeight: step.state == LinkStepState.running
                        ? FontWeight.bold
                        : null,
                  ),
                ),
              ),
            ],
          ),
          if (step.detail != null)
            Padding(
              padding: const EdgeInsets.only(left: 4),
              child: Text(
                step.detail!,
                style: const TextStyle(
                    color: Colors.gray, fontWeight: FontWeight.dim),
              ),
            ),
        ],
      ),
    );
  }
}

// ── Result holder ─────────────────────────────────────────────────────────────

class LinkResult {
  bool success = false;
}

// ── nocterm Link component ────────────────────────────────────────────────────

class LinkView extends StatefulComponent {
  const LinkView({
    required this.pluginName,
    required this.result,
    this.onExit,
    super.key,
  });
  final String pluginName;
  final LinkResult result;
  final VoidCallback? onExit;

  @override
  State<LinkView> createState() => _LinkViewState();
}

class _LinkViewState extends State<LinkView> {
  late final List<LinkStep> _steps = [
    LinkStep('Discovering modules'),
    LinkStep('Updating src/CMakeLists.txt'),
    LinkStep('Updating iOS podspec'),
    LinkStep('Updating Kotlin Plugin.kt'),
    LinkStep('Updating .clangd'),
  ];

  bool _finished = false;
  final bool _failed = false;
  final List<String> _nextSteps = [];

  @override
  void initState() {
    super.initState();
    Future<void>.delayed(Duration.zero, _run);
  }

  Future<void> _setRunning(int i) async {
    setState(() => _steps[i].state = LinkStepState.running);
  }

  Future<void> _setDone(int i, {String? detail}) async {
    setState(() {
      _steps[i].state = LinkStepState.done;
      _steps[i].detail = detail;
    });
  }

  Future<void> _setSkipped(int i, {String? detail}) async {
    setState(() {
      _steps[i].state = LinkStepState.skipped;
      _steps[i].detail = detail;
    });
  }

  Future<void> _run() async {
    final pluginName = component.pluginName;

    // Step 0 — discover modules
    await _setRunning(0);
    final moduleLibs = _discoverModuleLibs(pluginName);
    await _setDone(0,
        detail: '${moduleLibs.length} module(s): ${moduleLibs.join(', ')}');

    // Step 1 — CMake
    await _setRunning(1);
    final nitroNativePath = _resolveNitroNativePath();
    _linkCMake(pluginName, moduleLibs, nitroNativePath);
    await _setDone(1);

    // Step 2 — Podspec
    await _setRunning(2);
    if (Directory('ios').existsSync()) {
      _linkPodspec(pluginName, moduleLibs);
      await _setDone(2);
    } else {
      await _setSkipped(2, detail: 'ios/ not present');
    }

    // Step 3 — Kotlin Plugin
    await _setRunning(3);
    if (Directory('android').existsSync()) {
      _linkKotlinPlugin(pluginName, moduleLibs);
      await _setDone(3);
    } else {
      await _setSkipped(3, detail: 'android/ not present');
    }

    // Step 4 — .clangd
    await _setRunning(4);
    _linkClangd(pluginName);
    await _setDone(4);

    _nextSteps.addAll([
      'flutter pub get',
      'flutter pub run build_runner build --delete-conflicting-outputs',
      'Implement generated Hybrid*Spec interfaces in Kotlin/Swift',
    ]);

    component.result.success = !_failed;
    setState(() => _finished = true);
  }

  bool _handleKey(KeyboardEvent e) {
    if (!_finished) return false;
    if (component.onExit != null) {
      component.onExit!();
      return true;
    }
    shutdownApp(_failed ? 1 : 0);
    return true;
  }

  @override
  Component build(BuildContext context) {
    return Focusable(
      focused: true,
      onKeyEvent: _handleKey,
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 1, left: 1, right: 1),
            child: Container(
              decoration:
                  BoxDecoration(border: BoxBorder.all(color: Colors.cyan)),
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 2),
                child: Text(
                  ' nitrogen link — ${component.pluginName} ',
                  style: const TextStyle(
                      color: Colors.cyan, fontWeight: FontWeight.bold),
                ),
              ),
            ),
          ),
          const Padding(padding: EdgeInsets.only(bottom: 1), child: Text('')),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 1),
              child: Container(
                decoration: BoxDecoration(
                    border: BoxBorder.all(color: Colors.brightBlack)),
                child: Padding(
                  padding: const EdgeInsets.all(1),
                  child: ListView(
                    children: _steps.map(LinkStepRow.new).toList(),
                  ),
                ),
              ),
            ),
          ),
          if (_finished)
            Padding(
              padding:
                  const EdgeInsets.only(top: 1, bottom: 1, left: 1, right: 1),
              child: Column(
                children: [
                  if (!_failed) ...[
                    const Text('✨ Linked! Next steps:',
                        style: TextStyle(
                            color: Colors.green, fontWeight: FontWeight.bold)),
                    ..._nextSteps.asMap().entries.map(
                          (e) => Text(
                            '  ${e.key + 1}. ${e.value}',
                            style: const TextStyle(color: Colors.gray),
                          ),
                        ),
                  ],
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      if (component.onExit != null) ...[
                        HoverButton(
                          label: '‹ Back',
                          onTap: component.onExit!,
                          color: Colors.cyan,
                        ),
                        const Text('  •  ',
                            style: TextStyle(color: Colors.brightBlack)),
                      ],
                      const Text(
                        'Press any key to exit',
                        style: TextStyle(
                            color: Colors.gray, fontWeight: FontWeight.dim),
                      ),
                    ],
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  List<String> _discoverModuleLibs(String pluginName) =>
      discoverModuleLibs(pluginName);

  String _resolveNitroNativePath() => resolveNitroNativePath(p.absolute('.'));

  bool _cmakeNitroNativeExists(String cmakeNitroNative) =>
      nitroNativePathExists(cmakeNitroNative, p.absolute('src'));

  void _createLocalDartApiDl(String nitroNativePath) {
    Directory('src').createSync(recursive: true);
    File(p.join('src', 'dart_api_dl.c'))
        .writeAsStringSync(dartApiDlForwarderContent(nitroNativePath));
  }

  void _linkCMake(
      String pluginName, List<String> moduleLibs, String nitroNativePath) {
    // Always create/refresh the local src/dart_api_dl.c forwarder so that
    // the build never depends on a path that might not exist.
    _createLocalDartApiDl(nitroNativePath);

    final cmakeFile = File(p.join('src', 'CMakeLists.txt'));
    if (!cmakeFile.existsSync()) {
      _generateCMake(pluginName, moduleLibs, nitroNativePath);
      return;
    }
    var content = cmakeFile.readAsStringSync();
    bool modified = false;

    // ── NITRO_NATIVE variable ──────────────────────────────────────────────
    // Build the desired cmake set() line.  Prefer the cmake-relative form
    // (uses ${CMAKE_CURRENT_SOURCE_DIR}) when the path already exists on
    // disk; otherwise embed the resolved absolute path so the build works
    // even outside the original monorepo.
    final defaultCmakeNitro =
        r'${CMAKE_CURRENT_SOURCE_DIR}/../../packages/nitro/src/native';
    final String desiredNitroValue;
    if (_cmakeNitroNativeExists(defaultCmakeNitro)) {
      desiredNitroValue = defaultCmakeNitro;
    } else {
      desiredNitroValue = nitroNativePath.replaceAll(r'\', '/');
    }
    final nitroNativeSetLine = 'set(NITRO_NATIVE "$desiredNitroValue")';

    if (!content.contains('NITRO_NATIVE')) {
      content = '$nitroNativeSetLine\n\n$content';
      modified = true;
    } else {
      // Update stale value if the current cmake path no longer resolves.
      final staleMatch =
          RegExp(r'set\(NITRO_NATIVE\s+"([^"]+)"\)').firstMatch(content);
      if (staleMatch != null) {
        final currentVal = staleMatch.group(1)!;
        if (!_cmakeNitroNativeExists(currentVal) &&
            currentVal != desiredNitroValue) {
          content =
              content.replaceFirst(staleMatch.group(0)!, nitroNativeSetLine);
          modified = true;
        }
      }
    }

    // ── Include path for headers ───────────────────────────────────────────
    if (!content.contains('NITRO_NATIVE') ||
        !content.contains('packages/nitro/src/native') &&
            !content.contains(nitroNativePath)) {
      if (!content.contains(r'${NITRO_NATIVE}')) {
        content = content.replaceFirst(
          'target_include_directories($pluginName PRIVATE',
          'target_include_directories($pluginName PRIVATE\n'
              r'  "${NITRO_NATIVE}"',
        );
        modified = true;
      }
    }

    // ── dart_api_dl.c source file ─────────────────────────────────────────
    // Migrate legacy `${NITRO_NATIVE}/dart_api_dl.c` → local `dart_api_dl.c`
    if (content.contains(r'${NITRO_NATIVE}/dart_api_dl.c')) {
      content = content.replaceAll(
          r'"${NITRO_NATIVE}/dart_api_dl.c"', '"dart_api_dl.c"');
      modified = true;
    } else if (!content.contains('dart_api_dl.c')) {
      content = content.replaceFirst(
        'add_library($pluginName SHARED',
        'add_library($pluginName SHARED\n  "dart_api_dl.c"',
      );
      modified = true;
    }

    // ── Extra module targets ───────────────────────────────────────────────
    for (final lib in moduleLibs) {
      if (lib == pluginName) continue;
      if (!content.contains('add_library($lib ')) {
        content += _cmakeModuleTarget(lib);
        modified = true;
      }
    }

    if (modified) cmakeFile.writeAsStringSync(content);
  }

  void _generateCMake(
      String pluginName, List<String> moduleLibs, String nitroNativePath) {
    Directory('src').createSync(recursive: true);

    final String nitroValue;
    if (_cmakeNitroNativeExists(
        r'${CMAKE_CURRENT_SOURCE_DIR}/../../packages/nitro/src/native')) {
      nitroValue =
          r'${CMAKE_CURRENT_SOURCE_DIR}/../../packages/nitro/src/native';
    } else {
      nitroValue = nitroNativePath.replaceAll(r'\', '/');
    }

    final sb = StringBuffer()
      ..writeln('cmake_minimum_required(VERSION 3.10)')
      ..writeln('project(${pluginName}_library VERSION 0.0.1 LANGUAGES C CXX)')
      ..writeln()
      ..writeln('set(NITRO_NATIVE "$nitroValue")')
      ..writeln()
      ..writeln('add_library($pluginName SHARED')
      ..writeln('  "$pluginName.cpp"')
      ..writeln('  "dart_api_dl.c"')
      ..writeln(')')
      ..writeln('target_include_directories($pluginName PRIVATE')
      ..writeln('  "\${CMAKE_CURRENT_SOURCE_DIR}"')
      ..writeln('  "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp"')
      ..writeln('  "\${NITRO_NATIVE}"')
      ..writeln(')')
      ..writeln(
          'target_compile_definitions($pluginName PUBLIC DART_SHARED_LIB)')
      ..writeln('if(ANDROID)')
      ..writeln('  target_link_libraries($pluginName PRIVATE android log)')
      ..writeln(
          '  target_link_options($pluginName PRIVATE "-Wl,-z,max-page-size=16384")')
      ..writeln('endif()');
    for (final lib in moduleLibs) {
      if (lib != pluginName) sb.write(_cmakeModuleTarget(lib));
    }
    File(p.join('src', 'CMakeLists.txt')).writeAsStringSync(sb.toString());
  }

  String _cmakeModuleTarget(String lib) => '''

add_library($lib SHARED
  "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp/$lib.bridge.g.cpp"
  "dart_api_dl.c"
)
target_include_directories($lib PRIVATE
  "\${CMAKE_CURRENT_SOURCE_DIR}/../lib/src/generated/cpp"
  "\${NITRO_NATIVE}"
)
set_target_properties($lib PROPERTIES OUTPUT_NAME "$lib")
target_compile_definitions($lib PUBLIC DART_SHARED_LIB)
if(ANDROID)
  target_link_libraries($lib PRIVATE android log)
  target_link_options($lib PRIVATE "-Wl,-z,max-page-size=16384")
endif()
''';

  void _linkPodspec(String pluginName, List<String> moduleLibs) {
    final podspecFile = File(p.join('ios', '$pluginName.podspec'));
    if (!podspecFile.existsSync()) return;
    var content = podspecFile.readAsStringSync();
    bool modified = false;

    if (!content.contains("s.swift_version = '5.9'")) {
      content = content.replaceFirst(
          RegExp(r"s\.swift_version = '.+?'"), "s.swift_version = '5.9'");
      modified = true;
    }
    if (!content.contains("s.platform = :ios, '13.0'")) {
      content = content.replaceFirst(
          RegExp(r"s\.platform = :ios, '.+?'"), "s.platform = :ios, '13.0'");
      modified = true;
    }

    // Use ${PODS_ROOT}/../.symlinks/plugins/nitro/src/native so the path works
    // whether `nitro` is a local path dependency or installed from pub.dev.
    const correctSearchPath =
        r'"${PODS_ROOT}/../.symlinks/plugins/nitro/src/native"';
    if (!content.contains('HEADER_SEARCH_PATHS')) {
      // Use triple-quote raw string so the embedded `"` chars don't end it.
      const entry =
          r"""'HEADER_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}/../.symlinks/plugins/nitro/src/native"'""";
      content = content.replaceFirst(
        's.pod_target_xcconfig = {',
        's.pod_target_xcconfig = {\n    $entry,',
      );
      modified = true;
    } else if (content.contains('PODS_TARGET_SRCROOT') &&
        content.contains('HEADER_SEARCH_PATHS') &&
        !content.contains(correctSearchPath)) {
      // Migrate from the old (wrong) path to the correct one.
      content = content.replaceFirst(
        RegExp(
            r'''\$\{PODS_TARGET_SRCROOT\}\/\.\.\/(\.\.\/)*packages\/nitro\/src\/native'''),
        r'${PODS_ROOT}/../.symlinks/plugins/nitro/src/native',
      );
      modified = true;
    }

    if (!content.contains("'DEFINES_MODULE' => 'YES'")) {
      content = content.replaceFirst(
        's.pod_target_xcconfig = {',
        "s.pod_target_xcconfig = {\n    'DEFINES_MODULE' => 'YES',",
      );
      modified = true;
    }

    if (modified) podspecFile.writeAsStringSync(content);

    final classesDir = Directory(p.join('ios', 'Classes'));
    classesDir.createSync(recursive: true);

    // dart_api_dl MUST be a .c file so the compiler treats its contents as C,
    // not C++. C++ rejects the void*/function-pointer cast inside dart_api_dl.c.
    final dartApiDlCpp = File(p.join(classesDir.path, 'dart_api_dl.cpp'));
    if (dartApiDlCpp.existsSync()) dartApiDlCpp.deleteSync();

    // The forwarder includes from ../../src/dart_api_dl.c (created by
    // _createLocalDartApiDl) so that both Android CMake and iOS CocoaPods/SPM
    // resolve through the same local file, which in turn points at wherever
    // the nitro package is actually installed.
    final dartApiDlC = File(p.join(classesDir.path, 'dart_api_dl.c'));
    const forwarderContent =
        '// Forwarder — compiled by CocoaPods/SPM so the Dart DL API is\n'
        '// available in the dylib. Kept as .c so it compiles as C, not C++.\n'
        '#include "../../src/dart_api_dl.c"\n';
    if (!dartApiDlC.existsSync() ||
        dartApiDlC.readAsStringSync().contains('packages/nitro/src/native')) {
      dartApiDlC.writeAsStringSync(forwarderContent);
    }

    // Symlink so CocoaPods (Classes/**/*) picks up the generated Swift bridge
    // without needing a path outside the pod root.
    final symlinkPath = p.join(classesDir.path, '$pluginName.bridge.g.swift');
    final symlinkTarget =
        '../../lib/src/generated/swift/$pluginName.bridge.g.swift';
    final link = Link(symlinkPath);
    if (!link.existsSync()) {
      link.createSync(symlinkTarget);
    }

    // Package.swift — ensure it exists (created by init; re-create if missing).
    _ensureIosPackageSwift(pluginName);
  }

  void _ensureIosPackageSwift(String pluginName) {
    final packageSwift = File(p.join('ios', 'Package.swift'));
    if (packageSwift.existsSync()) return;

    final className = pluginName
        .split('_')
        .map((w) => w.isEmpty ? '' : w[0].toUpperCase() + w.substring(1))
        .join('');

    final swiftSrcDir = Directory(p.join('ios', 'Sources', className));
    final cppSrcDir = Directory(p.join('ios', 'Sources', '${className}Cpp'));
    swiftSrcDir.createSync(recursive: true);
    cppSrcDir.createSync(recursive: true);

    for (final name in [
      'Swift${className}Plugin.swift',
      '${className}Impl.swift',
      '$pluginName.bridge.g.swift',
    ]) {
      final lnk = Link(p.join(swiftSrcDir.path, name));
      if (!lnk.existsSync()) lnk.createSync('../../Classes/$name');
    }

    for (final name in ['$pluginName.cpp', 'dart_api_dl.c']) {
      final lnk = Link(p.join(cppSrcDir.path, name));
      if (!lnk.existsSync()) lnk.createSync('../../Classes/$name');
    }

    final includeLink = Link(p.join(cppSrcDir.path, 'include'));
    if (!includeLink.existsSync()) {
      includeLink.createSync('../../Classes');
    }

    packageSwift.writeAsStringSync('''// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "$pluginName",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "$pluginName", targets: ["$pluginName"]),
    ],
    targets: [
        // C/C++ bridge — SPM requires Swift and C++ in separate targets.
        .target(
            name: "${className}Cpp",
            path: "Sources/${className}Cpp",
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .unsafeFlags([
                    "-std=c++17",
                    "-I../../.symlinks/plugins/nitro/src/native",
                ])
            ]
        ),
        // Swift implementation + generated bridge.
        .target(
            name: "$pluginName",
            dependencies: ["${className}Cpp"],
            path: "Sources/$className"
        ),
    ]
)
''');
  }

  void _linkKotlinPlugin(String pluginName, List<String> moduleLibs) {
    final kotlinDir = Directory(p.join('android', 'src', 'main', 'kotlin'));
    if (!kotlinDir.existsSync()) return;
    final pluginFiles = kotlinDir
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('Plugin.kt'))
        .toList();
    if (pluginFiles.isEmpty) return;

    final pluginFile = pluginFiles.first;
    var content = pluginFile.readAsStringSync();
    bool modified = false;

    final missingLibs = moduleLibs
        .where((l) => !content.contains('System.loadLibrary("$l")'))
        .toList();
    if (missingLibs.isNotEmpty) {
      if (!content.contains('System.loadLibrary')) {
        final className = p.basenameWithoutExtension(pluginFile.path);
        final loadLines =
            moduleLibs.map((l) => '      System.loadLibrary("$l")').join('\n');
        content = content.replaceFirst(
          'class $className: FlutterPlugin {',
          'class $className: FlutterPlugin {\n'
              '  companion object {\n'
              '    init {\n'
              '$loadLines\n'
              '    }\n'
              '  }\n',
        );
      } else {
        for (final lib in missingLibs) {
          content = content.replaceFirst(
            'System.loadLibrary("$pluginName")',
            'System.loadLibrary("$pluginName")\n      System.loadLibrary("$lib")',
          );
        }
      }
      modified = true;
    }
    if (modified) pluginFile.writeAsStringSync(content);
  }

  void _linkClangd(String pluginName) {
    File('.clangd').writeAsStringSync('''CompileFlags:
  Add:
    - -I\${PWD}/src
    - -I\${PWD}/lib/src/generated/cpp
    - -I\${PWD}/../packages/nitro/src/native
''');
  }
}

// ── LinkCommand ───────────────────────────────────────────────────────────────

class LinkCommand extends Command {
  @override
  final String name = 'link';

  @override
  final String description =
      'Wires all Nitrogen-generated native bridges into the build system '
      '(CMake, Podspec, Kotlin plugin class).';

  @override
  Future<void> run() async {
    final projectDir = findNitroProjectRoot();
    if (projectDir == null) {
      stderr.writeln(
          '❌ No Nitro project found in . or its subdirectories (must have nitro dependency in pubspec.yaml).');
      exit(1);
    }

    final pubspecFile = File(p.join(projectDir.path, 'pubspec.yaml'));
    final pluginName = _getPluginName(pubspecFile);

    // Change working directory so that LinkView logic (File('ios'), etc) works correctly.
    Directory.current = projectDir;

    if (projectDir.path != Directory.current.path) {
      stdout
          .writeln('  \x1B[90m📂 Found project in: ${projectDir.path}\x1B[0m');
    }

    final result = LinkResult();
    await runApp(LinkView(pluginName: pluginName, result: result));

    if (result.success) {
      stdout.writeln('');
      stdout.writeln(
          '  \x1B[1;32m✨ $pluginName linked\x1B[0m  — run: flutter pub get && nitrogen generate');
      stdout.writeln('');
    }
  }

  String _getPluginName(File pubspec) {
    for (final line in pubspec.readAsLinesSync()) {
      if (line.startsWith('name: ')) {
        return line.replaceFirst('name: ', '').trim();
      }
    }
    return 'unknown';
  }
}
