// Generated by Nitrogen Modules. Do not edit.
// Generated from: my_camera.native.dart
part of 'my_camera.native.dart';

// --- Struct FFI representations (generated by Nitrogen) ---

final class CameraFrameFfi extends Struct {
  external Pointer<Uint8> data;
  @Int64()
  external int width;
  @Int64()
  external int height;
  @Int64()
  external int stride;
  @Int64()
  external int timestampNs;
}

extension CameraFrameFfiExt on CameraFrameFfi {
  CameraFrame toDart() {
    return CameraFrame(
      data: Uint8List.fromList(data.asTypedList(stride)),
      width: width,
      height: height,
      stride: stride,
      timestampNs: timestampNs,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension CameraFrameExt on CameraFrame {
  Pointer<CameraFrameFfi> toNative(Arena arena) {
    final ptr = arena<CameraFrameFfi>();
    ptr.ref.data = data.toPointer(arena);
    ptr.ref.width = width;
    ptr.ref.height = height;
    ptr.ref.stride = stride;
    ptr.ref.timestampNs = timestampNs;
    return ptr;
  }
}

// --- Struct Native Proxies (zero-copy, lazy field access) ---

/// Zero-copy proxy for [CameraFrame].
/// Extends [CameraFrame] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `CameraFrameProxy <: CameraFrame`, a `Stream<CameraFrameProxy>`
/// satisfies `Stream<CameraFrame>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'my_camera_release_CameraFrame'.
final class CameraFrameProxy extends CameraFrame implements Finalizable {
  final Pointer<CameraFrameFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
          'my_camera_release_CameraFrame'),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  CameraFrameProxy(this._native)
      : super(
            data: Uint8List(0),
            width: 0,
            height: 0,
            stride: 0,
            timestampNs: 0) {
    assert(_finalizer != null,
        'CameraFrameProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.');
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  Uint8List get data => _native.ref.data.asTypedList(_native.ref.stride);
  @override
  int get width => _native.ref.width;
  @override
  int get height => _native.ref.height;
  @override
  int get stride => _native.ref.stride;
  @override
  int get timestampNs => _native.ref.timestampNs;

  /// Eagerly copies all fields to a plain [CameraFrame] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  CameraFrame toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension ResolutionRecordExt on Resolution {
  static Resolution fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static Resolution fromReader(RecordReader r) => Resolution(
        width: r.readInt(),
        height: r.readInt(),
      );

  void writeFields(RecordWriter writer) {
    writer.writeInt(width);
    writer.writeInt(height);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension CameraDeviceRecordExt on CameraDevice {
  static CameraDevice fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static CameraDevice fromReader(RecordReader r) => CameraDevice(
        id: r.readString(),
        name: r.readString(),
        resolutions: List.generate(
            r.readInt32(), (_) => ResolutionRecordExt.fromReader(r)),
        isFrontFacing: r.readBool(),
      );

  void writeFields(RecordWriter writer) {
    writer.writeString(id);
    writer.writeString(name);
    writer.writeInt32(resolutions.length);
    for (final e in resolutions) {
      e.writeFields(writer);
    }
    writer.writeBool(isFrontFacing);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

class _MyCameraImpl extends MyCamera {
  final DynamicLibrary _dylib;

  _MyCameraImpl() : _dylib = NitroRuntime.loadLib('my_camera') {
    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>),
        int Function(Pointer<Void>)>('my_camera_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
          'my_camera: Dart API DL initialization failed with code $initCode.');
    }
    CameraFrameProxy._init(_dylib);
  }

  late final double Function(double, double) _addPtr = _dylib
      .lookup<NativeFunction<Double Function(Double, Double)>>('my_camera_add')
      .asFunction<double Function(double, double)>(isLeaf: true);
  late final Pointer<Utf8> Function(Pointer<Utf8>) _getGreetingPtr =
      _dylib.lookupFunction<Pointer<Utf8> Function(Pointer<Utf8>),
          Pointer<Utf8> Function(Pointer<Utf8>)>('my_camera_get_greeting');
  late final Pointer<Uint8> Function() _getAvailableDevicesPtr = _dylib
      .lookupFunction<Pointer<Uint8> Function(), Pointer<Uint8> Function()>(
          'my_camera_get_available_devices');
  late final void Function(int) _registerFramesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'my_camera_register_frames_stream');
  late final void Function(int) _releaseFramesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'my_camera_release_frames_stream');
  late final void Function(int) _registerColoredFramesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'my_camera_register_colored_frames_stream');
  late final void Function(int) _releaseColoredFramesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'my_camera_release_colored_frames_stream');
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr =
      _dylib.lookupFunction<Pointer<NitroErrorFfi> Function(),
          Pointer<NitroErrorFfi> Function()>('my_camera_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr =
      _dylib.lookupFunction<Void Function(), void Function()>(
          'my_camera_clear_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
      _getErrorNativePtr = _dylib.lookup('my_camera_get_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('my_camera_clear_error');

  @override
  // ignore: unnecessary_overrides
  void dispose() {
    super.dispose(); // sets isDisposed = true, calls onDestroy()
  }

  @override
  double add(double a, double b) {
    checkDisposed();
    final res = _addPtr(a, b);
    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
    return res;
  }

  @override
  Future<String> getGreeting(String name) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Utf8>>(
          _getGreetingPtr, [name.toNativeUtf8(allocator: arena)],
          getError: _getErrorNativePtr,
          clearError: _clearErrorNativePtr,
          methodName: 'getGreeting');
      return rawPtr.toDartStringWithFree();
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<List<CameraDevice>> getAvailableDevices() async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _getAvailableDevicesPtr, [],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getAvailableDevices');
    return LazyRecordList.decode(
        rawPtr, (r) => CameraDeviceRecordExt.fromReader(r));
  }

  @override
  Stream<CameraFrame> get frames {
    checkDisposed();
    return NitroRuntime.openStream<CameraFrameProxy>(
      register: (port) => _registerFramesPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError('Received null event on non-nullable stream frames');
        }
        return CameraFrameProxy(
            Pointer<CameraFrameFfi>.fromAddress(message as int));
      },
      release: (port) => _releaseFramesPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<CameraFrame> get coloredFrames {
    checkDisposed();
    return NitroRuntime.openStream<CameraFrameProxy>(
      register: (port) => _registerColoredFramesPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
              'Received null event on non-nullable stream coloredFrames');
        }
        return CameraFrameProxy(
            Pointer<CameraFrameFfi>.fromAddress(message as int));
      },
      release: (port) => _releaseColoredFramesPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }
}
