// Generated by Nitrogen Modules. Do not edit.
part of 'my_camera.native.dart';

// --- Struct FFI representations (generated by Nitrogen) ---

final class CameraFrameFfi extends Struct {
  external Pointer<Uint8> data;
  @Int64()
  external int width;
  @Int64()
  external int height;
  @Int64()
  external int stride;
  @Int64()
  external int timestampNs;
}

extension CameraFrameFfiExt on CameraFrameFfi {
  CameraFrame toDart() {
    return CameraFrame(
      data: data.asTypedList(stride),
      width: width,
      height: height,
      stride: stride,
      timestampNs: timestampNs,
    );
  }
}

extension CameraFrameExt on CameraFrame {
  Pointer<CameraFrameFfi> toNative(Arena arena) {
    final ptr = arena<CameraFrameFfi>();
    ptr.ref.data = data.toPointer(arena);
    ptr.ref.width = width;
    ptr.ref.height = height;
    ptr.ref.stride = stride;
    ptr.ref.timestampNs = timestampNs;
    return ptr;
  }
}

class _MyCameraImpl extends MyCamera {
  final DynamicLibrary _dylib;

  _MyCameraImpl() : _dylib = NitroRuntime.loadLib('my_camera') {
    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>), int Function(Pointer<Void>)>('InitDartApiDL');
    initFunc(NativeApi.initializeApiDLData);
  }

  late final double Function(double, double) _addPtr = _dylib.lookupFunction<Double Function(Double, Double), double Function(double, double)>('my_camera_add');
  late final Pointer<Utf8> Function(Pointer<Utf8>) _getGreetingPtr = _dylib.lookupFunction<Pointer<Utf8> Function(Pointer<Utf8>), Pointer<Utf8> Function(Pointer<Utf8>)>('my_camera_get_greeting');
  late final void Function(int) _registerFramesPtr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('my_camera_register_frames_stream');
  late final void Function(int) _releaseFramesPtr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('my_camera_release_frames_stream');
  @override
  // ignore: unnecessary_overrides
  void dispose() {
    super.dispose(); // sets isDisposed = true, calls onDestroy()
  }

  @override
  double add(double a, double b) {
    checkDisposed();
    return _addPtr(a, b);
  }

  @override
  Future<String> getGreeting(String name) async {
    checkDisposed();
    return withArena((arena) async {
      final result = await NitroRuntime.callAsync(_getGreetingPtr, [name.toNativeUtf8(allocator: arena)]);
      return (result as Pointer<Utf8>).toDartStringWithFree();
    });
  }

  @override
  Stream<CameraFrame> get frames {
    checkDisposed();
    return NitroRuntime.openStream<CameraFrame>(
      register: (port) => _registerFramesPtr(port),
      unpack: (rawPtr) => Pointer<CameraFrameFfi>.fromAddress(rawPtr).ref.toDart(),
      release: (port) => _releaseFramesPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

}
