// Generated by Nitrogen Modules. Do not edit.
// Generated from: my_camera.native.dart
part of 'my_camera.native.dart';

// --- Struct FFI representations (generated by Nitrogen) ---

final class CameraFrameFfi extends Struct {
  external Pointer<Uint8> data;
  @Int64()
  external int width;
  @Int64()
  external int height;
  @Int64()
  external int stride;
  @Int64()
  external int timestampNs;
}

extension CameraFrameFfiExt on CameraFrameFfi {
  CameraFrame toDart() {
    return CameraFrame(
      data: data.asTypedList(stride),
      width: width,
      height: height,
      stride: stride,
      timestampNs: timestampNs,
    );
  }
}

extension CameraFrameExt on CameraFrame {
  Pointer<CameraFrameFfi> toNative(Arena arena) {
    final ptr = arena<CameraFrameFfi>();
    ptr.ref.data = data.toPointer(arena);
    ptr.ref.width = width;
    ptr.ref.height = height;
    ptr.ref.stride = stride;
    ptr.ref.timestampNs = timestampNs;
    return ptr;
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension ResolutionRecordExt on Resolution {
  static Resolution fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static Resolution fromReader(RecordReader r) => Resolution(
        width: r.readInt(),
        height: r.readInt(),
      );

  void writeFields(RecordWriter w) {
    w.writeInt(width);
    w.writeInt(height);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final w = RecordWriter();
    writeFields(w);
    return w.toNative(alloc);
  }
}

extension CameraDeviceRecordExt on CameraDevice {
  static CameraDevice fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static CameraDevice fromReader(RecordReader r) => CameraDevice(
        id: r.readString(),
        name: r.readString(),
        resolutions: List.generate(
            r.readInt32(), (_) => ResolutionRecordExt.fromReader(r)),
        isFrontFacing: r.readBool(),
      );

  void writeFields(RecordWriter w) {
    w.writeString(id);
    w.writeString(name);
    w.writeInt32(resolutions.length);
    for (final e in resolutions) {
      e.writeFields(w);
    }
    w.writeBool(isFrontFacing);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final w = RecordWriter();
    writeFields(w);
    return w.toNative(alloc);
  }
}

class _MyCameraImpl extends MyCamera {
  final DynamicLibrary _dylib;

  _MyCameraImpl() : _dylib = NitroRuntime.loadLib('my_camera') {
    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>),
        int Function(Pointer<Void>)>('my_camera_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
          'my_camera: Dart API DL initialization failed with code $initCode.');
    }
  }

  late final double Function(double, double) _addPtr = _dylib.lookupFunction<
      Double Function(Double, Double),
      double Function(double, double)>('my_camera_add');
  late final Pointer<Utf8> Function(Pointer<Utf8>) _getGreetingPtr =
      _dylib.lookupFunction<Pointer<Utf8> Function(Pointer<Utf8>),
          Pointer<Utf8> Function(Pointer<Utf8>)>('my_camera_get_greeting');
  late final Pointer<Uint8> Function() _getAvailableDevicesPtr = _dylib
      .lookupFunction<Pointer<Uint8> Function(), Pointer<Uint8> Function()>(
          'my_camera_get_available_devices');
  late final void Function(int) _registerFramesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'my_camera_register_frames_stream');
  late final void Function(int) _releaseFramesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'my_camera_release_frames_stream');
  late final void Function(int) _registerColoredFramesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'my_camera_register_colored_frames_stream');
  late final void Function(int) _releaseColoredFramesPtr =
      _dylib.lookupFunction<Void Function(Int64), void Function(int)>(
          'my_camera_release_colored_frames_stream');
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr =
      _dylib.lookupFunction<Pointer<NitroErrorFfi> Function(),
          Pointer<NitroErrorFfi> Function()>('my_camera_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr =
      _dylib.lookupFunction<Void Function(), void Function()>(
          'my_camera_clear_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
      _getErrorNativePtr = _dylib.lookup('my_camera_get_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('my_camera_clear_error');

  @override
  // ignore: unnecessary_overrides
  void dispose() {
    super.dispose(); // sets isDisposed = true, calls onDestroy()
  }

  @override
  double add(double a, double b) {
    checkDisposed();
    final res = _addPtr(a, b);
    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
    return res;
  }

  @override
  Future<String> getGreeting(String name) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Utf8>>(
          _getGreetingPtr, [name.toNativeUtf8(allocator: arena)],
          getError: _getErrorNativePtr, clearError: _clearErrorNativePtr);
      return rawPtr.toDartStringWithFree();
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<List<CameraDevice>> getAvailableDevices() async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _getAvailableDevicesPtr, [],
        getError: _getErrorNativePtr, clearError: _clearErrorNativePtr);
    try {
      return RecordReader.decodeList(
          rawPtr, (r) => CameraDeviceRecordExt.fromReader(r));
    } finally {
      malloc.free(rawPtr);
    }
  }

  @override
  Stream<CameraFrame> get frames {
    checkDisposed();
    return NitroRuntime.openStream<CameraFrame>(
      register: (port) => _registerFramesPtr(port),
      unpack: (rawPtr) {
        final ptr = Pointer<CameraFrameFfi>.fromAddress(rawPtr);
        try {
          return ptr.ref.toDart();
        } finally {
          malloc.free(ptr);
        }
      },
      release: (port) => _releaseFramesPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<CameraFrame> get coloredFrames {
    checkDisposed();
    return NitroRuntime.openStream<CameraFrame>(
      register: (port) => _registerColoredFramesPtr(port),
      unpack: (rawPtr) {
        final ptr = Pointer<CameraFrameFfi>.fromAddress(rawPtr);
        try {
          return ptr.ref.toDart();
        } finally {
          malloc.free(ptr);
        }
      },
      release: (port) => _releaseColoredFramesPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }
}
