// Generated by Nitrogen Modules. Do not edit.
// Generated from: verification.native.dart
part of 'verification.native.dart';

// --- Struct FFI representations (generated by Nitrogen) ---

final class FloatBufferFfi extends Struct {
  external Pointer<Float> data;
  @Int64()
  external int length;
}

extension FloatBufferFfiExt on FloatBufferFfi {
  FloatBuffer toDart() {
    return FloatBuffer(
      data: data.asTypedList(length),
      length: length,
    );
  }
}

extension FloatBufferExt on FloatBuffer {
  Pointer<FloatBufferFfi> toNative(Arena arena) {
    final ptr = arena<FloatBufferFfi>();
    ptr.ref.data = data.toPointer(arena);
    ptr.ref.length = length;
    return ptr;
  }
}

class _VerificationModuleImpl extends VerificationModule {
  final DynamicLibrary _dylib;

  _VerificationModuleImpl() : _dylib = NitroRuntime.loadLib('verification') {
    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>),
        int Function(Pointer<Void>)>('verification_init_dart_api_dl');
    initFunc(NativeApi.initializeApiDLData);
  }

  late final double Function(double, double) _multiplyPtr =
      _dylib.lookupFunction<Double Function(Double, Double),
          double Function(double, double)>('verification_module_multiply');
  late final Pointer<Utf8> Function(Pointer<Utf8>) _pingPtr =
      _dylib.lookupFunction<Pointer<Utf8> Function(Pointer<Utf8>),
          Pointer<Utf8> Function(Pointer<Utf8>)>('verification_module_ping');
  late final Pointer<Utf8> Function(Pointer<Utf8>) _pingAsyncPtr =
      _dylib.lookupFunction<
          Pointer<Utf8> Function(Pointer<Utf8>),
          Pointer<Utf8> Function(
              Pointer<Utf8>)>('verification_module_ping_async');
  late final void Function(Pointer<Utf8>) _throwErrorPtr =
      _dylib.lookupFunction<Void Function(Pointer<Utf8>),
          void Function(Pointer<Utf8>)>('verification_module_throw_error');
  late final Pointer<Void> Function(Pointer<Float>, int) _processFloatsPtr =
      _dylib.lookupFunction<
          Pointer<Void> Function(Pointer<Float>, Int64),
          Pointer<Void> Function(
              Pointer<Float>, int)>('verification_module_process_floats');
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr =
      _dylib.lookupFunction<Pointer<NitroErrorFfi> Function(),
          Pointer<NitroErrorFfi> Function()>('verification_get_error');
  late final void Function() _clearErrorPtr =
      _dylib.lookupFunction<Void Function(), void Function()>(
          'verification_clear_error');
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
      _getErrorNativePtr = _dylib.lookup('verification_get_error');
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('verification_clear_error');

  @override
  // ignore: unnecessary_overrides
  void dispose() {
    super.dispose(); // sets isDisposed = true, calls onDestroy()
  }

  @override
  double multiply(double a, double b) {
    checkDisposed();
    final res = _multiplyPtr(a, b);
    NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
    return res;
  }

  @override
  String ping(String message) {
    checkDisposed();
    return withArena((arena) {
      final res = _pingPtr(message.toNativeUtf8(allocator: arena));
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      return res.toDartStringWithFree();
    });
  }

  @override
  Future<String> pingAsync(String message) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Utf8>>(
          _pingAsyncPtr, [message.toNativeUtf8(allocator: arena)],
          getError: _getErrorNativePtr, clearError: _clearErrorNativePtr);
      return rawPtr.toDartStringWithFree();
    } finally {
      arena.releaseAll();
    }
  }

  @override
  void throwError(String message) {
    checkDisposed();
    return withArena((arena) {
      final res = _throwErrorPtr(message.toNativeUtf8(allocator: arena));
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      return;
    });
  }

  @override
  FloatBuffer processFloats(Float32List inputs) {
    checkDisposed();
    return withArena((arena) {
      final res = _processFloatsPtr(inputs.toPointer(arena), inputs.length);
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      final structPtr = Pointer<FloatBufferFfi>.fromAddress(res.address);
      final decoded = structPtr.ref.toDart();
      malloc.free(structPtr);
      return decoded;
    });
  }
}
