import '../bridge_spec.dart';

class CppBridgeGenerator {
  static String generate(BridgeSpec spec) {
    final s = StringBuffer();
    s.writeln('// Generated by Nitrogen Modules. Do not edit.');
    s.writeln('#include "${spec.namespace}.bridge.g.h"');
    s.writeln('');

    // Preprocessor branch for Android JNI vs iOS Swift
    s.writeln('#ifdef __ANDROID__');
    s.writeln('#include <jni.h>');
    s.writeln('#include <android/log.h>');
    s.writeln('#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "Nitrogen", __VA_ARGS__)');
    s.writeln();
    s.writeln('static JavaVM* g_jvm = nullptr;');
    s.writeln('static jclass g_bridgeClass = nullptr;');
    s.writeln();
    s.writeln('extern "C" {');
    s.writeln();
    s.writeln('JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {');
    s.writeln('    g_jvm = vm;');
    s.writeln('    JNIEnv* env = nullptr;');
    s.writeln('    if (vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) != JNI_OK) {');
    s.writeln('        return -1;');
    s.writeln('    }');
    s.writeln('    jclass localClass = env->FindClass("nitro/${spec.lib.replaceAll('-', '_')}_module/${spec.dartClassName}JniBridge");');
    s.writeln('    if (localClass != nullptr) {');
    s.writeln('        g_bridgeClass = (jclass)env->NewGlobalRef(localClass);');
    s.writeln('    } else {');
    s.writeln('        LOGE("Failed to find JniBridge class");');
    s.writeln('    }');
    s.writeln('    return JNI_VERSION_1_6;');
    s.writeln('}');
    s.writeln();
    s.writeln('static JNIEnv* GetEnv() {');
    s.writeln('    JNIEnv* env = nullptr;');
    s.writeln('    int status = g_jvm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);');
    s.writeln('    if (status == JNI_EDETACHED) {');
    s.writeln('        g_jvm->AttachCurrentThread(&env, nullptr);');
    s.writeln('    }');
    s.writeln('    return env;');
    s.writeln('}');
    s.writeln();

    for (final func in spec.functions) {
      final cType = _typeToC(func.returnType.name);
      final paramsDecl = func.params.map((p) => '${_typeToC(p.type.name)} ${p.name}').join(', ');
      
      final jniSig = _jniSig(func.params, func.returnType.name);
      
      s.writeln('$cType ${func.cSymbol}(${paramsDecl.isEmpty ? 'void' : paramsDecl}) {');
      s.writeln('    JNIEnv* env = GetEnv();');
      s.writeln('    if (env == nullptr) return ${_defaultValue(func.returnType.name)};');
      s.writeln('    jmethodID methodId = env->GetStaticMethodID(g_bridgeClass, "${func.dartName}_call", "$jniSig");');
      s.writeln('    if (methodId == nullptr) { LOGE("Method not found"); return ${_defaultValue(func.returnType.name)}; }');
      
      // Call dispatch
      final callArgsList = <String>[];
      for (final p in func.params) {
        if (p.type.name == 'String') {
          s.writeln('    jstring j_${p.name} = env->NewStringUTF(${p.name});');
          callArgsList.add('j_${p.name}');
        } else {
          callArgsList.add(p.name);
        }
      }
      
      final callArgs = callArgsList.join(', ');
      final bridgePrefix = callArgs.isEmpty ? '' : ', $callArgs';
      
      if (func.returnType.name == 'void') {
        s.writeln('    env->CallStaticVoidMethod(g_bridgeClass, methodId$bridgePrefix);');
      } else if (func.returnType.name == 'double') {
        s.writeln('    return env->CallStaticDoubleMethod(g_bridgeClass, methodId$bridgePrefix);');
      } else if (func.returnType.name == 'String') {
        s.writeln('    jstring jstr = (jstring)env->CallStaticObjectMethod(g_bridgeClass, methodId$bridgePrefix);');
        s.writeln('    const char* nativeStr = env->GetStringUTFChars(jstr, 0);');
        s.writeln('    char* result = strdup(nativeStr);');
        s.writeln('    env->ReleaseStringUTFChars(jstr, nativeStr);');
        // also release parameter strings
        for (final p in func.params) {
          if (p.type.name == 'String') {
            s.writeln('    env->DeleteLocalRef(j_${p.name});');
          }
        }
        s.writeln('    env->DeleteLocalRef(jstr);');
        s.writeln('    return result;');
      } else {
        s.writeln('    return ${_defaultValue(func.returnType.name)}; // Fallback');
      }
      s.writeln('}');
      s.writeln('');
    }

    // (Properties and Streams omitted for brevity in template)
    
    s.writeln('} // extern "C"');
    s.writeln('#elif __APPLE__');
    s.writeln('// --- iOS Swift C-Bridge Proxy Implementation ---');
    s.writeln('extern "C" {');
    s.writeln('');
    s.writeln('// Swift exposes these symbols via @objc or @_cdecl');
    
    for (final func in spec.functions) {
      final cType = _typeToC(func.returnType.name);
      final params = func.params.map((p) => '${_typeToC(p.type.name)} ${p.name}').join(', ');
      final callParams = func.params.map((p) => p.name).join(', ');
      
      // Declaring the Swift registry symbol so C++ can link to it
      s.writeln('extern $cType _call_${func.dartName}(${params.isEmpty ? 'void' : params});');
      
      // Implementing our pure C symbol from dart FFI which bounces to Swift
      s.writeln('$cType ${func.cSymbol}(${params.isEmpty ? 'void' : params}) {');
      if (func.returnType.name != 'void') {
        s.writeln('    return _call_${func.dartName}($callParams);');
      } else {
        s.writeln('    _call_${func.dartName}($callParams);');
      }
      s.writeln('}');
      s.writeln('');
    }
    s.writeln('} // extern "C"');
    s.writeln('#endif');

    return s.toString();
  }

  static String _typeToC(String dartType) {
    switch (dartType.replaceFirst('?', '')) {
      case 'int': return 'int64_t';
      case 'double': return 'double';
      case 'bool': return 'int8_t';
      case 'String': return 'const char*';
      case 'Uint8List': return 'uint8_t*';
      case 'void': return 'void';
      default: return 'void*';
    }
  }

  static String _defaultValue(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int': return '0';
      case 'double': return '0.0';
      case 'bool': return 'false';
      case 'String': return '""';
      default: return 'nullptr';
    }
  }

  static String _jniSigType(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int': return 'J'; // Long
      case 'double': return 'D';
      case 'bool': return 'Z';
      case 'String': return 'Ljava/lang/String;';
      case 'void': return 'V';
      case 'Uint8List': return '[B';
      default: return 'Ljava/lang/Object;';
    }
  }

  static String _jniSig(List<BridgeParam> params, String returnType) {
    final sb = StringBuffer();
    sb.write('(');
    for (final p in params) {
      sb.write(_jniSigType(p.type.name));
    }
    sb.write(')');
    sb.write(_jniSigType(returnType));
    return sb.toString();
  }
}
