import '../bridge_spec.dart';
import 'enum_generator.dart';
import 'struct_generator.dart';

class DartFfiGenerator {
  static String generate(BridgeSpec spec) {
    final s = StringBuffer();
    s.writeln('// Generated by Nitrogen Modules. Do not edit.');
    s.writeln("part of '${spec.sourceUri.split('/').last}';");
    s.writeln();

    // Enum & struct extensions (class bodies live in .native.dart)
    final enumExt = EnumGenerator.generateDartExtensions(spec);
    if (enumExt.isNotEmpty) s.write(enumExt);
    final structExt = StructGenerator.generateDartExtensions(spec);
    if (structExt.isNotEmpty) s.write(structExt);

    // ── Impl class ──────────────────────────────────────────────────────────
    s.writeln('class _${spec.dartClassName}Impl extends ${spec.dartClassName} {');
    s.writeln('  final DynamicLibrary _dylib;');
    s.writeln();
    s.writeln('  _${spec.dartClassName}Impl() : _dylib = NitroRuntime.loadLib(\'${spec.lib}\') {');
    s.writeln("    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>), int Function(Pointer<Void>)>('InitDartApiDL');");
    s.writeln('    initFunc(NativeApi.initializeApiDLData);');
    s.writeln('  }');
    s.writeln();

    // ── Method pointers ─────────────────────────────────────────────────────
    for (final func in spec.functions) {
      final nativeType = _toNativeType(func);
      final dartType = _toDartType(func);
      s.writeln("  late final $dartType _${func.dartName}Ptr = _dylib.lookupFunction<$nativeType, $dartType>('${func.cSymbol}');");
    }

    // ── Property pointers ───────────────────────────────────────────────────
    for (final prop in spec.properties) {
      final ffiType = _typeToFFI(prop.type.name);
      final dartType = _typeToDartFFI(prop.type.name);
      if (prop.hasGetter) {
        s.writeln("  late final $dartType Function() _get${_cap(prop.dartName)}Ptr = _dylib.lookupFunction<$ffiType Function(), $dartType Function()>('${prop.getSymbol}');");
      }
      if (prop.hasSetter) {
        s.writeln("  late final void Function($dartType) _set${_cap(prop.dartName)}Ptr = _dylib.lookupFunction<Void Function($ffiType), void Function($dartType)>('${prop.setSymbol}');");
      }
    }

    // ── Stream register/release pointers ────────────────────────────────────
    for (final stream in spec.streams) {
      final cap = _cap(stream.dartName);
      s.writeln("  late final void Function(int) _register${cap}Ptr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('${stream.registerSymbol}');");
      s.writeln("  late final void Function(int) _release${cap}Ptr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('${stream.releaseSymbol}');");
    }

    s.writeln();

    s.writeln();

    // ── Method implementations ───────────────────────────────────────────────
    for (final func in spec.functions) {
      final returnType =
          func.isAsync ? 'Future<${func.returnType.name}>' : func.returnType.name;
      final asyncMod = func.isAsync ? 'async ' : '';
      final callArgs = func.params.map((p) {
        if (p.type.name.startsWith('Uint8List')) {
          return '${p.name}.toPointer(arena)';
        }
        return p.name;
      }).join(', ');
      final hasBuffer = func.params.any((p) => p.type.name.startsWith('Uint8List'));

      s.writeln('  @override');
      s.writeln('  $returnType ${func.dartName}(${_paramList(func.params)}) $asyncMod{');
      if (!func.isAsync) {
        if (hasBuffer) {
          s.writeln('    return withArena((arena) => _${func.dartName}Ptr($callArgs));');
        } else {
          s.writeln('    return _${func.dartName}Ptr($callArgs);');
        }
      } else {
        s.writeln('    return NitroRuntime.callAsync(_${func.dartName}Ptr, [${func.params.map((p) => p.name).join(', ')}]);');
      }
      s.writeln('  }');
      s.writeln();
    }

    // ── Property implementations ─────────────────────────────────────────────
    for (final prop in spec.properties) {
      final cap = _cap(prop.dartName);
      if (prop.hasGetter) {
        s.writeln('  @override');
        s.writeln('  ${prop.type.name} get ${prop.dartName} => _get${cap}Ptr();');
      }
      if (prop.hasSetter) {
        s.writeln('  @override');
        s.writeln('  set ${prop.dartName}(${prop.type.name} value) => _set${cap}Ptr(value);');
      }
      s.writeln();
    }

    // ── Stream implementations ───────────────────────────────────────────────
    for (final stream in spec.streams) {
      final cap = _cap(stream.dartName);
      final itemType = stream.itemType.name;
      // Is the item type a known primitive, or a @HybridStruct?
      final isStruct = spec.structs.any((st) => st.name == itemType);
      final unpackExpr = isStruct
          // Struct: rawPtr is the native pointer address (int).
          // Cast to Pointer<_XxxFfi>, ref it, then lift to Dart.
          ? '(rawPtr) => Pointer<_${itemType}Ffi>.fromAddress(rawPtr).ref.toDart()'
          // Primitive types: int/double/bool — openStream delivers the raw value
          // as int (bit-pattern); runtime coercion handled inside openStream impl.
          : '(rawPtr) => rawPtr as $itemType';

      s.writeln('  @override');
      s.writeln('  Stream<$itemType> get ${stream.dartName} {');
      s.writeln('    return NitroRuntime.openStream<$itemType>(');
      s.writeln('      register: (port) => _register${cap}Ptr(port),');
      s.writeln('      unpack: $unpackExpr,');
      s.writeln('      release: (port) => _release${cap}Ptr(port),');
      s.writeln('      backpressure: Backpressure.${stream.backpressure.name},');
      s.writeln('    );');
      s.writeln('  }');
      s.writeln();
    }

    s.writeln('}');
    return s.toString();
  }

  // ── Helpers ─────────────────────────────────────────────────────────────────

  static String _paramList(List<BridgeParam> params) =>
      params.map((p) => '${p.type.name} ${p.name}').join(', ');

  static String _cap(String name) =>
      name[0].toUpperCase() + name.substring(1);

  static String _toNativeType(BridgeFunction func) {
    final ret = _typeToFFI(func.returnType.name);
    final params = func.params.map((p) => _typeToFFI(p.type.name)).join(', ');
    return '$ret Function($params)';
  }

  static String _toDartType(BridgeFunction func) {
    final ret = _typeToDartFFI(func.returnType.name);
    final params = func.params.map((p) => _typeToDartFFI(p.type.name)).join(', ');
    return '$ret Function($params)';
  }

  static String _typeToFFI(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int': return 'Int64';
      case 'double': return 'Double';
      case 'bool': return 'Int8';
      case 'String': return 'Pointer<Utf8>';
      case 'Uint8List': return 'Pointer<Uint8>';
      case 'void': return 'Void';
      default: return 'Pointer<Void>';
    }
  }

  static String _typeToDartFFI(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int': return 'int';
      case 'double': return 'double';
      case 'bool': return 'int';
      case 'String': return 'Pointer<Utf8>';
      case 'Uint8List': return 'Pointer<Uint8>';
      case 'void': return 'void';
      default: return 'Pointer<Void>';
    }
  }
}
