import '../bridge_spec.dart';

/// Generates Dart extension helpers for HybridStructs.
/// The struct class itself MUST already be declared in the .native.dart spec file.
/// We only emit the FFI conversion extension here (in the generated part).
class StructGenerator {
  /// Called by DartFfiGenerator. Only emits conversion helpers, NOT class bodies.
  static String generateDartExtensions(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Struct FFI helpers (generated by Nitrogen) ---');
    s.writeln();
    for (final st in spec.structs) {
      s.writeln('extension _${st.name}FfiExt on ${st.name} {');
      s.writeln('  /// Pack this struct into a native buffer for a single synchronous call.');
      s.writeln('  void pack(Pointer<Uint8> buf) {');
      s.writeln('    // Fields must be packed in declaration order.');
      // Simplified: just a comment. Real impl would use ByteData.
      s.writeln('    // TODO: implement field-by-field packing.');
      s.writeln('  }');
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates C structs for the header file.
  static String generateCStructs(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      if (st.packed) s.writeln('#pragma pack(push, 1)');
      s.writeln('typedef struct {');
      for (final f in st.fields) {
        final cType = _dartTypeToCType(f.type.name);
        s.writeln('  $cType ${f.name}; ${f.zeroCopy ? "/* zero-copy */" : ""}');
      }
      s.writeln('} ${st.name};');
      if (st.packed) s.writeln('#pragma pack(pop)');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Kotlin @Keep data classes for structs.
  static String generateKotlin(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      s.writeln('@Keep');
      final params = st.fields
          .map((f) => 'val ${f.name}: ${_dartTypeToKotlin(f.type.name)}')
          .join(', ');
      s.writeln('data class ${st.name}($params)');
      s.writeln();
    }
    return s.toString();
  }

  /// Generates Swift structs.
  static String generateSwift(BridgeSpec spec) {
    if (spec.structs.isEmpty) return '';
    final s = StringBuffer();
    s.writeln('// --- Structs ---');
    for (final st in spec.structs) {
      s.writeln('public struct ${st.name} {');
      for (final f in st.fields) {
        final swiftType = _dartTypeToSwift(f.type.name);
        s.writeln('  public var ${f.name}: $swiftType');
      }
      s.writeln('}');
      s.writeln();
    }
    return s.toString();
  }

  static String _dartTypeToCType(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int': return 'int64_t';
      case 'double': return 'double';
      case 'bool': return 'int8_t';
      case 'String': return 'const char*';
      case 'Uint8List': return 'uint8_t*';
      default: return 'void*';
    }
  }

  static String _dartTypeToKotlin(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int': return 'Long';
      case 'double': return 'Double';
      case 'bool': return 'Boolean';
      case 'String': return 'String';
      case 'Uint8List': return 'ByteArray';
      default: return 'Any?';
    }
  }

  static String _dartTypeToSwift(String t) {
    switch (t.replaceFirst('?', '')) {
      case 'int': return 'Int64';
      case 'double': return 'Double';
      case 'bool': return 'Bool';
      case 'String': return 'String';
      case 'Uint8List': return 'Data';
      default: return 'Any?';
    }
  }
}
