import '../../../bridge_spec.dart';
import '../../code_writer.dart';
import 'cpp_interface_generator.dart';

/// Generates `*.impl.g.cpp` — a concrete C++ implementation starter for
/// desktop targets (`NativeImpl.cpp`).
///
/// Unlike other `.g.` files, this one is meant to be edited by the user.
/// It is generated once and not overwritten on subsequent `nitrogen generate`
/// runs (the build system skips it if the file already exists).
///
/// The generated file subclasses `Hybrid${ClassName}` and stubs every
/// method/property with `throw std::runtime_error("Not implemented: ...")`.
///
/// All signatures are produced by [CppInterfaceGenerator]'s type helpers so
/// the starter can never drift from the abstract class in `*.native.g.h`.
class CppImplGenerator {
  static String generate(BridgeSpec spec) {
    if (!spec.hasCppImpl) {
      return '// Not applicable: NativeImpl is not cpp for this module.\n';
    }

    final libStem = spec.lib.replaceAll('-', '_');
    final className = spec.dartClassName;
    final ifaceHeader = '$libStem.native.g.h';

    final enumNames = spec.enums.map((e) => e.name).toSet();
    final structNames = spec.structs.map((s) => s.name).toSet();
    final recordNames = {
      ...spec.recordTypes.map((r) => r.name),
      ...spec.variants.map((v) => v.name),
    };

    final w = CodeWriter();

    // Header comment — different from generatedFileHeader because this file IS editable.
    w.writeln('// Generated by Nitrogen — edit this file to implement $className.');
    w.writeln('//');
    w.writeln('// This file is a one-time starter: Nitrogen will NOT overwrite it.');
    w.writeln('// Rename it to e.g. "${className}Impl.cpp" and add it to CMakeLists.txt.');
    w.writeln('//');
    w.writeln('// Quick-start:');
    w.writeln('//   1. Implement each TODO method below.');
    w.writeln('//   2. Add this file to your CMakeLists.txt (target_sources).');
    w.writeln('//   3. Call ${libStem}_register_impl(&myImpl) during plugin/app init.');
    w.writeln('//   4. Call ${libStem}_register_impl(nullptr) in teardown.');
    w.writeln('//');
    w.writeln('// Ownership conventions:');
    w.writeln('//   • Record/variant/tuple RETURNS **and emit_* stream items**: pass');
    w.writeln('//     writer.toNativeBuffer() (or nitro_<Variant>_to_native) — a malloc\'d');
    w.writeln('//     [4B len][payload] block whose ownership transfers to the bridge/Dart.');
    w.writeln('//     Returning or emitting a non-owning writer.toBuffer() view is wrong:');
    w.writeln('//     Dart would decode-and-free a live local buffer.');
    w.writeln('//   • Record/variant PARAMS are non-owning payload views (no length prefix)');
    w.writeln('//     — copy if you need them after the call.');
    w.writeln('//   • TypedData RETURNS use NitroCppBuffer{ data, size } where size is in');
    w.writeln('//     BYTES, not elements (Float32List: count * sizeof(float)). A wrong');
    w.writeln('//     unit silently truncates the list Dart sees (bytes / elemSize).');
    w.writeln('//   • @zeroCopy TypedData returns are NOT copied by the bridge: the pointed-to');
    w.writeln('//     bytes must stay alive until Dart is done (e.g. store them in a member).');
    w.writeln('');
    w.writeln('#include "$ifaceHeader"');
    w.writeln('#include <stdexcept>');
    w.writeln('');
    w.writeln('// ── Implementation ───────────────────────────────────────────────────────────');
    w.writeln('');
    w.writeln('class ${className}Impl final : public Hybrid$className {');
    w.writeln('public:');
    w.writeln('    ${className}Impl() = default;');
    w.writeln('    ~${className}Impl() override = default;');

    if (spec.functions.isNotEmpty) {
      w.writeln('');
      w.writeln('    // ── Methods ──────────────────────────────────────────────────────────────');
      for (final func in spec.functions) {
        w.writeln('');
        if (func.isNativeAsync) {
          final params = CppInterfaceGenerator.cppMethodParamsFor(
            func.params,
            enumNames,
            structNames,
            recordNames,
          )
            ..add('NitroError* _nitro_err')
            ..add('int64_t dartPort');
          w.writeln('    void ${func.dartName}(${params.join(', ')}) override {');
          w.writeln('        // TODO: on error, populate _nitro_err (hasError/name/message via strdup) before posting.');
          w.writeln('        // TODO: post result via Dart_PostCObject_DL(dartPort, ...)');
          w.writeln('        throw std::runtime_error("Not implemented: ${func.dartName}");');
          w.writeln('    }');
        } else {
          final ret = CppInterfaceGenerator.cppReturnTypeFor(
            func.returnType,
            enumNames,
            structNames,
            recordNames,
          );
          final params = CppInterfaceGenerator.cppMethodParamsFor(
            func.params,
            enumNames,
            structNames,
            recordNames,
          );
          w.writeln('    $ret ${func.dartName}(${params.join(', ')}) override {');
          w.writeln('        // TODO: implement ${func.dartName}');
          w.writeln('        throw std::runtime_error("Not implemented: ${func.dartName}");');
          final placeholder = _placeholderReturn(ret);
          if (placeholder != null) {
            w.writeln('        // return $placeholder;');
          }
          w.writeln('    }');
        }
      }
    }

    if (spec.properties.isNotEmpty) {
      w.writeln('');
      w.writeln('    // ── Properties ───────────────────────────────────────────────────────────');
      for (final prop in spec.properties) {
        if (prop.hasGetter) {
          final cppType = CppInterfaceGenerator.cppReturnTypeFor(
            prop.type,
            enumNames,
            structNames,
            recordNames,
          );
          w.writeln('');
          w.writeln('    $cppType get_${prop.dartName}() const override {');
          w.writeln('        // TODO: implement get_${prop.dartName}');
          w.writeln('        throw std::runtime_error("Not implemented: get_${prop.dartName}");');
          w.writeln('    }');
        }
        if (prop.hasSetter) {
          final paramType = CppInterfaceGenerator.cppParamTypeFor(
            prop.type,
            enumNames,
            structNames,
            recordNames,
          );
          w.writeln('');
          w.writeln('    void set_${prop.dartName}($paramType value) override {');
          w.writeln('        // TODO: implement set_${prop.dartName}');
          w.writeln('        throw std::runtime_error("Not implemented: set_${prop.dartName}");');
          w.writeln('    }');
        }
      }
    }

    if (spec.streams.isNotEmpty) {
      w.writeln('');
      w.writeln('    // ── Streams ──────────────────────────────────────────────────────────────');
      w.writeln('    // Call emit_<name>(item) from any thread to push items to Dart.');
      w.writeln('    // emit_* helpers are defined in the generated bridge.');
      w.writeln('    // Record/variant items: pass record.toNativeBuffer() — ownership of the');
      w.writeln('    // heap [4B len][payload] block transfers to the bridge (same convention');
      w.writeln('    // as record returns). Never emit a non-owning writer.toBuffer() view.');
      w.writeln('    // Example — start emitting from a background thread:');
      w.writeln('    //');
      for (final stream in spec.streams) {
        final itemCpp = CppInterfaceGenerator.cppReturnTypeFor(
          stream.itemType,
          enumNames,
          structNames,
          recordNames,
        );
        w.writeln('    //   std::thread([this]{ emit_${stream.dartName}(/* $itemCpp value */); }).detach();');
      }
    }

    w.writeln('};');
    w.writeln('');

    // Registration section
    w.writeln('// ── Registration ─────────────────────────────────────────────────────────────');
    w.writeln('//');
    w.writeln('// Create a single instance and register it during plugin/app initialisation:');
    w.writeln('//');
    w.writeln('//   static ${className}Impl g_impl;');
    w.writeln('//   ${libStem}_register_impl(&g_impl);   // in your plugin init');
    w.writeln('//   ${libStem}_register_impl(nullptr);   // in your plugin dispose');
    w.writeln('//');
    w.writeln('// On Flutter desktop (Windows / Linux / macOS with NativeImpl.cpp) add the');
    w.writeln('// registration call to your Flutter plugin\'s RegisterWithRegistrar:');
    w.writeln('//');
    w.writeln('//   void ${className}Plugin::RegisterWithRegistrar(PluginRegistrar* registrar) {');
    w.writeln('//       static ${className}Impl impl;');
    w.writeln('//       ${libStem}_register_impl(&impl);');
    w.writeln('//   }');

    return w.toString();
  }

  /// Returns a commented placeholder return expression for non-void methods.
  static String? _placeholderReturn(String cppType) {
    switch (cppType) {
      case 'void':
        return null;
      case 'int64_t':
      case 'uint64_t':
        return '0';
      case 'double':
        return '0.0';
      case 'bool':
        return 'false';
      case 'std::string':
        return '""';
      case 'NitroCppBuffer':
        return '{ nullptr, 0 }';
      case 'void*':
        return 'nullptr';
    }
    if (cppType.endsWith('*')) return 'nullptr';
    if (cppType.startsWith('std::optional<')) return 'std::nullopt';
    return null;
  }
}
